### ISSUE TITLE
把关机从托盘提出来

### ISSUE THREAD

**Issue by shule1987** [linuxdeepin/internal-discussion#10]
<img width="815" alt="2018-10-26 10 21 10" src="https://user-images.githubusercontent.com/5448609/47540920-d23dd200-d909-11e8-91f1-097af17ab82b.png">

**Comment by wangjia12** [comment]
@Aichang2017 昨天论坛反馈的问题临时改的，15.8就会实现。

**Comment by zhuxiujuancindy** [comment]
@Aichang2017

**Comment by listenerri** [comment]
@zhaofangfangdeepin 
https://cr.deepin.io/c/dde/dde-dock/+/39284

**Comment by zhaofangfangdeepin** [comment]
时尚模式下，电池图标和关机图标分离了？

**Comment by listenerri** [comment]
> 时尚模式下，电池图标和关机图标分离了？

目前的实现时尚和高效模式下都会有关机电池(如果有的话)图标
时尚模式下是如上图所示的大图标，没有在托盘内，高效模式下图标样式跟以前一样

@shule1987 是要这样的实现吧？
