### ISSUE TITLE
文件数据刻录功能

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#1000]
背景：

现有刻录工具 Brasero ，但有如下几点问题：

 1. 用户觉得这个软件不好用（界面交互）
 2. 在文件管理器里面没有入口，有的人不知道要单独下这个软件来用
 3. 成功率不高，经常会失败（这一条不是普遍现象多测试一下）

需求描述：

 1. 检测到有光盘，文件的右键显示“刻录”，点击后弹出刻录窗口。检测到光盘为只读时，右键菜单的刻录是灰色无法点击。
 2. 双击光盘图标，弹出刻录窗口。
 3. 刻录窗口可以拖拽文件添加，可以删除已添加的文件，需要选择刻录到哪个光盘，为光盘命名，选择刻录数据或者iso。（追加数据时同样操作）
 4. 点击刻录后设置配置项：速度、是否可以追加数据（默认勾选）、刻录后是否检验光盘数据（默认勾选，这一项也可以不做选项，直接默认检验）。如果选择可以追加数据，下次插入光盘仍然同之前一样使用，可以继续刻录数据；如果不选择可以追加数据，下次插入光盘时光盘为只读。
 5. 点击刻录后要显示刻录进度，刻录完成后显示验证进度。
 6. 可擦写的光盘可以格式化，也可以在还可以继续追加数据的情况下删减数据。
 7. 刻录ISO不可以追加数据。
 8. 光盘其他项，如属性、右键菜单无特殊提到的和其他设备保持一致。

![image](https://user-images.githubusercontent.com/10095765/55460311-43ee1a80-5624-11e9-9de9-273f7c69cf1e.png)
![image](https://user-images.githubusercontent.com/10095765/55460371-67b16080-5624-11e9-9477-52e1f43c7236.png)
![image](https://user-images.githubusercontent.com/10095765/55460383-713ac880-5624-11e9-885c-fc63fab786c3.png)
![image](https://user-images.githubusercontent.com/10095765/55460406-7bf55d80-5624-11e9-8d0a-72248b9f6b46.png)

ref: https://pms.deepin.cn/index.php?m=story&f=view&storyID=231

**Comment by liuwenhuan** [comment]
我们正在研究在文件管理器中，直接集成刻录功能。不过该功能正式提供的时间尚未确定。

Gary Wang <notifications@github.com> 于2019年3月1日周五 下午3:21写道：

**Comment by BLumia** [comment]
@zhuxiujuancindy 相关文案 :joy:

**Comment by BLumia** [comment]
pms同步需要，重开 #1046 ，关掉这个了。
