### ISSUE TITLE
控制中心-键盘快捷键增加重置/恢复默认选项

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1001]
![](http://ww1.sinaimg.cn/large/9f7599c7gy1g0nch8u16vj20d704bglo.jpg)

gnome的图有键盘快捷键恢复默认的选项
deepin没有，这样用户改了快捷键之后想改回来有些麻烦。

**Comment by wangjia12** [comment]
15.11加上。
