### ISSUE TITLE
屏幕旋转后，控制中心没有靠边显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1003]
【测试步骤】
在笔记本上进行屏幕旋转操作，查看控制中心显示

【预期结果】
旋转成功后，控制中心靠边显示

【测试结果】
控制中心没有靠边显示

【问题级别】
一般

【出现概率】
40%
![image](https://user-images.githubusercontent.com/12492745/53705434-6b07cf80-3e5f-11e9-9c81-4b8c83e2609a.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/41826

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
