### ISSUE TITLE
#建议 用户清除指纹的时候，不能逐个删除，只能一次删除所有指纹

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#101]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.录入多个指纹，点击清除指纹
【预期结果】
可以删除指定指纹
【测试结果】
所有指纹都被删除
【问题级别】
建议
【出现概率】
稳定

**Comment by yefeifei** [comment]
@wangjia12

**Comment by zccrs** [comment]
@justforlxz 确定一下接口能不能一个个删除

**Comment by justforlxz** [comment]
![image](https://user-images.githubusercontent.com/12298476/47829961-d7e15f00-ddc4-11e8-86f1-ed9611d77fd1.png)

只支持删一个用户的全部指纹

**Comment by wangjia12** [comment]
那没办法就这样吧
