### ISSUE TITLE
任务栏上高效模式下的显示桌面按钮

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1011]
希望【高效模式】下， dock 最右边，显示桌面按钮边长一些， 在4k屏幕，2.0缩放时，鼠标放到最右边是点击不到的， 必须得往左移动一点点

https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=175216&pid=564159&fromuid=27275

**Comment by zccrs** [comment]
高分屏缩放问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
