### ISSUE TITLE
拷贝文件进度显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1012]
【测试步骤】
打开文件管理器，任意选中一个iso拷贝到U盘
然后再次选中一个100多M的文件拷贝到U盘

【预期结果】
拷贝进度显示正确

【测试结果】
拷贝进度显示错误

【问题级别】
一般

【出现概率】
100%
![_dde-file-manager_20190304153216](https://user-images.githubusercontent.com/12492745/53717418-141bed80-3e93-11e9-80a7-18bdec472048.png)

**Comment by zccrs** [comment]
因为计算U盘复制文件速度是读取的系统中实际往U盘已写入的数据量，无法区分是哪个复制任务写入的，因此有多个往U盘复制的任务时速度不正确

**Comment by liuwen123** [comment]
还是存在问题
1、文件还没有完全拷贝完成，进度条就已经显示100%了
2、文件已经拷贝完成，100%进度条不消失
![深度截图_选择区域_20190426105104](https://user-images.githubusercontent.com/12492745/56780359-967cba00-6811-11e9-95e5-4f63dbe29076.png)
![深度截图_选择区域_20190426105249](https://user-images.githubusercontent.com/12492745/56780361-967cba00-6811-11e9-9866-b754f8517d89.png)

**Comment by zccrs** [comment]
> 还是存在问题
> 1、文件还没有完全拷贝完成，进度条就已经显示100%了
> 2、文件已经拷贝完成，100%进度条不消失
> ![深度截图_选择区域_20190426105104](https://user-images.githubusercontent.com/12492745/56780359-967cba00-6811-11e9-95e5-4f63dbe29076.png)
> ![深度截图_选择区域_20190426105249](https://user-images.githubusercontent.com/12492745/56780361-967cba00-6811-11e9-9866-b754f8517d89.png)

这个已经和本任务无关了, 新建任务吧
