### ISSUE TITLE
[功能需求]深度影院按住下键（快进）时实现帧的连续播放

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1013]
用户建议
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174966

**Comment by wangjia12** [comment]
已经记录，会在后面版本改进，但是时间应该比较久。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
