### ISSUE TITLE
U盘不显示磁盘容量进度条

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1014]
【测试步骤】
插入U盘，U盘名称较长，查看磁盘容量显示

【预期结果】
磁盘容量进度条显示正常

【测试结果】
磁盘容量没有显示

【问题级别】
一般

【出现概率】
100%
![_dde-file-manager_20190304163740](https://user-images.githubusercontent.com/12492745/53720658-3fefa100-3e9c-11e9-94a7-dfdae3d3bc8b.png)

**Comment by zhaofangfangdeepin** [comment]
这个问题依然存在。只要label需要用两行显示的时候，就没有容量的显示了。
![深度截图_选择区域_20190404134749](https://user-images.githubusercontent.com/14539782/55532401-54fc6180-56e0-11e9-839a-e20fd816e8d2.png)

**Comment by zccrs** [comment]
@chirs241097 这个问题 @BLumia 应该知道原因，要是不好修就放到最后处理

**Comment by zccrs** [comment]
@wangjia12 这个放后面处理

**Comment by BLumia** [comment]
assoc: https://github.com/linuxdeepin/developer-center/issues/998

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
