### ISSUE TITLE
英文安装家目录下有中文的“模板”目录

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1016]

**Comment by listenerri** [comment]
@BLumia 
来看看：
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175236&extra=

**Comment by listenerri** [comment]
@liuwen123 
麻烦你什么时候装新系统的时候留一下，看是不是有这个情况

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1018

我装了一遍确实出现了

**Comment by BLumia** [comment]
可以看看是不是WPS创建的？文件管理器创建的模板文件夹应该不是中文的。

**Comment by liuwen123** [comment]
> @liuwen123
> 麻烦你什么时候装新系统的时候留一下，看是不是有这个情况

有

**Comment by BLumia** [comment]
WPS 的问题 :joy:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
