### ISSUE TITLE
Xrdp/Vnc远程桌面下dde-dock不显示

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1017]
用户反馈
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175225

deepin安装xrdp作为远程端，本地端通过rdp客户端连接后dde-dock不显示。

我在办公电脑上安装后确认存在问题。

**Comment by lq95v5** [comment]
用户反馈更新 vnc下dde-dock也无法使用。

**Comment by zccrs** [comment]
15.9.3 阶段看一下

**Comment by zhaofangfangdeepin** [comment]
vnc配置步骤：
方法：使用x11vnc和remmina两个工具，搭建远程连接环境
服务器上安装x11vnc，构建vnc的服务端：

sudo apt-get install x11vnc

设置并存储vnc连接密码为deepin

sudo x11vnc -storepasswd deepin /etc/x11vnc.pass

启动 x11vnc服务端

sudo x11vnc -display :0 -auth /var/run/lightdm/root/:0 -forever -bg -o /var/log/x11vnc.log -rfbauth /etc/x11vnc.pass -shared -noxdamage -xrandr "resize" -rfbport 5900

客户端安装并启动remmina：

sudo apt-get install remmina -y
remmina
选择VNC服务，直接输入服务端的IP，输入前面服务端设置的连接密码进行链接：

按照这个方法，使用vnc正常。

**Comment by zccrs** [comment]
@zhaofangfangdeepin xdrp也测一下吧

**Comment by zhaofangfangdeepin** [comment]
xrdp 使用步骤：
1.在deepin OS端使用命令sudo apt-get install xrdp -y 。注销系统。
2.打开windows 客户端：远程桌面链接，输入 deepin OS的IP地址和用户名，确定。

xrdp使用访问deepin15.9.3，远程图形界面显示正常。

**Comment by wphu** [comment]
> xrdp 使用步骤：
> 1.在deepin OS端使用命令sudo apt-get install xrdp -y 。注销系统。
> 2.打开windows 客户端：远程桌面链接，输入 deepin OS的IP地址和用户名，确定。
> 
> xrdp使用访问deepin15.9.3，远程图形界面显示正常。

嗯，工作站更新到了15.9.3，xrdp可以正常使用了，以前不行。
不过家里的台式机更新到15.9.3，用surface3的远程桌面连接deepin，dock和control-center还是不出来。。。 奇了怪
