### ISSUE TITLE
安装镜像，在英语模式下安装在~/下有多余的‘模板’文件夹

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1018]
![](http://ww1.sinaimg.cn/large/9f7599c7gy1g0rvjoxezfj20zq0qthaz.jpg)

如图，我在虚拟机安装选择英语，会有多余的‘模板’文件夹

**Comment by lq95v5** [comment]
![](http://ww1.sinaimg.cn/large/9f7599c7gy1g0rvlc2giuj20y30kvtmt.jpg)

**Comment by BLumia** [comment]
和 #1016 重复，先关掉这个了
