### ISSUE TITLE
字体设置为最大，小窗口launcher日期显示不全

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1019]
【测试步骤】
将launcher设置为小窗口，然后设置字体为最大，查看小窗口日期显示

【预期结果】
日期显示正常

【测试结果】
日期显示不全

【问题级别】
一般

【出现概率】
100%
![_ _20190305140152](https://user-images.githubusercontent.com/12492745/53784209-7c300980-3f4f-11e9-9fff-30ec7d868131.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/41852

https://tower.im/teams/9487/todos/230605/

**Comment by liuwen123** [comment]
+1

**Comment by zhaofangfangdeepin** [comment]
@justforlxz 这个怎么放在15.9.2里程碑里面了？
dde-launcher:
  已安装：4.6.6-1
  候选： 4.6.6-1

并没有修复这个问题

**Comment by justforlxz** [comment]
4.6.7修复的

zhaofangfangdeepin <notifications@github.com> 于2019年3月6日周三 上午9:55写道：

**Comment by liuwen123** [comment]
已修复
