### ISSUE TITLE
系统只有一个账户时，关机界面出现切换用户的入口

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1021]
【测试环境】
Deepin15.9.1环境升级到内测Deepin15.9.2
dde-session-ui:
  已安装：4.8.11-1
【测试步骤】
1.在Deepin15.9.1的系统上，添加内部测试源，升级到Deepin15.9.2
2.升级完成之后，点击关机-查看关机界面。
【预期结果】
1.升级完成之后，关机界面显示正常。
【测试结果】
1.升级完成之后，关机界面显示异常。只有一个账户时，存在用户切换入口
【问题级别】
一般
【出现概率】
稳定出现

**Comment by zhaofangfangdeepin** [comment]
![_ _20190305151406](https://user-images.githubusercontent.com/14539782/53787733-be127d00-3f5a-11e9-975d-24661c341df0.gif)

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/developer-center/issues/886 

https://cr.deepin.io/#/c/dde/dde-session-ui/+/41884/
