### ISSUE TITLE
切换用户鼠标焦点会被锁住，键盘无法输入

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1023]
【测试步骤】
在控制中心新建两个用户a，b，登录a成功后再切换到b用户，再次切换到a用户

【预期结果】
可以正常输入并登录

【测试结果】
键盘无法输入

【问题级别】
严重

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41861/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
