### ISSUE TITLE
深度影院窗口分屏之后，切换到“迷你模式”，窗口大小显示异常

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1024]
【测试环境】
deepin-movie:
  已安装：3.2.20-1
deepin-wm:
  已安装：1.9.37-1
【预置条件】

【测试步骤】
1.打开深度影院，播放任意视频。
2.拖动深度影院窗口到右下角，触发窗口分屏
3.切换深度影院为mini模式
【预期结果】
窗口分屏模式下，切换到mini模式，影院窗口显示正常。
【测试结果】
窗口分屏模式下，切换到mini模式，影院窗口显示异常
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20190306104506](https://user-images.githubusercontent.com/14539782/53852579-798bed80-3ffd-11e9-9673-2f1fc62a94bd.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
