### ISSUE TITLE
之前的“显示桌面”图标默认不在dock上

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#103]
【测试环境】

【预置条件】

【测试步骤】

【预期结果】
因为高效模式已经有右下角显示桌面了，所以不需要左边的大图标。时尚模式也许还需要，所以就默认去掉在dock上的显示，需要的话自己添加到dock。

【测试结果】

【问题级别】

【出现概率】

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-desktop-schemas/+/39377/

**Comment by zhaofangfangdeepin** [comment]
测试通过
