### ISSUE TITLE
dock点击右键--所有窗口，窗口软件大小显示异常

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1030]
【测试步骤】
升级到最新系统，打开两个文件管理器窗口，在dock选中文件管理器，右键--所有窗口

【预期结果】
显示文件管理器窗口正常

【测试结果】
窗口显示异常

【问题级别】
严重

【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
