### ISSUE TITLE
最近使用中有太多文件，打开文管特别慢

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1033]
【测试步骤】
打开文件管理器，在最近使用中添加很多个文件，然后重新打开文件管理器

【预期结果】
可以正常打开文件管理器

【测试结果】
文件管理器打开很慢

【问题级别】
一般

【出现概率】
100%

**Comment by BLumia** [comment]
#977 重复，关掉这个了 :)
