### ISSUE TITLE
重新测试文件管理器快速搜索功能

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1034]
更新deepin-anyting 到0.0.4+r25+gd5fff65(或更高版本)
文件管理器到4.7.7.1+r8+g58d7cc89(或更高版本)

重写了快速搜索的实现(包含设置中的 "索引" 功能)

需要关注的问题:

* 索引内部磁盘和外部磁盘的设置项是否生效
* 开启快速搜索后是否能快速的正确搜到文件
* 索引数据是否会更新(新建/删除/重命名文件时)
* deepin-anything-tool 进程是否存在崩溃问题(测试全过程安装其已经其依赖包的debug包, 并安装systemd-coredump)

辅助性测试工具:

工具提供了 com.deepin.anything dbus接口

* qdbus --system com.deepin.anything /com/deepin/anything com.deepin.anything.allPath 返回当前已创建所以数据的所有目录
* qdbus --system com.deepin.anything /com/deepin/anything com.deepin.anything.autoIndexInternal 返回是否开启"内置磁盘索引"
* qdbus --system com.deepin.anything /com/deepin/anything com.deepin.anything.autoIndexExternal 返回是否开启"外置磁盘索引"
* qdbus --system com.deepin.anything /com/deepin/anything com.deepin.anything.sync "" 将内存中的所有索引数据同步到硬盘, 保存在 /var/cache/deepin/deepin-anything 目录, 后缀名为 .LFT

**Comment by zccrs** [comment]
测出来的问题在此楼建立检查项

**Comment by liuwen123** [comment]
- [ ] 搜索结果为空，/usr/bin/deepin-anything-monitor  在搜索的过程中会出现，搜索完成后就退出了
![_dde-file-manager_20190307140947](https://user-images.githubusercontent.com/12492745/53936564-23927500-40e5-11e9-828e-141a822c2636.png)

**Comment by zhaofangfangdeepin** [comment]
测试通过
