### ISSUE TITLE
更新完成之后，重启系统之后，打开控制中心-首页-依然会有更新提示

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1035]
【测试环境】
dde-control-center:
  已安装：4.9.4-1
【预置条件】
Deepin5.9.1 系统
【测试步骤】
1.在Deepin15.9.1系统上，添加内部测试源。打开控制中心-更新-检查更新-下载并安装更新。
2.更新安装完成之后，重启系统，打开控制中心-首页，检查是否存在更新提示
【预期结果】
1.没有更新提示
【测试结果】
1.依然存在更新提示
【问题级别】
一般
【出现概率】
概率出现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/41882/

**Comment by zhaofangfangdeepin** [comment]
测试通过
