### ISSUE TITLE
遇到了一次更新完成系统之后，启动器中没有深度音乐的应用程序

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1036]
【测试环境】
deepin-fpapp-org.deepin.flatdeb.deepin-music
3.1.14
【预置条件】
Deepin15.9.1 系统
【测试步骤】
1.系统从Deepin15.9.1 添加内部测试仓库，升级到Deepin15.9.2.
2.升级完成之后，打开启动器，搜索音乐，查看是否存在深度音乐应用。
【预期结果】
1.存在深度音乐应用
【测试结果】
1.不存在深度音乐应用
【问题级别】
一般
【出现概率】
遇到了一次，重装了深度音乐之后，该现象消失

**Comment by listenerri** [comment]
@zhaofangfangdeepin 
应该用 dpkg 先确定一下包装了没吧？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
