### ISSUE TITLE
多选本地deb包时，打开方式-软件包管理器。只导入了一个deb包

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1037]
【测试环境】
deepin-deb-installer 1.3.0-1
【预置条件】

【测试步骤】
1.下载多个deb包到本地，选中多个deb包。右键-打开方式-软件包管理器。
【预期结果】
1.打开软件包管理器，可以导入选中的多个deb包
【测试结果】
打开的软件包管理器，只导入了一个deb包
【问题级别】
一般
【出现概率】
稳定出现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/deepin-deb-installer/+/41891

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
