### ISSUE TITLE
com.deepin.daemon.SoundEffect 改接口

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#1038]
为了方便实现 登录音效配置同步到系统级别，改动 com.deepin.daemonSoundEffect 的接口

https://cr.deepin.io/#/c/dde/dde-daemon/+/41874/

新增方法：
  EnableSound(name s, enabled b) -> ()
  GetSoundEnabledMap() -> (result a{sb})
  GetSoundFile(name s) -> (file s)
  IsSoundEnabled(name s) -> (enabled b)
  PlaySound(name s) -> ()

废弃：
  GetSystemSoundFile(name s) -> (file s)
  PlaySystemSound(name s) -> ()

dde-control-center 配合修改

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/42019/

**Comment by zhaofangfangdeepin** [comment]
![image](https://user-images.githubusercontent.com/14539782/54892971-a7729c80-4eee-11e9-8c42-17a50edd4383.png)
废弃的接口并没有废弃
@electricface 小哥说等到大版本的时候手动废弃，这个任务留着跟踪一下吧。

**Comment by zhaofangfangdeepin** [comment]
新增接口测试通过
废弃的接口没有删除。需要在大版本中再次回归废弃的接口是否删除。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
