### ISSUE TITLE
数位板相关文案修改

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1041]
![image](https://user-images.githubusercontent.com/34529003/53946319-762c5b00-40fe-11e9-8a8f-c57876f39824.png)
Pressure Sensitive 改为Pressure Sensitivity
light 和 heavy 首字母大写

**Comment by chirs241097** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41906
