### ISSUE TITLE
把dde-shutdown和dde-lock的重启从session-ui-guardien换到startdde的watchdog

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#1042]
现在已经不需要session-ui-guardien监控屏幕发生变化来重启这两个进程来避免一些问题了，监控进程的动作可以由startdde来做。

**Comment by justforlxz** [comment]
只在国产化平台上启用dde-lock --daemon和dde-shutdown --daemon.

**Comment by electricface** [comment]
@zccrs @hualet  国产化平台有必要有这个功能吗？

**Comment by hualet** [comment]
> @zccrs @hualet 国产化平台有必要有这个功能吗？

考虑常驻主要是加速界面显示，后端实现有什么难点么？

**Comment by zccrs** [comment]
> > @zccrs @hualet 国产化平台有必要有这个功能吗？
> 
> 考虑常驻主要是加速界面显示，后端实现有什么难点么？

目前是常驻的吧，这个自动拉起来说的不是进程异常退出后被自动拉起吗

**Comment by justforlxz** [comment]
startdde支持一下配置文件形式添加watchdog的内容吧，然后安装session-ui的时候我添加进去。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
