### ISSUE TITLE
多项 Bug

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1059]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175328&extra=

下面是这两个帖子中有价值的两个问题：

- [ ] dtk主题应用在gtk应用上时，窗口最大化左右上角居然有圆角空隙
- [ ] deepin-greeter登陆，触摸板轻触无效必须要左键点击

**Comment by xiaoc-arch** [comment]
补充一下：1、deepin-greeter只有在关机重启之后，触摸板不能轻触点击屏幕键盘和关机按钮，但从待机唤醒确可以
2、gnome-xxx软件全屏或贴靠屏幕左右两边会自动变直角，但dde自带软件貌似不行

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
