### ISSUE TITLE
文管地址栏使用 tab 键补全地址时有问题

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1060]
当输入到最后一层目录后（不再有子目录），再次按 tab 键就会把当前这个最后一层目录再次补全上去，最后的结果是这样的：

![图片](https://user-images.githubusercontent.com/7995379/54097238-1aa5ea00-43ea-11e9-80c5-8ea524627075.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
