### ISSUE TITLE
更新nvidia显卡驱动

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1061]
nvidia驱动有用户反应需要更新，源里的390.67太旧了

Debian sid 更新410.93了

ubuntu的ppa 更新418.43了 

需要保留nvidia 340xx 和390xx 来支持旧的gpu型号

现在valve搞得proton兼容层对显卡驱动的版本要求较高，开发进度比较快，需要更新。nvidia 415.27版本之前的驱动有可能产生gpu挂起的问题

直接添加418.43的驱动比较好。

tower： https://tower.im/teams/9487/todos/230042/

**Comment by lq95v5** [comment]
![深度截图_选择区域_20190322155009](https://user-images.githubusercontent.com/29811622/54808183-68f49c00-4cba-11e9-9c29-a9afe2714a02.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
