### ISSUE TITLE
dock 动效2

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1070]
任务来源：https://github.com/linuxdeepin/internal-discussion/issues/663

原任务完成了部分动效，拖得时间太长了，先处理掉原任务中相应的提交吧，剩下的动效放到这个任务来做。

目前剩余一个动效没做：拖拽应用程序图标驻留到任务栏的动效

相关设计如下：

[dock 动效-拖动图标进行驻留.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2955274/dock.-.tar.gz)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
