### ISSUE TITLE
键盘布局指示器放在托盘保留区域后有空白托盘

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1071]
键盘布局指示器放在托盘保留区域后再次按快捷键切换键盘布局时，就会出现空白的托盘：

文件是个视频，下载后去掉后缀 txt：

[bug.mp4.txt](https://github.com/linuxdeepin/internal-discussion/files/2955413/bug.mp4.txt)

**Comment by listenerri** [comment]
https://cr.deepin.io/#/c/dde/dde-dock/+/41950

**Comment by liuwen123** [comment]
已修复
