### ISSUE TITLE
dock 托盘 item key 以及 application key

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1072]
问题描述写的比较多，主要是为了我自己分析可行方案 : )

目前 dock 中 item key 有两个用处：
- 运行时唯一匹配到一个托盘项
- 为相应托盘项写入配置文件时作为配置项的 key

`方案一：`
以前对托盘 item key 相关的处理是：
- XEmbed：使用窗口的 id (一串数字)
- SNI：使用 DBus 上的一个 service 名称

这样做的问题是，这些 item key 的来源是动态的，同一个应用程序下次启动或者注销重启后再次启动，dock 拿到的新的 item key 跟之前的没有任何关系，那么 item key 的第二个用途，基于其保存的配置文件也就无效了。

`方案二：`
为了解决这个问题获取 item key 的方法改为了：
- XEmbed：使用窗口的 WM_CLASS
- SNI：使用 SNI 协议中 id 接口提供的数据

这个改变虽然解决了上一个问题，但是引入了新的问题，同一个应用程序启动的多个实例无法在托盘上全部显示出来，因为比如 SNI 协议下同一个程序提供的 id 接口的数据都是相同的，dock 在处理时为了保证 item key 的第一个用途有效，不允许添加使用了相同的 item key 的托盘项，这也是合乎情理的。

`方案三：`
前一段时间解决了 XEmbed 协议下的这个问题(当时没有考虑到 SNI 也有相同的问题)，使用的方法由 XEmbed 协议的 Controller 记录已经提供给 dock 的所有 item key (WM_CLASS) 如果再有使用相同 item key 的托盘项需要添加就给这个 item key 添加数字后缀 (递增)，这样可以解决问题，但感觉不是一个好方法，而且有出现同一个托盘对象使用了两个不同的 item key 的可能性。

在实施`方案三：`时 @zccrs 说可以考虑使用多值 Map 来处理，现在想想感觉也不是很好，首先目前代码的结构都是按照一对一的方式处理的，改为一对多的话代码变动应该会比较大。

`方案四：`
结合上述三种方案的缺陷，item key 的获取依然使用`方案一`的方法，但存储配置文件时使用`方案二`的方法获取一个`application key`作为配置项的 key，可以在托盘 item 的抽象层上加一个获取`application key`的接口，有具体的 item 决定自己要使用的用于存储配置的 key。

@hualet @zccrs @justforlxz @BLumia 
不知道`方案四`会不会有其他的没有考虑到的隐藏问题？

**Comment by listenerri** [comment]
相关 issue：https://github.com/linuxdeepin/developer-center/issues/885

**Comment by hualet** [comment]
应该没什么问题。SNI同一个应用的多个实例，service应该也是不同的吧？

**Comment by listenerri** [comment]
> 应该没什么问题。SNI同一个应用的多个实例，service应该也是不同的吧？

刚刚用 demo 测了下，确认是不同的

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/42022

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
