### ISSUE TITLE
将字体设置为最大，设置壁纸字体重叠

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1073]
【测试步骤】
将系统字体设置为最大，然后在桌面点击右键--壁纸

【预期结果】
字体显示正常

【测试结果】
字体和按钮会重叠

【问题级别】
一般

【出现概率】
100%
![深度截图_选择区域_20190312153459](https://user-images.githubusercontent.com/12492745/54182491-9a13e600-44dc-11e9-8d18-8468bf8fbb32.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
