### ISSUE TITLE
dde文案优化

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1076]
[dde strings to be changed.xls.zip](https://github.com/linuxdeepin/internal-discussion/files/2959637/dde.strings.to.be.changed.xls.zip)

@justforlxz @electricface 译员帮我们优化了部分dde文案，请按照New English修改一下文案。

**Comment by zhuxiujuancindy** [comment]
更新成功 Update successfully -> Updated successfully

**Comment by electricface** [comment]
问一下 Failed to active VPN connection, reason unknown 是不是 active 应该改成 activate

**Comment by electricface** [comment]
有关 PIN check failed 英文文档里就是这样的。
NM_DEVICE_STATE_REASON_GSM_PIN_CHECK_FAILED | = 34 | PIN check failed
也不一定就是提供的 PIN 不正确的意思。
https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html

**Comment by zhuxiujuancindy** [comment]
> 问一下 Failed to active VPN connection, reason unknown 是不是 active 应该改成 activate

是的 我写错了

**Comment by zhuxiujuancindy** [comment]
> 有关 PIN check failed 英文文档里就是这样的。
> NM_DEVICE_STATE_REASON_GSM_PIN_CHECK_FAILED | = 34 | PIN check failed
> 也不一定就是提供的 PIN 不正确的意思。
> https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html

那就不改吧

**Comment by electricface** [comment]
dde-daemon 项目 https://cr.deepin.io/#/c/dde/dde-daemon/+/41966

**Comment by zhuxiujuancindy** [comment]
@electricface 看了你给的链接
原译文：连接依赖失败 | A connection dependency failed
它写的是A dependency of the connection failed 与中文意思一样吗 如果是，就用这个吧

**Comment by electricface** [comment]
连接的依赖关系失败，就用【A dependency of the connection failed】原文吧

**Comment by electricface** [comment]
https://www.cnblogs.com/likebeta/archive/2012/07/03/2574595.html
VPN connection status changed 我改成 VPN connection state changed 了，代码里也是用 state

**Comment by zhuxiujuancindy** [comment]
> https://www.cnblogs.com/likebeta/archive/2012/07/03/2574595.html
> VPN connection status changed 我改成 VPN connection state changed 了，代码里也是用 state

OK

**Comment by electricface** [comment]
这个可以关闭了吗？
