### ISSUE TITLE
待机唤醒后键盘失灵,grub启动选项操作反应迟缓

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1077]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175487

三个问题：

- [ ]  待机唤醒后键盘失灵
- [ ]  grub启动选项操作反应迟缓
- [ ]  企业微信，点击大群打开时，直接卡死

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
