### ISSUE TITLE
[用户建议]更改深度文件管理器面包屑导航的地址修改方式

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1079]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175531

用户反馈

**Comment by wangjia12** [comment]
这个是从之前的设计改的，为了增加顶部可拖拽的视觉空间，暂时不会改了。

**Comment by BLumia** [comment]
另见：https://github.com/linuxdeepin/developer-center/issues/952
