### ISSUE TITLE
在桌面任意播放一首歌曲会导致最近文件内容显示为空

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1090]
【测试步骤】
打开文件管理器进入最近文件目录，然后在桌面任意双击一首歌曲使用深度音乐播放

【预期结果】
播放的歌曲被添加到最近文件中

【测试结果】
最近文件内容会被清空

【问题级别】
一般

【出现概率】
100%
![深度截图_dde-file-manager_20190315100443](https://user-images.githubusercontent.com/12492745/54403187-163f4100-470a-11e9-885c-fdf1cd97f980.png)

**Comment by BLumia** [comment]
@chirs241097 修复 bug 后记得把 issue 指派给测试 :)

**Comment by liuwen123** [comment]
已修复
