### ISSUE TITLE
编辑按钮没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1092]
【测试步骤】
在默认程序中添加新程序，然后再编辑删除

【预期结果】
编辑按钮显示正常

【测试结果】
编辑按钮没有翻译

【问题级别】
一般

【出现概率】
100%
![深度截图_选择区域_20190315101428](https://user-images.githubusercontent.com/12492745/54403515-3f140600-470b-11e9-8c20-db25ae320c16.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41988

**Comment by liuwen123** [comment]
已修复
