### ISSUE TITLE
当手动安装应用比仓库版本高时，update如果检测到，应用会被降级与仓库同步。

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#11]
此策略我们已在社区宣导，但依然不定期有人咨询。

是否可以控制中心做一个开关，默认是关闭的，策略依然是降级。

当把开关打开，就不会自动降级，而是跳过。

同时弹窗二次确认以及文案提醒：打开此开关会带来XX后果，是否开启等等

@wangjia12  @deepinzhangshuang @hualet

**Comment by hualet** [comment]
去掉降级策略了，更新注记里面提一下吧。
