### ISSUE TITLE
安装完成提示重启前拔掉u盘，但是拔掉直接就字符显示了<周四>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#110]
【测试环境】：
deepin-installer  2.4.2-1
【测试步骤】：
1.安装完成后，提示“重启前拔掉U盘”，但是拔掉u盘直接进入黑屏字符界面了。
【预期结果】：
1.拔掉u盘不会进入黑屏字符界面，正常重启。

**Comment by hualet** [comment]
这是安装器崩溃了？

**Comment by hualet** [comment]
@justforlxz

**Comment by hualet** [comment]
这个可以考虑换文案之类的了 @CallMeR

**Comment by zccrs** [comment]
@hualet 这个还搞吗

**Comment by zhaofangfangdeepin** [comment]
这个还搞吗

**Comment by wangjia12** [comment]
这个本质是“u盘直接进入黑屏字符界面”这个bug要修好，不是改需求和设计，你们抓紧时间看看这个问题吧，既然之前是好的就快修好吧。

**Comment by hualet** [comment]
> 这个本质是“u盘直接进入黑屏字符界面”这个bug要修好，不是改需求和设计，你们抓紧时间看看这个问题吧，既然之前是好的就快修好吧。

这个以前不一定是没有问题的 现在这个问题也不是稳定出现的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
