### ISSUE TITLE
dock 翻译有误

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1103]
![图片](https://user-images.githubusercontent.com/7995379/54412115-865ebe80-472c-11e9-8982-2f60867b9050.png)

**Comment by listenerri** [comment]
中文少了一个占位

**Comment by zhuxiujuancindy** [comment]
> @zhuxiujuancindy
> 中文少了一个占位

已改为%1插件和系统版本不兼容。

**Comment by listenerri** [comment]
回归的时候测一下吧

**Comment by liuwen123** [comment]
已修复
