### ISSUE TITLE
切换屏幕缩放提示没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1104]
【测试步骤】
打开控制中心切换屏幕缩放，系统会弹出提示

【预期结果】
提示已经翻译

【测试结果】
提示没有翻译

【问题级别】
一般

【出现概率】
100%
![image](https://user-images.githubusercontent.com/12492745/54416174-a21c9180-4739-11e9-99e6-ea1beef6e5b9.png)

**Comment by electricface** [comment]
已更新翻译

**Comment by liuwen123** [comment]
已修复
