### ISSUE TITLE
从smb复制文件到管理员身份打开的文件夹中，提示源文件不存在

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1105]
【测试步骤】
打开文件管理器进入smb，新开一个窗口任意选中一个目录，以管理员身份打开
从smb拷贝文件到管理员打开的目录中

【预期结果】
可以正常拷贝

【测试结果】
提示源文件不存在

【问题级别】
一般

【出现概率】
100%
![image](https://user-images.githubusercontent.com/12492745/54416819-6e426b80-473b-11e9-9638-a0ad4949da12.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
