### ISSUE TITLE
创建共享热点后，dock上的WiFi列表勾选显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1106]
【测试步骤】
在控制中心创建共享热点，创建成功后查看dock的WiFi列表显示

【预期结果】
显示为共享热点

【测试结果】
还是显示原来的WiFi列表

【问题级别】
一般

【出现概率】
小概率
![深度截图_选择区域_20190315172050](https://user-images.githubusercontent.com/12492745/54421376-48bb5f00-4747-11e9-9664-03dfa1c82ce8.png)
![深度截图_选择区域_20190315172036](https://user-images.githubusercontent.com/12492745/54421377-4953f580-4747-11e9-816d-68ff201b80bb.png)

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/dde-dock/pull/151

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
