### ISSUE TITLE
关机提示没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1107]
![深度截图_选择区域_20190315173257](https://user-images.githubusercontent.com/12492745/54421969-781e9b80-4748-11e9-99c3-25601f48bc32.png)

**Comment by justforlxz** [comment]
翻译已更新，内网源测试。

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
