### ISSUE TITLE
挂载iphone手机，打开图片进行左右点击时，不能轮循图片

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#111]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
【测试步骤】：
1.挂在iPhone手机，深度看图打开里面图片，并点击左右按钮，图片不会切换。

**Comment by zccrs** [comment]
这个不是问题，所有的flatpak应用无法打开非家目录以外的文件。
关于flatpak文件隔离机制的问题再另外讨论
