### ISSUE TITLE
填写用户全名后，切换用户时，用户名称会连在一起

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1111]
【测试步骤】
新建多个用户，然后填写全名，再进行切换用户

【预期结果】
在切换用户界面，用户名称显示清楚

【测试结果】
用户名连在一起

【问题级别】
一般

【出现概率】
100%
![深度截图_选择区域_20190318132507](https://user-images.githubusercontent.com/12492745/54508647-7a1f6f00-4981-11e9-9405-16712aea61f7.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
