### ISSUE TITLE
grub界面选项文字显示不全

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#112]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
【测试步骤】：
1.安装完系统，重启进入grub界面，发现grub选项显示不全。
![img_0068](https://user-images.githubusercontent.com/12388744/47785653-50eca200-dd44-11e8-9800-03d4a104ac13.JPG)

**Comment by wangjia12** [comment]
@shule1987 看一下效果，是否需要调整

**Comment by shule1987** [comment]
只在分辨率很低的情况下才会这样, 且不影响使用, 暂不处理
