### ISSUE TITLE
建议增加提示 overlay 的功能

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1126]
驱动管理器测试驱动时会启动 overlay，虽说代码中会关闭 overlay，但仍然有很多用户出现了 overlay 没有关掉的问题，导致数据丢失，后果严重，目前不知道是 overlay 自己的问题，还是某种用户操作导致的。

建议在桌面某个显眼的地方提示当前处于 overlay 模式，点击可以关闭它，比如任务栏插件

另外我也修改下驱动管理器的代码，尽量避免这种事情出现。

**Comment by wangjia12** [comment]
“建议在桌面某个显眼的地方提示当前处于 overlay 模式”

可是这个提示太匪夷所思了，有的用户都不明白这是什么意思，能不能从根本上找到原因，解决无法关闭的问题。这相当于是因为bug做了一个提示的功能，还让人不懂是什么意思。

**Comment by listenerri** [comment]
> “建议在桌面某个显眼的地方提示当前处于 overlay 模式”
> 
> 可是这个提示太匪夷所思了，有的用户都不明白这是什么意思，能不能从根本上找到原因，解决无法关闭的问题。这相当于是因为bug做了一个提示的功能，还让人不懂是什么意思。

这个 bug 带来的问题很严重呀，最好还是提醒下，而且就算不是因为驱动管理器创建的 overlay，而是用户自己手动创建的，我觉得也应该有提示，至少可以让用户明确知道当前的变动不会被保存，我就吃过这亏

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1143#issuecomment-474697597

**Comment by wangjia12** [comment]
1. 进入overlay模式后开机弹出对话框，内容如下；
2. 如果点击取消按钮，在overlay模式下，dock插件区域显示一个图标，一直提示用户，点击这个图标再打开对话框。

【本次启动处于 overlay 保护模式下，您的所有操作将不会被保存，是否要关闭此模式并重启？】
【取消】
【关闭并重启】
@zhuxiujuancindy 
@shule1987 需要一个图标

**Comment by shule1987** [comment]
[warning.svg.zip](https://github.com/linuxdeepin/internal-discussion/files/2986852/warning.svg.zip)

**Comment by zhuxiujuancindy** [comment]
【本次启动处于 overlay 保护模式下，您的所有操作将不会被保存，是否要关闭此模式并重启？】
【The system is in overlay mode, and all your work will not be saved. Do you want to exit and restart?】
【取消】【Cancel】
【关闭并重启】Restart】

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/dde-dock/pull/155

**Comment by liuwen123** [comment]
已修复
