### ISSUE TITLE
libomp-dev这个包依赖有问题

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1127]
libomp-dev 这个包依赖 libomp-7-dev，但是 libomp-7-dev 不存在。

内网和外网都有这个问题，我是在外网源的机器上发现的。
以前这个 libomp-dev 的依赖是正常的，最近外网更新后提示 libomp-dev 要更新，但是却升不上去，手动升级发现有这个依赖问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
