### ISSUE TITLE
两个问题：软件源中obs-studio闪退，搜狗输入法内存溢出

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1128]
- [ ] 用户测试  obs-studio 闪退 已验证
Package: obs-studio
Version: 21.0.2+dfsg1-1
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175704

- [ ] sogou输入法内存溢出

https://bbs.deepin.org/forum.php?mod=viewthread&tid=175697

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
