### ISSUE TITLE
建议回收站中有隐藏文件时，直接显示隐藏文件

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1129]
发现一个问题，当回收站中有隐藏文件时，状态栏和dock回收站显示的个数不一致，可能会导致用户以为是一个Bug，
看了一下鹦鹉螺，鹦鹉螺的回收站是直接将隐藏文件显示出来的，状态栏和dock提示就保持一致了

![深度截图_选择区域_20190319102441](https://user-images.githubusercontent.com/12492745/54576072-b4484980-4a31-11e9-96ad-44770390e0f5.png)

![深度截图_nautilus_20190319103119](https://user-images.githubusercontent.com/12492745/54576209-2b7ddd80-4a32-11e9-985b-fce40a16f25d.png)

**Comment by wangjia12** [comment]
别的目录下显示或者不显示隐藏文件时，最下面的项数都是随之变化的，为什么回收站不能显示真实的数量？ @zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
