### ISSUE TITLE
[建议]应用商店的 非原生软件 注明软件适配信息

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1131]
![](https://bbs.deepin.org/data/attachment/forum/201903/19/104202uzo8yiaw5ttrzaz8.png)

用户建议 
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175718

**Comment by wangjia12** [comment]
![image](https://user-images.githubusercontent.com/34432879/54582510-e6ff3b80-4a4b-11e9-81fa-0deee95b13b5.png)
后面有计划先把安卓应用标明出来，其他应用看后期情况。

**Comment by wangjia12** [comment]
已经在下一个商店版本规划中了。
