### ISSUE TITLE
15.9.2 Beta 问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1132]
- [ ] 4K高分屏支持不友好
- [ ] 浏览器或者视频播放器在全屏下看视频，会黑屏
- [ ] 使用屏幕缩放后，virtualbox里的分辨率异常
- [ ]  当系统语言使用American Egnlish的时候，
        dedit打开文本中文乱码
        dedit保存中文乱码  dedit的默认文本编码问题
![094749ekihsydk9vzzdhhd](https://user-images.githubusercontent.com/29811622/54579327-ecee2000-4a3d-11e9-9a05-0baf076f1b0b.gif)

- [ ]  显卡管理器驱动切换失败，NV-prime不支持
[deepin-graphics-driver-manager.log.zip](https://github.com/linuxdeepin/internal-discussion/files/2981468/deepin-graphics-driver-manager.log.zip)
[deepin-feedback-cli-Deepin-15.9.2-all-20190319-085659 (1).tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2981472/deepin-feedback-cli-Deepin-15.9.2-all-20190319-085659.1.tar.gz)

- [ ] 播放了一个webm文件后，深度影院，恢复，出现黑边。
![014527sy636r69a6ma9i9o](https://user-images.githubusercontent.com/29811622/54579304-cd56f780-4a3d-11e9-903e-46056a4378f6.png)

**Comment by lq95v5** [comment]
窗口管理器的bug

https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=175602&pid=569783&fromuid=101846

**Comment by lq95v5** [comment]
1.默认主题图标显示不完整。
![200818nshxk969k6fgg19k](https://user-images.githubusercontent.com/29811622/55298622-50764580-5461-11e9-8ff4-b3a50e292421.png)

2.文件共享老问题！ 手动输入ip时能默认smb:// 而不是smb行吗？

![201626nrcpc172c7z7fdpf](https://user-images.githubusercontent.com/29811622/55298646-6a178d00-5461-11e9-9b2d-5b3c6ff3a24f.png)

**Comment by lq95v5** [comment]
打开一个wine应用，待机几小时，唤醒有问题，打开的应用，全被清掉了。
[deepin-feedback-cli-Deepin-15.9.2-all-20190326-075423 (1).tar.gz](https://github.com/linuxdeepin/internal-discussion/files/3027446/deepin-feedback-cli-Deepin-15.9.2-all-20190326-075423.1.tar.gz)

**Comment by BLumia** [comment]
> 手动输入ip时能默认smb:// 而不是smb行吗？

这个是啥意思，没看懂啊...

**Comment by lq95v5** [comment]
> > 手动输入ip时能默认smb:// 而不是smb行吗？
> 
> 这个是啥意思，没看懂啊...

已修改

**Comment by BLumia** [comment]
> > > 手动输入ip时能默认smb:// 而不是smb行吗？
> > 
> > 
> > 这个是啥意思，没看懂啊...
> 
> 已修改

这不可能啊，只输入 IP 地址的话我没法知道你输的是 ftp 还是 smb 还是 sftp 还是别的协议呀...

**Comment by lq95v5** [comment]
> > > > 手动输入ip时能默认smb:// 而不是smb行吗？
> > > 
> > > 
> > > 这个是啥意思，没看懂啊...
> > 
> > 
> > 已修改
> 
> 这不可能啊，只输入 IP 地址的话我没法知道你输的是 ftp 还是 smb 还是 sftp 还是别的协议呀...
> 
> 以及输入 smb://x.x.x.x/ 和 smb:/// **不是**等价的

实在深度文件管理器-网络邻居-windows网络下smb协议默认填充的是smb:///  而不是smd://
![深度截图_选择区域_20190401100535](https://user-images.githubusercontent.com/29811622/55299483-bbc21680-5465-11e9-812c-28fce4aaca3f.png)

**Comment by BLumia** [comment]
> 是在深度文件管理器-网络邻居-windows网络下smb协议默认填充的是smb:/// 而不是smb://
> ![深度截图_选择区域_20190401100535](https://user-images.githubusercontent.com/29811622/55299483-bbc21680-5465-11e9-812c-28fce4aaca3f.png)

这个默认填充和你当前在哪个位置是没有关系的啊，你默认填充了 smb:/// 是因为你之前手动输入过 smb:/// 并按下回车访问过这个位置，于是被记成历史记录了。实际上文件管理器并没有任何直接访问 smb:/// 的入口，我们提供的入口是 `network:///`

**Comment by lq95v5** [comment]
![深度截图_选择区域_20190401141715](https://user-images.githubusercontent.com/29811622/55307089-ff7a4780-5488-11e9-99a5-5637dbc745de.png)

测试版的motd没有修改

**Comment by lq95v5** [comment]
显卡驱动（锐龙2500U的核显），驱动版本太低，无法开启窗口特效。但是在unstable版的可以。
https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=175601&pid=570822&fromuid=101846

**Comment by hualet** [comment]
> ![深度截图_选择区域_20190401141715](https://user-images.githubusercontent.com/29811622/55307089-ff7a4780-5488-11e9-99a5-5637dbc745de.png)
> 
> 测试版的motd没有修改

这个 @deepinzhangshuang 处理一下呀

**Comment by lq95v5** [comment]
文管问题：文管中文件夹属性中，文件夹下文件数量不对。
文件夹下有5个文件，没有隐藏文件。通过ls -a看到是5个文件，文官属性却显示6个文件。
![](https://bbs.deepin.org/data/attachment/forum/201904/01/233912dufll8tfag7a547j.png)

**Comment by BLumia** [comment]
> 文管问题：文管中文件夹属性中，文件夹下文件数量不对。
> 文件夹下有5个文件，没有隐藏文件。通过ls -a看到是5个文件，文官属性却显示6个文件。
> 
> ![233912dufll8tfag7a547j](https://user-images.githubusercontent.com/29811622/55394631-5445bd00-5572-11e9-9e74-ebee78ed31c4.png)

这个我之前问过，不是 bug，那个统计包含当前文件夹自身

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
