### ISSUE TITLE
当程序有较多窗口时 dock 预览显示不正确

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1134]
bug：

![bug](https://user-images.githubusercontent.com/7995379/54655780-24240600-4afe-11e9-877e-5d67f6152cf3.png)

改动后：

![修复](https://user-images.githubusercontent.com/7995379/54655853-59305880-4afe-11e9-86f5-6a0465288de0.png)

这是个以前遗留的问题，当时没有彻底处理好，后来我找时间做了一部分提交，但有小问题一直在 cr 上没接着处理，现在已经完善改动，迁移到 github 上了，相关 pr：

https://github.com/linuxdeepin/dde-dock/pull/150

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
