### ISSUE TITLE
相同分辨率大小的图片，预览显示大小不一致

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1135]
【测试步骤】
将多张相同的分辨率图片放在同一个目录中，任意选中一张按空格预览
出现预览后，按→键，查看预览大小显示

【预期结果】
预览大小不变

【测试结果】
预览大小会变小

【问题级别】
一般

【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
