### ISSUE TITLE
预览字体会导致文件管理器崩溃

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1137]
【测试步骤】
打开文件管理器任意选中一个otf文件，按空格进行预览

【预期结果】
可以正常预览

【测试结果】
会导致文件管理器崩溃

【问题级别】
严重

【出现概率】
100%

`(gdb) bt
#0  0x00007fffab563320 in dde_file_manager::FontPreview::title() const ()
    at /usr/lib/x86_64-linux-gnu/dde-file-manager/plugins/previews/libdeepin-font-preview-plugin.so
#1  0x00007ffff768a6bb in dde_file_manager::FilePreviewDialog::switchToPage(int) (this=this@entry=0x7fffdec63180, index=index@entry=0) at dialogs/filepreviewdialog.cpp:477
#2  0x00007ffff768b143 in dde_file_manager::FilePreviewDialog::FilePreviewDialog(QList<DUrl> const&, QWidget*) (this=0x7fffdec63180, previewUrllist=..., parent=<optimized out>)
    at dialogs/filepreviewdialog.cpp:246
#3  0x00007ffff74efe3c in DialogManager::showFilePreviewDialog(QList<DUrl> const&, QList<DUrl> const&) (this=0x7ffff7b9ea20 <(anonymous namespace)::Q_QGS_gsDialogManager::innerFunction()::holder>, selectUrls=..., entryUrls=...) at dialogs/dialogmanager.cpp:828
#4  0x00007ffff4b0687c in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffbe40, r=0x7ffff7b9ea20 <(anonymous namespace)::Q_QGS_gsDialogManager::innerFunction()::holder>, this=0x7fffe328c340)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#5  0x00007ffff4b0687c in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x55555576f960 <Singleton<FileSignalManager>::instance()::instance>, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=47, argv=argv@entry=0x7fffffffbe40) at kernel/qobject.cpp:3750
#6  0x00007ffff4b06e87 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x55555576f960 <Singleton<FileSignalManager>::instance()::instance>, m=m@entry=0x7ffff7b807c0 <FileSignalManager::staticMetaObject>, local_signal_index=local_signal_index@entry=47, argv=argv@entry=0x7fffffffbe40) at kernel/qobject.cpp:3629
#7  0x00007ffff772fdfa in FileSignalManager::requestShowFilePreviewDialog(QList<DUrl> const&, QList<DUrl> const&) (this=this@entry=0x55555576f960 <Singleton<FileSignalManager>::instance()::instance>, _t1=..., _t2=...) at moc_filesignalmanager.cpp:1113
#8  0x00007ffff74c2666 in DFileView::keyPressEvent(QKeyEvent*) (this=0x7fffce04e650, event=<optimized out>) at views/dfileview.cpp:897
#9  0x00007ffff5be2f57 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5c80abe in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff5c89563 in QAbstractScrollArea::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5de2861 in QAbstractItemView::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff74c39f0 in DFileView::event(QEvent*) (this=0x7fffce04e650, e=0x7fffffffc620)
    at views/dfileview.cpp:1804
#14 0x00007ffff5ba63ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
