### ISSUE TITLE
显卡驱动管理器界面字体显示挤着了

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#114]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.i+n卡场景，打开显卡驱动管理器，加载了版本号后，中间2个选项显示挤在一起了
![img_0069](https://user-images.githubusercontent.com/12388744/47786047-76c67680-dd45-11e8-9096-faba0c3563c6.JPG)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
