### ISSUE TITLE
为 kwin 适配添加dbus接口

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1146]

**Comment by zccrs** [comment]
dubs interface还叫 com.deepin.wm
* [ ] 壁纸相关接口（每个工作区可以单独设置）
* [ ] 窗口快捷键相关接口（使用libkf5globalaccel-dev）
* [ ] 热区相关设置接口

获取工作区相关的接口可以使用 libkf5windowsystem-dev

**Comment by listenerri** [comment]
@zccrs 窗口快捷键是指什么？

**Comment by zccrs** [comment]
> @zccrs 窗口快捷键是指什么？

就是控制中心设置的那些和窗管相关的全局快捷键

**Comment by zccrs** [comment]
热区设置：

使用kconfig加载kwinrc配置文件，如 “显示桌面” 功能，需要设置设置 ElectricBorders 组，如需要设置右下角热区为显示桌面：
````
KConfig config("kwinrc");
KConfigGroup group = config.group("ElectricBorders");
group.writeEntry("BottomRight", “ShowDesktop”);
````

写入配置文件为：

````
[ElectricBorders]
BottomRight=ShowDesktop
````

以此为例，左下角热区设置"所有窗口"配置文件内容为：
````
[Effect-PresentWindows]
BorderActivate=5
BorderActivateAll=9
BorderActivateClass=7
````

右上角打开控制中心设置为：

[Script-runcommandaction]
Border3Program=dde-control-center
Border3Args=--show
BorderActivate=3
````
右上角关闭窗口的配置内容：
````
[Script-closewindowaction]
BorderActivate=3
````
每个热区角落对应的值如下图所示（从上往下从左往右分别为 0123456789）：

![图片](https://user-images.githubusercontent.com/13449038/54737226-e7cdd400-4be9-11e9-92b8-ecc87f914c30.png)


* 这些热区设置项之间的互斥需要另外实现。

**Comment by listenerri** [comment]
> 这些热区设置项之间的互斥需要另外实现

互斥是指两个热区，比如左上和右下不能同时设置为一个动作吗？
如果是的话没有必要做这种互斥吧？

**Comment by listenerri** [comment]
- [ ] ShowWorkSpace (Super + s)
- [ ] ShowWindow (Super + w)
- [ ] ShowAllWindow (Super + a)

还剩这三个接口没有实现，在 kwin 的源码中与第一个相关的线索是 DesktopGrid，与第二和第三相关的线索是：PresentWindows
另外还有 dbus 上的 org.kde.kwin.Effect 接口，这里可以查询和控制启用了哪些动效（包括上面三个），不过没有调用某个动效的接口

**Comment by listenerri** [comment]
热区实现：
由于后端直接修改 GSettings 的值因此不需要提供 com.deepin.wm DBus 上的接口，而是监听 GSettings 上相应的 path 上的值变动信号，将其值以特定的格式通过 KConfig 库转存到 kwinrc 中 kwin 相应的热区设置中。

从 dde-file-manager 源码中可知目前热区所支持的选项有：
```
// all the actions' dbus-about string
const QString CONTROL_CENTER_FROM_LEFT_STR = "dbus-send --print-reply --dest=com.deepin.dde.ControlCenter /com/deepin/dde/ControlCenter com.deepin.dde.ControlCenter.ToggleInLeft";
const QString CONTROL_CENTER_FROM_RIGHT_STR = "dbus-send --print-reply --dest=com.deepin.dde.ControlCenter /com/deepin/dde/ControlCenter com.deepin.dde.ControlCenter.Toggle";
const QString ALL_WINDOWS_STR = "dbus-send --session --dest=com.deepin.wm --print-reply /com/deepin/wm com.deepin.wm.PerformAction int32:6";
const QString LAUNCHER_STR = "dbus-send --print-reply --dest=com.deepin.dde.Launcher /com/deepin/dde/Launcher com.deepin.dde.Launcher.Toggle";
const QString SHOW_DESKTOP_STR = "/usr/lib/deepin-daemon/desktop-toggle";
const QString NONE_STR = "";
const QString FAST_SCREEN_OFF = "sh -c 'sleep 0.5 && xset dpms force off'";
const QString CLOSE_MAX_WINDOW_STR = "!wm:close";
```

从上述列表中可知除了最后一项：`CLOSE_MAX_WINDOW_STR` 需要由窗管特殊处理，其他的都是以执行命令的方式实现的。

这些命令中唯一要确认的是：`SHOW_DESKTOP_STR` 这个我们提供的二进制在 kwin 下是否可以正常工作，已与 @electricface 确认可以正常工作。

因此在热区的实现中，以 `!wm:` 开头的值以特殊的 js 脚本处理，如关闭窗口：
```
[Script-closewindowaction]
BorderActivate=3
```
而其他类型的值则全部以执行命令的脚本处理：
```
[Script-runcommandaction]
Border3Program=dde-control-center
Border3Args=--show
BorderActivate=3
```

@zccrs 你看我理解的有没有错误？

**Comment by nanpuyue** [comment]
希望可以顺便支持一下 `com.canonical.AppMenu.Registrar`

就是 ubuntu 那种全局菜单，kde 好像是支持的：
https://github.com/KDE/plasma-workspace/blob/master/appmenu/com.canonical.AppMenu.Registrar.xml

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
