### ISSUE TITLE
开启热点后，无线提示没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1149]
【测试步骤】
打开控制中心开启热点，然后进入无线网络，查看提示信息

【预期结果】
显示正常

【测试结果】
没有翻译

【问题级别】
一般

【出现概率】
100%
![深度截图_选择区域_20190321092823](https://user-images.githubusercontent.com/12492745/54729004-e8e80c80-4bbb-11e9-9c2d-e989f480b41b.png)

**Comment by listenerri** [comment]
之前我们的打包一直有问题

**Comment by zhaofangfangdeepin** [comment]
测试通过
dde-control-center:
  已安装：4.9.8+r16+gf0b6ae2a
