### ISSUE TITLE
i+n笔记本环境，开源驱动切换大黄蜂失败

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#115]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.i+n笔记本，从nvidia开源驱动切换至大黄蜂方案，切换失败。

**Comment by mmxzmmxz** [comment]
[history.log](https://github.com/linuxdeepin/internal-discussion/files/2547033/history.log)
[term.log](https://github.com/linuxdeepin/internal-discussion/files/2547034/term.log)

**Comment by deepinzhangshuang** [comment]
这个日志不对

**Comment by listenerri** [comment]
在这个任务里处理吧: #834
