### ISSUE TITLE
深度音乐应用没有启动时，任务栏上的右键菜单“下一首/暂停/上一首”能不能不显示？因为这种情况下，这三个菜单并不响应

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1152]
【测试环境】
deepin-music:
  已安装：3.1.13-1
【预置条件】

【测试步骤】
1.深度音乐没有打开时，在任务栏-深度音乐上右键，查看右键菜单。
2.点击右键菜单中的上一首、下一首、暂停继续。
【预期结果】

【测试结果】
1.点击上一首、下一首、暂停没有任何响应
【问题级别】

【出现概率】

**Comment by zhaofangfangdeepin** [comment]
@wangjia12

**Comment by zhaofangfangdeepin** [comment]
![深度截图_选择区域_20190322134622](https://user-images.githubusercontent.com/14539782/54803203-810fef80-4ca9-11e9-9701-7c40c101bfc5.png)

**Comment by wangjia12** [comment]
@zccrs 这个问题直接当bug处理吧

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
