### ISSUE TITLE
webp格式的图片无法设置为系统壁纸

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1153]
【测试环境】

【预置条件】

【测试步骤】
1.打开webp格式的图片，设置为系统壁纸
【预期结果】

【测试结果】
1.不能设置为壁纸。
【问题级别】
建议
【出现概率】
@wangjia12 要不要支持这种格式？

**Comment by wangjia12** [comment]
这格式用的不是特别广泛，好做就支持，不好做就先不用支持。 @zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
