### ISSUE TITLE
使用Qt 5.12链接libdtkwidget.so报错

### ISSUE THREAD

**Issue by joseph1002** [linuxdeepin/internal-discussion#1154]
机器安装了使用Qt 5.12，编译shadowsocks-deepin时报以下错误：
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdtkwidget.so: undefined reference to `QWidgetPrivate::setStyle_helper(QStyle*, bool, bool)@Qt_5_PRIVATE_API'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/shadowsocks-deepin.dir/build.make:525: src/shadowsocks-deepin] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: src/CMakeFiles/shadowsocks-deepin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

deepin目前用的是Qt 5.10.1，QWidgetPrivate::setStyle_helper签名如下：
void setStyle_helper(QStyle *newStyle, bool propagate, bool metalHack = false);

但是这个方法在Qt 5.12 LTS时发生了变化：
void setStyle_helper(QStyle *newStyle, bool propagate);

不知道有什么办法在使用Qt 5.12情况下可以链接成功？

**Comment by zccrs** [comment]
你应该把libdtkwidget以及它依赖的libdtkcore都用Qt 5.12编译才行

**Comment by joseph1002** [comment]
嗯。看来也只有这种办法。但是代价有点大了。我还是改回用5.10来编译吧。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
