### ISSUE TITLE
添加电池供电和无线网连接的音效开关

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1155]
![083958v2btt39tqh2hw2q2](https://user-images.githubusercontent.com/29811622/54889395-5dce8580-4edf-11e9-8844-8f9eed3db710.png)

如上图中，反映如下：

1 无线网连接成功或断开后有音效，没有开关选择关闭。可否加一个开关；默认勾选

2 当笔记本纯电池供电时，可否加一个开关：电池供电自动关闭所有音效；默认勾选

**Comment by wangjia12** [comment]
第二个音效现在有插上电源和拔出电源的音效，应该是一个场景吧。
第一个暂时不会加音效，因为音效主题是找人一次性做的。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
