### ISSUE TITLE
N卡环境，默认驱动文案显示错误，误导性较强

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#116]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.n卡台式机，查看显示文案。有3个选项，NVIDIA默认驱动、nvidia开源驱动，看了之后搞不清楚两者区别，经过询问，默认驱动指vesa驱动（且并不是nvidia才有）。且默认驱动提示文案错误。
【预期结果】：
1.默认驱动文案更改；
 默认驱动提示文字错误。
![img_0070](https://user-images.githubusercontent.com/12388744/47786492-eb4de500-dd46-11e8-84d8-d7bd252311ed.JPG)

**Comment by wangjia12** [comment]
第一个选项文案改为：
【使用默认驱动】
【检测当前环境没有NVIDIA相关驱动。】
@zhuxiujuancindy 这里要改一下文案和翻译

**Comment by wangjia12** [comment]
显卡驱动管理器的文案我们系统的核对一次。给一点时间。保证可以发布。
@zhuxiujuancindy 完成了在这里回复一下

**Comment by zhuxiujuancindy** [comment]
请修改红色部分的英文内容，再上传到transifex。
![image](https://user-images.githubusercontent.com/34529003/47844467-7f7a8380-ddfd-11e8-8465-a8e4b35fe77b.png)

![image](https://user-images.githubusercontent.com/34529003/47844531-a33dc980-ddfd-11e8-87f0-a99f5cd69473.png)

**Comment by zhuxiujuancindy** [comment]
https://shimo.im/doc/1MRkNeJzNCwdb6h4文案在这 @listenerri

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-graphics-driver-manager/+/39437/

**Comment by zhuxiujuancindy** [comment]
文案修改好了，可以测试了 @mmxzmmxz

**Comment by mmxzmmxz** [comment]
这个目前还没合并至ppa/dde-panda仓库。

**Comment by mmxzmmxz** [comment]
验证通过
deepin-graphics-driver-manager 1.1.0-1
