### ISSUE TITLE
dbus启动的程序（dde-lock、dde-shutdown等）缩放不正确

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#1162]
现在dbus.service在session退出的时候不会被杀掉，所以会保留有上个session的环境变量。所以，上面的情况是先使用QT_SCREEN_SCALE_FACTORS设置缩放，退出session后再使用QT_SCALE_FACTOR设置屏幕缩放，两个倍数就会被叠加。

有两种解决方式：
- 设置环境变量时，使用dbus-update-activate-environment更新一下dbus的环境变量？
- 不管单屏还是多屏，都使用QT_SCREEN_SCALE_FACTORS设置缩放？

@chirs241097 @jouyouyun @electricface @snyh

**Comment by electricface** [comment]
把QT_SCALE_FACTOR 给设置为空即可

**Comment by hualet** [comment]
> 不同缩放比和单个缩放比，都把QT_SCALE_FACTOR 和 QT_SCREEN_SCALE_FACTORS 设置。

好像也有点问题，startdde设置的环境变量不会更新到dbus进程

**Comment by snyh** [comment]
https://github.com/linuxdeepin/startdde/blob/master/session.go#L528 
startdde在初始化的时候 已经在更新  https://github.com/linuxdeepin/startdde/blob/master/session.go#L507 这些环境变量了。

**Comment by electricface** [comment]
并没有遇到 dbus.service在session退出的时候不会被杀掉的情况。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
