### ISSUE TITLE
注销重新登录，dock会出现插件加载不出来的情况，此时鼠标点击任何地方都没响应，键盘也没有响应

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#117]
【测试环境】
dde-dock:4.7.4-2
dde-desktop:4.6.9-2
dde-daemon:3.3.0-1
kernel:4.15.0-29deepin-generic #31
deepin-wm:1.9.32-1
【预置条件】
无
【测试步骤】
1.注销系统，重新登录，登录到桌面后，检查dock显示，等待一段时间；
2.检查dock显示；
【预期结果】
dock加载正常，鼠标键盘都可以操作
【测试结果】
dock插件没有加载出来，卡住，鼠标点击dock和桌面都没响应；
键盘操作也没有响应
【问题级别】
严重
【出现概率】
不稳定重现，但重现概率高，至少遇到3次了

**Comment by hualet** [comment]
@sonald 你看看这个有没有办法绕啊？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
