### ISSUE TITLE
文件管理器被调用 [打开文件]时，输入文件地址无效

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1177]
![](https://oforz.tk/deepin-open-file.gif)

动态图片：https://oforz.tk/deepin-open-file.gif

经我测试确实无法打开

**Comment by lq95v5** [comment]
用户反馈贴： https://bbs.deepin.org/forum.php?mod=viewthread&tid=175880

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
