### ISSUE TITLE
grub界面上下键响应较慢，不灵敏，装的系统较多时

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#118]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.装了5个系统，开机进入grub界面，一直按住↓往下，最后松开，后续↑↓箭头切换时，反应较迟钝。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
