### ISSUE TITLE
使用 KWin 且打开多屏不同比例缩放时，Dtk::Widget::DDialog 窗口会被异常放大

### ISSUE THREAD

**Issue by chirs241097** [linuxdeepin/internal-discussion#1186]
![Screenshot_20190326_162257](https://user-images.githubusercontent.com/11586814/54981853-52b14d80-4fe4-11e9-86c0-88261edf0369.png)

90%以上概率复现

复现方法：安装 `dde-kwin` ，为多个屏幕设定不同的缩放比，重新登录调出任意使用 `Dtk::Widget::DDialog` 的对话框（如文件管理器删除确认，启动可执行文件的询问框，`dde-polkit-agent`等）。

满足以下任意一项，该问题均不会出现：
 - 不使用 KWin （`deepin-wm` / `deepin-metacity`均可）
 - 在 `DDialogPrivate::init()` 中添加
```q->setWindowFlag(Qt::WindowType::BypassWindowManagerHint);```

**Comment by zccrs** [comment]
BypassWindowManagerHint 是肯定不能加的

**Comment by chirs241097** [comment]
> BypassWindowManagerHint 是肯定不能加的

列出的两个情况均非解决方案，只是说明问题的直接原因是 KWin。
