### ISSUE TITLE
鼠标移开dde-dock后，系统后台图标的选定状态未取消

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1187]
概率发生 

![TIM图片20190326172839](https://user-images.githubusercontent.com/29811622/54986496-b5f3ad80-4fed-11e9-9583-841b34222832.png)

鼠标不在dde-dock系统后台区域，但仍然显示选中状态

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
