### ISSUE TITLE
kwin完成内容

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1195]

**Comment by zccrs** [comment]
* 快捷键设置
* 壁纸设置
* 仿deepin-wm标题栏
* 模糊支持
* launcher特殊窗口支持
* gtk应用的窗口阴影支持（如gedit）

**Comment by zccrs** [comment]
CC @wangjia12

**Comment by zccrs** [comment]
CC @chirs241097

**Comment by zhaofangfangdeepin** [comment]
@liuwen123

**Comment by zhaofangfangdeepin** [comment]
@zccrs
多点手势
窗口分屏
多工作区
 deepin-wm实现的有这些。

**Comment by liuwen123** [comment]
- [ ] 无法设置壁纸

- [ ] 切换到kwin后，所有浏览器都出现了系统标题栏

- [ ] 按Super+D显示桌面，在右上角会有一个隐藏小窗口显示

- [ ] 无法切换3D和2D

**Comment by zccrs** [comment]
窗口可以拖动到dock以下

这个不是问题吧？不一直都可以拖到dock下面吗

**Comment by zccrs** [comment]
未适配内容：
* 热区设置
* 快捷键设置时和KWin其它快捷键的冲突提示
* 窗口预览
* 窗口停靠到左右半边的的手势
* 特效模式下无壁纸显示
* 设置壁纸时其它窗口未隐藏
* 窗口特效的设置未记录（注销后需要重新设置）
* 个性化窗口主题设置无效

@lq95v5
