### ISSUE TITLE
切换壁纸设置 无“全部设置”

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#12]
现有壁纸设置功能，只有
1.“只设置桌面”
2.“只设置锁屏”

为什么没有“全部设置”呢？

**Comment by rekols** [comment]
之前是有的，不知道什么原因把它移除了。

**Comment by shule1987** [comment]
点击壁纸时默认就是"全部设置" , 当需要"只设置桌面"或"只设置锁屏"时才点击下面的按钮

**Comment by rekols** [comment]
原来是这样   (
