### ISSUE TITLE
launcher不支持手指触摸滚动

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#120]
【测试环境】
dde-laucnher:4.5.0-1
联想触摸笔记本
【预置条件】
无
【测试步骤】
1.打开launcher，使用手指在屏幕滑动，检查launcher是否可以滚动
【预期结果】
launcher支持手指触摸滚动
【测试结果】
launcher不支持手指触摸滚动，只能点击和拖动操作
【问题级别】
严重
【出现概率】
稳定重现

**Comment by zhaofangfangdeepin** [comment]
这个版本不需要。

**Comment by wangjia12** [comment]
> @zccrs @wangjia12 这个版本需要支持么？

15.8不支持，发了之后会专门做触摸屏的功能

**Comment by mmxzmmxz** [comment]
已经支持。
dde-launcher 4.5.4-1
