### ISSUE TITLE
开机启动没有声音

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1201]
https://pms.deepin.cn/index.php?m=bug&f=view&bugID=40

**Comment by electricface** [comment]
https://github.com/linuxdeepin/startdde/pull/23

**Comment by electricface** [comment]
https://github.com/linuxdeepin/dde-api/pull/7

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
