### ISSUE TITLE
建议网络异常检测添加一个白名单用作容错处理

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#1202]

**Comment by deepinzhangshuang** [comment]
如题，我们现在网络异常检测依赖与packages.deepin.com 上面服务，以前是依赖arch服务，都出现过异常，且异常时候不好处理，所以可以添加一个白名单，做二次检测，如网络异常时ping baidu.com 类似做一个名单检测。

**Comment by deepinzhangshuang** [comment]
@hualet @21wmd @wangjia12 @listenerri

**Comment by felixonmars** [comment]
目前是用的 nm 自己的检测吧，要做定制需要自己加一层

**Comment by hualet** [comment]
nm的一层保留 在异常的时候额外再做一次检查

**Comment by hualet** [comment]
@zccrs @listenerri 这个刚好最近有问题，所以近期处理一下？

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/dde-network-utils/pull/6

**Comment by zhaofangfangdeepin** [comment]
拔掉网线，重启系统。进入系统之后，再插入网线，依然可以重现这个问题。

**Comment by listenerri** [comment]
@zhaofangfangdeepin 使用内网最近的 libdde-network-utils 和 dde-dock 测试

**Comment by zhaofangfangdeepin** [comment]
测试通过
