### ISSUE TITLE
【任务管理器】我的电脑-属性，显示版本是15.9.2 。应该是15.9.3

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1206]
[环境]

dde-file-manager:
  已安装：4.7.8.1-1

[步骤]

1.在计算机右键-属性。
[结果]

1.属性页面显示系统版本是15.9.2
[期望]

1,属性页面显示系统版本正确。

**Comment by zhaofangfangdeepin** [comment]
![深度截图_选择区域_20190329172447](https://user-images.githubusercontent.com/14539782/55222879-ee8ec380-5247-11e9-865c-ddd173afc08f.png)

**Comment by BLumia** [comment]
Product Version 和 Deepin Version 有啥区别啊 :joy:

**Comment by zccrs** [comment]
/etc/os-release 文件内容没有更新 @deepinzhangshuang

**Comment by liuwen123** [comment]
已修复
