### ISSUE TITLE
DDialog 标题和文本不应该支持富文本（或应该可选支持）

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#1207]
快速复现步骤：

任意目录创建包含 html 标签的文件名的文件，然后在深度文件管理器 <kbd>Shift + Delete</kbd> 尝试删除文件。

``` shell
$ touch '<h1>ROSE IS <font color="red">RED'
```

![image](https://user-images.githubusercontent.com/10095765/55287414-15c9ca00-53db-11e9-9f80-6493948f1227.png)

DDialog 不应该默认支持此类富文本排版，使用 QLabel 类的情况应当考虑 `setTextFormat()` 为 `Qt::PlainText` 。

不过当初选择用 DDialog 做询问对话框而不是用 QMessageBox 的原因是什么？

**Comment by justforlxz** [comment]
@zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
