### ISSUE TITLE
阿拉伯字体问题 arabic fonts issues on deepin 15.9.2

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1208]
![1GoZjPX](https://user-images.githubusercontent.com/29811622/55311032-93054580-5494-11e9-9a2e-05b6a92dcd7e.png)

**Comment by hualet** [comment]
看不懂有什么问题？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
