### ISSUE TITLE
控制中心有线网络编辑界面部分没有翻译

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#121]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.打开有线网络，进入编辑界面，检查最后一项
【预期结果】
标题应该汉化
【测试结果】
标题显示Ethernet
【问题级别】
一般
【出现概率】
稳定

**Comment by listenerri** [comment]
只有“以太网(Ethernet)”这个字段没有翻译，处理了，回归测试吧

**Comment by listenerri** [comment]
最新内网已经翻译了

**Comment by yefeifei** [comment]
ISO 测试通过
