### ISSUE TITLE
统一文案“认证“”授权“

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1213]
检查文案时，遇到中文里面”认证“和”授权“混用的情况，建议统一改为”认证“（使用”认证“的较多）。
![image](https://user-images.githubusercontent.com/34529003/55313313-0eb5c100-549a-11e9-8295-0fe61b4a2b16.png)
![图片已粘贴至2019-4-1 16-24](https://user-images.githubusercontent.com/34529003/55313648-e4b0ce80-549a-11e9-8bdd-a56fc00d1f64.png)
如改为认证，”授权“按钮也一起修改。
![图片已粘贴至2019-4-1 16-21](https://user-images.githubusercontent.com/34529003/55313424-52102f80-549a-11e9-82ce-5832bb5b63ce.png) 
改为认证
![image](https://user-images.githubusercontent.com/34529003/55313432-58061080-549a-11e9-8d49-a616c08e983b.png) 
改为Authentication is required to xxx Confirm改为Authenticate

可参阅
![image](https://user-images.githubusercontent.com/34529003/55313474-779d3900-549a-11e9-93c1-365f762c7291.png)
https://tower.im/teams/9487/todos/190116/#84d48a15dfa542b9a980dcde1335a704

**Comment by zhuxiujuancindy** [comment]
@hualet @wangjia12 帮忙看看吧

**Comment by hualet** [comment]
可以，挺好。

**Comment by lolimay** [comment]
观察得真仔细 😂

**Comment by wangjia12** [comment]
> @hualet @wangjia12 帮忙看看吧

可以，中文也都改认证吧

**Comment by zhuxiujuancindy** [comment]
在https://github.com/linuxdeepin/internal-discussion/issues/1269处理

**Comment by zccrs** [comment]
@zhuxiujuancindy 只是把中文的授权改为 "认证" 吗，英文需不需要改？

**Comment by zhuxiujuancindy** [comment]
> @zhuxiujuancindy 只是把中文的授权改为 "认证" 吗，英文需不需要改？

英文的还是用Confirm，中文我改为认证
