### ISSUE TITLE
控制中心自动调节色温和消息通知、宽度的问题

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1215]
- [ ] 1.控制中心自动调节色温的功能最近几天似乎没起作用，早、晚使用电脑看不到色温变化

- [ ]  2.消息通知，很多时候打开通知时，太多历史消息，建议关机、重启后，清空消息通知记录

- [ ]  3.控制中心宽度与整个桌面相比，感觉占比太大（普通分辨率显示屏），看论坛中别人发的高分屏显示的控制中心比例更协调一些，个人猜测，控制中心宽度是按像素数量来定义的，导致在高分屏上宽度合适、低分屏上宽度占比过大，那么可否定义为屏幕宽度的百分比呢？这样的话，在高、低分屏上显示的比例效果就一致了，看起来会更协调、更完美

自动色温调节选项
![074518qli84swwloufszod](https://user-images.githubusercontent.com/29811622/55369322-b24db280-5528-11e9-9847-025cc2544bd7.png)

当日之前的消息
![](https://bbs.deepin.org/data/attachment/forum/201904/02/074518qli84swwloufszod.png)

**Comment by hualet** [comment]
色温调节好像是有问题，一直开机没有用，有时候注销登录一次才会生效。

**Comment by wangjia12** [comment]
先处理第一个问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
