### ISSUE TITLE
deepin的开发代号的文案

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1216]
建议把代号放进系统信息或者可以看得见的地方，这样先入为主，绝对比数字版本号好记，而且记忆更长久、更深刻。建议从中国的珍惜动植物、著名历史建筑、五岳名山中选取代号

用户反馈：https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=176235&pid=571086&fromuid=101846 

我也想了一个仓库代号 taichi

**Comment by hualet** [comment]
每个仓库代号里面又会有小版本的，所以版本号肯定还是会有的。

**Comment by wangjia12** [comment]
现在仓库不是有代号吗  12个动物都选好了
