### ISSUE TITLE
控制中心无线网络列表，点击加密方式为企业级的，点击之后控制中心无法隐藏

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#123]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.点击控制中心WiFi列表，选择企业级加密方式的WiFi；
2.如deepin,只点击名称，不点击后面的箭头，检查操作结果
3.此时再点击桌面或者dock，检查控制中心是否隐藏
【预期结果】
控制中心可以隐藏
【测试结果】
步骤2之后，dock会闪一下，步骤3，点击dock和桌面，控制中心不隐藏
【问题级别】
严重
【出现概率】
稳定重现

**Comment by justforlxz** [comment]
后端崩溃导致的，XEventMonitor接口失效了

**Comment by electricface** [comment]
已经修正 https://cr.deepin.io/#/c/dde/dde-daemon/+/39387/
