### ISSUE TITLE
应用适配屏幕不同缩放比

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1231]
更新缩放比后，窗口需要自行根据新的缩放比例更新自己的geometry，目前需要适配的项目：

- [ ] 控制中心 @listenerri 
- [ ] dde-dock @listenerri
- [ ] dde-launcher @justforlxz 
- [ ] 通知 @justforlxz
- [ ] 截图 @justforlxz 
- [ ] 录屏 @justforlxz 
- [ ] 取色器 @justforlxz 
- [ ] greeter @justforlxz  /etc/lightdm/deepin/qt-theme.ini
- [ ] 系统修复工具 @listenerri 
- [ ] deb包安装器 @listenerri 

使用方式：
由配置文件 ~/.config/deepin/qt-theme.ini 控制，与屏幕缩放相关的配置项共有三个：

* ScreenScaleFactors：多屏幕设置不同缩放比，值格式和环境变量QT_SCREEN_SCALE_FACTORS一致
* ScaleFactor: 强制设置缩放比，值格式和环境变量QT_SCALE_FACTOR一致
* ScaleLogcailDpi：指定屏幕逻辑dpi，可影响仅设置了 point size 的 QFont 的绘制大小。未设置此值时，默认会在 ScreenScaleFactors 值改变后将屏幕逻辑dpi更改为主屏默认值，一般情况下，不需要设置此值。

在Deepin桌面环境中，默认对所有Qt5应用生效，可以在QCoreApplication对象创建之前设置 Qt::AA_DisableHighDpiScaling 为 true，或添加环境变量 D_DISABLE_RT_SCREEN_SCALE 关闭此功能。

@electricface

**Comment by zccrs** [comment]
@justforlxz @listenerri https://github.com/linuxdeepin/dtkwidget/pull/20

另外提供接口，可在应用启动时设置跟随某用户的主题配置。

**Comment by zccrs** [comment]
测试时可以手动编辑 ~/.config/deepin/qt-theme.ini 配置文件，保存后即生效

**Comment by electricface** [comment]
控制中心设置 屏幕缩放比时，调用  SetScreenScaleFactors 方法，而不调用 SetScaleFactor 方法。

特殊处理 多屏幕复制模式的情况，只显示一个设置项目。

**Comment by justforlxz** [comment]
/etc/lightdm/deepin/qt-theme.ini

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
