### ISSUE TITLE
修改磁盘名称，提示信息没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1234]
【测试步骤】
打开文件管理器选中未挂载磁盘，点击右键--重命名，然后弹出授权对话框后，点击取消按钮

【预期结果】
给出提示信息

【测试结果】
没翻译

【问题级别】
一般

【出现概率】
100%

**Comment by BLumia** [comment]
这个是 gio 给的错误提示内容

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
