### ISSUE TITLE
锁屏和登录界面，解锁，登录，重启的按钮都被剪裁了

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#124]
【测试环境】
dde-session-ui:
  已安装：4.6.0-1
【预置条件】

【测试步骤】
1.进入登录界面，查看密码输入框的登录图标显示。
2.进入锁屏界面，查看密码输入框右边的解锁图标显示。
【预期结果】
1.图标都没有被剪裁。
【测试结果】
1.图标都被剪裁
【问题级别】
提示
【出现概率】
稳定复现。

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39476/

**Comment by zhaofangfangdeepin** [comment]
V+1
