### ISSUE TITLE
通过WiFi密码输入提示框输入正确的密码，总是提示密码错误，无法连接网络

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#125]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.点击控制中心WiFi列表，选择个人版加密方式的WiFi进行连接
2.点击之后，在弹出的密码输入框内输入正确的密码，点击连接，检查操作结果；
3.在WiFi列表点击进入编辑界面，手动输入密码保存，检查操作结果
【预期结果】
2和3 都可以连接成功
【测试结果】
2.在弹框输入密码无法连接成功；
3.在编辑界面输入密码可以连接成功
【问题级别】
严重
【出现概率】
稳定重现

**Comment by listenerri** [comment]
还能重现吗？ @yefeifei

**Comment by listenerri** [comment]
这个回归测试一下，看能不能复现

**Comment by yefeifei** [comment]
> 这个再测试一下，看能不能复现

未重现，测试正常
