### ISSUE TITLE
帮助手册中没有欢迎的说明文档

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#126]
【测试环境】
dde-introduction：1.0.6-1

【测试步骤】
打开欢迎软件，点击页面最后的帮助按钮

【预期结果】
自动弹出帮助手册文档，并显示欢迎说明文档

【测试结果】
可以弹出帮助手册，但是帮助手册中没有欢迎的使用说明文档

【出现概率】
100%
![_dde-introduction_20181101114224](https://user-images.githubusercontent.com/12492745/47831375-41646c00-ddcb-11e8-9ce2-99620d2d8fb8.png)

**Comment by wangjia12** [comment]
帮助手册里不需要包含欢迎文档的使用说明，这个不算是一个应用或者工具，只是一个介绍。

**Comment by wangjia12** [comment]
这里的“帮助”意思不是要打开欢迎程序的帮助手册，而是打开整个系统的帮助手册。
另外欢迎程序在桌面环境里有写了一章。
