### ISSUE TITLE
合并云同步相关分支到 master

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#1261]
- [x] 后端合并分支
- [x] dock 合并分支

测试：
合并之后 dock 所有与插件相关的配置都将保存到后端，而不是 ~/.config/deepin/dde-dock.conf
此外以前在上述配置文件中保存的设置都将丢失，dock 插件会恢复到无配置的默认状态

测试时要留意一下内容：
- 插件默认状态是否与设计相符，比如排序等
- 插件修改配置后重启 dock 或 重新登录能否正确显示为刚刚的设置状态

插件相关的配置有：
- 插件图标顺序
- 插件是否禁用
- 托盘内图标的顺序
- 时尚模式下托盘的收起状态
- 时尚模式下托盘图标是否在保留区域
- 高效模式下托盘图标是否被放到隐藏区域

**Comment by lolimay** [comment]
云同步真的要来了😆

**Comment by listenerri** [comment]
> 云同步真的要来了laughing

不是的，只是要把 dock 这块对云同步的改动合并到 master 分支，那个分支留的时间太长了

云同步的核心控制功能在控制中心，那个还没做呢
