### ISSUE TITLE
transifex项目文案修改

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1268]
文案修改内容见附件。
请注意”x2“代表有2个相同词条需要修改。
有不明白的请直接问我，修改后直接上传到Transifex。上传完毕后通知我，谢谢。
@zccrs 

[文案优化.xls.zip](https://github.com/linuxdeepin/internal-discussion/files/3052425/xls.zip)

**Comment by zhuxiujuancindy** [comment]
![DeepinScreenshot_dde-polkit-agent_20190408085145](https://user-images.githubusercontent.com/34529003/55695541-9d22c900-59eb-11e9-9d60-8e3038a213d8.png)
去掉the。这个看下由谁修改一下？

**Comment by BLumia** [comment]
关联 #1269

**Comment by zccrs** [comment]
> ![DeepinScreenshot_dde-polkit-agent_20190408085145](https://user-images.githubusercontent.com/34529003/55695541-9d22c900-59eb-11e9-9d60-8e3038a213d8.png)
> 去掉the。这个看下由谁修改一下？

这个是GParted这个应用自己的，最好不要改，改了会影响它的多语言
