### ISSUE TITLE
更新项目文案

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1269]
### 这个任务大家优先处理

[xls.zip](https://github.com/linuxdeepin/internal-discussion/files/3052481/xls.zip)

**Comment by zccrs** [comment]
- [ ] 商店 @myml 
- [ ] deepin-boot-maker @zccrs 
- [ ] deepin-music @chirs241097  
- [ ] 深度录音 @justforlxz 
- [ ] 深度终端 @chirs241097  
- [ ] 深度录屏 @justforlxz 
- [ ] deepin-repair @listenerri 
- [ ] 控制中心 @listenerri 
- [ ] dde-launcher @justforlxz 
- [ ] dde-pro @zccrs 
- [ ] deb安装器 @listenerri 
- [ ] 系统监视器 @justforlxz 
- [ ] deepin-editor @chirs241097  
- [ ] deepin-clone @zccrs 
- [ ] 云打印 @zccrs 
- [ ] 显卡驱动管理器 @listenerri 
- [ ] 深度看图 @chirs241097 
- [ ] dde-file-manager @chirs241097 
- [ ] deepin-installer @justforlxz 
- [ ] deepin-movie @chirs241097 
- [ ] deepin-calculator @chirs241097

**Comment by zccrs** [comment]
已经更新了翻译的项目at @zhuxiujuancindy

**Comment by zccrs** [comment]
@zccrs @justforlxz @listenerri @chirs241097 大家最好直接从表格中复制新文案，避免手动更改出错。改完后先自己过一遍，等更新到翻译网站之后再发现错误，更改起来就比较麻烦了。

**Comment by zccrs** [comment]
@zhuxiujuancindy  https://github.com/linuxdeepin/internal-discussion/issues/1213 这个任务也没处理呢是吧

**Comment by hualet** [comment]
@zhuxiujuancindy deepin calculator 项目已经上传了。

**Comment by zhuxiujuancindy** [comment]
> @zhuxiujuancindy #1213 这个任务也没处理呢是吧

相关的已经写在表格里了

**Comment by zccrs** [comment]
@zccrs @justforlxz @chirs241097 @BLumia @listenerri 有些项目是需要更新 desktop 文件的，需要注意下，不能只更改desktop文件本身，先查看项目中是否包含 desktop.tx 文件，存在此文件时，需要使用 deepin-desktop-ts-convert 命令将新的desktop转换为对应的desktop.ts文件

**Comment by listenerri** [comment]
@zccrs @zhuxiujuancindy 

部分需要翻译的文案在对应的项目中没有找到
黄色背景是我负责的项目，红色背景文案表示在项目中没有找到

[文案优化2.xls.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/3052929/2.xls.tar.gz)

**Comment by electricface** [comment]
dde-daemon 项目中的修改已经上传到 transifex 了。

**Comment by BLumia** [comment]
> @zhuxiujuancindy deepin calculator 项目已经上传了。

计算器我没看到提交记录啊
