### ISSUE TITLE
网络连接提示通知重复

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#127]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.断开有线连接，再点击连接；检查系统通知提示；
2.选择WiFi连接，连接成功后，检查系统通知提示；
【预期结果】
系统通知不会弹出重复的通知
【测试结果】
一次操作会弹出4次同样的通知
【问题级别】
严重
【出现概率】
稳定

**Comment by zccrs** [comment]
@electricface 今天有时间这个也看一下

**Comment by electricface** [comment]
没有重现
