### ISSUE TITLE
dde-kwin 2019年 04月 03日 测试反馈搜集

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1270]

**Comment by lq95v5** [comment]
- [ ]  状态栏上的右键菜单会飞。
![104332b03z7657tza3kazv](https://user-images.githubusercontent.com/29811622/55712950-47b5de80-5a22-11e9-88cf-99f008506c5d.png)


- [ ] 多任务视图未适配
![110654f83vxtxqgw8c8fp5](https://user-images.githubusercontent.com/29811622/55713068-821f7b80-5a22-11e9-98d9-3c18c5a37395.gif)

- [ ] dock栏右键菜单 飞了～
![110726rz82jj1a5pay255z](https://user-images.githubusercontent.com/29811622/55713143-9fece080-5a22-11e9-8a3d-e7a69af5d00c.gif)

- [ ]  窗口装饰

![110917ats256mlgs656532](https://user-images.githubusercontent.com/29811622/55713267-e8a49980-5a22-11e9-84c0-809022ab6bf0.png)

- [ ] 鼠标主题未适配
![111043s1ppge3g39d6p5k4](https://user-images.githubusercontent.com/29811622/55713304-f9eda600-5a22-11e9-9559-bc0ad2eab7bc.gif)

- [ ] 窗口特效的开关无效

- [ ] 控制中心的透明度调节无效

- [ ] 控制中心_声音_音效    页面没有标题，其他的都有标题。
![113804uxnmmttmo5zlhn5x](https://user-images.githubusercontent.com/29811622/55713712-cb23ff80-5a23-11e9-8049-cde2edaa5241.png)

- [ ] Kde钱包 会被自动安装
![114540rg0gv16gy8dv9d4d](https://user-images.githubusercontent.com/29811622/55713776-f1e23600-5a23-11e9-84a9-adc15cfef3d5.png)

- [ ] 商店中 标题栏位置的搜索框 无法输入，其他部分程序也存在相应问题

- [ ]  1.双屏，扩展屏幕截图工具无法关闭。  2. 截图时，如果选择保存至特定文件夹，有一定概率鼠标无法在弹出的保存界面上操作.
![133548t7d9awpby4e66evz](https://user-images.githubusercontent.com/29811622/55713927-41c0fd00-5a24-11e9-840a-984191b09eb4.jpg)

- [ ] kwin 显示桌面 出现残影
![160348m95ttt5qztw5maq4](https://user-images.githubusercontent.com/29811622/55714011-70d76e80-5a24-11e9-889d-06c68cf6229d.png)

- [ ] 火狐浏览器无法通过内置的定制功能关闭标题栏 「待测试」可能是上游问题？
![160821qrgd99o49b5so2xt](https://user-images.githubusercontent.com/29811622/55714122-9cf2ef80-5a24-11e9-9a01-0e914927db05.gif)

- [ ]  使用alt+tab切换窗口时，缺少窗口提示 「建议」

- [ ] win+shift+tab试图切换到2D，窗管挂了，无法操作。

- [ ] 窗口混成器不工作，没有窗口阴影
![193739fv3p63ujejgln16e](https://user-images.githubusercontent.com/29811622/55714356-20144580-5a25-11e9-81fe-ddbc40a1715c.png)

- [ ] 当一个窗口都没有的时候，ctrl+tab切换，会导致任务栏消失。

- [ ] 通知区域，通知消失后有一条竖线。
![072144m6fgxjlc72dmc2jd](https://user-images.githubusercontent.com/29811622/55714780-d9731b00-5a25-11e9-9233-af2c9df849ed.png)
![072157k9enze24nw2w5oq2](https://user-images.githubusercontent.com/29811622/55714786-db3cde80-5a25-11e9-8a32-4e27e4b46379.png)

- [ ]  窗口管理器的程序判定存在问题 (两个窗体)？「待测试」
1.开启一个终端窗口，在该窗口开2个tab页；
2.在tab1中切换到中文，输入，没问题，多次输入也没问题；
3.切换到tab2，输入法被切换成英文了；
4.切换回tab1，输入法被切换成英文了。

**Comment by lq95v5** [comment]
- [ ] 文件管理器被其他程序调用时，右上角最大化按钮显示异常。图片是被QQ调用时
![101628nov5kwjkppm5z755](https://user-images.githubusercontent.com/29811622/55780857-8065be80-5adb-11e9-906e-af8722a59381.png)

- [ ] qt5右键菜单的浮动信息 显示异常
![221758cpii4psvjgl2i4bp](https://user-images.githubusercontent.com/29811622/55781171-23b6d380-5adc-11e9-9805-f31daefc2e32.gif)

**Comment by lq95v5** [comment]
- [ ] 顶栏扩展[虽然不是官方应用]，文字重叠，闪烁
![深度截图_选择区域_20190409155513](https://user-images.githubusercontent.com/29811622/55782929-e6544500-5adf-11e9-9b9d-19043df8849a.png)

**Comment by bibichuan** [comment]
1.全盘安装时，没有考虑物理内存大小8G，直接将Swap分区预留了11G，造成了SSD磁盘浪费。
2.命令行什么命令没输的时候，按退格键，能不能不发出声音？
3.系统更新的逻辑有些问题https://bbs.deepin.org/forum.php?mod=viewthread&tid=177955&extra=
4.15.10任务栏微信抖动没有意义https://bbs.deepin.org/forum.php?mod=viewthread&tid=177902&extra=

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
