### ISSUE TITLE
应用问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1273]
～

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27189

系统版本15.9.3，网易云音乐闪退，搜狗输入法崩溃

**Comment by lq95v5** [comment]
最近出现多次应用程序使用中闪退现象，包括深度文件管理器、WPS、PDF Mod。
https://feedback.deepin.org/feedback/detail/27125

**Comment by lq95v5** [comment]
obs软件源里的闪退，本人已测试。
https://bbs.deepin.org/forum.php?mod=viewthread&tid=176796

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27197

有道词典卡屏

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1516

文件管理器崩溃，频率较高

**Comment by lq95v5** [comment]
deepin有道词典存在内存泄露问题 搜狗也有这俩卸载后我的系统非常稳定
![深度截图_选择区域_20190423212204](https://user-images.githubusercontent.com/29811622/56720457-77c8e580-6775-11e9-91cc-d14ef2064f47.png)

**Comment by lq95v5** [comment]
文件管理器自动关闭，在使用列表格式浏览时，管理器会经常自动关闭
https://feedback.deepin.org/feedback/detail/27480

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
