### ISSUE TITLE
在文件管理器被调用时和启动器右键菜单中添加属性选项

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1279]
- [ ] 需求一：在文件管理器别其他程序调用时，右键菜单添加属性选项

![image](https://user-images.githubusercontent.com/29811622/55790370-c8421100-5aee-11e9-800d-f39b2bdc2234.png)

![image](https://user-images.githubusercontent.com/29811622/55788949-ed815000-5aeb-11e9-87e8-1e3eb6f93b60.png)

启动器右键菜单中添加属性，需要额外设计属性对话框文案 ，比如显示desktop文件信息等  
![深度截图_选择区域_20190409173038](https://user-images.githubusercontent.com/29811622/55789596-3980c480-5aed-11e9-9b77-14030c735fa3.png)

- [x] 右键菜单加图标,例如下图
![深度截图_选择区域_20190409173434](https://user-images.githubusercontent.com/29811622/55789881-ca57a000-5aed-11e9-88c5-908fb58d5b2a.png)

**Comment by justforlxz** [comment]
菜单的图标是 @shule1987 要求去掉的。

**Comment by BLumia** [comment]
多个不同的 issue 以后还是分开创建吧，不然容易漏看然后被关掉 :joy: @lq95v5 

@sonichy 有问题可以直接去 developer-center 提，群里 at aida 和你直接提效果基本一样（

顺便关于上下文菜单图标，这个我觉得值得重新拿出来讨论。现在很多地方对用户交互不友好，比如对话框按钮不能通过快捷键使用，上下文菜单也没有快捷键标记和图标。

<summary>
文管对于上下文菜单图标其实有个隐藏配置的简单支持（不应当被认为是官方支持的特性）。
<details>

配置文件：`~/.config/deepin/dde-file-manager.obtusely.json`

``` json
{
    "ApplicationAttribute": {
   	    "DisplayContextMenuIcon": true
    }
}
```

</details>
</summary>

**Comment by sonichy** [comment]
@BLumia internal-discussion 刚开的时候，提了一个建议，被喷了一脸，说是只许内部人员 New Issue，从此不敢 New Issue了，github 难道不能限制 New Issue 权限吗？

**Comment by justforlxz** [comment]
很显然，你提issue应该去对应的项目或者developer center才对。

海天鹰 <notifications@github.com> 于2019年4月10日周三 上午10:30写道：

**Comment by lq95v5** [comment]
> @BLumia internal-discussion 刚开的时候，提了一个建议，被喷了一脸，说是只许内部人员 New Issue，从此不敢 New Issue了，github 难道不能限制 New Issue 权限吗？

真的被喷了一脸么 https://github.com/linuxdeepin/developer-center

**Comment by BLumia** [comment]
off-topic:

> github 难道不能限制 New Issue 权限吗？

不能......

> internal-discussion 刚开的时候，提了一个建议，被喷了一脸

没有官方人员喷你啊.. 顺便深度一直以来都用 Developer-Center 这个 repo 处理社区建议，我们就是**为了区分内部 issue 和社区 issue** 才后来专门开的 Internal-Discussion ，你还发到那儿了...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
