### ISSUE TITLE
dock上的小键盘位置显示错误

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#128]
【测试环境】
dde-dock:4.7.4-2
【预置条件】
无
【测试步骤】
1.不稳定重现，dock崩溃会容易出现
【预期结果】
键盘输入法图标应该显示在dock插件栏
【测试结果】
键盘输入法图标显示在时间的上面，覆盖住时间了  
【问题级别】
严重
【出现概率】
不稳定重现
![1211](https://user-images.githubusercontent.com/14539819/47832475-b8503380-ddd0-11e8-86fe-b4fd3eb64948.png)

**Comment by zccrs** [comment]
@yefeifei dock崩溃的问题还存在吗？

**Comment by listenerri** [comment]
即使dock崩溃了重启后也没有发小输入法图标不在托盘区域的问题

**Comment by zccrs** [comment]
@yefeifei 这个任务你再观测一下，dock没有崩溃问题就可以关闭了
