### ISSUE TITLE
双屏状态下，密码错误的提示不能跟随鼠标移动

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#129]
【测试环境】
dde-session-ui:
  已安装：4.6.0-1
【预置条件】

【测试步骤】
1.接入双屏重启系统。在登录界面输入错误的密码，确定。
2.出现错误密码提示之后，移动鼠标到另外一个屏幕。
【预期结果】
1.密码错误提示随着鼠标移动
【测试结果】
1.密码错误提示不随着鼠标移动
【问题级别】
提示
【出现概率】
稳定出现

**Comment by rekols** [comment]
两个提交：
dtk: https://cr.deepin.io/#/c/dtkwidget/+/39594/
session-ui: https://cr.deepin.io/#/c/dde/dde-session-ui/+/39596/

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39642/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
