### ISSUE TITLE
无密码的WiFi以及隐藏WiFi无法连接

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#130]
【测试环境】
dde-daemon:3.3.0-1
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.WiFi列表点击没有加密的WiFi，进行连接；
2.点击隐藏网络，输入隐藏WiFi名称，点击连接
【预期结果】
网络连接正常
【测试结果】
未加密的WiFi和隐藏网络都无法连接
【问题级别】
严重
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39417

修复编辑一个无密码的wifi后无法连接，提示密码不正确

连接到有密码的隐藏网络并没有问题，连接到无密码的隐藏网络跟上面的原因一样，已修复

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/39417
> 
> 修复编辑一个无密码的wifi后无法连接，提示密码不正确
> 
> 连接到有密码的隐藏网络并没有问题，连接到无密码的隐藏网络跟上面的原因一样，已修复

cr+1 测试无密码以及隐藏网络都正常

**Comment by yefeifei** [comment]
ISO 测试通过
