### ISSUE TITLE
网络修改完点击保存后，应该返回到上一个页面，现在点击之后页面没有跳转

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#131]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.进入网络编辑界面，输入密码后，点击保存；
2.进入网络编辑界面，修改ip地址为手动，如修改IPv4地址，点击保存
【预期结果】
点击保存之后，页面应该跳转到上一个页面，返回到网络列表界面
【测试结果】
步骤1，测试正常；
步骤2：修改网络地址或者MTU，点击保存不会跳转，给人感觉像是没有生效，实际已经生效
【问题级别】
一般
【出现概率】
稳定重现

**Comment by listenerri** [comment]
没有复现
