### ISSUE TITLE
高分屏密码输入弹框中的x图标模糊，没有适配

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#133]
【测试环境】

【预置条件】

【测试步骤】
1.点击WiFi进行连接，在弹出的密码输入框内输入密码，检查输入框右侧的x图标
【预期结果】
图标显示正常
【测试结果】
图标显示巨大
【问题级别】
一般
【出现概率】
稳定重现

**Comment by yefeifei** [comment]
![91](https://user-images.githubusercontent.com/14539819/47835696-3cf67e00-dde0-11e8-9bea-173a56b831ac.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-session-ui/+/39426

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-session-ui/+/39426

+1

**Comment by yefeifei** [comment]
2倍缩放下，x图标显示模糊

**Comment by listenerri** [comment]
还没有打tag，回归测试吧

**Comment by yefeifei** [comment]
iso 测试通过
