### ISSUE TITLE
#高分屏 小窗口界面右上角的x图标显示不全：如关于界面、密码提示框、属性等

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#134]
【测试环境】
高分屏
15.8
【预置条件】
无
【测试步骤】
1.高分屏下，打开文件管理器，点击文件属性，检查属性界面；
2.点击关于，检查关于界面显示；
3.点击WiFi，检查密码输入框显示
【预期结果】
窗口右上角的x图标显示正常，没有截断
【测试结果】
以上窗口的右上角x图标显示不全
【问题级别】
一般
【出现概率】
稳定

**Comment by zccrs** [comment]
升级dtk后测试

**Comment by yefeifei** [comment]
升级测试通过，等回归

**Comment by yefeifei** [comment]
ISO测试通过
