### ISSUE TITLE
个性化点击关闭窗口特效，按钮关闭后，又自动弹开又自动关上。

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#135]
【测试环境】
dde-control-center:
【预置条件】
无
【测试步骤】
1.个性化点击关闭窗口特效，检查关闭特效过程中，按钮动画效果
【预期结果】
点击关闭后，直接关闭，不会再弹开再关闭
【测试结果】
点击直接关闭，又自动弹开再关闭
【问题级别】
一般
【出现概率】
无

**Comment by zccrs** [comment]
@justforlxz 这个问题稳定出现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39456/ 以前留的刷新

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-control-center/+/39456/ 以前留的刷新

cr +1

**Comment by yefeifei** [comment]
ISO测试通过
