### ISSUE TITLE
deepin failsafe无法启动

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#136]
【测试环境】
Deepin15.8
【预置条件】

【测试步骤】
1.刻录安装盘，启动进入安装盘-deepin failsafe选项
【预期结果】
1.能够进入
【测试结果】
1.不能够进入
【问题级别】
一般
【出现概率】
稳定复现

**Comment by hualet** [comment]
15.7 可以正常进入？ @zhaofangfangdeepin

**Comment by deepinzhangshuang** [comment]
删除nolapic 选项即可正常进入系统　禁用apic是为了兼容旧主板。

**Comment by deepinzhangshuang** [comment]
新iso 暂时移除nolapic选项

**Comment by zhaofangfangdeepin** [comment]
> 15.7 可以正常进入？ @zhaofangfangdeepin

不能
