### ISSUE TITLE
熟悉项目

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1369]

**Comment by zccrs** [comment]
- [ ] deepin-deb-installer @listenerri 
- [ ] deepin-editor @BLumia 
- [ ] deepin-terimtal @BLumia 
- [ ] deepin-image-viewer 
- [ ] 深度日历 @justforlxz 
- [ ] 深度截图 @justforlxz

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
