### ISSUE TITLE
无线热点，创建wep类型密码，手机和电脑都无法连接共享的热点

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#137]
【测试环境】
dde-control-center:4.7.1-2
【预置条件】
无
【测试步骤】
1.创建无线热点，加密方式设置为WEP40/128位秘钥
2.输入SSID、设置密码为10位数字，点击保存
3.使用电脑和笔记本进行连接
【预期结果】
可以连接
【测试结果】
无法连接
【问题级别】
严重
【出现概率】
稳定

**Comment by listenerri** [comment]
其他加密方式是否可以连接？

**Comment by yefeifei** [comment]
> 其他加密方式是否可以连接？

其他的可以

**Comment by zccrs** [comment]
@yefeifei 不是说稳定复现吗，你那能复现吗
