### ISSUE TITLE
安装器通过语言来进行粗略的时区定位

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#1384]
在无网络无无线网卡的机器上安装时，安装器默认使用Utc时区，但是地图上无法显示这个位置，所以打算改成通过语言来确定国家位置，使用国家的某一个时区。

有些语言在很多国家都使用，没考虑好如何确定时区。

@zccrs @hualet  @listenerri @BLumia @felixonmars

**Comment by hualet** [comment]
还是不要了吧，容易被打……

**Comment by justforlxz** [comment]
> 还是不要了吧，容易被打……

那默认时区应该选谁 :sob:

**Comment by hualet** [comment]
Asia/Shanghai?

**Comment by zccrs** [comment]
> Asia/Shanghai?

不科学吧，默认啥都没有有什么问题吗？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
