### ISSUE TITLE
最近使用的右键菜单

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#139]
文件的右键菜单：打开、打开文件所在位置、打开方式、复制、移除、压缩、创建链接、发送到桌面、标记信息、属性；
文件夹的在此基础上增加文件夹的常规选项。
增加的文案是：
【移除】
@zhuxiujuancindy 麻烦翻译一下
@zccrs

**Comment by zhuxiujuancindy** [comment]
【移除】【Remove】
