### ISSUE TITLE
创建拨号连接，输入用户和密码后点击保存没有响应，无法保存，也没有任何提示

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#140]
【测试环境】
dde-control-center:4.7.1-2
dde-daemon:3.3.0-1
network-manager:1.10.8-2deepin
【预置条件】
无
【测试步骤】
1.点击拨号连接，创建连接输入用户名和密码后，点击保存
【预期结果】
1.创建保存成功
【测试结果】
1.点击保存没有响应，也没提示，保存失败
【问题级别】
严重
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39408
