### ISSUE TITLE
「需求」深度终端服务器列表支持方向键选定

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1400]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=176661

用户需求：ctrl+/打开远程管理以后，可不可以默认用光标上下选
![162936mbixz26mmkdgoxvb](https://user-images.githubusercontent.com/29811622/56178110-9ae7ec80-6033-11e9-9005-74bcf1d422c1.png)

**Comment by wangjia12** [comment]
@CallMeR 键盘交互规范里面涉及到这个吗

**Comment by CallMeR** [comment]
> @CallMeR 键盘交互规范里面涉及到这个吗

这个没有，我没使用过服务器版本。不过这个适用键盘交互的总体逻辑思路，适用TAB键切换。

**Comment by wangjia12** [comment]
这个问题在键盘交互完成之后就会被覆盖了。
