### ISSUE TITLE
【stable】网络错误时，没有”已连接但无法访问“错误提示

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1405]
<p>
	[前置条件]
</p>
路由器WAN口不接入网线。
<p>
	[步骤]
</p>
<p>
	1.连接此路由的WiFi，连接成功，检查dock上的WiFi提示
</p>
<p>
	2.连接有线网络，检查dock上有线网络提示
</p>
<p>
	[结果]
</p>
显示获取的IP地址。<br>
<p>
	[期望]
</p>
<p>
	显示已连接，但无法访问
</p>
<p>
	<a href="https://github.com/linuxdeepin/internal-discussion/issues/1405">https://github.com/linuxdeepin/internal-discussion/issues/1405</a>
</p>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=172](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=172)

**Comment by listenerri** [comment]
tag: 4.9.7 已修复
