### ISSUE TITLE
[stable][文件管理器]文档查看器-打开已有文档-smb共享的密码输入框不是深度文件管理器自己提供的。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1407]
<p>
	[步骤]
</p>
<p>
	1.打开文档查看器-打开已有文档。输入smb://10.0.12.150 .访问smb共享目录。
</p>
<p>
	2.查看弹出的smb密码输入框是否是文件管理器提供的。
</p>
<p>
	[结果]
</p>
1.弹出的smb密码输入框不是深度文件管理器提供的。<br>
<p>
	[期望]
</p>
<p>
	1.弹出的smb密码输入框是深度文件管理器提供的。
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=174](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=174)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
