### ISSUE TITLE
【stable】dock上点击WiFi进行连接，弹出密码输入框，点击取消后，还在尝试连接，并未取消连接

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1409]
<p>
	[步骤]
</p>
<p>
	1.点击dock上的WiFi图标，任意选择加密的WiFi名进行连接，如deepin-guest
</p>
<p>
	2.弹出密码输入框，点击取消
</p>
<p>
	3.检查操作结果
</p>
<p>
	[结果]
</p>
1.仍然还在进行连接deepin-guest；<br>
<p>
	[期望]
</p>
<p>
	1.取消连接并提示连接失败。
</p>
<p>
	<a href="https://github.com/linuxdeepin/internal-discussion/issues/1409">https://github.com/linuxdeepin/internal-discussion/issues/1409</a>
</p>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=182](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=182)

**Comment by electricface** [comment]
在我这里没重现。

**Comment by zccrs** [comment]
> 在unstable 上没重现。
> 
> 在 stable 上，不知道为什么 ，Network Manager 的表现不一致，给出空密码后，没有立即报告“需要密码，但未提供”，并断开连接，而是等待了一段时间后才报告的。

点击取消后先把ui隐藏，这样处理会有问题吗

**Comment by electricface** [comment]
ui 本来就会退出

**Comment by listenerri** [comment]
> ui 本来就会退出

dock 上仍然显示正在连接的标记应该是 NM 还在努力激活那个 conn，也就是说仍然处于正在连接的状态

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
