### ISSUE TITLE
VPN无法导出

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#141]
【测试环境】
dde-control-center:4.7.1-2
dde-daemon:3.3.0-1
network-manager:1.10.8-2deepin
【预置条件】
无
【测试步骤】
1.创建L2TP类型VPN，创建成功后，检查是否可以导出
【预期结果】
可以导出
【测试结果】
没有导出的功能
【问题级别】
严重
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39398

**Comment by yefeifei** [comment]
ISO测试通过
