### ISSUE TITLE
[stable][触摸屏]深度应用不支持触摸屏拖动窗口位置

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1410]
<p>
	[环境]
</p>
<p>
	Deepin15.10 stable
</p>
<p>
	[步骤]
</p>
<p>
	1.在stable 的触摸屏环境下，打开多个深度应用窗口，如深度文件管理器，深度终端、深度编辑器。
</p>
<p>
	2.使用触摸屏，触摸打开的深度应用的窗口位置。
</p>
<p>
	[结果]
</p>
<p>
	1.无法移动。https://tower.im/teams/9487/todos/214244/#cbf1ffe6936748249ab85a46080c7291
</p>
<p>
	[期望]
</p>
1.移动窗口位置正常。        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=189](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=189)

**Comment by zccrs** [comment]
@wangjia12 暂不处理
