### ISSUE TITLE
【stable】dock上WiFi连接时，WiFi列表上的转圈图标显示不居中，控制中心网络连接转圈也是没有居中。

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1411]
<p>
	【测试步骤】
</p>
<p>
	1.点击dock上的WiFi列表，点击WiFi进行连接，检查正在连接的图标-圈圈-
</p>
<p>
	2.检查控制中心-无线网络列表，点击连接，检查转圈显示
</p>
<p>
	【测试结果】
</p>
<p>
	1.圈圈图标显示位置没有居中
</p>
<p>
	【预期结果】
</p>
<p>
	1.转圈图标显示居中
</p>
<p>
	<br>
</p>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=190](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=190)

**Comment by listenerri** [comment]
4 K 屏幕 3.0 缩放下 dock 正常, 控制中心的确有此问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
