### ISSUE TITLE
[stable][wine]深度看图-复制图片之后，到wine的微信和QQ中粘贴。粘贴不成功。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1412]
<p>
	[步骤]
</p>
<p>
	1.使用深度看图，打开任意图片，右键-复制。
</p>
<p>
	2.打开微信窗口进行粘贴。
</p>
<p>
	3.打开QQ窗口进行粘贴。
</p>
<p>
	[结果]
</p>
1.微信和QQ窗口无法粘贴成功。
<p>
	[期望]
</p>
<p>
	1.粘贴正常。
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=191](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=191)

**Comment by electricface** [comment]
安装 eog ，使用eog 打开图片，复制图片，可以在wine 的微信上粘贴成果。

**Comment by electricface** [comment]
text/uri-list 这个target 如果删除，就能被 wine 的微信粘贴。

**Comment by zhaofangfangdeepin** [comment]
测试通过
