### ISSUE TITLE
 [stable] 任务栏的已打开窗口有时候显示空白

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1414]
重现步骤
[步骤]

1.打开多个应用，如浏览器、深度终端、音乐、文件管理器；

2.鼠标移动到dock上，逐个查看各个打开应用的预览窗口

[结果]

会出现有些窗口预览显示空白
[期望]

预览窗口显示正常。
![QQ图片20190417100047](https://user-images.githubusercontent.com/14539819/56255693-6427da00-60f8-11e9-818c-b0fda44d6e85.jpg)
![QQ图片20190417100055](https://user-images.githubusercontent.com/14539819/56255694-6427da00-60f8-11e9-9d31-77db35518647.jpg)
https://pms.deepin.cn/index.php?m=bug&f=view&bugID=194

**Comment by listenerri** [comment]
是因为程序被最小化了

**Comment by listenerri** [comment]
不过我们的程序(使用了 dxcb 插件), 及时最小化了也可以通过共享内存的方式拿到窗口图片

**Comment by zccrs** [comment]
已知问题，暂不处理 @wangjia12
