### ISSUE TITLE
【stable】【深度商店】深度商店上架软件还有空白位置

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1415]
<p>
	[步骤]
</p>
<p>
	打开深度商店，查看界面显示
</p>
<p>
	<br>
</p>
<p>
	[结果]
</p>
<p>
	上架软件布满界面
</p>
<p>
	<br>
</p>
<p>
	[期望]
</p>
<p>
	首页显示还有空白位置
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=195](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=195)

**Comment by zccrs** [comment]
@wangjia12

**Comment by wangjia12** [comment]
@deepinzhangshuang @lq95v5 按照unstable的商店首页，尽快把首页内容打完填满吧。

**Comment by zhuxiujuancindy** [comment]
更换了部分应用，现在stable中国区国际区的首页已经填满了
@liuwen123
