### ISSUE TITLE
【stable】launcher上的爱奇艺没有图标，打开后dock上显示的图标是chrome的图标。

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1416]
<p>
	[步骤]
</p>
<p>
	1.安装爱奇艺，检查launcher上的图标显示；
</p>
<p>
	2.发送到桌面和dock，检查图标显示；
</p>
<p>
	3.打开爱奇艺，检查dock上的图标显示；
</p>
<p>
	[结果]
</p>
<p>
	1.launcher上的图标显示异常，显示为齿轮。
</p>
<p>
	2.桌面上的图标显示正常；dock图标也是显示齿轮。
</p>
<p>
	3.打开应用后，图标变成chrome图标。
</p>
<p>
	[期望]
</p>
<p>
	1.爱奇艺图标显示正常，且打开后图标显示正常。
</p>
<p>
	<br>
</p>
<p>
	<a href="https://github.com/linuxdeepin/internal-discussion/issues/1416">https://github.com/linuxdeepin/internal-discussion/issues/1416</a>
</p>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=196](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=196)

**Comment by yefeifei** [comment]
![image](https://user-images.githubusercontent.com/14539819/56257309-60975180-60fe-11e9-8cf2-fcc6a4ec97d0.png)

**Comment by electricface** [comment]
安卓应用不能被正确识别，识别到的是 chrome

**Comment by zccrs** [comment]
> 安卓应用不能被正确识别，识别到的是 chrome

当前版本先不处理

**Comment by zhaofangfangdeepin** [comment]
1.launcher上的图标显示异常，显示为齿轮。这个复现步骤如下：
重启或者注销重新登录之后，安装360浏览器。然后打开启动器。
