### ISSUE TITLE
【stable】高分屏，双屏模式下，登录界面没有适配高分屏。

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1419]
<p>
	[步骤]
</p>
<p>
	1.4k屏幕开启2倍缩放，然后接入双屏（1080p）；
</p>
<p>
	2.注销系统，检查登录界面显示
</p>
<p>
	[结果]
</p>
1.登录界面没有缩放<br>
<p>
	[期望]
</p>
<p>
	登录界面需要缩放
</p>
<p>
	<a href="https://github.com/linuxdeepin/internal-discussion/issues/1419">https://github.com/linuxdeepin/internal-discussion/issues/1419</a>
</p>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=198](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=198)

**Comment by electricface** [comment]
@justforlxz 应该已经修正
