### ISSUE TITLE
#偶现 部分键盘快捷键失效：打开终端、launcher、截图、录屏、锁屏、关机等等

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#142]
【测试环境】
15.8ISO
【预置条件】
无
【测试步骤】
1.偶现的，测试中突然发现键盘快捷键失效：快捷键打开终端、launcher、截图、锁屏、文件管理器等
2.最大化窗口、切换窗口、工作区、显示工作区等快捷键测试正常
【预期结果】
键盘快捷键使用正常
【测试结果】
部分快捷键功能失效
【问题级别】
严重
【出现概率】
偶现

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/39387/ 修正

**Comment by yefeifei** [comment]
iso 测试通过
