### ISSUE TITLE
打印机问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1421]

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27244

打印机在使用的时候有时候一开始能打印，后来就没法使用了

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27459
Epson L380

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27394
三星打印机

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
