### ISSUE TITLE
[stable][授权]指纹验证失败之后的提示没有翻译

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1422]
<p>
	[步骤]
</p>
<p>
	1.接入指纹，打开gpart-密码输入框。输入错误的指纹。
</p>
<p>
	2.检查指纹验证失败的提示信息
</p>
<p>
	[结果]
</p>
1.指纹验证失败的提示信息没有翻译。<br>
<p>
	[期望]
</p>
1.指纹验证失败的提示信息显示正常。        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=200](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=200)

**Comment by wangjia12** [comment]
【指纹验证失败】
@zhuxiujuancindy

**Comment by electricface** [comment]
还有一种失败是开始指纹验证，但是一直没有去按手指，就会提示验证超时，英文是 “Verification timed out”。

**Comment by zhuxiujuancindy** [comment]
> 【指纹验证失败】
> @zhuxiujuancindy

【Fingerprint verification failed】

**Comment by wangjia12** [comment]
【指纹验证超时】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
【Fingerprint verification timed out】

**Comment by zhuxiujuancindy** [comment]
可以把fingerprint都去掉@electricface

**Comment by electricface** [comment]
还是又必要加上的，界面上密码和指纹会用同一个提示区域。

**Comment by electricface** [comment]
@zhuxiujuancindy  翻译文件已经上传，帮我翻译一下。

**Comment by zhuxiujuancindy** [comment]
写好了

**Comment by zhaofangfangdeepin** [comment]
最新的stable环境，依然没有翻译

**Comment by electricface** [comment]
这个错误是 fprintd 的 pam 模块提供的，本来就是没有翻译的字符串。
