### ISSUE TITLE
 [stable] 子网掩码设置为含有253，网络设置无法保存

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#1427]
重现步骤
[步骤]

1.控制中心网络模块-ipv4-设置手动：

2.IP：192.168.1.100；子网掩码：255.255.255.253

3.点击保存，检查是否可以保存。

[结果]

1.保存失败，点击保存没有响应。
[期望]

1.可以保存成功。
https://pms.deepin.cn/index.php?m=bug&f=view&bugID=204

**Comment by felixonmars** [comment]
这个掩码是非法的，前三段为255时最后一段合法值只有0/128/192/224/240/248/252/254/255。控制中心应当提示错误。
