### ISSUE TITLE
lightdm登录界面，输入密码之后，切换用户，输入的密码没有清空，会同步再另外用户的密码输入框

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#143]
【测试环境】
dde-session-ui:
  已安装：4.6.0-1
【预置条件】
新建两个用户：deepin和test
【测试步骤】
1.重启系统，在deepin登录界面，输入密码。
2.输入密码之后不登录，点击切换账户，切换到test登录界面。
【预期结果】
1.登录到test登录界面之后，密码被清空。
【测试结果】
1.登录到test登录界面之后，密码没有被清空。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39475

**Comment by zhaofangfangdeepin** [comment]
有毒的cr提交。安装之后，lightdm起不来。

**Comment by zhaofangfangdeepin** [comment]
测试通过
