### ISSUE TITLE
upgrade升级警告

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#1431]
<p>
	[步骤]
</p>
1. 打开终端，执行命令：sudo apt-get upgrade<br>
2. 输入N<br>
3. 重复步骤1，输入y<br>
<p>
	[结果]
</p>
1.没有弹出警告。<br>
<p>
	[期望]
</p>
1. 弹出警告：upgrade可能造成DDE组件功能异常，请使用full-upgrade或者dist-upgrade进行升级。<br>
2. 终止升级<br>
3. upgrade升级成功<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=206](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=206)

**Comment by deepinzhangshuang** [comment]
这个补丁以前打过，感觉没有多少意义，所以新版本不维护了。
