### ISSUE TITLE
【stable】【文件管理器】文件管理器无法搜索到文件

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1435]
<p>
	[步骤]
</p>
<p>
	打开文件管理器进行文件搜索，查看搜索结果显示
</p>
<p>
	<br>
</p>
<p>
	[结果]
</p>
<p>
	有时候搜索结果为空
</p>
<p>
	<br>
</p>
<p>
	[期望]
</p>
可以正常搜索到文件        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=207](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=207)

**Comment by zccrs** [comment]
@liuwen123 只在新装系统上遇到过一次吗？在下个ios中再看一下吧

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
