### ISSUE TITLE
#Qt# 在vpn编辑界面，名称输入框切换到中文，输入后，再点击密码输入框，输入法还显示是中文输入

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#144]
【测试环境】
15.8ISO
【预置条件】
无
【测试步骤】
1.在vpn编辑界面，先在名称输入框，切换中文输入法，输入内容后，
2.点击密码输入框，进行输入，检查操作结果
【预期结果】
不会显示为中文输入法
【测试结果】
密码输入框还显示中文输入，且可以输入中文
【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
切换输入法为中文后，此时点击密码输入框，输入法还是中文状态，此时无法输入 @zccrs

**Comment by zccrs** [comment]
只解决无法输入问题，可以输入中文的不处理

**Comment by zccrs** [comment]
从输入中文的输入框调用输入法后直接点击进入密码框后还是中文输入法，是Qt的问题，暂不处理

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
