### ISSUE TITLE
【stable】【热区设置】设置桌面左上角热区为无，然后将鼠标移动到左上角还是会触发热区

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1442]
<p>
	[步骤]
</p>
<p>
	在桌面设置左上角热区为无，然后将鼠标移动到左上角
</p>
<br>
<p>
	[结果]
</p>
<p>
	将鼠标移动到左上角还是会触发热区
</p>
<br>
<p>
	[期望]
</p>
<p>
	不显示任何东西
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=214](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=214)

**Comment by zccrs** [comment]
这个任务有重复的吧，已经修过了，可以在下一波更新后测试

**Comment by liuwen123** [comment]
已修复
