### ISSUE TITLE
【stable】【桌面】安装Ctrl键无法选中并拖拽文件

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1443]
<p>
	[步骤]
</p>
<p>
	在桌面安装Ctrl后，然后任意选中一个文件并拖拽
</p>
<br>
<p>
	[结果]
</p>
<p>
	无法拖拽
</p>
<br>
<p>
	[期望]
</p>
<p>
	可以正常拖拽
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=215](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=215)

**Comment by liuwen123** [comment]
在自动整理模式下，展开任意一个目录，然后选中一个文件按Ctrl，然后拖拽无法选中拖动

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
