### ISSUE TITLE
【stable】【热区设置】将鼠标移动到右上角后，窗口直接关闭了

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1446]
<p>
	[步骤]
</p>
<p>
	在桌面设置右上角热区为关闭窗口，然后最大化软件，将鼠标移动到右上角
</p>
<br>
<p>
	[结果]
</p>
<p>
	直接将应用程序关闭了
</p>
<br>
<p>
	[期望]
</p>
<p>
	会显示一个×
</p>
<br>        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=217](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=217)

**Comment by zccrs** [comment]
@wangjia12 热区问题暂不处理，kwin的热区行为和我们不一致
