### ISSUE TITLE
【stable】【热区设置】应用全屏时，依然可以触发热区

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#1448]
<p>
	[步骤]
</p>
<p>
	用看图打开一张图片，然后全屏显示，将鼠标移动到桌面四个角
</p>
<p>
	<br>
</p>
<p>
	[结果]
</p>
<p>
	依然可以触发热区
</p>
<p>
	<br>
</p>
<p>
	[期望]
</p>
无法触发热区        

imported from: [https://pms.deepin.cn/index.php?m=bug&f=view&bugID=218](https://pms.deepin.cn/index.php?m=bug&f=view&bugID=218)

**Comment by zccrs** [comment]
@wangjia12 热区问题暂不处理，kwin的热区行为和我们不一致

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
