### ISSUE TITLE
仓库中的KDE桌面非常不好用，特别容易卡死，崩溃

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#145]
【测试环境】
kde-full:
  已安装：5:101
【预置条件】

【测试步骤】
1.打开终端，执行命令:sudo apt-get install kde-full。安装kde的桌面环境。
2.注销系统，登录到KDE环境，使用KDE环境。
【预期结果】
1.KDE环境使用正常。
【测试结果】
1.KDE桌面非常不好用，特别容易卡死，崩溃。
【问题级别】
一般
【出现概率】
稳定出现

**Comment by justforlxz** [comment]
之前我遇到过，可能和gnome的一些设置有关系，高版本的kde没有问题，我们仓库版本的kde就会卡死，新建用户不进deepin或者gnome，直接使用kde是没有问题的，但是只要进一次gnome就废掉了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
