### ISSUE TITLE
安装器的高级分区页面，名称没有显示完全

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#146]
【测试环境】
Deepin15.8
【预置条件】

【测试步骤】
1.刻录启动盘，启动安装，进入高级分区页面。
2.查看高级分区页面信息显示
【预期结果】
1.信息显示完整。
【测试结果】
1.高级分区页面，分区上的系统名称没有显示完全。
【问题级别】
提示
【出现概率】
稳定出现

**Comment by zccrs** [comment]
找 @shule1987 对一下

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/39561/
