### ISSUE TITLE
实现把系统监视器用来做屏保，总在桌面显示

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1467]
用户需求：https://bbs.deepin.org/forum.php?mod=viewthread&tid=176920

**Comment by lq95v5** [comment]
![055651psvvtq6wbt06yyh6](https://user-images.githubusercontent.com/29811622/56400188-0674c880-6285-11e9-8e00-51f1e0a745d5.png)

需求描述：
把这个界面显示到桌面上，做成类似conky的功能。

**Comment by hualet** [comment]
内部不会开发，但是欢迎其他人提交patch。
