### ISSUE TITLE
三个BUG反馈+两个功能需求[ARCH+DDE]

### ISSUE THREAD

**Issue by naixzh** [linuxdeepin/internal-discussion#1475]
链接图片说明
https://deepin-feedback.b0.upaiyun.com/2019/04/22/310735216d4bdc9ccb0dac7291d9ad03/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190422095111.png
https://deepin-feedback.b0.upaiyun.com/2019/04/22/33545dd997c67a48f91a58de1a67b1ce/%E6%9C%AA%E6%A0%87%E9%A2%98-1.png
https://deepin-feedback.b0.upaiyun.com/2019/04/22/4ac61c2b7f505ec46c241a54cf2c5811/%E9%A2%9D%E5%A4%96.png

https://deepin-feedback.b0.upaiyun.com/2019/04/22/b5a3862b52442270c55b591a0e0f31e6/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190421125931.png

Linux 5.0.8-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 17 14:56:15 UTC 2019 x86_64 GNU/Linux

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
