### ISSUE TITLE
[功能需求] 鼠标滚动文字行数设定

### ISSUE THREAD

**Issue by naixzh** [linuxdeepin/internal-discussion#1476]
[一次能滚动多少行设定]
DEEPIN DE默认行数,满足不了,长网页浏览
滚动一次,行数太少

**Comment by wangjia12** [comment]
在控制中心里面滚动速度的值设大一点，一次滚的内容会变多。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
