### ISSUE TITLE
15.10 更新内容

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#1482]

**Comment by zccrs** [comment]
commit 6766e9155f4a7f8b0677fed3c3b0643506e23c96
Author: deepin-crp <crp@deepin.com>
Date:   Mon Apr 22 17:41:11 2019 +0800

    topic: 15.10-3
    
    dtkwm:
* 修复双屏左上角坐标错误
    
    deepin-installer-reborn:
* 修复oem定制的安装进度图片序列读取错误
* 删除有道的安装图片
* 修复清理用户密码失败
* 修复简单安装安装失败 https://github.com/linuxdeepin/internal-discussion/issues/1277
    
    deepin-screenshot:
* 在保存图片时检查路径是否存在，若不存在则创建
* 更新 README 中的依赖和编译步骤
    
    dde-session-ui:
* 修复锁屏和greeter多屏幕数据不同步
    
    dde-kwin:
* 移除标题栏左边的所有按钮
    
    commit by zccrs

commit 709d841e4278090f04f903b26424984952a5c83f
Author: deepin-crp <crp@deepin.com>
Date:   Mon Apr 22 16:48:18 2019 +0800

    topic: 15.10-3
    
    dtkcore:
* 修复交叉编译时文件安装路径错误
    
    dtkwidget:
*   修复打包符号错误问题
    
    qt5dxcb-plugin:
* 修复在多屏设置了不同缩放比时，窗口从一个屏幕移动到另一个屏幕后阴影绘制异常
* 修复在Qt 5.7.x 编译失败
    
    qt5integration:
* 开启多屏不同缩放比时，支持当窗口所在屏幕缩放比改变时自动更新窗口实际大小
* 开启多屏不同缩放比时，修复插入一个新屏幕后Qt应用字体变小
* 修复 ScreenScaleFactors 字段只设置了一个值时没有对所有屏幕都是生效
    
    dde-kwin:
* 所有对话框类型窗口禁止最小化
    
    dde-session-ui:
* 使用新的dpi缩放方式 https://github.com/linuxdeepin/internal-discussion/issues/1231
* 修复在锁屏阶段无法通过nopassword解锁
    
    dde-daemon:
* 修正指纹验证提示未翻译问题
    
    startdde:
* 缩放支持 wps
* 修正使用 kwin 时，dde-wm-choose 选择无窗口特效无效问题
    
    deepin-kwin:
* 修复关闭窗口特效后在Alt+Tab界面点击x关闭当前选中的窗口时崩溃
    
    deepin-music:
* 设置对话框翻译更新
    
    deepin-image-viewer:
    修复复制文件后无法粘贴到windows应用（如QQ）
    
    deepin-editor:
* 修复设置对话框的翻译问题
    
    deepin-anything:
* 修复使用不分段搜索时进程崩溃
    
    deepin-movie-reborn:
* 设置对话框翻译文案更新
    
    dde-control-center:
* 修复网络ipv4的子网掩码的有效性检查 https://github.com/linuxdeepin/internal-discussion/issues/1427
* 修复2d下屏幕旋转没有适配高分屏 https://github.com/linuxdeepin/internal-discussion/issues/1458
* 修复无线网络链接列表的动画没有居中 https://github.com/linuxdeepin/internal-discussion/issues/1411
    
    dde-dock:
* 修复在overlay状态下没有通知提醒
* 修复禁用overlay状态的授权认证框没有翻译
    
    dde-file-manager:
* 修复deepin-topbar会覆盖桌面图标的问题
* 减少文件管理器潜在的崩溃问题
* 修复磁盘属性对话框显示文件数量不正确的问题
* 修复最近文件中双击打开文件，若造成最近文件更新，列表可能被显示为空的问题
* 修复未知修改时间不能被显示正确的问题
* 桌面自动整理相关的若干错误修复
    
    qcef:
* 支持web页面跟随QWidget的缩放比
    
    netease-cloud-music:
*   在ubuntu系统上无法打开（在 ubuntu 18.04 版本验证过）
*   打开一段时间后会崩溃退出（不用做任何操作）
*   修复开启高分屏缩放后桌面歌词显示模糊
*   修复无法在锁屏界面设置静音
*   修复保存图片后应用退出
*   支持使用本地文件选择对话框(deepin系统环境)
*   修复登录窗口没有支持高分屏缩放
    
    deepin-screen-recorder:
* 修复开启缩放以后无法在多屏幕下录屏
    
    commit by deepinzhangshuang

commit 45ec6f70682c549d2b021843cad4bc54be128123
Author: deepin-crp <crp@deepin.com>
Date:   Wed Apr 17 09:57:37 2019 +0800

    topic: 15.10-2
    
    dde-network-utils:
* 增大检查网络连通性的几率
    
    dde-dock:
* 在高效模式下 dock 右键菜单中不显示回收站插件
* 修复 stable 版本部分插件配置无法正确得保存到后端
* 修复点击预览窗口后无法没有将其置顶
* 修复预览窗口经过拖拽进入操作后无法在使用鼠标 hover
    
    dde-control-center:
* 优化无线列表的排序
* 修复多屏缩放相关问题
* 修复音效界面没有标题
* 修复无限投屏相关问题
    
    deepin-image-viewer:
* 默认使用彩色打印
    
    go-gir-generator:
* 改进输出
* 修正 Makefile 路径错误
    
    deepin-feedback:
* 修改依赖
    
    lastore-daemon:
* 修改 github pull request 模板
* 修正更新检查失败
* 修正使用自定义镜像站失败
    
    commit by listenerri

commit 387c9359fb9577d9820fcc31f9ea16f79b0286ff
Author: deepin-crp <crp@deepin.com>
Date:   Mon Apr 15 11:00:18 2019 +0800

    topic: 15.10-1
    
    dde-kwin:
* 支持startdde的等待启动
* 适配5.8.6版本的kwin
* 快捷键设置添加对符号的转义（后端使用英文名描述符号）
* 添加 plasma-formwork 和  libkf5globalaccel-bin 安装依赖
    
    deepin-kwin:
* 合并上游一些修复崩溃的patch
* 修复工作区视图被拖动的窗口不显示
* 更改工作区视图按钮的样式
    
    startdde:
* 修正ISO安装后进入系统，没有自动适配高分屏，控制中心显示缩放为2，配置文件没有显示缩放比，且只缩放了gtk程序。
* 等待 kwin 启动
* 修正切换屏幕缩放没有弹出提示信息
    
    deepin-menu:
* 修复高分屏下深度终端右键菜单有偏移 https://github.com/linuxdeepin/internal-discussion/issues/1350
    
    deepin-terminal:
* kwin 下会失去焦点的问题
* vte 触屏优化后鼠标三击不能选中全行的问题修复
    
    deepin-manual:
*   添加15.10内容
    
    commit by zccrs

commit b2c65279047a70d707537db4ceb3e8861fa29156
Author: deepin-crp <crp@deepin.com>
Date:   Fri Apr 12 09:42:22 2019 +0800

    topic: 翻译
    
    deepin-screen-recorder:
* 更新翻译
    
    deepin-picker:
* 更新翻译
    
    deepin-graphics-driver-manager:
* 翻译
    
    deepin-repair-tools:
* 翻译
    
    deepin-deb-installer:
* 翻译
    
    dde-control-center:
* 翻译
* 修复无法使用 ESC 键退出屏幕旋转界面
    
    dde-polkit-agent:
*   更新翻译
    
    dde-network-utils:
* 翻译
    
    dde-dock:
* 翻译
    
    deepin-font-installer:
*  更新翻译
    
    dde-daemon:
* 更新翻译
* 更新依赖
    
    startdde:
* 更新依赖
    
    dde-api:
* 更新翻译
    
    deepin-cloud-print-client:
* 更新翻译
    
    deepin-boot-maker:
* 更新翻译
    
    deepin-clone:
* 更新翻译
    
    deepin-license:
* 更新翻译
* 支持 Y2019E0001
*
    
    deepin-appstore:
* 更新翻译
    
    deepin-music:
* 翻译更新
    
    deepin-terminal:
* 支持 “粗体即亮色” 的选项配置（默认关闭）
* 更新翻译
    
    deepin-editor:
* 更新翻译
    
    deepin-image-viewer:
* 数据库读写的线程安全问题处理
* 更新翻译
    
    deepin-movie-reborn:
* 更新翻译
    
    deepin-calculator:
* 计算器不再依赖特定字体
* 更新翻译
    
    commit by zccrs

commit 677254b8293ad94101ba61696d5ce181dcba7aa4
Author: deepin-crp <crp@deepin.com>
Date:   Wed Apr 10 13:06:03 2019 +0800

    topic: 15.10
    
    deepin-system-monitor:
* 修复flatpak启动崩溃 https://github.com/linuxdeepin/developer-center/issues/980
* 更新翻译
    
    commit by deepinzhangshuang

commit 3297ff15891a0cc08b514bee2ec92df0f154bcc7
Author: deepin-crp <crp@deepin.com>
Date:   Wed Apr 10 09:55:41 2019 +0800

    topic: 15.10
    
    qt5integration:
* 修复在Qt 5.7.x版本编译失败
* 支持通过 qt-theme.ini 设置应用的屏幕缩放
    
    dde-kwin:
* 完成除窗口预览外的Deepin WM相关的所有接口
* 添加一个默认的窗口切换主题
* 修复stable环境编译失败
    
    deepin-icon-theme:
* 修复在archlinux上ttf sqlite等文件图标显示错误
* 支持bzip m3u等文件图标
    
    deepin-desktop-base:
*   rebuild
    
    dde-file-manager:
* 支持打开ELF类型文件时提示是否为其添加可执行权限
* 添加桌面文件自动整理功能
    
    deepin-editor:
* 修复 TAB 字符宽度不正确问题（感谢 SquareFong@GitHub）
* 支持在状态栏显示文档的字符数量（包含空白字符，如换行符）
* 调整窗口最小大小限制
* 调整英文翻译
    
    go-dbus-factory:
* 更新接口
    
    go-lib:
* 不在库中处理字段 X-Deepin-Vendor
    
    dde-daemon:
* 支持设置 kwin 窗口装饰主题
    
    startdde:
* 使用 com.deepin.wm 接口设置混成开关
    
    deepin-installer-reborn:
* 更新用户协议界面
* 修复分区失败
    
    dde-session-ui:
* 锁屏支持密码和指纹的同步验证
* greeter支持不同屏幕的缩放比
    
    dde-launcher:
* 修复sw上launcher画面闪烁
    
    dde-dock:
* 修复多屏环境且设置了多屏缩放后位置不正确
* 修复插件开发文档部分错误
* 新增网络连通性提示错误
* 插件相关配置又后端保存不再使用配置文件
    
    dde-control-center:
* 修复窗口大小错误
* 修复通知的音效示例效果和实际播放的效果不同 https://github.com/linuxdeepin/internal-discussion/issues/1160
* 修复显示模块在多屏环境下相关设置没有显示
* 新增音效开关的显示区分台式机和笔记本
    
    dde-network-utils:
* 新增网络连通性检测 fallback 机制
    
    dde-polkit-agent:
* 更新翻译
    
    dde-introduction:
* 更新视频到15.10
    
    commit by zccrs

**Comment by zccrs** [comment]
@zhuxiujuancindy @zhaofangfangdeepin @deepinzhangshuang @wangjia12 @lq95v5 @liuwen123 @yefeifei @justforlxz @BLumia @electricface @chirs241097 这是 15.10.4 阶段所有的bug修复日志

**Comment by zhuxiujuancindy** [comment]
更新日志见 https://www.deepin.org/2019/04/28/deepin-system-updates-2019-04-28/
