### ISSUE TITLE
添加工作区任务栏隔离任务选项

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1514]
需求描述：xfce和kde有这个功能，在不同的工作区任务栏仅显示该工作区内的任务

期望行为：在dock栏右键菜单中添加「任务隔离」 的选项，仅显示当前工作区任务

**Comment by wangjia12** [comment]
这是我们设计的特性，为了方便切换到别的工作区。20之前不会改，20之后看情况。
