### ISSUE TITLE
开关触摸板开关的时候没有OSD显示

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#152]
【测试环境】
Deepin15.8
【预置条件】
存在触摸板开关快捷键
【测试步骤】
1.开关笔记本上的触摸板开关。查看是否有OSD显示
【预期结果】
1.有OSD显示
【测试结果】
1.没有OSD显示
【问题级别】
一般
【出现概率】
稳定复现

**Comment by electricface** [comment]
一台鸿基Acer笔记本
xev 没有发现事件
libinput-debug-events 有事件 513 与 512

**Comment by electricface** [comment]
XF86TouchpadToggle keycode 199
XF86TouchpadOn keycode 200
XF86TouchpadOff keycode 201

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
