### ISSUE TITLE
#iso 蓝牙耳机连接不到10s，突然没有声音了

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#153]
【测试环境】
15.8 ISO
【预置条件】
无
【测试步骤】
1.连接华为蓝牙耳机，成功之后播放音频；测试蓝牙耳机使用是否正常
【预期结果】
蓝牙耳机连接正常
【测试结果】
耳机播放音频不到10s就没音了，听不到任何系统的声音
【问题级别】
严重
【出现概率】
稳定

**Comment by zccrs** [comment]
可以加一个iso的标签

**Comment by electricface** [comment]
我测试了没有重现

**Comment by electricface** [comment]
出问题的电脑上的现象是： 播放一段时间后，就不能从蓝牙耳机听到声音了，但是bluetoothd 告知的与设备的连接状态 还是连接的。

**Comment by zccrs** [comment]
@deepinzhangshuang 升级 bluez 测一下

**Comment by yefeifei** [comment]
第二轮ISO测试和升级测试都没有重现
