### ISSUE TITLE
kwin下打游戏时关闭了窗口特效

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1539]
用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=177320

kwin下打游戏会自动关闭窗口特效

**Comment by zccrs** [comment]
查过了，这是游戏的主动行为，不是bug

**Comment by wangjia12** [comment]
@zccrs 可以知道是什么程序关闭的窗口特效吗

**Comment by zccrs** [comment]
可以呀

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
