### ISSUE TITLE
安装器双屏显示存在问题，win+p切换界面显示不全，不能安装

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#154]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.双屏安装系统，win+p切换模式，切换之后界面显示不全，按钮看不到，不能正常安装。
![img_0077](https://user-images.githubusercontent.com/12388744/47850644-eeada300-de10-11e8-9e38-577cf9ba56f9.JPG)

**Comment by zccrs** [comment]
@mmxzmmxz 不要用转接头测一下这个问题

**Comment by mmxzmmxz** [comment]
不用转接头，hdmi直连电视、笔记本，没有上述问题。
