### ISSUE TITLE
dde-kwin下注销后图标显示带有kde风格

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1540]
注销后一次正常，其它不正常
用户反馈：https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=177343

出现此问题时的图示

![141229g00t8ubdtdmu0ovu](https://user-images.githubusercontent.com/29811622/56880495-912ca300-6a8f-11e9-8494-c940448f79bf.png)
![141226dhm82a7lc2ask5p8](https://user-images.githubusercontent.com/29811622/56880496-925dd000-6a8f-11e9-975c-6d6c99f6e6c5.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
