### ISSUE TITLE
stable n卡使用闭源驱动时，390.87-2-bpo9+1 很卡。

### ISSUE THREAD

**Issue by wj008** [linuxdeepin/internal-discussion#1543]
【测试环境】
deepin stable 15.10  dde桌面。amd 2700x  geforce gtx 1050TI  4k显示器
【预置条件】

【测试步骤】

【预期结果】
修正 deepin stable 版本下闭源驱动的bug.
【测试结果】
在 stable 版本下面 看高清卡顿，拖动各种软件窗口有瞬间重绘破裂现象。
在 非 stable 版本下面比较流畅，
【问题级别】
高
【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
