### ISSUE TITLE
lightdm开机登陆页面分辨率异常/过低

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1544]

**Comment by lq95v5** [comment]
![TIM图片20190505144840](https://user-images.githubusercontent.com/29811622/57189743-f3305100-6f44-11e9-8dc9-18de8674a677.jpg)

用户反馈：lightdm分辨率异常/过低，导致登陆界面观感模糊

**Comment by hualet** [comment]
这好像是我说得那个被重复缩放的问题。 @zccrs @electricface @justforlxz

**Comment by justforlxz** [comment]
> 这好像是我说得那个被重复缩放的问题。 @zccrs @electricface @justforlxz

群里问了，升级以后/etc/lightdm/deepin/qt-theme.ini不存在，走自动缩放了。  @electricface 升级后是不是木有写这个文件？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
