### ISSUE TITLE
安装器高级模式出现安装失败问题

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#155]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.安装系统，分区界面，进入高级模式，删除中间3个分区，挂在已存在的home分区，安装失败。
![img_0075](https://user-images.githubusercontent.com/12388744/47850686-100e8f00-de11-11e8-9174-f7ce00039c94.JPG)

**Comment by hualet** [comment]
暂时无法重现 @mmxzmmxz 再试一下吧

**Comment by mmxzmmxz** [comment]
这个问题分析了下，具体如下：
【之前分区】：
1.磁盘为msdos分区表；
2.sda1-sda3为主分区+ntfs类型；
3.sda4为扩展分区，下面就是逻辑分区：
  sda8   /home （之前的home分区）
  sda5  sda6 sda7 sda9 为ext4类型。
【安装重新分配分区】：
4.安装进入高级模式，删除sda3、sda5、sda6、sda7，用sda5-sda7扇区重新新建分区挂载为/，sda8依旧挂载为/home，此时安装失败。
【分析】：
根据zhuzi说法，分区已经成功，但是分区信息没有写入配置文件，导致安装失败。至于写入失败问题，他会重新整理这块逻辑，完成后，用新的安装器测试该问题。

**Comment by mmxzmmxz** [comment]
还有一个问题说明下，sda3主分区删除了，不应该直接划入扩展分区滴

**Comment by hualet** [comment]
@mmxzmmxz 这个还能重现么？

**Comment by liuwen123** [comment]
暂未复现
