### ISSUE TITLE
屏幕缩放下，dock和控制中心出现白色线条

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1550]

**Comment by lq95v5** [comment]
用户反馈，已测试验证，开启屏幕缩放后出现白线问题，大概率出现。
![深度截图_选择区域_20190505175722](https://user-images.githubusercontent.com/29811622/57205883-4f9e7980-6ff4-11e9-94e6-fa70b1c3717e.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
