### ISSUE TITLE
桌面文件自动整理功能，存在文件删除后仍显示的问题

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1554]

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=177667
用户反馈
未复现

**Comment by hualet** [comment]
是不是贴错链接了呀 @lq95v5

**Comment by lq95v5** [comment]
> 是不是贴错链接了呀 @lq95v5

嗯。。贴错了，已更正。

**Comment by BLumia** [comment]
已经有调整一部分相关逻辑避免这种情况发生了，这周推送的修复更新会涵盖。

**Comment by liuwen123** [comment]
已修复
