### ISSUE TITLE
全盘安装，ntfs分区卷标错误，不是显示数据

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#156]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.全盘安装，安装完成后，进入系统，查看ntfs分区卷标是不是“数据”。
【测试结果】：
1.不是数据，显示分区大小。
![img_0078](https://user-images.githubusercontent.com/12388744/47850735-3f250080-de11-11e8-9c0a-efc63cb83772.JPG)

**Comment by zccrs** [comment]
在新iso中验证即可

**Comment by mmxzmmxz** [comment]
全盘安装非加密场景，盘符显示正确，显示“数据盘”；
但是全盘安装加密场景，盘符显示仍然不正确，为“414GB卷”

**Comment by zccrs** [comment]
@justforlxz 试一下加密分区能不能设置

**Comment by mmxzmmxz** [comment]
验证通过
