### ISSUE TITLE
「用户反馈」mout.ntfs进程占用高

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1560]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=177705

用户反馈
top查看进程发现有两个 mount.ntfs进程在大量的操作硬盘，导致很多操作一直卡住，系统没有死，但是操作很久才有反应

**Comment by leogorden** [comment]
我也遇到同样的问题，不知道是不是文件管理器的问题

**Comment by felixonmars** [comment]
是因为系统使用 NTFS 分区的问题吧，我之前有提过这种性能问题……

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
