### ISSUE TITLE
15.10 stable 版本 非deepin官方软件的窗口边缘 没有拖动箭头调整的鼠标样式提示。

### ISSUE THREAD

**Issue by wj008** [linuxdeepin/internal-discussion#1564]
【测试环境】
deepin 15.10 stable  dde 
【预置条件】

【测试步骤】
打开google 浏览器，或者 phpstrom 或者 visual studio code, 鼠标放到窗口 右侧边缘，或者 右下角边缘，并未出现拖动调整的鼠标样式提示，但是可以拖动窗口调整。
官方软件，和 部分软件没有这个现象。
【预期结果】

【测试结果】

【问题级别】
一般
【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
