### ISSUE TITLE
deepin-terminal 3.2.2.1-1. 鼠标右键点击打开右键菜单时，右键菜单的位置显示不正确

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1567]
deepin-terminal 3.2.2.1-1. When you right click on terminal, the menu appears in a wrong position away

https://bbs.deepin.org/forum.php?mod=viewthread&tid=177781

**Comment by lq95v5** [comment]
![deepin-screen-recorder_dde-file-manager_20190507181751](https://user-images.githubusercontent.com/29811622/57344748-0462a300-717b-11e9-8804-640848835c64.gif)

已测试未复现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
