### ISSUE TITLE
kwin下「坚果云」界面异常

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1569]

**Comment by lq95v5** [comment]
![深度截图_选择区域_20190508164330](https://user-images.githubusercontent.com/29811622/57362501-8a014580-71b1-11e9-9a6d-a464f5153b2c.png)

如图，屏幕分辨率4k

**Comment by zccrs** [comment]
这是坚果云自己的问题，在开启缩放为2倍的情况下，它初始化设置大小为 1026x854，后来又设置固定大小为 400x446，因此导致窗口内容显示不全

**Comment by zccrs** [comment]
由于无坚果云客户端源代码，因此无法确认问题出现的原因，目前只能使用kwin窗口脚本绕过此问题。
