### ISSUE TITLE
没联网情况下，驱动管理器切换方案成功

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#158]
【测试环境】：
deepin-installer  2.4.2-1
dde-file-manager         4.6.9-2           amd64
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
deepin-graphics-driver-manager 1.0.8-1
【测试步骤】：
1.不联网情况下，切换驱动管理器方案，提示成功且重启系统，重启之后发现切换失败。
【预期结果】：
1.没联网不应该提示用户切换成功。

**Comment by hualet** [comment]
那个地方不应该提示成功……

**Comment by listenerri** [comment]
@mmxzmmxz 还有这个问题吗, 我记得当时是因为没有使用最新的tag才有的这个问题

**Comment by hualet** [comment]
> @mmxzmmxz 还有这个问题吗, 我记得当时是因为没有使用最新的tag才有的这个问题

我记得显卡驱动管理工具在选择了一个方案以后会做一些准备工作，准备工作完成以后界面上提示的是“切换成功”之类的，改成“准备工作已完成”之类的就不会有issue标题说得这种误导了。

**Comment by listenerri** [comment]
> > @mmxzmmxz 还有这个问题吗, 我记得当时是因为没有使用最新的tag才有的这个问题
> 
> 我记得显卡驱动管理工具在选择了一个方案以后会做一些准备工作，准备工作完成以后界面上提示的是“切换成功”之类的，改成“准备工作已完成”之类的就不会有issue标题说得这种误导了。

准备工作如果没有完成, 比如下载失败, 也就是issue里说的没有联网的时候, 驱动管理器会显示下载失败之类的界面的

**Comment by mmxzmmxz** [comment]
验证通过
deepin-graphics-driver-manager:
  已安装：1.1.0-1
