### ISSUE TITLE
15.10.1 更新日志

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#1585]

**Comment by hualet** [comment]
@electricface @justforlxz @BLumia @zccrs

**Comment by electricface** [comment]
dde-daemon
* 修正识别爱奇异安卓版窗口失败
* 修正登录后自动给换壁纸在特殊情况不换
* 不在模块初始化过程中设置窗口主题

startdde
* 设置wine 程序缩放比
* 修正自动设置缩放比也发送了通知

dde-api
* 设置kwin 窗口管理器鼠标光标主题

go-dbus-factory
* 更新接口

lastore-daemon
* 更新镜像源列表

go-gir-generator
* 修正打包时测试失败

deepin-desktop-schemas
* 默认开启唤醒屏幕后锁屏

**Comment by justforlxz** [comment]
##### 截图
* 修复副屏幕开启缩放后不能选择窗口

##### 录屏
* 修复副屏幕开启缩放后不能选择窗口

##### 录音
* 修复dock的声音列表里出现了两个录音图标

##### 启动器
* 修复按ESC退出菜单后会选择到其他位置的图标

##### dock
* 修复对电池剩余时间的估计

##### 控制中心
* 修复更新完成后首页仍然提醒更新系统
* 修复wifi列表链接图标没有对齐中心
* 修复从非自定义模式切换到自定义模式会删除旧的配置

##### dde-session-ui
* 修复登录界面首次启动会崩溃
* 修复展开桌面会话列表时没有选择当前用户上次使用的桌面环境
* 修复切换用户会提醒密码错误

**Comment by BLumia** [comment]
deepin-terminal 终端 (3.2.3.1):

 - 修复使用 KWin 时雷神终端无法在失去焦点后重新获取焦点的问题
 - 支持在 KWin 下使用背景模糊
 - 选中路径后右键打开的功能增加支持相对路径
 - 支持标题栏移动到窗口下方位置（无界面入口，仅有配置文件，感谢 @avently ）
 - 右键菜单增加“打开链接”功能（感谢 @lolimay ）
 - 支持 `deepin-menu` 的缩放选项

dde-file-manager 文管 (4.8.4):

 - 修复桌面背景和屏幕尺寸部分情况下不一致的问题
 - 修复专业版部分情况下“我的共享”显示缺失项目的问题
 - 修复自动整理桌面部分情况可能显示空隙的问题
 - 对于 NTFS 分区，隐藏快速索引及 tag 产生的数据库文件以免在 Windows 中显示

**Comment by hualet** [comment]
@deepinzhangshuang

**Comment by zccrs** [comment]
dde-kwin
* 禁用窗口拖动时的半透明特效
* 禁用显示桌面的后四个角的窗口缩略图
* 修复显示桌面后点击激活或打开窗口时会导致其它已隐藏窗口显示
* 禁用窗口标题栏菜单
* 支持任务栏窗口预览功能

deepin-icon-theme
* 修复kwin上拖动或改变窗口大小时鼠标光标样式无变化

**Comment by deepinzhangshuang** [comment]
deepin-wine  2.18-18
修复了wine程序缩放问题

**Comment by deepinzhangshuang** [comment]
xserver-xorg-core
  更新修复m250/1060显卡３ｄ窗管不能使用问题。

**Comment by justforlxz** [comment]
wine的缩放修改需要用户重新设置一下缩放才能生效。

**Comment by yefeifei** [comment]
目前发现的问题：
1.副屏录制屏幕有问题；未修复；
2.dock电池剩余时间：经测试，不同笔记本存在异常，等待张丁元修复。
3.展开桌面会话列表时没有选择当前用户上次使用的桌面环境  -没有修复
4.显示桌面后点击激活或打开窗口时会导致其它已隐藏窗口显示 -没修复
5.kwin上拖动或改变窗口大小时鼠标光标样式无变化 --非深度应用 没有修复
6.控制中心音效和dock上电源提示没有翻译

**Comment by zccrs** [comment]
> 目前发现的问题：
> 1.副屏录制屏幕有问题；未修复；
> 2.dock电池剩余时间：经测试，不同笔记本存在异常，等待张丁元修复。
> 3.展开桌面会话列表时没有选择当前用户上次使用的桌面环境 -没有修复
> 4.显示桌面后点击激活或打开窗口时会导致其它已隐藏窗口显示 -没修复
> 5.kwin上拖动或改变窗口大小时鼠标光标样式无变化 --非深度应用 没有修复
> 6.控制中心音效和dock上电源提示没有翻译

4和5等待更新 kwin-x11 到 5.8.6.8

**Comment by zccrs** [comment]
@zhuxiujuancindy 需要整理和翻译一下日志

**Comment by electricface** [comment]
还需要再更新startdde

**Comment by zhuxiujuancindy** [comment]
> @zhuxiujuancindy 需要整理和翻译一下日志
翻译完毕。
[15.10.1 changelog.txt](https://github.com/linuxdeepin/internal-discussion/files/3176316/15.10.1.changelog.txt)

**Comment by yefeifei** [comment]
15.10.1 升级和ISO测试完成；以上问题剩余
1.副屏录制屏幕有问题；未修复；
2.dock电池剩余时间-已回退。
3.展开桌面会话列表时没有选择当前用户上次使用的桌面环境 -没有修复
更新日志需要删掉以上的信息

**Comment by zccrs** [comment]
> 15.10.1 升级和ISO测试完成；以上问题剩余
> 1.副屏录制屏幕有问题；未修复；
> 2.dock电池剩余时间-已回退。
> 3.展开桌面会话列表时没有选择当前用户上次使用的桌面环境 -没有修复
> 更新日志需要删掉以上的信息

@zhuxiujuancindy @Iq95v5

**Comment by zccrs** [comment]
> 15.10.1 升级和ISO测试完成；以上问题剩余
> 1.副屏录制屏幕有问题；未修复；
> 2.dock电池剩余时间-已回退。
> 3.展开桌面会话列表时没有选择当前用户上次使用的桌面环境 -没有修复
> 更新日志需要删掉以上的信息

@lq95v5
