### ISSUE TITLE
建议深度音乐优先从本地读取歌词

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1587]
![DeepinScreenshot_select-area_20190513104256](https://user-images.githubusercontent.com/34529003/57592977-027a5480-756c-11e9-8fc7-dd89df9d9dc6.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
