### ISSUE TITLE
华为笔记本 deepin-movie 播放4k视频cpu占用率达100%，没有使用硬件解码

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#159]
【测试环境】
15.8 ISO
【预置条件】
4k高分屏
【测试步骤】
1.使用深度影院播放4k视频；检查播放画面以及cPU占用率
【预期结果】
画面不卡顿，cpu占用率正常
【测试结果】
画面卡顿，cpu利用率高
【问题级别】
严重
【出现概率】
稳定

**Comment by yefeifei** [comment]
@liuwen123

**Comment by sonald** [comment]
原因大致是现在系统中有两个版本的libva(1,2)。abi不兼容，系统中的libva驱动都是基于libva2 api的，而mpv同时支持libva1和libva2，默认走了libva1，于是找不到驱动。还不知道怎么修。 

@zccrs  @hualet

**Comment by sonald** [comment]
@deepinzhangshuang 重新编译mpv，不要依赖libva1，依赖libva2

**Comment by sonald** [comment]
libva版本的问题解决了。
还有第二个问题 [ffmpeg/video] h264: Hardware does not support image size 3840x2160 (constraints: width 0-2048 height 0-1152). 也就是硬解不支持4K材质。

**Comment by zccrs** [comment]
@yefeifei 测点低分辨率的视频看能否硬解

**Comment by zhaofangfangdeepin** [comment]
@deepinzhangshuang 华为笔记本上依然没有硬解

**Comment by CallMeR** [comment]
@yefeifei  @deepinzhangshuang 这个华为的本子还有Windows吗？如果有的话下载一个叫做[DXVA Checker](https://www.videohelp.com/software/DXVA-Checker)的软件。然后点开测试一下CPU和GPU的硬解支持情况。我的PC机的测试结果给你参考一下：
![snipaste_2019-01-23_11-00-39](https://user-images.githubusercontent.com/11908641/51580069-328ae280-1efe-11e9-9dbf-78c11fac3445.png)
![snipaste_2019-01-23_11-01-02](https://user-images.githubusercontent.com/11908641/51580077-361e6980-1efe-11e9-9a1a-64fa1f618376.png)

**Comment by sonald** [comment]
我上面不是说的很清楚了么，显卡不支持4k材质，咋硬解啊

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
