### ISSUE TITLE
「KWIN」窗口工作区显示界面，壁纸显示异常

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1591]

**Comment by lq95v5** [comment]
![photo_2019-05-13_14-14-47](https://user-images.githubusercontent.com/29811622/57599568-bccc8480-7589-11e9-8895-03286ead1bf8.jpg)
![photo_2019-05-13_14-15-00](https://user-images.githubusercontent.com/29811622/57599569-bccc8480-7589-11e9-9103-5428c8b81782.jpg)


如图所示，工作区壁纸不同，但工作区概览（多任务视图）显示同样的壁纸

**Comment by zccrs** [comment]
内部任务中已有重复任务，短时间内无法处理
