### ISSUE TITLE
拨号连接没有显示连接过程的动效，点击后直接显示为已连接的图标，实际上未连接成功

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#162]
【测试环境】
dde-control-center:
【预置条件】
无
【测试步骤】
1.创建拨号连接后，点击进行连接，检查连接过程显示是否正常
【预期结果】
点击后，正在连接应该和vpn连接动效类似，未连接成功不能显示已连接的图标
【测试结果】
没有连接过程的动效图标，未连接成功还是显示已连接的图标
【问题级别】
一般
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39434

**Comment by listenerri** [comment]
> > https://cr.deepin.io/c/dde/dde-control-center/+/39434
> 
> 没有连接的状态，可以加上一个转圈的图标 ，参考vpn

有线连接也没有等待的状态，感觉不需要，一般都是直接就连上了

**Comment by yefeifei** [comment]
> > > https://cr.deepin.io/c/dde/dde-control-center/+/39434
> > 
> > 
> > 没有连接的状态，可以加上一个转圈的图标 ，参考vpn
> 
> 有线连接也没有等待的状态，感觉不需要，一般都是直接就连上了

@wangjia12  拨号连接是否需要？

**Comment by wangjia12** [comment]
> > > > https://cr.deepin.io/c/dde/dde-control-center/+/39434
> > > 
> > > 
> > > 没有连接的状态，可以加上一个转圈的图标 ，参考vpn
> > 
> > 
> > 有线连接也没有等待的状态，感觉不需要，一般都是直接就连上了
> 
> @wangjia12 拨号连接是否需要？

如果是和有线一样很快就连上了就不需要了

**Comment by listenerri** [comment]
@yefeifei 测一下以太网成功连接的时间吧，看是不是很短

**Comment by yefeifei** [comment]
> @yefeifei 测一下以太网成功连接的时间吧，看是不是很短

以太网秒连，但是DSL一直连不上

**Comment by wangjia12** [comment]
@hualet 帮我看看这个

**Comment by zccrs** [comment]
单单有线链接一般是很快的，不过拨号就不一定了，拨号是有一个过程的，最好加一个动画

**Comment by wangjia12** [comment]
> 单单有线链接一般是很快的，不过拨号就不一定了，拨号是有一个过程的，最好加一个动画

好 加一个转圈圈

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39498

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/39498

cr +1

**Comment by yefeifei** [comment]
ISO 测试通过
