### ISSUE TITLE
最新更新 stable 15.10.1 deepin dde-kwin 的一些bug 。

### ISSUE THREAD

**Issue by wj008** [linuxdeepin/internal-discussion#1623]
【测试环境】
deepin stable 15.10.1 桌面版  
amd 2700x 4k屏幕  1.5倍。 GTX 1050Ti

【预置条件】

【测试步骤】
1 鼠标样式虽说已经修正但是还存在问题，在切换为 光标主题为 DMZ-White 和 DMZ-Black 的时候依然无样式。
2 打开一个窗口 比如 google 浏览器，然后再打开设置 ，点击其中一个选项卡比如  账号 进入 所有设置， 当鼠标经过 设置窗口左侧的icon 时，google浏览器不停的闪动，输入框焦点不停的变化。并且出现黑边（google浏览器等非官方软件窗口失去焦点也比较容易出现黑边）， 如果打开的是 文件管理器 也出现类似的闪动。感觉这个问题是 设置窗口不停的激活和释放焦点造成。
3 非官方壁纸设置问题一直没有解决，如果是非官方的壁纸，点击开始按钮，没有模糊透明，注销页面不是一片黑就是一片白。

【预期结果】
感觉先修复好这些细节问题，其实其他新功能可以晚些添加都可以。
【测试结果】

【问题级别】

【出现概率】
100%

**Comment by wj008** [comment]
4  google 浏览器或者第三方应用 右键标题栏，或者标签栏目空白处，出现菜单，先设置使用系统标题栏和边框。 在这个情况下 窗口失去焦点，或者 点击标题栏目的时候，会出现标题栏半透明一闪而过。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
