### ISSUE TITLE
15.10.1控制中心左侧图标不能滚动到最下面

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1624]
![image](https://user-images.githubusercontent.com/34529003/57992408-90af8700-7ae6-11e9-94f5-72e58ce0df1a.png)
There is an issue in the control center, if I'm in the last tab, the keyboard tab is highlighted.
It is lagging when I scroll down and up in control center..

**Comment by justforlxz** [comment]
已知问题，暂无解决方法。

**Comment by wj008** [comment]
我给个建议，当你滚到菜单顶端的时候 应该以屏幕（菜单可见区域）顶端为计算，如果移到菜单底部的时候应该以屏幕（菜单可见区域）底部为计算，如果移到中间 则以屏幕（菜单可见区域）中间计算。
基准轴应该不是固定的，而是浮游的。
比如 菜单高度为 2000  窗口为800   如果滚到底部了，那么 基准轴应该在 800位置，也就是 滚动条+800
如果是 滚到到顶部  那么 基准轴在顶部 应该是 0   如果是在中间 那么 基准轴也在中间 所以是 滚动条+400 的位置

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
