### ISSUE TITLE
Deepin15.5 环境直接升级到Deepin15.8之后，登录界面的壁纸没有模糊处理

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#163]
【测试环境】
Deepin15.5 ISO
Deepin15.8 ISO
【预置条件】
1.测试机器上安装的Deepin15.5 Release 环境
【测试步骤】
1.在Deepin15.5 的环境上，添加测试仓库，打开控制中心-更新-检查并安装更新。
2.更新完成之后，重启系统，重新登录。
【预期结果】
1.升级正常，登录成功，登录界面正常。
【测试结果】
1.登录界面壁纸没有模糊。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
没有检查文件是不是符号链接。
