### ISSUE TITLE
系统监视器中云打印图标显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#164]
【测试环境】
deepin-system-monitor：1.4.6-1

【测试步骤】
打开系统监视器，打开深度云打印，在系统监视器中查看云打印图标显示

【预期结果】
图标显示正确

【测试结果】
图标显示为齿轮

【出现概率】
100%
![_ _20181102114622](https://user-images.githubusercontent.com/12492745/47892925-4aba0b00-de95-11e8-8196-00fc7f8f212b.png)

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-system-monitor/+/39564/

**Comment by liuwen123** [comment]
已修复
