### ISSUE TITLE
stable 15.10.1 deepin 在高效模式下，底部任务栏时常会直接变成黑条。

### ISSUE THREAD

**Issue by wj008** [linuxdeepin/internal-discussion#1655]
【测试环境】
stable 15.10.1 deepin 在高效模式下，底部任务栏时常会直接变成黑条。
2700x 1050ti 4k  1.5分辨率
【预置条件】

【测试步骤】
在打开浏览器，或者一些ide 在正常工作大约几个小时候，或者屏幕息屏后唤醒会出现底部工具栏变成一块黑条，没有icon 时间 关机 等等按钮。 但是猜到位置可以点击到。 不知道是不是溢出还是刷新重绘的问题。
【预期结果】

【测试结果】

【问题级别】

【出现概率】
小概率出现。

**Comment by wj008** [comment]
![深度截图_选择区域_20190524010335](https://user-images.githubusercontent.com/4304017/58337804-2a758c00-7e79-11e9-9e88-ea2b963840aa.png)
![深度截图_选择区域_20190524010222](https://user-images.githubusercontent.com/4304017/58337810-2ea1a980-7e79-11e9-8902-9e83f131784e.png)
![深度截图_20190524010444](https://user-images.githubusercontent.com/4304017/58337815-319c9a00-7e79-11e9-9d36-25cc2b2bbe7e.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
