### ISSUE TITLE
双无线网卡，创建热点失败，无法创建热点

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#166]
【测试环境】
15.8 iso
【预置条件】
2个无线网卡
【测试步骤】
1.无线网络模块，点击热点，创建热点，点击保存；
2.检查热点是否创建成功
【预期结果】
热点创建成功
【测试结果】
保存之后，返回到热点列表，热点还是显示关闭状态，新创建的热点并没有创建成功
【问题级别】
一般
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39462

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/39462

cr +1

**Comment by yefeifei** [comment]
ISO 测试通过
