### ISSUE TITLE
双无线网卡时，任务栏-无线列表中，个别的加密无线没有显示加锁标志。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#167]
【测试环境】
dde-dock:
  已安装：4.7.5-1
【预置条件】
1.系统中存在两块无线网卡。
【测试步骤】
1.打开两块无线网卡的无线列表，查看每个列表中的无线列表是否都一样。
【预期结果】
1.两块无线网卡的无线列表都显示正确。
【测试结果】
1.个别的加密无线没有显示加锁标志。
【问题级别】
提示
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181102134258](https://user-images.githubusercontent.com/14539782/47895883-b1dfbb80-dea5-11e8-9b43-08f3e8f19433.gif)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39515

**Comment by zhaofangfangdeepin** [comment]
测试通过
