### ISSUE TITLE
GTK的应用关闭按钮两边有竖线

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#168]
【测试环境】
deepin-gtk-theme 17.10.9-1
【预置条件】

【测试步骤】
1.打开gedit或者gnome的字体查看器，查看应用程序的窗口菜单是否都显示正确。
【预期结果】
1.窗口菜单都显示正确。
【测试结果】
1.窗口菜单的关闭按钮两边有竖线。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181102140414](https://user-images.githubusercontent.com/14539782/47896381-42b79680-dea8-11e8-96b4-6bd38438ae18.png)

**Comment by shule1987** [comment]
现在应该没这个问题了吧

**Comment by zhaofangfangdeepin** [comment]
测试通过
