### ISSUE TITLE
任务栏挂载插件-卸载全部，不能卸载smb共享挂载

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#169]
【测试环境】
dde-file-manager:
  已安装：4.6.10-1
dde-dock:
  已安装：4.7.5-1
【预置条件】
已挂载共享目录
【测试步骤】
1.在任务栏-挂载插件右键-卸载全部
【预期结果】
1.共享目录也被卸载
【测试结果】
1.共享目录没有被卸载。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39424/

**Comment by zhaofangfangdeepin** [comment]
这个卸载全部还是不能卸载。但是单次卸载，可以卸载。

**Comment by BLumia** [comment]
更新包后得重启 dde-dock 再测（

**Comment by liuwen123** [comment]
已修复
