### ISSUE TITLE
15.10.1 进不了桌面

### ISSUE THREAD

**Issue by ganrui** [linuxdeepin/internal-discussion#1691]
【测试环境】
15.10.1, dell 台式电脑，
【预置条件】

【测试步骤】
安装后正常使用了一段时间，重启登录后一直显示圆圈，进不了桌面，ctrl+alt+f2-f5 startx 可进入桌面，tty2 与 tty1 来回多次切换后，tty1显示如下，重启现象一至：
[Firmware Bug]:TSC_DEADLINE disabled due to Errate: please update microcode to version: 0x22 (or later)
【预期结果】

【测试结果】

【问题级别】

【出现概率】
重启现象一至

**Comment by felixonmars** [comment]
应当是 #183 已经解决的问题，为何还存在？ @deepinzhangshuang @liuwen123

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
