### ISSUE TITLE
桌面程序总是死掉，不知道什么情况

### ISSUE THREAD

**Issue by q5276** [linuxdeepin/internal-discussion#1697]
系统版本是15.10.1版本的，在昨天还更新了一个补丁包。

电脑是双屏，总是不定期屏幕就黑了，不过程序运行都正常。
桌面不能右键，没有壁纸，注销出去所有在运行的程序全都挂掉，不好重来。

虽然不影响工作，但是电脑没壁纸还是很不爽的。

**Comment by q5276** [comment]
![出状况的图片](https://github.com/q5276/component/blob/master/src/%E6%B7%B1%E5%BA%A6%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190530144532.gif?raw=true)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
