### ISSUE TITLE
#建议#assign an icon to any program

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1699]
John Smith Please ... make users a program for setting icons. The user can assign an icon to any program, and then create a package of icons for free distribution! More settings! Let it be deep in the style of MIUI, OS X Lion and not only ... Go on to create a community!
![DeepinScreenshot_select-area_20190531170815](https://user-images.githubusercontent.com/34529003/58694906-b1b98700-83c6-11e9-806f-3bb96033c90e.png)
from Facebook

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
