### ISSUE TITLE
新功能不是最重要的，我们要稳定性还有性能！！！

### ISSUE THREAD

**Issue by FlyMan2004** [linuxdeepin/internal-discussion#17]
RT，Windows10的升级删除文件已经非常令人爆炸了。deepin的稳定性相较于debian的testing分支还要差上一些，当务之急是把**稳定性和性能**搞起来！
另外能不能把使用触控的UI和使用鼠标的UI搞成像Windows那样的两套，一套打天下很危险。

**Comment by justforlxz** [comment]
internal-discussion主要是给内部人员使用，有问题可以在https://github.com/linuxdeepin/developer-center/issues 提issue.
