### ISSUE TITLE
任务栏为一直隐藏时上，插件栏，QQ和微信的右键菜单，弹出之后默认都被任务栏挡住

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#170]
【测试环境】
dde-dock:
  已安装：4.7.5-1
【预置条件】
1.任务栏设置为一直隐藏。
【测试步骤】
1.登录QQ和微信。任务栏设置为时尚模式。
2.在任务栏，插件栏。QQ和微信图标上右键。
3.查看弹出的右键菜单位置
【预期结果】
1.右键菜单位置没有被任务栏挡住
【测试结果】
1.右键菜单被任务栏挡住。
【问题级别】
提示
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181102144145](https://user-images.githubusercontent.com/14539782/47897608-721cd200-dead-11e8-8634-245e1a4d2c16.png)

**Comment by listenerri** [comment]
只有wine的程序右键菜单会这样，菜单出现后，鼠标在哪个窗口上，那个窗口就会处于置顶而盖住另一个

**Comment by zccrs** [comment]
@zhaofangfangdeepin 看一下15.7有没有问题

**Comment by zhaofangfangdeepin** [comment]
15.7 也是如此。

**Comment by zhaofangfangdeepin** [comment]
关闭处理
