### ISSUE TITLE
开启自动下载更新，进入更新界面，当更新下载完成后，界面还是显示下载大小，刷新界面才会显示已下载

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#171]
【测试环境】
dde-control-center:4.7.2-1
【预置条件】
系统有更新；打开自动下载                         
【测试步骤】
1.点击系统更新，等待操作结果
【预期结果】
提示已下载
【测试结果】
还是显示”下载大小xxMB“，界面没有自动刷新
【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
打开自动下载，点击更新，当更新已下载后，界面没有自动更新，需要刷新页面才显示为已下载

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40163/ 自动下载完成后会再刷新一下

**Comment by liuwen123** [comment]
已修复
