### ISSUE TITLE
「用户反馈」图片查看器对一个文件，可以打开多个窗口实例

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1711]

**Comment by lq95v5** [comment]
![072108qni7hhv5kzes4gnw](https://user-images.githubusercontent.com/29811622/58845684-a314ed80-86ae-11e9-9435-dc1b60b6bef8.png)

**Comment by zccrs** [comment]
这个不算问题，只是没有做这样的限制
