### ISSUE TITLE
深度显卡驱动管理器amd显卡驱动安装存在问题

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1714]

**Comment by lq95v5** [comment]
![TIM图片20190604132301](https://user-images.githubusercontent.com/29811622/58858530-47f8f000-86da-11e9-8760-cad3a5dd272a.jpg)


mesa 已经安装 显示不支持

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
