### ISSUE TITLE
安装器定位时区为莫斯科

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#172]
【测试环境】：
deepin-installer  2.4.3-1
【测试步骤】：
1.实体台式机，联网场景，安装系统，选择语言为中文，查看时区默认选中，选中莫斯科。
ps：大概率出现，方方、张爽均碰到过。

**Comment by justforlxz** [comment]
可能是走代理了，现在代理切换到俄罗斯了

**Comment by zccrs** [comment]
@justforlxz 贴一下关闭代理的方式
@mmxzmmxz 关闭网络代理后再测一下

**Comment by mmxzmmxz** [comment]
验证通过，代理设置为国内，则时区默认为上海。
