### ISSUE TITLE
插入或拔出USB设备后，WPS会冻住

### ISSUE THREAD

**Issue by levisliujunqi** [linuxdeepin/internal-discussion#1720]
DEEPIN 15.10.1
比如说刚刚，我插入鼠标，WPS直接冻住，鼠标和触摸版都不能操作WPS软件，但键盘可以操作WPS，在我的电脑上这个问题出现的概率为100%，望修复，谢谢！

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
