### ISSUE TITLE
launcher显示时，点击dock栏启动器图标，出现消失又闪出的问题

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#173]
【测试环境】：
deepin-installer  2.4.3-1
dde-dock	4.7.5-1
【测试步骤】：
1.launcher显示，点击dock启动器图标。
【预期结果】：
1.launcher消失。
【测试结果】：
1.launcher闪一下又出来。

**Comment by hualet** [comment]
我这好像没有问题

**Comment by felixonmars** [comment]
我这里也可以重现，但不是 100%。dock 版本更新到 4.7.5.2 后还是这样。

**Comment by zhaofangfangdeepin** [comment]
测试通过。这个以前的老问题。非概率重现，概率也比较低。不跟踪了。
