### ISSUE TITLE
切换键盘布局的bug

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1734]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=178652&extra=page%3D1
The problem with switching the keyboard layout. I use the English and Russian. The layout switches with a third or fourth press. This is not immediately apparent, it appear during work.

**Comment by lallmon** [comment]
This is a really big problem. Not only does it change my keyboard from Dvorak -> US English after my laptop sleeps, but it persists until I reboot. This is a a blocker from using what could be the best DE in the game.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
