### ISSUE TITLE
安装器输入密码处切换大小写建议有提示

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#174]
【测试环境】：
deepin-installer  2.4.3-1
dde-dock	4.7.5-1
【测试步骤】：
1.安装器账号界面、全盘安装加密界面，建议输入密码时，切换大小写有提示。可跟登录界面一样。

**Comment by zccrs** [comment]
@justforlxz 来得及就加

**Comment by mmxzmmxz** [comment]
这个目前仍然没加大小写状态。
deepin-installer 2.5.10

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41258/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/deepin-installer-reborn/+/41258/

v+1

**Comment by liuwen123** [comment]
已修复
