### ISSUE TITLE
账号登录问题

### ISSUE THREAD

**Issue by spilledyear** [linuxdeepin/internal-discussion#1747]
问题/建议描述
用户名 spilledyear，之前用spilledyear这个账号登录过官网，今天登录的时候提示用户未激活。

问题如何重现
用spilledyear 用户名登录就会提示用户未激活

问题重现频率
all the time
--- from:https://feedback.deepin.org/feedback/detail/27250

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
