### ISSUE TITLE
自动锁屏后光标不会在密码输入栏， 无法输入

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1748]

**Comment by lq95v5** [comment]
用户反馈 https://bbs.deepin.org/forum.php?mod=viewthread&tid=179167

在使用过程中，本人也出现过此情况

**Comment by zccrs** [comment]
在新版中已经通过其它方式提升了此问题的体验

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
