### ISSUE TITLE
修改并上传“xxx需要认证”的文案到transifex翻译

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1749]
有用户反馈，字体安装器和系统修复工具的“xxx需要认证”的文案没有上传到transifex翻译，且用词不统一。
![Fonts](https://user-images.githubusercontent.com/34529003/59580451-c787b580-9103-11e9-867f-b42fdf08a9cd.png)
![Repair](https://user-images.githubusercontent.com/34529003/59580454-c8204c00-9103-11e9-8ae4-7c3217cef07f.png)

现需要修改文案，并上传到transifex。
文案更改如下：
字体安装器：Authentication is required to install the font file
系统修复工具：Authentication is required to run the repair tools

**Comment by BLumia** [comment]
@electricface deepin-gettext-tools 应该需要个 tag ？

**Comment by zhuxiujuancindy** [comment]
已修复
