### ISSUE TITLE
全盘安装swap分区大小设置不正确

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#175]
【测试环境】：
deepin-installer  2.4.3-1
dde-dock	4.7.5-1
【测试步骤】：
1.安装器进行全盘安装，内存大小为2G，安装完后，查看swap分区大小，也是2G。
【预期结果】：
1.3G。

**Comment by mmxzmmxz** [comment]
![_ _20181102172425](https://user-images.githubusercontent.com/12388744/47906737-d8f9b580-dec4-11e8-9ec1-246359b89393.png)

6G内存，实际分的swap为7G，按照计算方法应该为8G。

**Comment by justforlxz** [comment]
换实现了，好像有另外的重复任务，在新iso中测试吧

**Comment by mmxzmmxz** [comment]
验证通过
deepin-installer 2.5.10
