### ISSUE TITLE
回收站文件权限出现问题，无法删除

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1750]

**Comment by lq95v5** [comment]
用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=178838
相关反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=168768&extra=

用户测试已复现


期望行为：优化删除行为逻辑

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
