### ISSUE TITLE
安装live系统ISO，语言不能切换，维护软件太少

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1751]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=179357&extra=page%3D1

**Comment by zccrs** [comment]
live系统为了减少磁盘占用，本身就精简了很多东西

**Comment by zccrs** [comment]
建议下载专用的live系统使用 packagess.deepin.com:8088/live-system/
