### ISSUE TITLE
options nvidia-drm modeset=1 的字样

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1777]
改为0以后 sudo update-initramfs -u重启 外接屏幕依旧没图像

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174676&page=2#pid590190

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
