### ISSUE TITLE
全盘安装后，再次安装系统，分区名称显示均为primary

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#179]
【测试环境】：
deepin-installer  2.4.3-1
dde-dock	4.7.5-1
dde-daemon               3.4.0-1           amd64
dde-api                  3.4.0-1           amd64
dde-control-center       4.7.3-2           amd64
network-manager          1.10.8-2deepin    amd64
【测试步骤】
1.先进行全盘安装，会自动进行分区。后重启安装系统，查看简单分区显示，均显示primary。

**Comment by mmxzmmxz** [comment]
![img_0081](https://user-images.githubusercontent.com/12388744/47908702-bd90a980-dec8-11e8-96e6-f5f434eda0fb.JPG)

**Comment by zccrs** [comment]
没有问题
