### ISSUE TITLE
点击声音图标后，提示信息无法消失

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#18]
【测试环境】
dde-dock：4.7.4+r0+g2d273cd

【预置条件】
高效模式

【测试步骤】
在高效模式下，将声音图标向上拖拽隐藏，然后点击^图标中的声音按钮，会自动弹出音量进度条显示

【预期结果】
点击其他地方后，音量进度条会自动消失

【测试结果】
进度条无法消失

【问题级别】
一般

【出现概率】
100%

![image](https://user-images.githubusercontent.com/12492745/47625535-c009a100-db60-11e8-9f6e-2764de03131c.png)

**Comment by liuwen123** [comment]
![_ _20181029093052](https://user-images.githubusercontent.com/12492745/47625638-47571480-db61-11e8-952f-d3b8d5c2585a.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39292
系统图标不应该被允许拖拽到容器里，修了这个，那么就不会再有上述bug了
