### ISSUE TITLE
低分辨率下软件商店窗口 大小修正

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1802]

**Comment by lq95v5** [comment]
![211943hsgsli2mmmkxk86m](https://user-images.githubusercontent.com/29811622/60068002-80bb4080-973f-11e9-8dd3-0071221705b8.png)
问题如图
期望行为:在低分辨率下应用商店不会遮挡任务栏

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
