### ISSUE TITLE
DDE 窗管bug反馈

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1804]

**Comment by lq95v5** [comment]
用户反馈：（1）使用快捷键切换2D与3D窗管后，终端标题栏的按钮会无法点击（deepin以及manjaro deepin上均可复现）
（2）使用快捷键切换2D与3D窗管后，3D窗管下的控制中心背景模糊有一定概率渲染错位（仅在manjaro deepin上有较大概率复现）
（3）3D窗管下，打开Deepin原生应用（深度终端除外）和WPS办公软件，最小化后恢复会导致：a.无法再次最小化；b.尝试调整窗口大小，鼠标图标会出错；c.进行窗口最大化，会导致标题栏部分或全部按钮无法点击（WPS无b c两点问题，所有问题仅在manjaro deepin上可稳定复现）

https://bbs.deepin.org/forum.php?mod=viewthread&tid=179859

**Comment by zccrs** [comment]
manjaro deepin的kwin是原生的，第三个问题是在deepin-kwin项目中解决的。其它环境可以先通过删除 /etc/xdg/kwinrc 中的 “HiddenPreviews=6” 这行（如果 ~/.config/kwinrc 中存在也需要一并删除）避免问题，注销再进入系统后查看这两个文件确保此配置项已被删除！需要注意的是，删除这个配置项后会导致dock上无法预览最小化的窗口

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
