### ISSUE TITLE
支持AppImage

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/internal-discussion#181]
请在Deepin中支持开箱即用的AppImage格式。 AppImage是一种将Linux的第三方应用程序作为单个文件分发的格式。 就像macOS上的.dmg一样。

TIM, QQ等应用程序已经以AppImage格式提供。

文档位于https://docs.appimage.org/

要更方便地使用AppImage文件，请考虑预安装[AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)。

支持AppImage（http://appimage.org/）将具有以下优势：
 - 打包为AppImage的应用程序可以在许多发行版上运行（包括Deepin, Ubuntu，Fedora，openSUSE，CentOS，elementaryOS，Linux Mint等）
 - 一个app =一个文件=超级简单的用户：只需下载一个AppImage文件，[make it executable]（http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80） ，并运行
 - 无需拆包或安装
 - 不需要root
 - 没有系统库发生变化
 - 开箱即用，无需安装运行时
 - 与`appimaged`的可选桌面集成
 - 可选的二进制增量更新，例如，使用AppImageUpdate进行连续构建（仅下载二进制差异）
 - 可以选择GPG2签署您的AppImages（在文件内）
 - 适用于实时ISO (Live ISO)
 - 双启动多个发行版时可以使用相同的AppImages
 - 可以在可用AppImages的AppImageHub（https://appimage.github.io/apps）中心目录中列出
 - 可以使用`--appimage-extract`参数兼作自解压压缩归档

这里是一个概述（https://appimage.github.io/apps）已经分发上游提供的官方AppImages的项目。

如果您有疑问，AppImage开发人员在irc.freenode.net上的#AppImage上。

**Comment by justforlxz** [comment]
你好，文件管理器已经支持运行双击运行appimage了。
