### ISSUE TITLE
Swahili 时间显示问题

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1822]
Hi, am doing a localization to Kiswahili. The typical clock is split into 12 hours, but starts at 6:00am in the morning to 6:00pm at night, so that 7:00am corresponds to 1:00 in the morning and 7:00pm corresponds to 1:00 in the night. Is there any way to accommodate this in Deepin desktop? See for example https://www.spokenswahili.com/blog/telling-the-time-in-swahili/
切换到Swahili语，应该比正常时间晚6个小时

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
