### ISSUE TITLE
系统启动会有错误日志打印

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#183]
【预置条件】
系统启动

【测试步骤】
系统启动查看启动界面显示

【预期结果】
系统开机到启动完成，没有日志打印显示

【测试结果】
系统启动后会有一段错误日志打印

【出现概率】
100%
![_20181105111040](https://user-images.githubusercontent.com/12492745/47976030-7cc4aa80-e0eb-11e8-892d-e5c57296ac3c.jpg)

**Comment by liuwen123** [comment]
已经上传

**Comment by zccrs** [comment]
@deepinzhangshuang 这个好像是需要装一个包吧，能预装吗

**Comment by deepinzhangshuang** [comment]
intel-microcode, amd64-microcode　添加这两个固件的预装。

**Comment by liuwen123** [comment]
已预装
