### ISSUE TITLE
启动器软件图标右边有一条黑色的细线

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#185]
【测试环境】
dde-launcher：4.5.1-1

【测试步骤】
安装最新系统后，在分辨率为1920*1080的系统上，将屏幕缩放设置为1.25倍，打开启动器上下滚动鼠标，查看软件显示

【预期结果】
软件显示正常

【测试结果】
软件右边会有一条细线

【出现概率】
100%
![_dde-launcher_20181105113848](https://user-images.githubusercontent.com/12492745/47976965-6a00a480-e0f0-11e8-8372-251e413aabf0.png)

**Comment by zccrs** [comment]
高分屏细线问题暂不处理

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
