### ISSUE TITLE
telegram dde-kwin反馈bug

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1854]

**Comment by lq95v5** [comment]
![深度截图_选择区域_20190703103823](https://user-images.githubusercontent.com/29811622/60559345-b20ac080-9d7e-11e9-8d92-b6b2b36dd402.png)


[ ] 俄语输入法没有后台图标
[ ] 窗口边角不统一 ，有圆角有直角
[ ] 有些窗体的标题栏过大  @shule1987

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
