### ISSUE TITLE
Fix the big problems at Deepin Store

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/internal-discussion#1864]
The Deepin Store has just a nice look but little practicality, the servers do not work properly, the apps are very outdated (in my opinion this is a big problem that needs to be fixed)

**Comment by BLumia** [comment]
Deepin stable will catchup the debian buster version in the 15.11 release and after that most of the packages will be updated.

Please notice that  [internal-discussion](https://github.com/linuxdeepin/internal-discussion/) is not for developer discussion, so please consider post your issue to [developer-center](https://github.com/linuxdeepin/developer-center/)
