### ISSUE TITLE
#高分屏 dock上WiFi列表图标显示没有对齐

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#187]
【测试环境】
dde-dock:4.7.5.1-1
【预置条件】
开启高分屏：1.5或者2倍
【测试骤】
1.高分屏下，检查dock的上无线网络列表显示
【预期结果】
WiFi列表图标显示对齐
【测试结果】
无线网络图标显示没有对齐
【问题级别】
一般
【出现概率】
稳定
![_ _20181105114948](https://user-images.githubusercontent.com/14539819/47977242-ec3d9880-e0f1-11e8-99b5-c3cfc711f008.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39454

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-dock/+/39454

cr+1

**Comment by yefeifei** [comment]
ISO测试通过
