### ISSUE TITLE
卸载图标过大

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1872]

**Comment by lq95v5** [comment]
[Desktop Entry]
Name=Shift
Icon=/home/deepin/.local/share/icons/hicolor/1024x1024/apps/shift.png
Version=3.8.0
GenericName=Shift
X-GNOME-FullName=Shift
Comment=Shift
Encoding=UTF-8
Type=Application
Terminal=false
Exec=/usr/share/shift-linux/resources/../Shift -mailto %u
Categories=Network;
MimeType=x-scheme-handler/mailto;
X-Deepin-CreatedBy=com.deepin.dde.daemon.Launcher
X-Deepin-AppID=shift-application

deepin@deepin-PC:~$ file /home/deepin/.local/share/icons/hicolor/1024x1024/apps/shift.png
/home/deepin/.local/share/icons/hicolor/1024x1024/apps/shift.png: PNG image data, 1024 x 1024, 8-bit/color RGBA, non-interlaced

![图片已粘贴至2019-7-4 17-09](https://user-images.githubusercontent.com/29811622/60654954-84f20700-9e7f-11e9-88dc-7d882d25d0bb.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
