### ISSUE TITLE
点击系统监视器我的进程一栏时，系统卡死，所有位置都不能点击，只能长按电源重启

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1873]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180260

**Comment by Playhi** [comment]
> playhi@playhi-PC:\~$ deepin-system-monitor
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/deepin-system-monitor/translations/deepin-system-monitor_zh_CN"
Ethernet link detected
QXcbConnection: XCB error: 152 (Unknown), sequence: 1302, resource id: 0, major code: 143 (Unknown), minor code: 2
QXcbConnection: XCB error: 152 (Unknown), sequence: 1546, resource id: 0, major code: 143 (Unknown), minor code: 2
QXcbConnection: XCB error: 152 (Unknown), sequence: 2340, resource id: 0, major code: 143 (Unknown), minor code: 2
QXcbConnection: XCB error: 152 (Unknown), sequence: 2646, resource id: 0, major code: 143 (Unknown), minor code: 2
QXcbConnection: XCB error: 152 (Unknown), sequence: 2902, resource id: 0, major code: 143 (Unknown), minor code: 2
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
playhi@playhi-PC:~$ deepin-system-monitor
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/deepin-system-monitor/translations/deepin-system-monitor_zh_CN"
Ethernet link detected
QXcbConnection: XCB error: 152 (Unknown), sequence: 1329, resource id: 0, major code: 143 (Unknown), minor code: 2
已终止


用着用着发现，如果打开以后，点下列表里的项或者右上角缩下去再放大，或者点缩小边上的“三条杠”再切换就没事。
上面是日志，已终止的是被我tty2 kill的，另一个是正常使用然后我自行正常关闭的

**Comment by zccrs** [comment]
https://github.com/linuxdeepin/qt5dxcb-plugin/commit/8ee20d5751120bb1d1005f9a9dc47bef8f15dd12
