### ISSUE TITLE
dependencies need libc6 and bumblebee

### ISSUE THREAD

**Issue by mathpfvr** [linuxdeepin/internal-discussion#1874]
I tried install firefox .deb and the application manager displays an error message saying that the dependency libc6 is missing

**Comment by lolimay** [comment]
This repo is only for internal discussion. Please make your feedbacks by creating the issues in the [linuxdeepin/developer-center](https://github.com/linuxdeepin/developer-center/issues/new?template=bug_report.md) repository. Thanks!

**Comment by BLumia** [comment]
Please make sure your .deb package is provided for Deepin distro (not a ubuntu package, for example), consider install firefox via the Deepin official package repo is generally recommended.
