### ISSUE TITLE
15.10.2 bug汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1878]

**Comment by lq95v5** [comment]
- [ ]  更新后“系统监视器”出现问题，打开后如果点击“用户的进程”会直接卡死，

**Comment by lq95v5** [comment]
- [ ]  安装器密码变成明文了

**Comment by lq95v5** [comment]
- [ ] 

有时候启动出现这个，不知道我USB接了一个风扇有没有影响，但不应该有影响啊
--
![image](https://user-images.githubusercontent.com/29811622/60777882-2a022d80-a167-11e9-8dab-138c816a2dbb.png)
https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=180282&pid=601464&fromuid=101846

- [ ] 双击文件夹有时打不开，甚至有时点了不下十次才打开
- [ ] 系统更新后，打开深度监视器会导致死机，经过多次测试都是这样。

intel 核显，今天切换为加速模式，才出现这个问题。昨天使用默认驱动没有问题。

- [ ] 在开启对话框选择保存位置的时候，对话框窗口又丢了，只能强杀。
![image](https://user-images.githubusercontent.com/29811622/60777979-95e49600-a167-11e9-85c6-dd1b63cca18b.png)

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180372 

前几天更新系统后，偶尔会出现一个bug。描述：我习惯了ALT-F4关闭当前窗口，有一定概率出现黑屏，然后让我输入账号、密码，输入后，能返回桌面，之后每插入一次u盘都要提示要验证密码，及其麻烦。

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180366 

PC:~$ sudo apt upgrade正在读取软件包列表... 完成正在分析软件包的依赖关系树       正在读取状态信息... 完成       您也许需要运行“apt --fix-broken install”来修正上面的错误。下列软件包有未满足的依赖关系：libglx-mesa0 : 依赖: libglapi-mesa (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装libglx-mesa0:i386 : 依赖: libglapi-mesa:i386 (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。 | PC:~$ sudo apt upgrade正在读取软件包列表... 完成正在分析软件包的依赖关系树       正在读取状态信息... 完成       您也许需要运行“apt --fix-broken install”来修正上面的错误。下列软件包有未满足的依赖关系：libglx-mesa0 : 依赖: libglapi-mesa (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装libglx-mesa0:i386 : 依赖: libglapi-mesa:i386 (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。
-- | --
PC:~$ sudo apt upgrade正在读取软件包列表... 完成正在分析软件包的依赖关系树       正在读取状态信息... 完成       您也许需要运行“apt --fix-broken install”来修正上面的错误。下列软件包有未满足的依赖关系：libglx-mesa0 : 依赖: libglapi-mesa (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装libglx-mesa0:i386 : 依赖: libglapi-mesa:i386 (= 18.1.9-1~bpo9+1) 但是 18.1.9-1~bpo9+3deepin 已经安装E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180359 【致命BUG】Deepin KWin经常随机性卡死

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180377 屏幕缩放1.5倍，应用商店显示有问题 
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180376 升级到最新版本15.10.2之后，显示屏亮度严重偏暗。

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180469 回收站清空无效  **[严重]**

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180470 15.10.1安装后登录闪退

**Comment by zccrs** [comment]
说文件管理器中不显示图标的那个问题，让他看一下是不是 dde-qt5integration 这个包没了

**Comment by zccrs** [comment]
系统监视器卡死问题已解决

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
