### ISSUE TITLE
控制中心 系统信息不好看

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#188]
![image](https://user-images.githubusercontent.com/24972525/47977378-b0ef9980-e0f2-11e8-99d3-8ffc7d1be803.png)
copyright 2011-2-18建议单独一行

**Comment by Aichang2017** [comment]
@shule1987

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/229
