### ISSUE TITLE
deepin 15.10 doesn't let me mount the persistence partition on the USB disk

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1880]
![image](https://user-images.githubusercontent.com/34529003/60780122-c0d2e800-a16f-11e9-819d-c12989720718.png)
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180159&extra=page%3D1

**Comment by BLumia** [comment]
I don't understand the issue itself, way to reproduce?

**Comment by David1501** [comment]
> 
> 
> I don't understand the issue itself, mount partition via gparted should always works without problem (please notice that the partition list in the file manager is not correct when gparted is open), way to reproduce?

Ciao this is David..and i'm not an expert on linux :-) Can you please elaborate a bit on "is not correct when gparted is open), way to reproduce"

**Comment by BLumia** [comment]
Sorry about my bad English. I means, while gparted is open, all the partition will be disappeared due to the partition get removed thus gparted is able to edit/modify them, so if you expect a list of your partitions on your disk while gparted is opened, then the list is not correct.

**Comment by David1501** [comment]
Hummm i see but why is it that 15.8 work fine without problems and 15.10 don't? 
Any solution to correct the list?

**Comment by BLumia** [comment]
Technically the list is correct but it probably can make some people confuse(That's why I say the list is "not correct" above). But in fact user shouldn't use the file manager with gparted also opened. Maybe consider close your gparted window first?

**Comment by David1501** [comment]
even i i close gparted....the problem with 15.10 remain....so how can i make 15.10 recognize the persistence partition?

THX

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
