### ISSUE TITLE
Deepin calculator: use [, - comma] as decimal mark instead of [. - dot] in polish and other languages

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1884]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180158&extra=page%3D1
![image](https://user-images.githubusercontent.com/34529003/60784834-16fd5680-a183-11e9-9a26-67e1c2927fde.png)
use [, - comma] as decimal mark instead of [. - dot]

**Comment by wangjia12** [comment]
计算机新版的时候看看能不能处理一下国家的事情 估计不能

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
