### ISSUE TITLE
文件管理器最近使用

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#189]
有的文件被打开了但是文件管理器“最近使用”里面没有记录，15.8发布之前需要都记录下来。
@zccrs

**Comment by wangjia12** [comment]
txt文件能显示，doc和png不显示试时新建的文件反复打开再进入最近使用目录没有显示

论坛ID
deepin157

E-mail
326543252@qq.com

QQ
326543252

**Comment by wangjia12** [comment]
还有一个人说以前用的能显示，当天的不能显示。
估计是同一个问题

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
