### ISSUE TITLE
DTK 相关工具的 CMake 支持

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#1897]
这里指的是 `libdtkcore-bin` 包和 `deepin-gettext-tools` ，前者提供了 `/usr/lib/dtk2/dtk-settings` 供从 json 生成 cpp 文件以供设置对话框的国际化支持使用，后者提供了包括 `deepin-policy-ts-convert` （policy 文件的国际化生成工具）在内的一些辅助工具。

目前在 deepin-movie-reborn 等项目的 CMakeLists.txt 使用了调用 `/usr/lib/dtk2/dtk-settings` 来生成所需文件，deepin-font-installer 等项目也有类似的做法直接调用了 `deepin-policy-ts-convert`，而这些依赖不能通过 CMake 的 find_package 方式进行检测，而如果提供 CMake 支持的话，还可以顺带提供一些辅助函数用来进行这些生成工作（比如 [`dtk_create_i18n_from_json()`](https://github.com/BLumia/deepin-terminal-ng/blob/60d6651e69741dc9f2591a5508fb9ecc154bb96d/DtkSettingsToolsMacros.cmake) 之类），而不是每个项目都写一遍相同的执行操作。

所以目前的问题是：

1. 是否需要添加 CMake 支持？
2. 如果添加这种支持，这种功能非常近似的功能分散在两个不同的项目和包中是不是不太合适？是否需要调整？

cc @hualet @justforlxz @zccrs @electricface

**Comment by BLumia** [comment]
补充： https://github.com/linuxdeepin/dtkcore/pull/24 更新后 dtk-settings 的 binary 位置也变了，从 `/usr/lib/dtk2/dtk-settings` 变成了 `/usr/lib/x86_64-linux-gnu/libdtk-2.0.16/DCore/bin/dtk-settings` 。需要使用 `dtk-settings` 时，`DtkCore/DtkCoreConfig.cmake` 提供了 `DTKCORE_TOOL_DIR` 获得这个路径。

**Comment by hualet** [comment]
@BLumia 来个修改看看？

**Comment by BLumia** [comment]
`deepin-gettext-tools` 的目前大概不会处理。`dtkcore` 的已在内网提交并合并，暂时先关掉了。
