### ISSUE TITLE
高效模式下键盘按钮图标会隐藏

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#19]
【测试环境】
dde-dock：4.7.4+r0+g2d273cd

【预置条件】
时尚模式

【测试步骤】
将dock调整为市场模式，在时尚模式下点击< > 按钮，可以展开和隐藏系统图标
在按钮为 > 状态时，点击旁边的键盘按钮图标

【预期结果】
会显示键盘设置菜单

【测试结果】
键盘图标会隐藏

【问题级别】
一般

【出现概率】
100%

![_ _20181029100223](https://user-images.githubusercontent.com/12492745/47625704-c64c4d00-db61-11e8-92aa-85b9361c79c6.png)

**Comment by listenerri** [comment]
这个是正常的，因为控制按钮右边的图标是当前活动的图标，点击之后意味着已经取消了其活动状态，所以将其隐藏到收起的控制按钮里了

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39291
这个提交修复了活动图标消失后没有重新计算整个托盘以及dock的大小
