### ISSUE TITLE
wifi密码输入框按钮显示删除锯齿

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#190]
【测试环境】
新装ISO

【测试步骤】
将屏幕缩放设置为1.25，任意点击WiFi热点，弹出密码输入框，任意输入密码，查看删除按钮显示

【预期结果】
删除按钮显示正常

【测试结果】
显示锯齿

【出现概率】
100%
![_dnetwork-secret-dialog_20181105132052](https://user-images.githubusercontent.com/12492745/47979434-1e54f780-e0fe-11e8-8a7e-947adf08a8e4.png)

**Comment by listenerri** [comment]
这个应该已经修复了，跟之前一个清空图标显示过大的issue一样，可以回归测一下，或者装内网最新的dde-session-daemon测一下

**Comment by liuwen123** [comment]
已修复
