### ISSUE TITLE
时钟的时间不正确

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1908]
![image](https://user-images.githubusercontent.com/34529003/60865878-880f3d80-a259-11e9-814f-56f18177b338.png)
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180426&extra=page%3D1

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
