### ISSUE TITLE
用户许可协议滚动条右键菜单没翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#193]
【预置条件】
安装新ISO

【测试步骤】
在安装的过程中进入到用户许可协议界面，在滚动条上点击右键

【预期结果】
在第一个页面设置中文后，许可协议界面滚动条右键菜单也是中文

【测试结果】 
右键菜单没有翻译

【出现概率】
100%
![_20181105133900](https://user-images.githubusercontent.com/12492745/47979876-3594e480-e100-11e8-81b3-b7871f9b4a87.jpg)

**Comment by yefeifei** [comment]
不是控制中心的bug，我以为是控制中心的

**Comment by liuwen123** [comment]
已修复
