### ISSUE TITLE
15.10.2 待机后，Polish 键盘问题

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1939]
Sebastian Musielak：
After installing this update I'have been having problems with my Polish keyboard, it is loosing typical Polish letters after each wake from suspend, I have to reboot the computer to get my Polish qwertz functioning again. Can you fix this? Or how to revert to the previous version of the Desktop?

from facebook

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
