### ISSUE TITLE
遇到了有线网络连接正常，但是dock上显示有线连接断开的情况。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#194]
【测试环境】
dde-dock:
  已安装：4.7.5.1-1
【预置条件】
无
【测试步骤】
1.正常使用系统，如待机和重启之后。查看有线连接显示连接是否正常。
【预期结果】
1.有线连接显示正常。
【测试结果】
1.有线连接连接正常，但是dock上显示有线连接断开。
【问题级别】
一般
【出现概率】
遇到了一次

**Comment by zhaofangfangdeepin** [comment]
![_ _20181105135122](https://user-images.githubusercontent.com/14539782/47980284-eea7ee80-e101-11e8-8206-277611938b43.gif)

**Comment by zhaofangfangdeepin** [comment]
[deepin-feedback-cli-Deepin-15.8-all-20181105-134539.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547074/deepin-feedback-cli-Deepin-15.8-all-20181105-134539.tar.gz)

**Comment by listenerri** [comment]
这个问题在专业版上比较容易复现, 应该是网络库里面发出设备状态变化的信号出了问题

**Comment by listenerri** [comment]
应该是后端没有完整转发NetworkManager的信号导致的:
![default](https://user-images.githubusercontent.com/7995379/49640160-c5071d80-fa47-11e8-914e-baad02537fd8.png)

**Comment by liuwen123** [comment]
已推送
