### ISSUE TITLE
加载EFI启动时，有一些报错

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#195]
【测试环境】
Deepin15.8
【预置条件】
EFI启动
【测试步骤】
1.UEFI启动系统，查看启动打印日志
【预期结果】
1.没有异常打印日志
【测试结果】
1.有异常打印日志
【问题级别】
1.提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![20181105135524](https://user-images.githubusercontent.com/14539782/47980467-bf45b180-e102-11e8-87ed-10ae3b87525a.jpg)

**Comment by hualet** [comment]
新问题还是老问题？ @zhaofangfangdeepin

**Comment by zhaofangfangdeepin** [comment]
老问题

**Comment by deepinzhangshuang** [comment]
安装器先把这个mmx64.efi加上吧。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
