### ISSUE TITLE
时尚模式-托盘区域来消息处理的问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#196]
【测试环境】

【预置条件】
时尚模式托盘区域收起，qq来消息闪烁

【测试步骤】
点击qq闪烁的消息

【预期结果】
没有未读消息之后qq就要收进去了

【测试结果】
没有未读消息后企业图标还在外面，再点一下才进去

【问题级别】

【出现概率】

**Comment by wangjia12** [comment]
@zccrs @listenerri

**Comment by wangjia12** [comment]
@shule1987

**Comment by wangjia12** [comment]
【预期结果】
没有未读消息之后qq就要收进去了

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39488

需要测试：
收起后是否有托盘留在外面
收起后qq等程序消息提示是否正常出现
收起后点击活动图标(如qq消息)后活动图标是否被正确隐藏

**Comment by zhaofangfangdeepin** [comment]
测试通过
