### ISSUE TITLE
覆盖文件时的提示 不够清晰

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1968]
![195618epf6sx3c626n66p6](https://user-images.githubusercontent.com/29811622/61539401-0647bd00-aa6e-11e9-8952-7d6fc366cf00.png)

用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=180582

用户觉得 ，覆盖文件时的提示不够清晰。

期望行为：优化覆盖文件提示。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
