### ISSUE TITLE
15.11 bugs

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1969]

**Comment by lq95v5** [comment]
- [] dde-dock时间显示永远是12小时制，怎么也改不了

**Comment by lq95v5** [comment]
安装失败 https://bbs.deepin.org/forum.php?mod=viewthread&tid=180866

**Comment by lq95v5** [comment]
15.11最大的BUG，亮度调节到最大屏幕极暗
 https://bbs.deepin.org/forum.php?mod=viewthread&tid=180786

日志：
https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=180786&pid=606046&fromuid=101846

**Comment by lq95v5** [comment]
新安装字体无效？https://bbs.deepin.org/forum.php?mod=viewthread&tid=180951 

待测试哦

**Comment by lq95v5** [comment]
deepin 15.10.2升级15.11 后 锁屏在进入桌面无法进行无密码进入 


【严重 】 待测试

**Comment by lq95v5** [comment]
![112340guhf737x7do3jthu](https://user-images.githubusercontent.com/29811622/61609077-8ac15800-ac87-11e9-8c6b-2517c1207ec6.jpg)


锁屏bug，双屏下副屏幕仍然显示内容

用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=180961&page=1#pid607276


【严重】   @zccrs  @deepinzhangshuang

**Comment by lidanger** [comment]
热区似乎比以前强不少，触发率提高了。不过要在热区位置停一会而才行。

**Comment by lq95v5** [comment]
死机  https://feedback.deepin.org/feedback/detail/30841

**Comment by lq95v5** [comment]
近期的集中问题：

文件管理器删除/复制文件后，文件【显示】不会刷新，删除后的文件仍然【显示】。，

dock/任务栏，system tray 不确定性消失。

大黄蜂、nvidia 双显卡驱动问题

**Comment by jay763190097** [comment]
bug什么时候能够修复啊，等了一个多月了，都是准备大招了？系统稳定也很重要啊

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
