### ISSUE TITLE
编辑器：Arabic文本，每次打开需要重新设置UTF-8

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#1970]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180783&extra=page%3D1
I have to choose UTF8 again (even when it's already chosen), then F5 works.
Of course, I'll have to do that every time I open an Arabic file

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
