### ISSUE TITLE
若是空文件夹，双击后左侧项消失

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#198]
【测试环境】

【预置条件】

【测试步骤】
文件管理器打开一个空文件夹，双击名称后面的边线
【预期结果】
没有反应
【测试结果】
名称这一列消失了
【问题级别】

【出现概率】

@zccrs

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39469/

**Comment by liuwen123** [comment]
已修复
