### ISSUE TITLE
【需求】耳机 断开中断媒体播放

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#1988]

**Comment by lq95v5** [comment]
其实我在用户反馈那里也报过了，就是不知道deepin的官方大大们会不会很少去那里看hhh
因此我的建议有如下两条：
1、当我们在办公室们场所插耳机或连蓝牙耳机听音乐时，特别是带蓝牙耳机的时候，有时候人有急事走开了，蓝牙便断开连接。deepin如果加入“检测到声音输出源改变这一事件后自动暂停当前正在播放状态的多媒体”，我相信是很必要的吧，毕竟是会有这样的情况发生的，这样便避免了我们对“耳机断开连接会不会突然外放吓到人”这种担忧，从而能更从容地使用deepin~
2、关于dock栏，我也有些见解。虽然我们有时会需要点击一些托盘图标，我相信大多数人还是喜欢dock栏把SystemTray缩起来时的状态吧，比较和谐、美观，不突兀。所以我想说，deepin能不能考虑一下这样一个设定：用户展开SystemTray之后一段时间（比如30s）后自动缩起，这样就帮我们省了一步点击了，我相信这样的设定应该还是比较人性化的吧～
当然，如果能够进一步设定自动缩起的时间，那更好了：）
好了，我的建议目前就是这些，感谢deepin团队的辛勤付出，让deepin有了今天的模样和人气，感谢你们！I❤deepin.
@aida
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180988

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
