### ISSUE TITLE
flatpak deepin应用右上角三个图标与新版不一致

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#199]
flatpak deepin应用右上角三个图标与新版不一致

论坛ID
gnaymuyi

@zccrs @deepinzhangshuang 
没有说具体是哪个

**Comment by zccrs** [comment]
@Aichang2017 问他一下是哪个应用，啥版本

**Comment by zccrs** [comment]
@mmxzmmxz 是的，后面的是深度音乐吗， @deepinzhangshuang 更新一下吧

**Comment by deepinzhangshuang** [comment]
已经更新处理

**Comment by Aichang2017** [comment]
恩 用户回复  深度音乐和日历

**Comment by mmxzmmxz** [comment]
最新打包音乐右上角图标正常。
deepin-fpapp-org.deepin.flatdeb.deepin-music           3.1.9
