### ISSUE TITLE
时尚模式的托盘里的插件不能调节顺序 <周五>

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#2]
测试环境
dde-dock 4.7.3.3+r21+g6224d76
预置条件
任务栏切换为时尚模式
测试步骤
1.打开托盘，左右拖动托盘内的插件图标。
预期结果
1.托盘内的插件图标可以左右调整顺序。
测试结果
1.无法拖动调整插件的顺序。
问题级别
一般
复现概率
100%

**Comment by zhaofangfangdeepin** [comment]
makedown的语法格式不适合提交bug，真难看啊

**Comment by rekols** [comment]
markdown 多棒啊.

**Comment by zhaofangfangdeepin** [comment]
奥。markdown，拼音拼错了。。用来提交bug，不够棒

**Comment by iamhyc** [comment]
> makedown的语法格式不适合提交bug，真难看啊

试试3号title？（###）

**Comment by listenerri** [comment]
@wangjia12 时尚模式下需要拖拽吗？需要的话具体设计怎么做呢？

**Comment by wangjia12** [comment]
> @wangjia12 时尚模式下托盘内的图标需要支持拖拽吗？需要的话具体设计怎么做呢？

需要支持拖拽，但是拖拽拖进度的话可以后面更新发出去。

**Comment by listenerri** [comment]
@wangjia12 @shule1987 
目前在做始终可见(收起托盘后也可见)的托盘区域, 下面简称为: **保留区域**
需要确认三个设计:
1. 在收起时`保留区域`的位置, 在控制按钮哪边? 在活动图标哪边? (最好有设计图)
2. 在展开时`保留区域`的位置, 在控制按钮哪边? (最好有设计图)
3. 具体如何将一个图标拖拽到`保留区域`? (最好有动效图)

**Comment by wangjia12** [comment]
这个设计还需要再确认一下，放到15.8.2吧

**Comment by listenerri** [comment]
@zhaofangfangdeepin 
目前做了一部分, 先测一下吧, 打算这下周三把已经做完的这一部分发出去.
已经做完了托盘图标的排序和拖拽并且记住顺序
https://cr.deepin.io/c/dde/dde-dock/+/40136

**Comment by wangjia12** [comment]
需求背景：
之前实现的情况是时尚模式展开时内容很多很长，收起时一个也不显示。未满足在多个图标中想有一两个展示在收起状态时的外侧，所以增加将图标拖出来的功能。
需求说明：

1. 时尚模式托盘可以将托盘内应用移到托盘外（相对于收起状态时）；
2. 抓起托盘内图标时，细线产生呼吸效果（参见视频）；
3. 未移到竖线区域时，正常调节图标顺序；（已实现）；
4. 移到竖线区域时（超过50%或其他，具体数据可以实现时跟设计师调节），竖线左移让出位置；
5. 移到竖线右边放下图标后，图标移动到当前位置。收起状态时，在三角图标的右侧展示；

**Comment by liuwen123** [comment]
已修复

**Comment by listenerri** [comment]
@shule1987 

> [托盘动效.mp4.zip](https://github.com/linuxdeepin/internal-discussion/files/2627484/mp4.zip)

这个动效里新增的那个分隔条的透明度变化范围是多少？

**Comment by shule1987** [comment]
10% 到30%

**Comment by listenerri** [comment]
@liuwen123 

https://cr.deepin.io/c/dde/dde-dock/+/40998

**Comment by liuwen123** [comment]
- [ ] 所有图标全部拖出来后，无法拖回进去

**Comment by listenerri** [comment]
@liuwen123 

https://cr.deepin.io/c/dde/dde-dock/+/41007

**Comment by liuwen123** [comment]
已修复
