### ISSUE TITLE
托盘右键菜单会跑到最左侧

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#20]
【测试环境】
dde-dock：4.7.4+r0+g2d273cd

【预置条件】
高效模式

【测试步骤】
在高效模式下，右键点击右下角的系统托盘图标，查看右键菜单显示

【预期结果】
右键菜单在当前图标上

【测试结果】
右键菜单会跑到桌面最左侧位置

【问题级别】
一般

【出现概率】
100%

![_ _20181029100405](https://user-images.githubusercontent.com/12492745/47625789-4b376680-db62-11e8-8c12-e0056eaffb39.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39276
