### ISSUE TITLE
gtk应用按钮图标模糊

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#200]
论坛ID
iamhyc65

[deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547119/deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz)

**Comment by wangjia12** [comment]
@shule1987 @zccrs

**Comment by zccrs** [comment]
@wangjia12 他有没有说哪些应用的呀

**Comment by wangjia12** [comment]
> @wangjia12 他有没有说哪些应用的呀

没有说  可以让 @Aichang2017 问

**Comment by wangjia12** [comment]
@Aichang2017 问一下

**Comment by shule1987** [comment]
我猜的话应该是标题栏按钮图标， 这个 已经修复了

**Comment by zccrs** [comment]
那关了哦
