### ISSUE TITLE
启动菜单的反馈

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#201]
Grub背景太丑，字体太丑；没有滚动条，看不出来到底有几个entry

论坛ID
iamhyc65

[deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547121/deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz)

**Comment by shule1987** [comment]
等我先把背景壁纸找到
