### ISSUE TITLE
时尚模式图盘区域的反馈

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#202]
* 时尚模式托盘整个可以拖动，有这个必要吗？

* 时尚模式托盘折叠时，应该可以拖拽显示/隐藏托盘图标，就像高效模式一样

* 时尚模式托盘信息弹出位置有问题，在右下角而不是托盘区域（使用微信测试）

论坛ID
iamhyc65

[deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547134/deepin-feedback-cli-Deepin-15.8-all-20181102-174153.tar.gz)

@shule1987 第一个你是什么意见，我是觉得可以换位置就可以换，不用特意去掉
@zccrs 第二个 第三个我测试没明白是什么问题

**Comment by zccrs** [comment]
第二个我也没明白，第三个应该是bug

**Comment by listenerri** [comment]
第二个应该是期望像高效模式下一样有一个单独的托盘区域可以隐藏不想看到的图标如下图：
![default](https://user-images.githubusercontent.com/7995379/47998772-69d9c680-e13b-11e8-92d3-8b05e45092b6.png)

第三个估计是在说微信，qq这些wine程序的消息弹窗是像windows一样出现在右下角，而不是托盘图标所在的位置，这个问题应该是wine程序那边控制的
