### ISSUE TITLE
安装字体后会改变深度音乐字体显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#203]
【测试环境】
deepin-music：3.1.8.4-1

【测试步骤】
先打开深度音乐并导入音乐，查看界面显示
在系统中安装任意字体，重启深度音乐，查看界面显示

【预期结果】
界面显示正常

【测试结果】
安装字体后，重启深度音乐，会导致深度音乐字体改变

【出现概率】
100%
![_deepin-music_20181105142130](https://user-images.githubusercontent.com/12492745/47981271-2dd83e80-e106-11e8-8d3b-20858f00f3bd.png)
![_deepin-music_20181105142151](https://user-images.githubusercontent.com/12492745/47981272-2e70d500-e106-11e8-88da-5d0d65035faa.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
