### ISSUE TITLE
蓝牙和无线网络问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#204]
问题一：蓝牙启动失败；

问题二：无线网开关打开搜不到无线信号

论坛ID
care

[deepin-feedback-all-20181102-181111.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547141/deepin-feedback-all-20181102-181111.tar.gz)

**Comment by electricface** [comment]
# Wireless Device Switches(rfkill)

    0: phy0: Wireless LAN
    	Soft blocked: no
    	Hard blocked: yes

发现是 rfkill 硬件 blocked 了

**Comment by wangjia12** [comment]
> 执行 rfkill 命令的输出是什么？

问谁啊

**Comment by electricface** [comment]
我让 care 用github.com 回复，之前用手机短信。
