### ISSUE TITLE
深度看图按Delete键无法删除图片

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#206]
【预置条件】
deepin-image-viewer：1.3.0-2

【测试步骤】
使用深度看图打开任意图片，然后按delete键删除图片

【预期结果】
图片可以正常删除

【测试结果】
按Delete键无效

【出现概率】
100%

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/39458/ 
@liuwen123 删掉配置文件后测试

**Comment by liuwen123** [comment]
已修复
