### ISSUE TITLE
时尚模式，托盘展开按钮-右键，建议打开任务栏的右键菜单

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#207]
【测试环境】
dde-dock:
  已安装：4.7.5.1-1
【预置条件】
1.任务栏为时尚模式
【测试步骤】
1.在任务栏-向右展开托盘的图标上右键。查看响应。
【预期结果】
1.能够打开任务栏的右键菜单。
【测试结果】
1，没有任何响应。
【问题级别】
建议
【出现概率】
稳定浮现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39470

**Comment by zhaofangfangdeepin** [comment]
@listenerri 这个提交不行。

**Comment by listenerri** [comment]
还没有打tag，回归测试吧

**Comment by listenerri** [comment]
@zhaofangfangdeepin 再试一下，留意下其他图标的鼠标点击事件

**Comment by zhaofangfangdeepin** [comment]
V+1 @listenerri

**Comment by zhaofangfangdeepin** [comment]
测试通过
