### ISSUE TITLE
深度影院焦点问题

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#2075]

**Comment by lq95v5** [comment]
用户反馈：
https://bbs.deepin.org/forum.php?mod=viewthread&tid=181044


待测试

**Comment by bobwxc** [comment]
15.11 同样出现此焦点自动夺取问题，所有软件已经最新

**Comment by BLumia** [comment]
v20 后 issue 处理流程变化，不再通过 internal-discussion 跟进和处理 issue。遗留的 v15 问题不再处理（在 v20 中很可能已不再存在）。若您有类似问题/获取更新后仍有问题，请移步 developer-center 仓库进行汇报。感谢支持！
