### ISSUE TITLE
i+n显卡prime方案下，录屏不能使用

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#209]

**Comment by mmxzmmxz** [comment]
【测试环境】：
ii  deepin-fprt-org.deepin.flatdeb.base.p 1.0.7                   amd64 
ii  deepin-fpapp-org.deepin.flatdeb.deepi 3.1.8.4                 amd64
ii  nvidia-driver                         390.67-3deepin          amd64

01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 860M] (rev a2)
【测试步骤】：
1.i+n显卡环境，切换显卡驱动为prime方案，使用录屏，录制界面为黑色。

**Comment by mmxzmmxz** [comment]
![img_0104](https://user-images.githubusercontent.com/12388744/47988781-1c9b2c00-e11e-11e8-9c69-ba1fe9c6521a.JPG)

**Comment by zccrs** [comment]
@mmxzmmxz 上面那两个flatpak包名是啥呀，没有贴全

**Comment by mmxzmmxz** [comment]
> @mmxzmmxz 上面那两个flatpak包名是啥呀，没有贴全

不好意思哈。
deepin-installer 2.4.4-1
deepin-fprt-org.deepin.flatdeb.base.platform-15.8       1.0.7                   amd64 
deepin-fpapp-org.deepin.flatdeb.deepin-music            3.1.8.4                 amd64
deepin-fpapp-org.deepin.flatdeb.deepin-screen-recorder  2.7.5+r1
deepin-fpapp-org.deepin.flatdeb.deepin-screenshot       4.1.1+r1
nvidia-driver                                           390.67-3deepin          amd64

**Comment by mmxzmmxz** [comment]
验证通过
deepin-fprt-org.deepin.flatdeb.base.platform-15.8:
  已安装：1.0.9
deepin-fpapp-org.deepin.flatdeb.deepin-screen-recorder:
  已安装：2.7.5+r1
