### ISSUE TITLE
计算机图标在dock上显示和启动器中图标显示不一致

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#21]
【测试环境】
dde-dock: 4.7.4+r0+g2d273cd

【预置条件】
高效模式

【测试步骤】
在启动器中将计算机图标添加到dock上，查看dock图标显示

【预期结果】
dock上计算机图标和启动器中图标保持一致

【测试结果】
显示不一致

【问题级别】
一般

【出现概率】
100% 

![_ _20181029101831](https://user-images.githubusercontent.com/12492745/47626114-74f18d00-db64-11e8-8224-daaa476bcd5c.png)
![_ _20181029102409](https://user-images.githubusercontent.com/12492745/47626183-cc8ff880-db64-11e8-956a-e9802824fdf3.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-dock/+/39307/ 16x16的图标不适合使用

**Comment by liuwen123** [comment]
已修复
