### ISSUE TITLE
launcher中不应该显示帮助手册

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#210]
【测试环境】
15.8 ISO  
【预置条件】
无
【测试步骤】
1.新装ISO，检查launcher中应用显示
【预期结果】
不会显示帮助手册
【测试结果】
显示帮助手册
【问题级别】
一般
【出现概率】
稳定

**Comment by hualet** [comment]
要显示啊，为啥不显示？

**Comment by yefeifei** [comment]
> 要显示啊，为啥不显示？

@wangjia12  说不要显示帮助手册的图标啊

**Comment by wangjia12** [comment]
> > 要显示啊，为啥不显示？
> 
> @wangjia12 说不要显示帮助手册的图标啊

不好意思，你昨天问我的是个双重否定啊。。我没看清楚  是要在启动器的  我以为你问我是不是要在启动器显示
