### ISSUE TITLE
深度商店的窗口无法最大化和调整大小

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#211]
【测试环境】
deepin-appstore:
  已安装：5.1.0.1-1
【预置条件】

【测试步骤】
1.打开深度商店窗口之后，调整窗口的大小或者最大化。
【预期结果】
1.能够调整窗口大小和最大化。
【测试结果】
1.无法调节大小和最大化。
【问题级别】
一般
【出现概率】
低概率

**Comment by liuwen123** [comment]
已修复
