### ISSUE TITLE
应用商店不能登录

### ISSUE THREAD

**Issue by Fozei** [linuxdeepin/internal-discussion#2119]
【测试环境】
15.10.1/15.11
【预置条件】
应用商店能正常联网,下载应用;我的网络环境是通过代理服务器,链接外网,APT配置文件做了代理设置.
【测试步骤】
点击首页面右上角登录图标,在弹出的页面,输入正确的账号密码,点击登录,显示加载中,稍后弹窗消失;再次点击首页登录按钮,再次弹出输入账号密码弹窗.
刚刚升级到了15.11,设置里的云同步登录也是这样,登录成功后,依然是未登录的状态.
【预期结果】
登录成功,保存登录状态,并且能对应用进行评论操作
【测试结果】

【问题级别】
高
【出现概率】
必现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
