### ISSUE TITLE
恢复官方仓库之后，打开深度商店之后，热门推荐为空白，导致用户无法通过深度商店下载和安装新软件。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#212]
【测试环境】
deepin-appstore:
  已安装：5.1.0.1-1
lastore-daemon:
  已安装：0.11.0-1
【预置条件】

【测试步骤】
1.修改/etc/apt/sources.list的仓库之后，重启系统。
2.重启之后，弹出修改到官方仓库之后，点击恢复。
3.恢复仓库之后，打开深度商店，下载并安装软件。
【预期结果】
1.深度商店下载安装正常。
【测试结果】
1.深度商店无法下载安装软件。
【问题级别】
严重
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181105154304](https://user-images.githubusercontent.com/14539782/47984663-3b93c100-e112-11e8-941c-187ed1996a1b.png)

**Comment by myml** [comment]
我觉得这个应该是提示恢复官方仓库的程序来做update
@Iceyer

**Comment by Iceyer** [comment]
@zccrs 恢复sources.list后有执行apt update 吗？

**Comment by zccrs** [comment]
@justforlxz @electricface

**Comment by electricface** [comment]
恢复sources.list 后没有执行apt update

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/39702

**Comment by hualet** [comment]
@electricface 这个有合并到 ISO 里面么？

**Comment by electricface** [comment]
还没有

**Comment by liuwen123** [comment]
已修复
