### ISSUE TITLE
计算器功能太过简单,建议恢复老版本具有高级功能(程序员模式)的计算器

### ISSUE THREAD

**Issue by Fozei** [linuxdeepin/internal-discussion#2120]
15.10.1的计算器太简单了,原来那个有高级功能的计算器多好,有程序员模式,有二级制显示,多么好的功能,怎么被砍掉了呢?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
