### ISSUE TITLE
15.11个别应用不能最小化窗口

### ISSUE THREAD

**Issue by Fozei** [linuxdeepin/internal-discussion#2125]
【测试环境】
15.11桌面版,15.10.1升级过来的;
【预置条件】
通过APT安装DB Browser for SQLite:
sudo apt-get install sqlitebrowser
【测试步骤】
运行 DB Browser For Sqlite,点击窗口最小化按钮.
【预期结果】
窗口能正常被最小化.
【测试结果】
窗口最小化后,又恢复到之前状态.
【问题级别】
高
【出现概率】
必现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
