### ISSUE TITLE
深度终端-设置-第一次打开字体的时候，字体列表会显示之后立马隐藏

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#213]
【测试环境】
deepin-terminal:
  已安装：3.0.9-1
【预置条件】

【测试步骤】
1.打开深度商店-设置-字体设置。查看字体列表显示
【预期结果】
1.直接打开字体列表，显示正正常
【测试结果】
1.打开字体列表之后，立马隐藏。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181105155235](https://user-images.githubusercontent.com/14539782/47985132-ae516c00-e113-11e8-8071-bf60579e626a.gif)

**Comment by hualet** [comment]
应该是上游GTK控件的bug，基本上不影响正常使用。 不处理。
