### ISSUE TITLE
选全盘加密安装后，磁盘容量显示异常

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#214]
![deepin15 8-2018-11-05-07-50-59](https://user-images.githubusercontent.com/24972525/47985120-a691c780-e113-11e8-9e1b-87b65a700491.png)
左边是Gparted，右边是文件管理器。
环境虚拟机，分配20g磁盘。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dtkcore/+/39585/

**Comment by liuwen123** [comment]
文件管理器磁盘属性显示正常，控制中心--系统信息显示--磁盘显示，依然显示错误

**Comment by BLumia** [comment]
控制中心是另一回事，目前还不是从 dtkcore 拿的数据，区分到另一个 issue #255

**Comment by liuwen123** [comment]
已修复
