### ISSUE TITLE
控制中心侧边栏图标和当前内容显示没有保持一致

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#215]
【测试环境】
dde-control-center：4.7.3-2

【测试步骤】
打开控制中心点击侧边栏图标“声音”，然后使用鼠标中键滚动到顶部，查看侧边栏图标和当前内容显示

【预期结果】
侧边栏图标和内容显示保持一致

【测试结果】
侧边栏图标和内容没有显示保持一致

【出现概率】
100%

![_ _20181105155612](https://user-images.githubusercontent.com/12492745/47985389-6da62280-e114-11e8-8d10-37c6ca34a39a.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
