### ISSUE TITLE
TIM在任务栏上左右键菜单失灵

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#216]
TIM在来一次新消息后后左键右键点击均没有效果，高效模式同样问题（这好像不是托盘的问题，而是wine的问题……

论坛ID
coldwind

[deepin-feedback-all-20181102-190826.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547370/deepin-feedback-all-20181102-190826.tar.gz)

**Comment by wangjia12** [comment]
tim右键菜单打开后如果不做选择无法关闭
论坛ID
always-one

E-mail
always_one@qq.com

QQ
1413117598

[deepin-feedback-cli-Deepin-15.8-all-20181103-000038.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547561/deepin-feedback-cli-Deepin-15.8-all-20181103-000038.tar.gz)

**Comment by zccrs** [comment]
@listenerri 关于wine程序的问题，主要是测试非时尚模式下的托盘有没有同样的问题，且优先级稍低

**Comment by zccrs** [comment]
@Aichang2017 @wangjia12 问一下用户关闭topbar还有没有问题
