### ISSUE TITLE
Shadowsocks-Qt5 的开机启动会失效

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#217]
从15.7更新上来，Shadowsocks-Qt5 的开机启动会失效，且需通过更改软件内的设置才能取消开始启动

[deepin-feedback-all-20181102-190826.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547397/deepin-feedback-all-20181102-190826.tar.gz)

论坛ID
coldwind

@zccrs

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/39491/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-launcher/+/39491/

+1

**Comment by liuwen123** [comment]
已修复
