### ISSUE TITLE
在文件管理器-最近使用目录下调整是否显示最近使用

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#219]
如果文件管理器显示的是“最近使用”界面，此时取消“显示最近使用文件”，左侧导航“最近使用”会随之生效，但是文件管理器显示的仍然是“最近使用”的界面。建议设置为跳回主目录。

论坛ID
syqiven

如果在最近使用的目录下进行调整，不显示最近使用界面，自动调到主目录，如果再继续选择显示最近使用，不用特意跳回去，还是在主目录。

**Comment by zccrs** [comment]
设置项是实时生效的，根据用户的选择，当设置为不显示后就已经自动跳转到了主目录，所以不存在：“如果再继续选择显示最近使用，不用特意跳回去，还是在主目录。”

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39481/
将会在隐藏最近文件入口时跳转到 home 目录

**Comment by liuwen123** [comment]
已修复
