### ISSUE TITLE
时尚模式托盘区域点击消息提示出错

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#220]
打开微信后，关闭微信主界面（不退出）。此时如果来了新信息，双击托盘处闪动的微信图标，没有反应。
 QQ、微信均无法左键弹出程序，也无法右键显示菜单
收起托盘，单击闪动的微信图标，微信图标会突然消失又出现。

论坛ID
syqiven

[deepin-feedback-cli-Deepin-15.8-all-20181102-115034 (1).tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547415/deepin-feedback-cli-Deepin-15.8-all-20181102-115034.1.tar.gz)

**Comment by felixonmars** [comment]
是否可能和 https://github.com/linuxdeepin/dde-dock/issues/120 说的是一个问题？

**Comment by listenerri** [comment]
第一个点击问题与 #216 重复
第二个活动图标处理问题与 #196 重复

这个就关闭了，问题在其他issue里处理
