### ISSUE TITLE
深度商店和文件管理器版本显示错误问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#223]
深度商店和文件管理器版本显示错误问题，虽然升级成功，功能也有，但在‘关于’显示的版本号还是旧版本号。

论坛ID
mohuan

E-mail
461771675@qq.com

QQ
461771675

现在这两个项目版本号 是自动的么

**Comment by zccrs** [comment]
版本号是跟随tag号的，没问题
