### ISSUE TITLE
LZ4 Compression 支持

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#2247]
Boot Faster Thanks To LZ4 Compression-深度科技论坛|深度操作系统正在为全世界的电脑提供强劲动力！ - https://bbs.deepin.org/forum.php?mod=viewthread&tid=182561&page=1#pid619138

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
