### ISSUE TITLE
透明度调整之后启动器没有变化

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#225]
论坛ID
mohuan

E-mail
461771675@qq.com

QQ
461771675
[deepin-feedback-cli-Deepin-15.8-all-20181102-213202.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547449/deepin-feedback-cli-Deepin-15.8-all-20181102-213202.tar.gz)

**Comment by wangjia12** [comment]
论坛ID
jinshuichengliu

E-mail
jinshuichengliu@163.com

QQ
382179584

[deepin-feedback-cli-Deepin-15.8-all-20181102-213202 (1).tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547450/deepin-feedback-cli-Deepin-15.8-all-20181102-213202.1.tar.gz)

**Comment by wangjia12** [comment]
两个人都是启动器没有变化

**Comment by justforlxz** [comment]
只有dock和控制中心支持透明度调节。

**Comment by hualet** [comment]
暂不支持

**Comment by wangjia12** [comment]
> 暂不支持

晕 我怎么记得支持  我还在问卷写了 难怪人家反馈这个问题

**Comment by hualet** [comment]
> > 暂不支持
> 
> 晕 我怎么记得支持 我还在问卷写了 难怪人家反馈这个问题

姐姐 上班的时候清醒点……

**Comment by wangjia12** [comment]
> > > 暂不支持
> > 
> > 
> > 晕 我怎么记得支持 我还在问卷写了 难怪人家反馈这个问题
> 
> 姐姐 上班的时候清醒点……

小的就是支持的啊

**Comment by wangjia12** [comment]
@Aichang2017 你回复一下上面两个人，说大launcher不支持，小的支持。

**Comment by Aichang2017** [comment]
好
