### ISSUE TITLE
deepin 系统通知消息泄露个人隐私-深度科技论坛|深度操作系统正在为全世界的电脑提供强劲动力！ - https://bbs.deepin.org/forum.php?mod=viewthread&tid=182337&extra=

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#2269]
deepin 系统通知消息泄露个人隐私-深度科技论坛|深度操作系统正在为全世界的电脑提供强劲动力！ - https://bbs.deepin.org/forum.php?mod=viewthread&tid=182337&extra=

期望行为：修改通知的显示存留时间或者显示内容

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
