### ISSUE TITLE
任务栏时尚模式托盘的几个问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#228]
qbittorrent的dock图标是黑色的，在切换后，看不到了。两种模式都是
dock里的tg，右键好使，左键不起作用了，无法弹起程序。
收放都好使。但是QQ聊天窗口似乎很特殊，即使QQ联通窗口在下层，再点小方块后还是会弹到顶层。

论坛ID
jinshuichengliu

[deepin-feedback-cli-Deepin-15.8-all-20181102-213202 (2).tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547482/deepin-feedback-cli-Deepin-15.8-all-20181102-213202.2.tar.gz)

**Comment by felixonmars** [comment]
和 #220、 linuxdeepin/dde-dock#120 可能是一个问题

**Comment by listenerri** [comment]
第一个图标黑色已经处理了
第二个telegram无法相应鼠标左键是因为托盘SNI协议的问题，不过在kde下没有这个问题
第三个描述不清

这个issue关掉了，都是已知和重复问题
