### ISSUE TITLE
系统信息显示问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#229]
系统信息deepin下边第二行单独显示公司两个字，建议要么提到第一行完整显示，要么将公司名称在第二行完整显示

@shule1987 看看这个问题  只有中文适用，别的语言就不用管了。

**Comment by zccrs** [comment]
这个怎么看单行都是能显示完全的呀

**Comment by zccrs** [comment]
@wangjia12 问一下 @shule1987

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39548/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-control-center/+/39548/

+1

**Comment by yefeifei** [comment]
回归测试通过
