### ISSUE TITLE
深度商店经常显示网络错误无法连接

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#230]
【测试环境】
deepin-appstore：5.1.0.1-1

【测试步骤】
打开深度商店，查看软件显示

【预期结果】
商店可以正常显示

【测试结果】
商店经常显示网络错误

【出现概率】
100%
![_deepin-appstore_20181105164443](https://user-images.githubusercontent.com/12492745/47987476-8f0a0d00-e11a-11e8-98bc-dc6a34810d3d.png)

**Comment by hualet** [comment]
@Iceyer @myml 看看？

**Comment by myml** [comment]
这个已做优化https://cr.deepin.io/#/c/dstore/deepin-appstore/+/39384/

**Comment by liuwen123** [comment]
暂没有出现网络错误
