### ISSUE TITLE
i+n显卡prime方案下，深度音乐/深度录音/计算器/深度日历在dock插件显示空白，且右上角菜单选取不正常

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#231]
【测试环境】：
ii  deepin-fprt-org.deepin.flatdeb.base.p 1.0.7                   amd64 
ii  deepin-fpapp-org.deepin.flatdeb.deepi 3.1.8.4                 amd64
ii  nvidia-driver                         390.67-3deepin          amd64

01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 860M] (rev a2)
【测试步骤】：
1.i+n显卡环境，切换显卡驱动为prime方案，打开深度音乐，查看插件显示，显示空白；
2.点击右上角菜单，轮循hover显示菜单，选中异常。

**Comment by mmxzmmxz** [comment]
![_ _20181105152624](https://user-images.githubusercontent.com/12388744/47987803-72baa000-e11b-11e8-9eaa-da381902196f.png)
![_ _20181105152647](https://user-images.githubusercontent.com/12388744/47987805-73ebcd00-e11b-11e8-89a5-5442c2b64c41.png)

**Comment by deepinzhangshuang** [comment]
已经处理

**Comment by mmxzmmxz** [comment]
验证通过
deepin-fprt-org.deepin.flatdeb.base.platform-15.8:
  已安装：1.0.9
deepin-fpapp-org.deepin.flatdeb.deepin-music:
  已安装：3.1.8.4
