### ISSUE TITLE
我来提几点建议-深度科技论坛|深度操作系统正在为全世界的电脑提供强劲动力！ - https://bbs.deepin.org/forum.php?mod=viewthread&tid=183111&extra=

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#2311]
【新提醒】刚刚入坑，我来提几点建议-深度科技论坛|深度操作系统正在为全世界的电脑提供强劲动力！ - https://bbs.deepin.org/forum.php?mod=viewthread&tid=183111&extra=

**Comment by lq95v5** [comment]
1. 性能监视器不够智能，打开后把它调到后台，再次从启动器打开的时候如果能把窗口调到前台来就好了。我设置了快捷键启动性能监视器，结果按快捷键不能调到前台，每次都要按Alt+Tab切换，感觉很不方便。

2. 锁定电脑后屏幕关闭时间不合理，win 下锁定之后 1 分钟就关闭屏幕了，希望deepin也可以改成这样。

3. 把自带的快捷键改成别的之后，默认的那个快捷键好像也不能用了，比如 Ctrl+Alt+S，在我的 idea 里就失效了，希望改进。

4. 启动器和Ctrl+Alt+Delete出现的界面，每次都保留上次操作的状态，个人感觉这个设计不好，我更喜欢每次打开都是初始状态，比如启动器默认选中第一个应用，Ctrl+Alt+Delete默认且每次都选中第一个，这样如果想选择其他的选项也很方便，按方向键调整就好了。

5. 各种对话框比较难看，同时对话框的按钮默认选中了哪个，也没有明确的显示出来，用户很难知道当前选中的是哪个选项，对于键盘党来说，这很不方便。

6. 对话框里选中的按钮，希望可以按Tab键切换，文件管理器初始页面为计算机的时候，希望可以键盘操作，像win一样，比如上下左右键可以选中里面的项目。

7. 希望任务栏里的图标可以设置是否显示，个人不喜欢磁盘和电源图标显示在任务栏。

8. 希望能提供开机自启动项和系统服务的查看和管理功能，开机启动项现在在启动器里有显示，但是如果启动器里的软件太多，这样就不太方便了。

9. 商店里的软件版本太旧了，比如tg，还有gcc等（不要问要那么新的版本干什么，自然是有用），希望能提供更新的版本。

10. 感觉系统对用户操作的响应速度不够快，这个不是电脑配置不好，也不是电脑负载过重，个人感觉是cpu调度优先级没处理好，希望能优化一下。

11. 系统里快捷键的操作速度不能太快，太快了后面的快捷键就没反应，在win下操作速度再快都没问题，希望这个也能优化一下。

12. 希望在各种右键菜单里能加上快捷键，就像这样：新建(N)，按Alt+N就可以执行对应的操作了，不然就只能用鼠标或者上下左右键移动了，感觉不方便。

13. 任务栏的应用显示方式，希望能像win一样显示宽一点的方式，不然一个程序打开了多个窗口，切换很不方便。

14. Alt+Tab希望不要预览显示，感觉真的没必要，当一个窗口最小化之后，切换到其他的窗口，然后按Alt+Tab再选中刚刚被最小化的窗口时，预览界面显示出来了，这时候松开快捷键，预览窗口没了，界面又从最小化恢复到原来的大小，这个效果真的不怎么好。

15. 还是Alt+Tab，希望不要分行显示，跟win一样，在一行显示就好，这个不是我习惯了win，而是win的这种设计的确更好，切换任务的时候如果是一行，眼睛只需要从左扫到右就找到想切换的应用了，现在是两行，感觉不如一行好。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
