### ISSUE TITLE
连续多次单击“启动器”，有单击一次动作两次的情况

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#232]
1.连续多次单击“启动器”，有单击一次ui动作两次的情况，简单讲就是单击一次开始菜单闪烁，并没有关闭，（半屏开始菜单样式）。
@zhaofangfangdeepin 这个可以验证一下

论坛ID
valerian

**Comment by felixonmars** [comment]
和 #173 说的应该是一件事。
