### ISSUE TITLE
惠普星14s青春锐龙版，安装后Deepin出现的问题

### ISSUE THREAD

**Issue by zkqgxlbjx** [linuxdeepin/internal-discussion#2323]
【测试环境】
 系统：Deepin 15.11 stable
 APU: AMD Ryzen 7 3700U
 系统：Ubuntu kylin 19.04
 APU: AMD Ryzen 7 3700U
【测试结果】
在Deepin下，软件窗口切换状态卡顿，游戏运行非常卡顿从而导致APU温度升高，系统屏幕分辨率只有1024×768，主要是卡顿已经影响到办公了。
在Ubuntu kylin下，不存在窗口切换卡顿和游戏运行卡顿，系统屏幕分辨率有多种选择。
共同的问题没有对应的WiFi驱动。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
