### ISSUE TITLE
全盘安装-全盘加密安装系统失败

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#235]
全盘安装-全盘加密安装系统失败，已根据弹出的二维码链接提交反馈。
论坛ID
dlitchi

[deepin-feedback-cli-Deepin-15.8-all-20181102-232244.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547543/deepin-feedback-cli-Deepin-15.8-all-20181102-232244.tar.gz)

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/236 是同一个问题吧
