### ISSUE TITLE
文件管理器加入对鼠标返回前进键的支持

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#237]
是不是说某些特别的鼠标？ 
@zccrs

**Comment by hualet** [comment]
@21wmd 那个鼠标就有前进后退键，以前好像让 @justforlxz 修过的

**Comment by hualet** [comment]
以前改的是控制中心，文件管理器没有改。

**Comment by justforlxz** [comment]
@BLumia  在mouseReleaseEvent里判断button是不是Qt::BackButton就可以了

**Comment by zccrs** [comment]
@wangjia12 这个已经支持了，估计是用户的鼠标有问题

**Comment by BLumia** [comment]
这个是已经支持过的且测试正常的，代码参见 [dfileview.cpp#L1041](https://github.com/linuxdeepin/dde-file-manager/blob/4.6.10/dde-file-manager-lib/views/dfileview.cpp#L1041) 。可能是用户的鼠标按键映射不对导致的。
