### ISSUE TITLE
文件管理器管理员模式问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#238]
在文件管理器中右键进入管理员模式，然后在打开的管理员界面里面，一，应该去掉右键菜单里面的管理员打开选项，二，右键菜单在这里打开终端，无法输入中文（搜狗输入法不起作用）

论坛ID
always-one

**Comment by hualet** [comment]
要从根本上解决这个问题，需要前后端操作分离，管理员打开的话有一个特权后端才行。
