### ISSUE TITLE
点击dock的launcher图标，显示后，再次点击图标，launcher不隐藏

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#24]
【测试环境】
dde-dock:4.7.4-2
【预置条件】
无
【测试步骤】
1.点击dock上launcher图标，
2.待launcher显示后，再次点击launcher图标
【预期结果】
launcher窗口消失
【测试结果】
launcher窗口还显示
【问题级别】
一般
【出现概率】
稳定重现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/39297/ 需要更新dtkwidget

**Comment by felixonmars** [comment]
dtkwidget 已经是 2.0.9.5 了，还需要新 tag 吗？
