### ISSUE TITLE
时尚模式下，托盘收起时，左键单击输入法图标中英切换时闪抖明显

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#240]
论坛ID
toni

E-mail
tonise@qq.com

QQ
1075210919
[deepin-feedback-cli-Deepin-15.8-all-20181102-195437.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2547632/deepin-feedback-cli-Deepin-15.8-all-20181102-195437.tar.gz)

**Comment by listenerri** [comment]
同 #196
