### ISSUE TITLE
深度截屏 - 无法保存至指定目录

### ISSUE THREAD

**Issue by YannisZhao** [linuxdeepin/internal-discussion#2402]
【测试环境】
机器：联想小新bigger，系统：deepin v15.11
【预置条件】
截屏
【测试步骤】
截屏 -> 保存至指定目录(/develop/doc，有目录权限)
【预期结果】
保存成功
【测试结果】
实际未保存成功
只有保存到桌面时会成功
【问题级别】
中等
【出现概率】
必现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
