### ISSUE TITLE
sHover 字符不消失

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#241]
![p1haw9 _h xvt99 3m2 30](https://user-images.githubusercontent.com/24972525/47989075-e7dba480-e11e-11e8-8d2c-9b5aad276e62.gif)

如图

**Comment by felixonmars** [comment]
可以重现。

**Comment by justforlxz** [comment]
这次推送的更新有修这个。

**Comment by liuwen123** [comment]
已修复
