### ISSUE TITLE
failsafe方案不能使用

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#242]
【测试环境】：
1102ISO
【测试步骤】：
1.深度boot-make制作启动盘工具，选中failsafe不能进入live环境。

**Comment by zccrs** [comment]
这个的问题就不用提了，如果第一个启动项能进安装界面，第二个能不能进都不是问题

**Comment by mmxzmmxz** [comment]
问了张爽的，他会在grub界面去掉nolapci参数的，后期会更新～
第二个不能进入，说明失去了failsafe设置的意义
