### ISSUE TITLE
ISO：无法检测到指纹设备

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#244]
【测试环境】
15.8 ISO
【预置条件】
无
【测试步骤】
1.连接指纹设置，检查控制中心账户，是否显示指纹设置
【预期结果】
显示指纹设置
【测试结果】
没有指纹设置
【问题级别】
严重
【出现概率】
稳定

**Comment by justforlxz** [comment]
因为省电模式，关了就好了。   @hualet  @zccrs

**Comment by yefeifei** [comment]
设备问题，ISO测试又可以检测到。
