### ISSUE TITLE
如果无线网卡被禁用之后，建议和有线网络的插件保持一直，也不要在任务栏上显示出来。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#245]
【测试环境】
dde-dock:
  已安装：4.7.5.1-1
【预置条件】

【测试步骤】
1.打开控制中心，关闭无线网络的开关。
2.查看任务栏上无线网络的图标显示。
【预期结果】
1.无线网络的图标不会显示在任务栏上。
【测试结果】
1.无线网络的图标会显示在任务栏上。
【问题级别】
建议
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181105191635](https://user-images.githubusercontent.com/14539782/47995285-bf0fdb00-e12f-11e8-91cd-0c5891216f8f.png)

**Comment by justforlxz** [comment]
关闭无线网络并不会禁用设备，dock上确实不会消失。

**Comment by zccrs** [comment]
这里的关闭仅仅是关闭链接吧，在dock的无线插件上还有开关再重新打开它的

**Comment by zhaofangfangdeepin** [comment]
有线网络关闭之后，任务栏上就会消失。建议可以保持一致
