### ISSUE TITLE
在笔记本上，电源和关机的插件上右键，都有电源设置。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#246]
【测试环境】
dde-dock:
  已安装：4.7.5.1-1
【预置条件】
笔记本电脑
【测试步骤】
1，在笔记本上安装Deepin15.8 
2.在任务栏-关机插件上右键。查看右键菜单
3.在关机插件上右键，查看右键设置。
【预期结果】

【测试结果】
1.这俩菜单都有电源设置。建议可以优化下。
建议
【出现概率】
1.稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![Uploading 深度截图_选择区域_20181105192912.png…]()
![Uploading 深度截图_选择区域_20181105192930.png…]()

**Comment by zccrs** [comment]
@wangjia12

**Comment by wangjia12** [comment]
两种模式都只在电池右键里显示电源设置
关机按钮不显示电源设置
之前是公用一个所以都显示了，显示拆开了就各显示各的。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
