### ISSUE TITLE
文件管理器-分区上右键-属性，属性框里面展示的文件个数显示错误

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#248]
【测试环境】
dde-file-manager:
  已安装：4.6.10-1
【预置条件】

【测试步骤】
1.打开文件管理器，分区上右键-属性。查看文件个数的显示。
【预期结果】
1.文件个数显示正确。
【测试结果】
1.文件个数显示错误。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zccrs** [comment]
@zhaofangfangdeepin 你后面的背景给的是下载目录的呀

**Comment by zccrs** [comment]
@zhaofangfangdeepin 这个数量是包含隐藏文件的，没问题

**Comment by zhaofangfangdeepin** [comment]
![_ _20181106134540](https://user-images.githubusercontent.com/14539782/48045209-4e69cc80-e1ca-11e8-8658-77a44efb2548.png)

**Comment by zhaofangfangdeepin** [comment]
测试通过
