### ISSUE TITLE
出现了一次壁纸设置-设置壁纸，壁纸预览为灰的现象

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#249]
【测试环境】
dde-desktop:
  已安装：4.6.10-1
【预置条件】

【测试步骤】
1.桌面右键-设置壁纸。随机点击系统的壁纸，设置壁纸。
【预期结果】
1.设置正常。
【测试结果】
1.出现了一张壁纸设置之后，预览为灰色的现象。
【问题级别】
一般
【出现概率】
不稳定重现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181105203036](https://user-images.githubusercontent.com/14539782/47998392-26328d00-e13a-11e8-949b-430c8c625fc2.gif)

**Comment by felixonmars** [comment]
我这里一直有这个问题，从很多个版本以前就有了。

**Comment by zccrs** [comment]
@felixonmars 稳定吗

**Comment by felixonmars** [comment]
不稳定，而且如果遇到灰色情况，切换到别的壁纸再切换回来一般就好了。

**Comment by funnypro** [comment]
话说发行版也是deepin吗

**Comment by justforlxz** [comment]
现在换kwin了，这个问题不处理了。:)
