### ISSUE TITLE
小米 Pro 15.6 加强版无法安装

### ISSUE THREAD

**Issue by x403368945** [linuxdeepin/internal-discussion#2496]
小米 Pro 加强版安装界面弹不出来，难道是我安装姿势不对？
Security Boot 已经关了，使用的 UEFI 引导
下面是提示信息：
Bluetooth: hci0: Unsupported Intel hardware variant (19)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
