### ISSUE TITLE
深度看图的快捷键预览显示异常

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#251]
【测试环境】
deepin-fpapp-org.deepin.flatdeb.deepin-image-viewer 1.3.0
【预置条件】

【测试步骤】
1.使用深度看图，打开本地的任意图片，然后按住快捷键ctrl+shift+？调出快捷键预览。
【预期结果】
1.快捷键预览显示正常。
【测试结果】
1.快捷键预览显示异常。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181106105146](https://user-images.githubusercontent.com/14539782/48040094-7e0cda80-e1b2-11e8-817c-465f37d32545.png)

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/39487/

**Comment by liuwen123** [comment]
已修复
