### ISSUE TITLE
拔掉电源后dock电池还是显示充电状态

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#252]
【测试环境】
dde-dock：4.7.5.1-1

【测试步骤】
拔掉电源后，查看dock电池状态显示

【预期结果】
电池显示未充电状态

【测试结果】
电池还是显示充电状态

【出现概率】
100%
![_ _20181106105728](https://user-images.githubusercontent.com/12492745/48040247-025f5d80-e1b3-11e8-9af9-c6b08f7684fb.png)

**Comment by zccrs** [comment]
@deepinzhangshuang 找一下杨波的补丁

**Comment by liuwen123** [comment]
https://tower.im/projects/9950e27917904c3ea57c568fe2bcd228/todos/f279e22a92d84fe2a06abb9ef4295061/#a9ec8614484e404b93455c71bf24f7bf      对应的Tower

**Comment by deepinzhangshuang** [comment]
内部已修正，影响不大，外网等下个内核版本一起更新

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
