### ISSUE TITLE
window10系统安装deepin双系统，部分软件使用异常

### ISSUE THREAD

**Issue by jefferyE** [linuxdeepin/internal-discussion#2522]
【测试环境】
小米Pro电脑
【预置条件】
在原有window10系统基础上，U盘安装deepin15.11双系统
【测试步骤】
双击应用商店、网易云音乐、VS Code软件没有反应，打不开（目前测试只发现这3个软件），同时，默认的Chrome浏览器可以打开，但是无法正常联网、火狐浏览器可以正常上网。
【预期结果】
希望可以正常使用
【测试结果】
部分软件不能正常使用
【问题级别】
3
【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
