### ISSUE TITLE
无线在连接一个AP的时候，如果点击了另外一个AP，不会停止当前的连接动作连接新的AP

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#253]
@liuwenhuan 提的， 我这里没有出现
@linuxdeepin/qa-team  @listenerri   你们那边有出现么？

**Comment by listenerri** [comment]
没有重现

**Comment by yefeifei** [comment]
没有遇到

**Comment by felixonmars** [comment]
我遇到略有不同的情况，不知道是不是一个问题：
点击新AP后，其实连接上了原来的AP，但前端显示已连接的是新的AP，nmcli 可以验证实际连接的是老的 AP。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
