### ISSUE TITLE
WiFi连接不人性化

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#254]
【测试环境】
新装ISO

【测试步骤】
新装ISO，然后打开WiFi列表，任意选中一个WiFi，输入任意密码后点击连接

【预期结果】
输入错误密码后进行WiFi连接，当错误超过错误次数后，会重新弹出WiFi密码框，要求重新输入密码

【测试结果】
输入错误密码后，系统会不停的进行重连，永远不会弹出错误提示
要删除当前的WiFi连接，还要进入控制中心的无线网络详情界面才能删除

【出现概率】
100%

**Comment by electricface** [comment]
已经修正 https://cr.deepin.io/#/c/dde/dde-daemon/+/39565

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
