### ISSUE TITLE
全盘加密安装，不显示磁盘容量。

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#255]
![image](https://user-images.githubusercontent.com/24972525/48043954-4313a280-e1c4-11e8-9f47-982890f38ae0.png)

如图

**Comment by hualet** [comment]
@BLumia 文件管理器分区大小显示不对那个你是怎么处理的？

**Comment by BLumia** [comment]
:joy: 我怎么不记得有这么回事了，看了一下文管的计算机属性用的也是 `DSysInfo::systemDiskSize()` 啊

**Comment by hualet** [comment]
>  我怎么不记得有这么回事了，看了一下文管的计算机属性用的也是 `DSysInfo::systemDiskSize()` 啊

https://github.com/linuxdeepin/internal-discussion/issues/214

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dtkcore/+/39585/

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39587/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-control-center/+/39587/

cr +1

**Comment by yefeifei** [comment]
@mmxzmmxz 回归测试的时候帮忙验证一下 O(∩_∩)O谢谢

**Comment by liuwen123** [comment]
已修复
