### ISSUE TITLE
chrome  播放视频会卡顿

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#256]
【测试环境】
新装ISO

【预置条件】
chrome：70.0.3538.77

【测试步骤】
使用浏览器播放微博上面的视频，查看视频显示
http://n.miaopai.com/media/UwwfDXVukeOFtY5euecKROf8hdxS8MYy

【预期结果】
视频画面流畅，声音同步正常

【测试结果】
声音很流畅，但是画面会卡顿

【出现概率】
大概率出现

**Comment by zccrs** [comment]
@liuwen123 其它浏览器呢

**Comment by hualet** [comment]
是不是晃一晃鼠标就好了那种？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
