### ISSUE TITLE
停留在桌面，无法操作 AMD-Vi:unable to write to IOMMU perf counter

### ISSUE THREAD

**Issue by grakke** [linuxdeepin/internal-discussion#2565]
【测试环境】
Honor Magicbook
【预置条件】
添加过阿里源
【测试步骤】
正常启动
【预期结果】
正常启动、使用
【测试结果】
* 命令行闪现 AMD-Vi:unable to write to IOMMU perf counter
* 进入系统后只显示桌面，右键没反应
* ctrl+alt+F2 可以进入，无法输入
【问题级别】
严重
【出现概率】
每次出现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
