### ISSUE TITLE
按钮鼠标状态显示不一致

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#257]
【测试环境】
新装ISO

【测试步骤】
打开深度家族软件，用鼠标移动到右上角的设置、最小化、最大化、关闭按钮上，查看鼠标状态
打开gnome应用，用鼠标移动到右上角的按钮上，查看鼠标状态

【预期结果】
鼠标状态显示一致

【测试结果】
深度应用上显示为手状，gnome应用上显示为指针状

【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
