### ISSUE TITLE
Confusing Between UOS and Deepin v20. 

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/internal-discussion#2578]
When will Deepin v20 release.

**Comment by sarojpoudel33** [comment]
@BLumia @hualet  Please replay on this topic.

**Comment by BLumia** [comment]
**Disclaimer: This is not an official statement. No liability for the accuracy of the information provided.**

UOS is a commercial distro, it's the successor of Deepin commercial edition (deepin.com). It use the V20 codebase but it's not for community user, also it's not free (of charge).

Deepin is the distro which you can use right now, and DDE V20 update will also comes to its community edition in upcoming months. The source release should also comes out in the same peroid.
