### ISSUE TITLE
播放列表中有多个视频之后，切换打开视频之后，进度预览中显示的预览图不是正在播放视频的预览图

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#258]
【测试环境】
deepin-movie:
  已安装：3.2.14-3
【预置条件】

【测试步骤】
1.深度影院添加多个视频到播放列表。然后一次播放每个列表中的视频。
2.在播放其中的一个视频时，hover鼠标到进度条中，查看预览图。
【预期结果】
1.预览图显示的预览正常。
【测试结果】
1.预览图显示的预览并不是当前播放的视频的预览。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181106133141](https://user-images.githubusercontent.com/14539782/48044884-13b36480-e1c9-11e8-9f7b-92745a6b2646.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
