### ISSUE TITLE
个性化显示异常：图标窗口光标主题没有默认选中√显示；且字体显示不支持的字体

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#259]
【测试环境】
15.8ISO
【预置条件】
无
【测试步骤】
1.打开控制中心，点击个性化，修改窗口主题，检查默认显示；
2，点击字体，检查默认显示
【预期结果】
1.默认有选中的√显示；
2.字体不会显示正常
【测试结果】
1.默认没有√显示；
2.字体显示为不支持的字体，点击进入后，列表字体显示又是正常的
【问题级别】
一般
【出现概率】
大概率重现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39538/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-control-center/+/39538/

多次测试没有重现，cr+1

**Comment by yefeifei** [comment]
测试通过
