### ISSUE TITLE
使用exe文件安装软件时，提示“Could not load wine-gecko. HTML rendering will be disabled.”的错误

### ISSUE THREAD

**Issue by songyuc** [linuxdeepin/internal-discussion#2591]
开发者，你好！
我在使用deepin-wine环境时，使用exe文件安装软件时，提示“Could not load wine-gecko. HTML rendering will be disabled.”的错误，请问一下，该怎么解决呢？
是需要安装wine-gecko吗？

期待你的回复！

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！
