### ISSUE TITLE
fcitx不能切换键盘布局

### ISSUE THREAD

**Issue by UniqueDing** [linuxdeepin/internal-discussion#2597]
【测试环境】arch

【预置条件】

【测试步骤】英文输入使用colemak，中文输入使用qwert在fcitx设置中

【预期结果】英文colemak，中文qwert

【测试结果】英文colemak，中文colemak

【问题级别】严重

【出现概率】100%

在其他de或者wm上没有这个问题，
我根本无法输入中文用五笔了

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！
