### ISSUE TITLE
How to compile new version xorg for nvidia hybrid notebooks?

### ISSUE THREAD

**Issue by erickporto86** [linuxdeepin/internal-discussion#2598]
Dear Developers. I see that many are having problems related to NVIDIA going on hybrid notebooks. And it all depends on the version of xorg. I upgraded Sid's xorg 1.20.4 to 1.20.8 and managed to run nvidia. There is a possibility to compile this version of xorg for deepin . And using the prime settings app I can use prime offloading . 
There is a possibility of compiling a new version of xorg because version 1.20.4 is not at all friendly with hybrid notebooks with nvidia gpu.

![Screen Capture_20200827100621](https://user-images.githubusercontent.com/30264657/91446035-4b334b00-e84d-11ea-991e-d67fb99e2a45.png)

![Screen Capture_20200827100628](https://user-images.githubusercontent.com/30264657/91446047-4ff7ff00-e84d-11ea-9841-0175465a0b9d.png)

![Screen Capture_20200827100636](https://user-images.githubusercontent.com/30264657/91446060-538b8600-e84d-11ea-9028-674df25d7632.png)

![Screen Capture_dde-desktop_20200826152217](https://user-images.githubusercontent.com/30264657/91446112-61d9a200-e84d-11ea-9989-5f455f0287f1.gif)

![Screen Capture_select-area_20200827101002](https://user-images.githubusercontent.com/30264657/91446196-86ce1500-e84d-11ea-9f87-542f4eadbd52.png)

**Comment by BLumia** [comment]
Hi, sorry for the late reply.

We use developer-center repo instead of internal-discussion to track user feedback, if you still have question to ask or bug to report, please create a new issue at the developer-center repo. Thanks!
