### ISSUE TITLE
测试组能不能增加一台带AMD RX5700的机器测试？一直驱动不起来

### ISSUE THREAD

**Issue by dunkeng** [linuxdeepin/internal-discussion#2599]
【测试环境】
CPU AMD 3600X
GPU AMD RX5700
主板 微星迫击炮B450M MAX
内存 16G*2 DDR4 3600
无线网卡 INTEL AX200
【预置条件】
一张RX5700显卡
【测试步骤】
在带RX5700显卡的机器上安装系统
【预期结果】
正常安装，正常驱动
【测试结果】
从V20开始，无法正常安装，直接卡死，进不去图形界面，无法安装，最新版本可以通过safe模式安装，但报驱动问题，而且因为依赖的原因，也无法自行安装AMD官方基于DEBIAN的驱动。
错误日志
[drm:amdgpu_init [amdgpu]] **ERROR** VGACON disables amdgpu kernel modesetting.
【问题级别】
严重，驱动
【出现概率】
100%

**Comment by dunkeng** [comment]
今天的正式版一样不行

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！
