### ISSUE TITLE
从外接硬盘读取系统经常出现无法解锁的情况

### ISSUE THREAD

**Issue by zhimenzhang** [linuxdeepin/internal-discussion#2600]
【测试环境】
深度15.10.1桌面版
【预置条件】
将系统安装到硬盘,设置用户名密码
【测试步骤】
开机->登录>等待电脑自动锁屏再次输入密码
【预期结果】
可以正常登录
【测试结果】
偶现无法登录,一直密码输入界面 必须强制重启机器(出现几率很高)
【问题级别】

【出现概率】
10/5

**Comment by BLumia** [comment]
v20 后 issue 处理流程变化，不再通过 internal-discussion 跟进和处理 issue。遗留的 v15 问题不再处理（在 v20 中很可能已不再存在）。若您有类似问题/获取更新后仍有问题，请移步 developer-center 仓库进行汇报。感谢支持！
