### ISSUE TITLE
deepin v20 配置root自动登陆后，无法锁屏、注销，一触发锁屏等登陆器疯狂闪烁，直到桌面白屏。

### ISSUE THREAD

**Issue by proyy** [linuxdeepin/internal-discussion#2606]
deepin v20 配置root自动登陆后，无法锁屏、注销，一触发锁屏等登陆器疯狂闪烁，直到桌面白屏。
lightdm相关的配置文件全看了，对root有限制的配置全更改了，
pam.d验证也过了。

是lightdm-deepin-greeter有针对root做限制吗？？？？

没有找到lightdm-deepin-greeter的说明或者配置文件等

有没有这个的说明呢？

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！

（您这个情况可以看下目前最新 v20.5 是否仍然会出现，如果会的话可以在 developer-center 开个 issue 然后我们这边帮您进一步确认问题）
