### ISSUE TITLE
如何设置拖动窗口不显示窗口内容

### ISSUE THREAD

**Issue by gang929** [linuxdeepin/internal-discussion#2608]
【测试环境】

【预置条件】

【测试步骤】
KVM虚拟机里运行，拖动窗口时，表现有画面残留，如何能像windows那样设置在拖动时只显示边框，释放鼠标后，再显示窗口内容？

【预期结果】
能通过某种设置，以便在拖动窗口时，只显示边框，不显示内容。
这类设置在windows或linux gnome窗口管理器中都有。
 
【测试结果】

【问题级别】

【出现概率】
必然出现

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！
