### ISSUE TITLE
文件管理器右键菜单设置壁纸无效

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#261]
【测试环境】
dde-file-manager：4.6.10-1

【测试步骤】
打开文件管理器任意选中一个gif图片，点击右键--设置壁纸

【预期结果】
GIF图片右键菜单没有设置壁纸选项

【测试结果】
gif有设置壁纸选项，设置壁纸无效

【出现概率】
100%
![_ _20181106141005](https://user-images.githubusercontent.com/12492745/48046028-aeae3d80-e1cd-11e8-9da3-ee85c84b071b.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39505/

为 gif 格式禁用了 设置壁纸 选项

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
