### ISSUE TITLE
【bug】数位板、双屏无法同时支持

### ISSUE THREAD

**Issue by J4gQBqqR** [linuxdeepin/internal-discussion#2610]
【测试环境】
Deepin 20.2.4

【预置条件】
双屏，其中有且仅有一个屏幕是数位板

【测试步骤】
链接上述双屏

【预期结果】
数位板在且仅在一个屏幕上被激活，同时数位板的设置选项可以选择哪个屏幕是数位板。
在多个屏幕是数位板的情况下，可以选择哪个屏幕对应了哪个数位板。

【测试结果】
以上设置选项均不存在。
单个数位板的触摸区域被设置成两个屏幕的所有区域，在数位板上点击会拉伸映射到屏幕1和屏幕2上。
数位板有50%的区域作用于屏幕1，有50%的区域作用于屏幕2。
这导致数位板完全无法使用。

【问题级别】
Deepin系统级别。

【出现概率】
100%

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！
