### ISSUE TITLE
不支持分别设置双屏缩放比例

### ISSUE THREAD

**Issue by J4gQBqqR** [linuxdeepin/internal-discussion#2611]
和#985 有关

【测试环境】
Deepin 20.2.4

【预置条件】
双屏，不同分辨率，不同DPI

【测试步骤】
连接双屏，打开设置，尝试设置缩放比例

【预期结果】
https://github.com/linuxdeepin/internal-discussion/issues/985#issuecomment-467766181

【测试结果】
只有单一的缩放比例可以调整，无法分别调整屏幕缩放，导致屏幕图标偏大或者偏小，总有一个屏幕无法使用。

【问题级别】
Deepin系统级别。

【出现概率】
100%

**Comment by BLumia** [comment]
嗨，我们不使用 internal-discussion 来跟进用户反馈，如果您希望发起缺陷汇报或特性请求，请通过在 developer-center 里发起 issue 或 discussion 来进行反馈，感谢理解！

（关于您的问题，请移步 https://github.com/linuxdeepin/developer-center/discussions/2921 进行讨论）
