### ISSUE TITLE
Update Deepin Live System (live care)

### ISSUE THREAD

**Issue by alvarosamudio** [linuxdeepin/internal-discussion#2612]
it would be a good idea to update deepin live care with the new deepin features and applications such as deepin device manager, deepin disk manager, deepin log viewer, deepin defender and deepin phone assistant.

**Comment by BLumia** [comment]
Hi, sorry for the late reply.

We use developer-center repo instead of internal-discussion to track user feedback, if you have feature request, please create a new discussion thread at the developer-center repo. Thanks!
