### ISSUE TITLE
网络编辑界面，点击保存之后，总是会自动连接上

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#262]
【测试环境】
15.8 ISO
【预置条件】
无
【测试步骤】
1.关闭网络的自动连接，断开连接，点击保存，检查操作结果；
【预期结果】
1.网络不会自动连接
【测试结果】
1.网络会自动连接上；无线、有线、vpn等都是
【问题级别】
一般
【出现概率】
稳定

**Comment by wangjia12** [comment]
> @wangjia12 全都不需要自动连接，还是极个别类型的不需要

开启自动链接就自动链接，手动关闭了自动连接就都不要自动连接， 就字面意思。之前 @jouyouyun 做的这块，我刚问了，这是bug。

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39533

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/39533

cr +1

**Comment by yefeifei** [comment]
测试通过
