### ISSUE TITLE
修改网络的首选DNS保存后，查看配置文件，默认的DNS还存在

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#263]
【测试环境】
15.8 ISO
【预置条件】
无
【测试步骤】
1.修改有线网络或者无线网络的首选dns;如修改为6.6.6.6；
2.检查配置文件：cat /etc/resolv.cnf
【预期结果】
只显示nameserver 6.6.6.6
【测试结果】
第一行显示
wh.sndu.cn
nameserver 10.10.10.10
nameserver 6.6.6.6
【问题级别】
一般
【出现概率】
稳定

**Comment by listenerri** [comment]
这个给 @electricface

**Comment by zccrs** [comment]
@jouyouyun 这个是有networkmanager的配置文件在控制吗

**Comment by jouyouyun** [comment]
看下修改之后 networkmanager 配置中的值

**Comment by jouyouyun** [comment]
需要同时设置下 ignore-auto-dns

| key | type | default | description |
| -- | -- | -- | -- |
|ignore-auto-routes | boolean | FALSE | When "method" is set to "auto" and this property to TRUE,  automatically configured routes are ignored and only routes specified in  the "routes" property, if any, are used.|

**Comment by electricface** [comment]
改成 如果设置了 首选或备选DNS，则设置 ignore-auto-routes 为 true；如果没有设置首选和备选DNS，则设置 ignore-auto-routes 为 false。

**Comment by electricface** [comment]
IPv4 与 IPv6 都要做

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/39573

**Comment by yefeifei** [comment]
> 使用了：`ignore-auto-dns`这个键
> https://cr.deepin.io/c/dde/dde-control-center/+/39573

cr +1

**Comment by yefeifei** [comment]
ISO测试通过
