### ISSUE TITLE
超连接文件删除源文件后，属性菜单显示内容会重叠

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#267]
【测试环境】
dde-file-manager：4.6.10-1

【测试步骤】
任意选中一个文件，点击右键--发送到桌面，然后删除源文件
在桌面选中链接文件，点击右键--属性，查看权限管理显示

【预期结果】
属性界面显示正常

【测试结果】
属性内容会重叠

【出现概率】
100%
![_dde-file-manager_20181106145958](https://user-images.githubusercontent.com/12492745/48048032-fedcce00-e1d4-11e8-8d5a-98264ea7568f.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39500/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
