### ISSUE TITLE
gnome 应用最大化窗口后还原按钮显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#268]
【测试环境】
chrome：70.0.3538.77

【测试步骤】
打开nautilus和chrome，然后最大化显示，查看右上角的还原按钮显示

【预期结果】
窗口最大化后，最大化按钮变成还原按钮

【测试结果】
gedit、nautilus、chrome 最大化后都没有还原按钮显示

【出现概率】
100%
![_ _20181106152020](https://user-images.githubusercontent.com/12492745/48048772-7c094280-e1d7-11e8-9e65-d1009fd1d258.png)

**Comment by zccrs** [comment]
@hualet @sonald @shule1987 这个是因为gtk不支持吗

**Comment by zccrs** [comment]
这个做不了，gtk应用不支持
