### ISSUE TITLE
控制中心点击连接手机共享的热点，检查dock上的WiFi显示还是之前的

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#269]
【测试环境】
dde-dock:4.7.5.1-1
【预置条件】
无
【测试步骤】
1.无线网络连接的是deepin-guest，控制中心无线网络点击手机共享的热点进行连接；
2.等待提示连接成功后，检查dock上WiFi列表已连接显示
【预期结果】
1.dock上显示和控制中心已连接的显示一致
【测试结果】
1.dock上显示已连接的还是之前的无线网络
【问题级别】
一般
【出现概率】
小概率

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-network-utils/+/39580
https://cr.deepin.io/c/dde/dde-dock/+/39581

没有重现这个问题，这两个提交只是尽量减小这个问题出现的可能性

**Comment by yefeifei** [comment]
> [https://cr.deepin.io/c/dde/dde-network-utils/+/39580 ](https://cr.deepin.io/c/dde/dde-network-utils/+/39580)
> https://cr.deepin.io/c/dde/dde-dock/+/39581
> 
> 没有重现这个问题，这两个提交只是尽量减小这个问题出现的可能性

@zhaofangfangdeepin 试一下dock上WiFi已连接却显示没有连接的问题

**Comment by yefeifei** [comment]
测试未重现

**Comment by yefeifei** [comment]
ISO 又遇到这个问题了，控制中心修改WiFi连接，连接到另外一个WiFi，列表还是显示上次连接的

**Comment by listenerri** [comment]
只增加了关键数据的打印日志:
https://cr.deepin.io/c/dde/dde-dock/+/39735
https://cr.deepin.io/c/dde/dde-network-utils/+/39738

**Comment by liuwen123** [comment]
未复现，暂时关闭
