### ISSUE TITLE
从launcher选择拖动应用到dock上然后再移除，dock会崩溃

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#27]
【测试环境】
dde-dock:4.7.4-2
【预置条件】
无
【测试步骤】
1.launcher选择任意非驻留的应用拖动到dock上再拖回；
【预期结果】
1.应用不会驻留在dock上，且dock显示正常；
【测试结果】
1.dock崩溃
【问题级别】
严重
【出现概率】
稳定重现

**Comment by zhaofangfangdeepin** [comment]
@listenerri 是不是和这个差不多？我刚刚让你看的dock崩溃的现象

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39327

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-dock/+/39327

+1 验证通过

**Comment by yefeifei** [comment]
ISO测试通过
