### ISSUE TITLE
chrome点击最大化按钮时窗口会突然消失

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#270]
【测试环境】
chrome：70.0.3538.77

【测试步骤】
打开chrome浏览器进行正常的操作，然后点击右上角的最大化按钮

【预期结果】
浏览器最大化显示

【测试结果】
点击最大化按钮后，窗口会突然消失，要点击dock上的chrome图标才能显示

【出现概率】
小概率

**Comment by zccrs** [comment]
窗管的已知问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
