### ISSUE TITLE
安装topbar顶部拓展栏 点击底部托盘QQ图标无反应

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#271]
论坛ID
li914
[deepin-feedback-cli-Deepin-15.8-all-20181103-101237.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2552026/deepin-feedback-cli-Deepin-15.8-all-20181103-101237.tar.gz)

**Comment by zccrs** [comment]
这样的问题我就直接关了
