### ISSUE TITLE
桌面选中多个文件向下拖拽移动一个位置，会移动失败

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#273]
【测试环境】
dde-desktop：4.6.10-1

【测试步骤】
在桌面选中连个文件，在同一列向下拖拽移动一格

【预期结果】
可以移动成功

【测试结果】
会移动失败

【出现概率】
100%
![_desktop_20181106155152](https://user-images.githubusercontent.com/12492745/48050118-f1771200-e1db-11e8-9118-43dbba049d43.gif)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39590/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
