### ISSUE TITLE
dock托盘的问题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#274]
暂时发现不管是时尚还是高效模式，输入法的看不到图标内容。只有一个圈。
但是QQ用右键呼出菜单后，不会消失，只能点一下QQ图标才消失。

论坛ID
csand3c

**Comment by wangjia12** [comment]
全屏时，切换模式，界面闪烁
论坛ID
pikachuhy

**Comment by hualet** [comment]
> 但是QQ用右键呼出菜单后，不会消失，只能点一下QQ图标才消失。
这个一直有问题 @linuxdeepin/wine-team
