### ISSUE TITLE
这款笔记本电脑 装15.6 15.7 和如今的15.8 均不能驱动声卡

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#278]
测试电脑，神舟笔记本t96e

cpu i7 8750h

显卡 intel 630 nvidia 1060

内存 16g

硬盘 256固态+1T机械

声卡 alc 1220

我这款笔记本电脑 装15.6 15.7 和如今的15.8 均不能驱动声卡， 请研究下原因。

[deepin-feedback-cli-Deepin-15.8-all-20181103-182733.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2552120/deepin-feedback-cli-Deepin-15.8-all-20181103-182733.tar.gz)

**Comment by deepinzhangshuang** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1769721
应该是内核有问题，等我提供新内核测试

**Comment by deepinzhangshuang** [comment]
另外，我查似乎4.11就支持Realtek ALC1220音频解码

**Comment by deepinzhangshuang** [comment]
确定了，是device id 不支持，需要内核添加支持。

**Comment by deepinzhangshuang** [comment]
添加deb http://proposed.packages.deepin.com/kernel-4.15.0-30deepin.31 unstable main contrib non-free
sudo apt-get update && sudo apt-get install linux-headers-4.15.0-30deepin linux-headers-4.15.0-30deepin-generic  linux-modules-4.15.0-30deepin-generic linux-modules-extra-4.15.0-30deepin-generic
安装这５个包后重启进入新内核测试。

**Comment by wangjia12** [comment]
@Aichang2017 联系用户测一下吧

**Comment by Aichang2017** [comment]
收到

**Comment by wangjia12** [comment]
> 收到 用户名多少？ @wangjia12

论坛ID
aaacry

**Comment by Aichang2017** [comment]
已告知
