### ISSUE TITLE
时尚模式下展开和隐藏托盘图标很卡顿

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#28]
【测试环境】
dde-dock:4.7.4~gerrit+39292~1

【预置条件】
时尚模式

【测试步骤】
将ｄｏｃｋ切换成时尚模式，展开和隐藏托盘图标

【预期结果】
展开和隐藏很流畅

【测试结果】
展开和隐藏很卡顿

【出现概率】
100%

**Comment by liuwen123** [comment]
展开和隐藏时还是会比较卡

**Comment by wangjia12** [comment]
@shule1987 你看一下效果吧，昨天去看还是闪一下

**Comment by shule1987** [comment]
这个动效什么时候可以做出来

**Comment by listenerri** [comment]
目前尝试做出的动画都不理想，导致dock卡顿很严重，放到后面做吧

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39358

**Comment by liuwen123** [comment]
已修复
