### ISSUE TITLE
深度文件管理器最近使用列表显示不对

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#281]
![_ _20181106162141](https://user-images.githubusercontent.com/24972525/48051438-13729380-e1e0-11e8-9444-b3b7cd7f5d40.png)
如图 截图时间是11月6日

**Comment by hualet** [comment]
@rekols

**Comment by rekols** [comment]
没说哪里显示不对 -.-

**Comment by hualet** [comment]
> 没说哪里显示不对 -.-

应该说的是排序不是按照 “最近访问时间” 吧

**Comment by Aichang2017** [comment]
对 时间排序不是线性的
