### ISSUE TITLE
最近使用的目录中的文件-打开方式-选择默认程序对话框中，推荐应用列表为空。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#285]
【测试环境】
dde-file-manager:
  已安装：4.6.10-1

【预置条件】

【测试步骤】
1.在最近使用目录，在图片文件上右键-打开方式-选择默认程序。
2.切换设置图片的默认打开程序。
【预期结果】
1.打开打开方式列表，分别显示推荐应用和其他应用列表。
【测试结果】
1.对话框中，推荐应用没有显示任何应用。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181106162128](https://user-images.githubusercontent.com/14539782/48052629-7f0a3000-e1e3-11e8-9819-a065d511579a.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39560/

同时改掉了其他几处仍然在使用 gio 获得 MIME 类型的位置，测试的时候留意一下最近文件里对文件点属性，看打开方式一项中是否有勾选默认打开方式那一项（正常情况应该是有勾选的）。

**Comment by hualet** [comment]
kanbanmgr 是不是很好用 :)

**Comment by BLumia** [comment]
满分.jpg

**Comment by BLumia** [comment]
满分.jpg

**Comment by liuwen123** [comment]
已修复
