### ISSUE TITLE
最近使用列表中，对文件进行标记颜色，标记之后不能立马显示出来。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#287]
【测试环境】
dde-file-manager:
  已安装：4.6.10-1
【预置条件】

【测试步骤】
1.打开文件管理器-最近使用目录。对任意文件进行标记。
【预期结果】
1.标记之后，颜色立马显示出来。
【测试结果】
1.标记之后，颜色没有立马显示出来。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39537/

**Comment by zhaofangfangdeepin** [comment]
V+1

**Comment by liuwen123** [comment]
已修复
