### ISSUE TITLE
屏幕扩展在自定义设置中选中屏幕分辨率列表中，滚动鼠标中键不是一页一页的滚动

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#290]
【测试环境】
dde-control-center：4.7.3-2

【测试步骤】
将笔记本连接双屏，点击控制中心--显示--自定义设置，系统弹出自定义设置对话框
在分辨率列表中滚动鼠标中键，查看分辨率显示

【预期结果】
鼠标中键滚动一下，分辨率显示翻一页

【测试结果】
鼠标中键滚动一下，分辨率显示翻好几页

【出现概率】
100%
![_ _20181106170037](https://user-images.githubusercontent.com/12492745/48053728-5e8fa500-e1e6-11e8-806c-a5002dbae4e9.png)

**Comment by justforlxz** [comment]
是因为鼠标的滚动行数太大了，所以看起来不像是逐像素滚动。
