### ISSUE TITLE
文件管理器、深度音乐、深度商店的窗口从最大化到恢复原来大小时，窗口都是先往外抻一下，再往回缩。这点是否可以优化下。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#291]
【测试环境】
libdtkwidget2 2.0.9.6-1
【预置条件】

【测试步骤】
1.打开深度文件管理器，深度音乐，深度商店，分别最大化之后，在恢复到原来的大小。
【预期结果】
1.恢复原来大小的时候，直接缩小窗口的。
【测试结果】
1.先往外抻一下，再往回缩。
【问题级别】
建议
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181106171114](https://user-images.githubusercontent.com/14539782/48053986-0c9b4f00-e1e7-11e8-8e41-7dbe576bae30.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
