### ISSUE TITLE
#小概率 点击蓝牙键盘，弹出连接成功的同时，控制中心崩了

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#292]
【测试环境】
dde-control-center:
【预置条件】
无
【测试步骤】
1.测试反复连接和断开蓝牙设备，如蓝牙键盘，再某一刻连接成功的时候，检查控制中心是否会崩
【预期结果】
控制中心不会崩
【测试结果】
连接成功的提醒弹出的同时，控制中心闪退了
【问题级别】
一般
【出现概率】
小概率

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
