### ISSUE TITLE
全盘安装没有选择磁盘，点击下一步没有任何提示

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#294]
【测试环境】：
deepin-installer 2.4.4-1
【测试步骤】：
1.安装器进入安装位置选择界面，选择全盘安装，此时点击“下一步”，没有响应也没有提示。
【预期结果】：
1.可提示用户，需要选择硬盘。
ps：选择简单模式，没有选择分区安装，就会有相应提示。

**Comment by mmxzmmxz** [comment]
![img_0107](https://user-images.githubusercontent.com/12388744/48055131-ceebf580-e1e9-11e8-9cf1-1d9b994d51c1.JPG)

**Comment by wangjia12** [comment]
@CallMeR

**Comment by CallMeR** [comment]
1. 在用户只有一个硬盘时，且用户未选定该硬盘的情况下，用户点击“下一步”时，安装器提示“请选择一个磁盘来进行安装”。
2. 在用户有多个硬盘时，且用户未选择任意硬盘的情况下，用户点击“下一步”时，安装器提示“请选择一个磁盘来进行安装”。
3. 用户在未选择任何磁盘的情况下，下方的“加密该磁盘”为不可勾选状态，当用户选择某个磁盘后，该选项恢复正常，即为可操作状态。可操作状态下，该选项默认为非勾选状态。

@shule1987   该部分需要修改一下原始设计稿。

**Comment by CallMeR** [comment]
@zccrs  可以根据这个修改一下。

**Comment by CallMeR** [comment]
@zccrs  已经提交英语文案了，磁盘勾选状态的图，还是麻烦参考一下简单安装中的勾选设计吧

**Comment by mmxzmmxz** [comment]
验证通过
deepin-installer:
  候选： 2.4.9-1
