### ISSUE TITLE
安装器全盘安装选择“加密该磁盘”，字体有背景选中

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#295]
【测试环境】：
deepin-installer 2.4.4-1
【测试步骤】：
1.安装器进入安装位置选择界面，选择全盘安装，勾选“加密该磁盘”，字体有背景出现。
【预期结果】：
1.没有选中背景出现。

**Comment by mmxzmmxz** [comment]
![_ _20181106173745](https://user-images.githubusercontent.com/12388744/48055491-b03a2e80-e1ea-11e8-9667-31496872bc66.png)

**Comment by mmxzmmxz** [comment]
该问题仍然存在。181113ISO
deepin-installer 2.4.9-1

**Comment by zccrs** [comment]
@justforlxz 回一下tag号

**Comment by justforlxz** [comment]
2.5.7

**Comment by mmxzmmxz** [comment]
该问题仍然存在
deepin-installer 2.5.10

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41174/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/deepin-installer-reborn/+/41174/

v+1

**Comment by liuwen123** [comment]
已修复
