### ISSUE TITLE
可以使用左右键用户头像，但不能切换系统桌面

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#296]
【预置条件】
安装多个系统桌面gnome，kde，xfce4，再新建多个用户，然后注销系统

【测试步骤】
在登录界面，点击用户头像按钮，系统弹出头像列表，按左右键可以任意切换选中头像，连续按可以循环选中
点击切换系统桌面按钮，在桌面列表中，连续按方向键

【预期结果】
在桌面列表中，连续按方向键，也可以循环选中

【测试结果】
在桌面列表中无法循环选中
先打开桌面列表然后退出，再次打开桌面列表按方向键就无效了

【出现概率】
100%
![_20181106173751](https://user-images.githubusercontent.com/12492745/48055512-bc25f080-e1ea-11e8-9302-ad11b54f4511.jpg)
![_20181106173757](https://user-images.githubusercontent.com/12492745/48055514-bcbe8700-e1ea-11e8-9425-014e75d9e44e.jpg)

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39687/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
