### ISSUE TITLE
为何深度家族应用鼠标图标不一致

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#299]
有的是小手，有的是箭头。
![_ _20181106175301](https://user-images.githubusercontent.com/24972525/48056598-12942e80-e1ed-11e8-81cf-da250105f02d.gif)

**Comment by rekols** [comment]
深度终端已经改成了手型：https://cr.deepin.io/#/c/deepin-terminal/+/39571/
