### ISSUE TITLE
面向笔记本，区分连接电源时和使用电池时不同的电源方案

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#3]
电源管理中对于关闭显示器和电脑进入睡眠模式的设置，好像并不区分连接电源还是使用电池，我们是否可以将连接电源和使用电池的这两种状态区别对待。对于使用台式机的用户，这种设置并没有什么用，但现在使用笔记本的还是非常多的。

对于笔记本用户而言，在连接电源的情况下，用户可能并不关心何时关闭显示器、何时进入睡眠，在除去延长屏幕使用时间的情况下，更多的时候可能希望显示器常亮并且不进入睡眠。在未连接电源使用电池时，考虑到省电，可能会使用不同的屏幕亮度、设置关闭关闭显示器和进入睡眠的时间。
@wangjia12 @hualet

**Comment by jouyouyun** [comment]
之前界面上是可以分开设置的，现在也是有区分的，程序内部自动处理。

**Comment by jouyouyun** [comment]
> > 之前界面上是可以分开设置的，现在也是有区分的，程序内部自动处理。
> 
> 程序内部是如何自动处理的？

接上电源就使用电源的配置，拔掉电源就使用电池的配置，界面的修改也是

**Comment by hualet** [comment]
好像有点太隐式了 我自己都忘了还有这茬 :sweat_smile:

**Comment by 21wmd** [comment]
> > > 之前界面上是可以分开设置的，现在也是有区分的，程序内部自动处理。
> > 
> > 
> > 程序内部是如何自动处理的？
> 
> 接上电源就使用电源的配置，拔掉电源就使用电池的配置，界面的修改也是

**Comment by 21wmd** [comment]
> > > 之前界面上是可以分开设置的，现在也是有区分的，程序内部自动处理。
> > 
> > 
> > 程序内部是如何自动处理的？
> 
> 接上电源就使用电源的配置，拔掉电源就使用电池的配置，界面的修改也是

首先，经过测试，并不会根据是否连接电源改变配置，这有缺陷，请 @jouyouyun 修复。
其次，这个问题在社区版和专业版中都存在，应该是测试用例的缺失，请 @deepinzhangshuang 补充测试用例。
再次，即便是当前的这种方式没有Bug，我也认为这种电源管理设置方式有问题。希望无论当前是连接外接电源，还是使用电池，都能够对连接外接电源和使用电池这两种状态的电源策略进行配置。

**Comment by wangjia12** [comment]
@21wmd 的意思是无论是否在链接电源的请下都可以给链接电源和不链接电源两种方式设置。看了Windows和mac也是支持的。我们之前想的只加文案做不到这样，需要改一下设计。
@shule1987 @hualet @zccrs

**Comment by hualet** [comment]
> @21wmd 的意思是无论是否在链接电源的请下都可以给链接电源和不链接电源两种方式设置。看了Windows和mac也是支持的。我们之前想的只加文案做不到这样，需要改一下设计。15.8.1可能做不完吧。
> @shule1987 @hualet @zccrs

先按照上次讨论的那种简单模式做吧，如果真有用户喷不明显之类的，我们再改进。

**Comment by shule1987** [comment]
<img width="307" alt="2018-11-27 11 33 59" src="https://user-images.githubusercontent.com/5448609/49056872-61efdc80-f238-11e8-9aa4-e969b918aa5d.png">

**Comment by wangjia12** [comment]
需求说明：

1. 控制中心-电源管理的关闭显示器时间设置和电脑进入待机模式设置这两项，将使用电源和使用电池的设置情况分开展示；
2. 无论在是否连接电源的情况下都可以对两种状态的分别设置；

文案：
【使用电源】
【使用电池】
@zhuxiujuancindy

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39926/  

和 #492 是一个翻译cr

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
