### ISSUE TITLE
系统语言切换到正体中文之后，GPL协议显示的依然是英文

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#30]
【测试环境】
Deepin15.8
dde-control-center:
  已安裝：4.7.1-2
【预置条件】

【测试步骤】
1. 切换系统语言为繁体中文，然后打开控制中心-系统信息-版权信息，查看GPL协议内容。
【预期结果】
1.GPL协议内容显示为繁体版本。
【测试结果】
1.显示的是英文。
【问题级别】
1.一般
【出现概率】
1.稳定复现

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39309/
