### ISSUE TITLE
网易公开课在线无法观看，flash无法激活

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#301]
【测试环境】
libflashplugin:
  已安装：31.0.0.108
google-chrome-stable:
  已安装：70.0.3538.77-1

【预置条件】

【测试步骤】
1.打开网易公开课，播放在线视频。
【预期结果】
能够播放
【测试结果】
无法播放
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zccrs** [comment]
其它视频网站可以吗

**Comment by deepinzhangshuang** [comment]
@zhaofangfangdeepin  已经更新ppa/dde-panda

**Comment by zhaofangfangdeepin** [comment]
ISO回归验证，内网测试正常。

**Comment by liuwen123** [comment]
已修复
