### ISSUE TITLE
深度终端切换主题预览与实际切换结果不一致

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#305]
【问题】
在使用深度终端切换主题时，主题预览和实际切换结果不一致

【期望】
主题预览位置中，提示符颜色和实际切换后的提示符颜色一致，主题名称的颜色和实际切换后的输出文字颜色一致。

【目前】
主题预览位置中的提示符颜色对应了切换后的输出文字颜色，主题名称文字颜色并未对应提示符颜色或普通输出颜色中的任意一个。

【环境】
deepin-terminal 3.0.9+r0+g89ae450

【其他】
如图：
![image](https://user-images.githubusercontent.com/10095765/48105535-e6bb8c00-e272-11e8-81c4-0fb1fc28f8a1.png)

相关代码：[theme_button.vala#L117](https://github.com/linuxdeepin/deepin-terminal/blob/77546a4653ec17e36f5b7b2d5588c7dc78a960c8/widget/theme_button.vala#L117)

**Comment by zhaofangfangdeepin** [comment]
确实不一致。

**Comment by hualet** [comment]
那个颜色好像不是指提示符的颜色，而是前景色……
@shule1987

**Comment by BLumia** [comment]
> 那个颜色好像不是指提示符的颜色，而是前景色

对啊它应该是提示符颜色而不是前景色，下面的主题名称应该用前景色。另外我觉得可以把这个预览搞成和默认显示方式完全一样的格式：

``` plain
deepin@linux:~$ _
theme name
```

这样

**Comment by hualet** [comment]
> > 那个颜色好像不是指提示符的颜色，而是前景色
> 
> 对啊它应该是提示符颜色而不是前景色，下面的主题名称应该用前景色。另外我觉得可以把这个预览搞成和默认显示方式完全一样的格式：
> 
> ```
> deepin@linux:~$ _
> theme name
> ```
> 这样

可以呀 help wanted :joy:

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/deepin-terminal/+/39610/

大致改了一点.. 提示符应该是粗体这个没做，提示符这里也没有体现路径那部分的颜色（体现的话提示符可以是 `deepin@linux:~/theme/$ _` 之类的）。

**Comment by hualet** [comment]
我支持
 @shule1987 看看

**Comment by shule1987** [comment]
改吧

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/deepin-terminal/+/39654/

**Comment by liuwen123** [comment]
已修复
