### ISSUE TITLE
在锁屏界面输入错误密码登录，屏幕会闪一下

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#306]
【预置条件】
按Super+L锁屏

【测试步骤】
在锁屏状态下，输入错误密码，系统给出提示信息后，按backspace删除密码

【预期结果】
密码删除

【测试结果】
屏幕会闪一下

【出现概率】
100%

**Comment by justforlxz** [comment]
重构以后没了

**Comment by liuwen123** [comment]
已修复
