### ISSUE TITLE
系统监视器选中状态和其他按钮选中状态不一致<周一>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#308]
【预置条件】
进入系统后按Alt+Ctrl+Delete键，进入关机界面

【测试步骤】
在关机界面按左右方向键，查看选中状态显示
然后按下方向键选中系统监视器，查看选中状态显示

【预期结果】
系统监视器选中状态和其他按钮选中状态显示一致

【测试结果】
系统监视器选中状态和其他按钮选中状态不一致

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/40458

**Comment by justforlxz** [comment]
@shule1987  说去掉了边框，颜色和launcher保持一致。

**Comment by liuwen123** [comment]
已修复
