### ISSUE TITLE
升级环境，通过启动器-卸载crossover，卸载失败。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#310]
【测试环境】
Deepin15.5 升级到Deepin15.8
【预置条件】

【测试步骤】
1.打开启动器-crossover-右键-卸载。
【预期结果】
1.卸载成功
【测试结果】
1.卸载失败
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
11月 07 16:49:47 deepin-PC com.deepin.dde.Launcher[6229]: 2018-11-07, 16:49:47.553 [Debug  ] [                                                         0] appKey "cxmenu-cxoffice-0-29ra4ke-CrossOver"
11月 07 16:49:49 deepin-PC daemon/launcher[6401]: manager_ifc.go:154: RequestUninstall id: "cxmenu-cxoffice-0-29ra4ke-CrossOver"
11月 07 16:49:49 deepin-PC daemon/launcher[6401]: manager_ifc.go:157: uninstall "cxmenu-cxoffice-0-29ra4ke-CrossOver" failed: exit status 1
11月 07 16:49:49 deepin-PC daemon/launcher[6401]: manager.go:434: sendNotification summary: "\"CrossOver\" 卸载失败", body: "", icon: "deepin-appstore"
11月 07 16:49:49 deepin-PC com.deepin.dde.Launcher[6229]: 2018-11-07, 16:49:49.904 [Warning] [                                                         0] window == 0 passed.
11月 07 16:49:49 deepin-PC com.deepin.dde.Launcher[6229]: 2018-11-07, 16:49:49.904 [Warning] [                                                         0] QXcbConnection: XCB error: 152 (Unknown), sequence: 25624, resource id: 0, major code: 143 (Unknown), minor code: 2
11月 07 16:49:49 deepin-PC com.deepin.dde.Launcher[6229]: 2018-11-07, 16:49:49.905 [Warning] [                                                         0] QXcbConnection: XCB error: 152 (Unknown), sequence: 25633, resource id: 0, major code: 143 (Unknown), minor code: 2
11月 07 16:50:24 deepin-PC com.deepin.dde.Dock[6229]: 2018-11-07, 16:50:24.202 [Debug  ] [                                                         0] app item clicked, name: "微信" id: "e107T5be2a6cc" my-id: "e107T5be2a6cc" icon: "deepin.com.wechat"

**Comment by electricface** [comment]
cross over 创建的 desktop 是带有随机字符串的，比如 cxmenu-cxoffice-0-29ra4ke-CrossOver ，没法确定这个文件属于那个包，就不知道要卸载那个包。

**Comment by liuwen123** [comment]
已修复
