### ISSUE TITLE
深度日历打不开

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#312]
【测试环境】：
libdtkwidget2:
  已安装：2.0.9.7-1
dde-calendar:
  已安装：1.2.5-1

【测试步骤】：
1.点击不能打开。

uu@uu-PC:~$ dde-calendar 
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/dde-calendar/translations/dde-calendar_zh_CN"
dde-calendar: symbol lookup error: dde-calendar: undefined symbol: _ZN3Dtk6Widget12DApplication14setProductIconERK7QPixmap

**Comment by deepinzhangshuang** [comment]
ppa/dde-panda　已经更新　@mmxzmmxz

**Comment by mmxzmmxz** [comment]
验证通过
deepin-fpapp-org.deepin.flatdeb.deepin-calendar 1.2.5+r2
