### ISSUE TITLE
深度商店，主窗口正常大小时，hover在主页的任意程序上，所属的分类信息没有显示完全

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#313]
【测试环境】
deepin-appstore=5.1.0.1-1
【预置条件】

【测试步骤】
1.在x230笔记本上，打开深度商店。
2.hover深度商店的主页上应用程序，查看所属分类的信息是否显示完全。
【预期结果】
1.所属分类信息显示完全。
【测试结果】
1.所属分类的信息没有显示完全。
【问题级别】
提示
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181107113221](https://user-images.githubusercontent.com/14539782/48109429-66048c00-e282-11e8-838a-38b95e4350ca.png)

**Comment by hualet** [comment]
@myml

**Comment by zccrs** [comment]
@yefeifei 我试了下现在的商店已经没问题了，测一测吧

**Comment by yefeifei** [comment]
> @yefeifei 我试了下现在的商店已经没问题了，测一测吧

还有问题 5.1.2.7-1

**Comment by yefeifei** [comment]
升级到5.2.0.2-1，测试正常
