### ISSUE TITLE
深度商店的用户登录，记住密码功能失效。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#315]
【测试环境】
deepin-appstore:
  已安装：5.1.0.1-1
【预置条件】

【测试步骤】
1.打开深度商店，登录。输入用户名和密码，并且勾选记住密码。
2.退出登录之后，重新登录。、
【预期结果】
1.重新登录时，无需输入密码。
【测试结果】
1.退出登录，重新登录时，用户名和密码都被清空了
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by hualet** [comment]
@myml
