### ISSUE TITLE
建议考虑加强amd硬件适配

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#316]
15.7对AMD CPU支持不力，社区AMD笔记本用户普遍反应无法安装。
能否考虑 AMD硬件的适配呢？
例子 https://bbs.deepin.org/forum.php?mod=viewthread&tid=170025&extra=

**Comment by hualet** [comment]
@raphaelzhang 说过会投入人力在AMD驱动的开发和维护上的。
