### ISSUE TITLE
锁屏状态点击右下角的静音按钮，按钮状态错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#317]
【预置条件】
打开网易云音乐播放歌曲

【测试步骤】
按Super+L进入锁屏状态，点击右下角的音量按钮，声音会静音，再次点击音量按钮

【预期结果】
再次点击音量按钮后，声音还原

【测试结果】
再次点击音量按钮无效，声音没有还原，需要上下滚动鼠标调整音量才能还原

【出现概率】
100%
![image](https://user-images.githubusercontent.com/12492745/48112633-39587080-e292-11e8-84c8-88e765ad7513.png)

**Comment by hualet** [comment]
这个好像一直说是网易云音乐的bug吧。

**Comment by liuwen123** [comment]
网易云音乐Bug
