### ISSUE TITLE
锁屏状态下歌名滚动太快了

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#318]
【预置条件】
打开网易云音乐并播放“陕西木有啥”

【测试步骤】
按Super+L锁屏，在锁屏状态下查看右下角的歌名显示

【预期结果】
歌名缓慢滚动

【测试结果】
歌名滚动太快了，啥都看不见

【出现概率】
100%

![_desktop_20181107134618](https://user-images.githubusercontent.com/12492745/48113090-39597000-e294-11e8-91af-0e9eccb17243.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dtkwidget/+/39582/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
