### ISSUE TITLE
任务栏为立即隐藏的时候，展开和收缩托盘，任务栏就会立即隐藏。当鼠标移开任务栏的时候再隐藏效果更好

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#32]
【测试环境】
dde-dock:
  已安裝：4.7.4-2
  候選： 4.7.4-2
【预置条件】
1.任务栏设置为一直隐藏
【测试步骤】
1.设置任务栏的状态为一直隐藏，然后展开和收缩托盘。然后从任务栏上移开鼠标。
【预期结果】
1.移开鼠标之后，任务栏立即隐藏。
【测试结果】
1.还没有移开鼠标，任务栏就立即隐藏了。
【问题级别】
建议
【出现概率】
稳定出现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39338

**Comment by zhaofangfangdeepin** [comment]
V+1
