### ISSUE TITLE
系统网络断开之后，点击深度商店之后的左侧分类，右边页面依然可以刷新出内容

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#320]
【测试环境】
deepin-appstore 5.1.0.1-1
【预置条件】

【测试步骤】
1.打开深度商店，断开系统网络。
2.点击深度商店左侧的分类。查看右边页面的刷新
【预期结果】
1.刷新提示网络异常。
【测试结果】
1.右边页面依然能够刷新出内容。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by hualet** [comment]
那这个应该就没有问题了吧？ @zhaofangfangdeepin

**Comment by zhaofangfangdeepin** [comment]
现在还有问题啊。
deepin-appstore:
  已安装：5.1.2.1-2

**Comment by myml** [comment]
断网后不会再提示网络异常
https://tower.im/projects/643bc376f7754a28af541b293ba9a833/todos/8fe7e63da6fb49978ffc2a2089dfc761/

**Comment by myml** [comment]
> 现在还有问题啊。
> deepin-appstore:
> 已安装：5.1.2.1-2



> 现在还有问题啊。
> deepin-appstore:
> 已安装：5.1.2.1-2

断网后不会再提示网络异常
https://tower.im/projects/643bc376f7754a28af541b293ba9a833/todos/8fe7e63da6fb49978ffc2a2089dfc761/

**Comment by myml** [comment]
> 现在还有问题啊。
> deepin-appstore:
> 已安装：5.1.2.1-2

断网后不会再提示网络异常
https://tower.im/projects/643bc376f7754a28af541b293ba9a833/todos/8fe7e63da6fb49978ffc2a2089dfc761/

**Comment by wangjia12** [comment]
> 为啥呀？没有看懂 @wangjia12

因为他们告诉我 现在的商店是离线的  断网了也是可以打开下一个页面  
以前有这个提示因为真的打不开下一个页面

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
