### ISSUE TITLE
深度商店搜索栏的右键菜单显示异常

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#323]
【测试环境】
deepin-appstore 5.1.0.1-1
【预置条件】

【测试步骤】
1.打开深度商店，在搜索栏中输入字符串之后，右键
【预期结果】
1.右键菜单显示正常
【测试结果】
1.右键菜单显示异常。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/qt5integration/+/39708/ 已从根本上解决此问题
