### ISSUE TITLE
触摸板四指向下移动进入工作区，再次四指向下移动返回无效

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#324]
【预置条件】
使用蓝牙连接Apple触摸板，打开多个程序窗口

【测试步骤】
触摸板四指向下移动进入工作区，再次四指向下移动

【预期结果】
返回到当前工作区窗口

【测试结果】
返回无效

【出现概率】
100%

**Comment by jouyouyun** [comment]
已知问题，之前讨论过:

>不能退出的原因是：手势那里检查了keyboard是否被grabbed，是的话就忽略
>目的是不在一些特殊应用上执行手势动作，如锁屏界面。
>之前讨论的方案是：手势去掉对keyboard的检查，由这些特殊应用提供一个标志量给手势这边用，以此来决定是否执行手势动作。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
