### ISSUE TITLE
有道词典从搜索结果中点击"相关网页"的时候，没有响应

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#325]
【测试环境】
youdao-dict:
  已安装：1.0.8-1
【预置条件】

【测试步骤】
1.打开有道词典，搜索deepin。
2.在搜索结果出现之后，点击相关网页。
【预期结果】
1.点击相关网页时，调用浏览器打开相关网页
【测试结果】
1.没有响应
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_20181107153050](https://user-images.githubusercontent.com/14539782/48116946-87757000-e2a2-11e8-819a-c58d1035019c.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
