### ISSUE TITLE
有道词典点击口语练习时，不能调用麦克风进行录音

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#326]
【测试环境】
youdao-dict:
  已安装：1.0.8-1
【预置条件】

【测试步骤】
1.打开有道词典，输入test，搜索，例句。
2.在搜索到例句之后，点击麦克风图标，进行口语练习。
【预期结果】
1.打开麦克风进行录音。
【测试结果】
1.没有任何响应
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
