### ISSUE TITLE
有道词典迷你模式时，不响应键盘输入

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#327]
【测试环境】
youdao-dict:
  已安装：1.0.8-1
【预置条件】

【测试步骤】
1.打开有道词典之后，切换到迷你模式。
2.输入任何字符串。
【预期结果】
1.响应键盘输入
【测试结果】
1.不响应键盘输入
【问题级别】
一般
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
