### ISSUE TITLE
启动器菜单，拖住图片修改主题，设置无效

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#329]
【测试环境】
15.8 ISO和升级环境
【预置条件】
无
【测试步骤】
1.打开控制中心，选中启动菜单；在桌面选择任意图片（JPG、png）格式图片,拖拽到启动菜单的位置，
【预期结果】
拖拽图片修改主图背景生效
【测试结果】
拖拽没有任何效果，重启检查，也未生效
【问题级别】
严重
【出现概率】
稳定

**Comment by zccrs** [comment]
@justforlxz 禁用拖拽设置图片功能

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-control-center/+/39554/

cr 测试通过

**Comment by yefeifei** [comment]
iso    测试通过
