### ISSUE TITLE
输入法的右键菜单会跑到左上角显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#330]
【预置条件】
启动搜狗输入法

【测试步骤】
在dock上点击搜狗输入法图标

【预期结果】
在图标上面会弹出右键菜单

【测试结果】
输入法右键菜单会跑到桌面左上角

【出现概率】
大概率
![_desktop_20181107164416](https://user-images.githubusercontent.com/12492745/48120374-e6d87d80-e2ac-11e8-9979-7e9f58d09ed9.png)

**Comment by listenerri** [comment]
这个是输入法自己的问题，坐标传过了去的

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39607

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已经修复
