### ISSUE TITLE
在登录界面点击用户头像会切换桌面显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#331]
【预置条件】
安装桌面gnome

【测试步骤】
注销用户在登录界面，先登录gnome桌面然后注销，再把桌面选中为dde，不停的点击用户头像

【预期结果】
无任何反应

【测试结果】
桌面右下角的桌面选项会变成gnome

【出现概率】
100%
![_20181107170403](https://user-images.githubusercontent.com/12492745/48121173-31f39000-e2af-11e8-8a95-883bcfab25be.jpg)

**Comment by justforlxz** [comment]
现在点击用户头像已经没有动作了。

**Comment by liuwen123** [comment]
已修复
