### ISSUE TITLE
深度云打印添加之后，标题栏的信息没有显示完全

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#332]
【测试环境】
printer-driver-deepin-cloud-print=1.2.5-1
【预置条件】

【测试步骤】
1.打开云打印，添加IP和授权码
2.进入打印机添加界面，查看软甲界面标题栏显示。
【预期结果】
1.标题栏现实的信息完整，正确。
【测试结果】
1.标题栏现实的信息不完整。
【问题级别】
提示
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181107170200](https://user-images.githubusercontent.com/14539782/48121482-0cb35180-e2b0-11e8-9176-014a6d57c4c5.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
