### ISSUE TITLE
在托盘中右键wine的程序，弹出右键菜单之后，点击桌面，wine程序的菜单都不能主动隐藏

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#335]
【测试环境】
deepin-wine:
  已安装：2.18-14~rc1
【预置条件】

【测试步骤】
１．打开ｗｉｎｅ程序，如微信、ｑｑ、ＴＩＭ。然后在任务栏－托盘－右键对应的ｗｉｎｅ程序图标。
２．弹出右键菜单之后，点击桌面任意空白位置。
【预期结果】
１．点击桌面空白位置，ｗｉｎｅ程序的右键菜单能够主动隐藏
【测试结果】
１．不能主动隐藏
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zccrs** [comment]
wine 的问题，wine 都知道
