### ISSUE TITLE
在锁屏界面会显示启动器

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#336]
【预置条件】
启动器为小启动器，win7 列表状态

【测试步骤】
按Super+L锁屏后再快速按Super

【预期结果】
系统直接锁屏

【测试结果】
在锁屏界面会显示启动器

【出现概率】
100%
![_desktop_20181108102419](https://user-images.githubusercontent.com/12492745/48173941-ceb23e00-e340-11e8-8bb1-e0068e3448a5.png)

**Comment by listenerri** [comment]
小窗口的 launcher 很特别, 在显示 lock 时, 小 launcher 没有任何收到事件或者信号, 例如 focus, grab, 所以只在 launcher 内部应该处理不了这个问题, 目前考虑增加一个 dde-lock 的 dbus 来获取 lock 的状态

**Comment by listenerri** [comment]
@electricface 锁屏相关的那个 dbus 好了吗?

**Comment by electricface** [comment]
后端 startdde 代码合并了，前端 dde-lock 还不没。

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-launcher/+/41703

**Comment by liuwen123** [comment]
已修复
