### ISSUE TITLE
15.8花屏 来自tele 内测群  应该依然是历史遗留  amd硬件的适配问题

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#337]
amd cpu  amd 显卡
![photo_2018-11-08_10-37-30](https://user-images.githubusercontent.com/24972525/48174413-decb1d00-e342-11e8-83f6-e3b0b5d7c10b.jpg)
![photo_2018-11-08_10-40-23](https://user-images.githubusercontent.com/24972525/48174414-dffc4a00-e342-11e8-9269-26226095013b.jpg)
As you can see the problem is serious and usually affects half of the desktop this phenomenon is dragged from the version of Deepin 15.7 and is reaffirmed in the new version of Deepin 15.8 from the time of installation
The user did everything update drivers and also but the same effect, in version 15.7 the error occurred after the update after installation was correct but as soon as installed and appeared as in the previous image.
Now it happens nothing else to start the installation of Deepin and the error is aggravated, Mr. Hualet Wang and also creators of software I think it is convenient to give a solution to the problem since the new version of Deepin should appear clean of it if possible to avoid frustration and user problems.
Ryzen 5 2400g, 8 gigs, Mobo gaming plus MSI, Vega 11 graphics integrated into the processor

**Comment by hualet** [comment]
@felixonmars 见过么？

**Comment by felixonmars** [comment]
看起来还是我在隔壁某个被关掉的 issue 里写的 AMD 问题。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
