### ISSUE TITLE
2D 控制中心的导航栏tooltip样式显示有非常明显的白框

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#339]
【测试环境】
15.8 
【预置条件】
无
【测试步骤】
1.关闭窗口特效，打开控制中心，点击侧边导航栏，鼠标移动到导航栏，检查tooltip显示
【预期结果】
tooltip显示正常，没有白框
【测试结果】
tooltip显示有非常明显的白框
【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
![123](https://user-images.githubusercontent.com/14539819/48176230-243f1880-e34a-11e8-883c-34c4aeb95114.png)

**Comment by zccrs** [comment]
升级 qt5dxcb-plugin 再验证就和以前一样了

**Comment by yefeifei** [comment]
> 升级qt5dxcb-plugin再验证就和以前一样了

![image](https://user-images.githubusercontent.com/14539819/48240662-94af6d80-e40e-11e8-90e9-775c15579689.png)

**Comment by zccrs** [comment]
@yefeifei 你这开了高分屏缩放吧
