### ISSUE TITLE
chm文件阅读器的右键菜单打开之后，立马就隐藏

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#341]
【测试环境】
chmsee:
  已安装：1.3.0-3

【预置条件】

【测试步骤】
1.打开chm阅读器，打开任意chm文件。
2.打开右键菜单
【预期结果】
1.右键菜单的各个功能正常。
【测试结果】
1.右键菜单一闪而过，立马隐藏。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181108114512](https://user-images.githubusercontent.com/14539782/48176594-cb707f80-e34b-11e8-9ec8-6b44c933f5da.gif)

**Comment by zccrs** [comment]
选中文本后的菜单在鼠标release时会隐藏，感觉是软件自己的问题
