### ISSUE TITLE
无法拖拽virtualbox窗口

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#342]
【预置条件】
使用virtualbox新建deepin虚拟机

【测试步骤】
启动deepin虚拟机，启动完成后用鼠标点击标题栏并拖拽

【预期结果】
可以拖动窗口

【测试结果】
拖动无效

【出现概率】
100%
![_desktop_20181108114142](https://user-images.githubusercontent.com/12492745/48176571-9c5a0e00-e34b-11e8-9c5d-a6deb8561435.png)

**Comment by zccrs** [comment]
试了没问题呀

**Comment by zccrs** [comment]
2D和3D窗管下皆如此，看着像 virtualbox 自己设置了窗口事件接收区域

**Comment by liuwen123** [comment]
新装ISO测试正常
