### ISSUE TITLE
2d 高分屏下，拖拽launcher的应用，拖拽时图标显示不全

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#343]
【测试环境】
15.8
【预置条件】
无
【测试步骤】
1.高分屏，关闭窗口特效；打开launcher，自由排序模式下，选择应用拖拽，检查拖拽时，图标显示
【预期结果】
图标显示正常
【测试结果】
拖拽时，图标显示不全，只显示了1/4，还有很大黑块
【问题级别】
一般
【出现概率】
稳定

**Comment by zccrs** [comment]
@deepinzhangshuang https://codereview.qt-project.org/#/c/200049/ 新版Qt已经修复了，把这个patch打上测一下

**Comment by zccrs** [comment]
https://bugreports.qt.io/browse/QTBUG-61948 相关bug任务
