### ISSUE TITLE
深度商店需要下架远程协助

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#347]
【测试环境】
deepin-remote-assistance:
  已安装：1.0.18-3
【预置条件】
环境从15.4.1升级到15.8
【测试步骤】
1.安装Deepin15.4.1的环境，升级到15.8
2.升级上来之后，深度远程协助被卸载。
【预期结果】
升级上来之后，深度远程协助被卸载。
【测试结果】
1.升级上来之后，远程协助没有被卸载，而且也没被打开。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
深度商店，下架远程协助

**Comment by zhuxiujuancindy** [comment]
已下架
