### ISSUE TITLE
deepin-icon-theme dark 主题配置文件错误

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#348]
zs@zs-PC:~$ sudo gtk-update-icon-cache /usr/share/icons/deepin-dark/
gtk-update-icon-cache: The generated cache was invalid.

可能原因：
1.theme.index文件中的图标目录名称（apps / 24x24，places / 128x128 ...等）如果它们在索引文件中列出并且在图标目录中不存在（或反之亦然）

2.图标图像的名称，如果它们有空格或类似的东西

**Comment by deepinzhangshuang** [comment]
zs@zs-PC:/usr/share/icons/deepin-dark$ find ./ -name *.svg | xargs md5sum | grep "md5sum:"
md5sum: ./places/16/folder-bookmark.svg: 没有那个文件或目录
md5sum: ./devices/16/phone.svg: 没有那个文件或目录
md5sum: ./devices/16/phone-apple-iphone.svg: 没有那个文件或目录

**Comment by deepinzhangshuang** [comment]
https://cr.deepin.io/#/c/deepin-icon-theme/+/39588/

**Comment by shule1987** [comment]
https://cr.deepin.io/#/c/deepin-icon-theme/+/39613

**Comment by zccrs** [comment]
@deepinzhangshuang 已经修了
