### ISSUE TITLE
i卡+全盘加密系统场景，切换显卡驱动，在跑壶界面会卡死

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#349]
【测试环境】：
1102iso
【测试场景】：
i卡台式机
系统：全盘加密安装过的系统
【测试步骤】：
1.驱动管理器打开，切换默认驱动至加速驱动；
2.重启系统，进入茶壶界面，点击应用，界面卡住，一直没有响应。
【预期结果】：
2.可以正常切换驱动。

**Comment by mmxzmmxz** [comment]
可以复现，目前出现2次了

**Comment by mmxzmmxz** [comment]
不点击应用在茶壶界面一直等待，也会卡住～稳定复现

**Comment by hualet** [comment]
@liuwen123 也帮忙测试一下吧，排除一下机器的问题

**Comment by hualet** [comment]
@listenerri 这次再调一下吧

**Comment by listenerri** [comment]
专业版和社区版都没有重现

**Comment by liuwen123** [comment]
![_20190109155231](https://user-images.githubusercontent.com/12492745/50884768-d2d50780-1426-11e9-94ec-35a5f08513d7.jpg)

**Comment by hualet** [comment]
暂时误解，应该就是这个机器不支持这种模式。

**Comment by hualet** [comment]
暂时误解，应该就是这个机器不支持这种模式。

> 暂时误解，应该就是这个机器不支持这种模式。

需要改进一下针对这部分错误处理的设计。

**Comment by liuwenhuan** [comment]
如果不进行全盘加密，看反馈说是正常的。
最近我重装系统，改为用全盘加密，已经发行在拷贝大量文件的时候，多次卡死，需要等待较长时间才能恢复，估计是全盘加解密时对CPU占用过高引起。这个切换失败我怀疑是采用全盘加密导致切换失败。

**Comment by hualet** [comment]
> 如果不进行全盘加密，看反馈说是正常的。
> 最近我重装系统，改为用全盘加密，已经发现在拷贝大量文件的时候，多次卡死，需要等待较长时间才能恢复，估计是全盘加解密时对CPU占用过高引起。这个切换失败我怀疑是采用全盘加密导致切换失败。

你拷贝文件的时候CPU高么？你这么一说也有可能是全盘加密的时候IO偶尔会出问题。

**Comment by listenerri** [comment]
@hualet @zccrs 
经过测试, 茶壶界面卡住时主线程会卡死, 其他线程可以正常跑, 所以我考虑方案有以下两个:
1. 调用 killall 直接杀掉进程
2. 调用 xkill 等待用户点击(界面没法做出提示因为已经卡住了)

**Comment by listenerri** [comment]
另外目前不是稳定复现, 尝试多次才能复现一次, 大概 1/5 的概率吧

**Comment by listenerri** [comment]
> @hualet @zccrs
> 经过测试, 茶壶界面卡住时主线程会卡死, 其他线程可以正常跑, 所以我考虑方案有以下两个:
> 
>     1. 调用 killall 直接杀掉进程
> 
>     2. 调用 xkill 等待用户点击(界面没法做出提示因为已经卡住了)

使用了方案 1:
https://cr.deepin.io/c/deepin-graphics-driver-manager/+/41668

**Comment by liuwen123** [comment]
已修复
