### ISSUE TITLE
dock右键菜单点击即出现

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#350]
dock图标上右键，然后去另一个图标上右键第一次只是隐藏上一次右键显示出的菜单，再点一次才是点击dock图标上的右键菜单。建议合成一步，也就是点哪显示哪的右键菜单，如果有其他的显示应在显示之前关闭其他右键菜单
论坛ID
Snail1991

现在的右键菜单是：
点击A之后出现A的右键菜单，再次点击A之后A的右键菜单消失。
点击A之后出现A的右键菜单，点击B之后A的右键菜单消失，再次点击B之后才有B的右键菜单。

优化为：
点击谁就出谁的右键菜单

**Comment by hualet** [comment]
菜单会抓取所有焦点，所以菜单出现以后再点右键，只有菜单会收到事件（处理事件就是自己消失），任务栏不会收到事件，也就不会做出反应。  @Aichang2017 回复下就行了
