### ISSUE TITLE
窗口管理器只有一个桌面时，“打开工作区”操作失效。无法进行添加桌面操作。

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#356]
论坛ID
yao1110313
[deepin-feedback-cli-Deepin-15.8-all-20181106-235303.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2561112/deepin-feedback-cli-Deepin-15.8-all-20181106-235303.tar.gz)

**Comment by hualet** [comment]
没有吧？ @linuxdeepin/qa-team

**Comment by zccrs** [comment]
3D没试出来，而且2D下也不会出这个界面
