### ISSUE TITLE
下面一行提示信息是否需要加上

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#358]
【操作步骤】
关闭控制中心启动菜单主题

【测试结果】
在deepin主题下，下面一行提示信息是否需要加上

![_20181108170525](https://user-images.githubusercontent.com/12492745/48190049-9892af80-e37c-11e8-8216-05c93c31a82b.jpg)

**Comment by zccrs** [comment]
普通用户不会关注这个
