### ISSUE TITLE
更新后 dde-calendar 无法打开

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#359]
深度日历：更新后 dde-calendar 无法打开，重装无效，命令行执行报错如下

$ dde-calendar

load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"

load translate "/usr/share/dde-calendar/translations/dde-calendar_zh_CN"

dde-calendar: symbol lookup error: dde-calendar: undefined symbol: _ZN3Dtk6Widget12DApplication14setProductIconERK7QPixmap
论坛ID
lanseyujie
[deepin-feedback-all-20181107-203843.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2561136/deepin-feedback-all-20181107-203843.tar.gz)

**Comment by justforlxz** [comment]
张爽已经重新打包了

**Comment by liuwen123** [comment]
已修复
