### ISSUE TITLE
高效模式下，右键-插件，只有时间插件可以隐藏了。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#36]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
1.任务栏设置为高效模式
【测试步骤】
1.在任务栏上右键-插件。查看可以隐藏的插件列表
【预期结果】
1.可以隐藏的插件有，时间，网络，电源，声音。
【测试结果】
1。只有时间一个插件了
【问题级别】
一般
【出现概率】
稳定复现

**Comment by wangjia12** [comment]
因为其他内容已经放到托盘里面去了，所以外面只剩下两个，目前是正常的。

**Comment by wangjia12** [comment]
还有一个关机，但是我没有给文案，不知道是谁自己加的。不过文案也是对的。
