### ISSUE TITLE
拷贝文件去U盘，进度百分比显示异常

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#361]
拷贝一个iso去U盘，几秒钟就到了百分之99，然后一直持续很久的百分之99 传输速度越来越慢  速度显示可能也不准确
![_ _20181109085350](https://user-images.githubusercontent.com/24972525/48236440-2910d480-e3fd-11e8-8b2b-b25e21eb3312.gif)

**Comment by hualet** [comment]
这个我以前好像也报过，后来虽然不知道怎么好了……

**Comment by zccrs** [comment]
速度显示本身就是根据已用时间和已复制数据量计算的，只能是一个参考值，没法说准确不准确

**Comment by hualet** [comment]
> 速度显示本身就是根据已用时间和已复制数据量计算的，只能是一个参考值，没法说准确不准确

不是速度 是进度

**Comment by hualet** [comment]
@zccrs @BLumia 这个考虑提高一下优先级吧。

**Comment by zccrs** [comment]
这个已经改了，可以直接验证上周五的tag，或者内网版本 @liuwen123

**Comment by liuwen123** [comment]
已修复

**Comment by hualet** [comment]
> 这个已经改了，可以直接验证上周五的tag，或者内网版本 @liuwen123

什么问题？
