### ISSUE TITLE
不指定 wifi 的链接无法直接激活

### ISSUE THREAD

**Issue by jouyouyun** [linuxdeepin/internal-discussion#362]
【测试环境】
  deepin 15.8

【预置条件】
新建一个wifi连接，如 deepin-guest 填好加密方式及密码，但不指定 mac-address
【测试步骤】
将文件放入 /etc/NetworkManager/system-connections 中，接着 restart NetworkManager
【预期结果】
通过 dock 连接 deepin-guest 时可以直接连上，不用输入密码
【测试结果】
仍提示需要输入密码，/etc/NetworkManager/system-connections 又新建了一个 deepin-guest 开头的文件
【问题级别】
严重
【出现概率】
必现

deepin-guest 链接文件的内容如下：
```ini
[connection]
id=deepin-guest
uuid=5cdc888e-2625-4c50-a993-ba8192c02850
type=wifi
permissions=

[wifi]
mode=infrastructure
ssid=deepin-guest

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=linuxdeepin123

[ipv4]
dns-search=
method=auto

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
```

@electricface @zccrs @zhaofangfangdeepin

**Comment by hualet** [comment]
@jouyouyun 给我讲了一下，大概搞清楚情况了。 

这种情况下后端的链接列表里面其实有相应的额链接，只是 HwAddress 是空，现在看起来应该是前端过滤掉了，应该显示出来，相应地链接Mac地址设置的地方应该多一个选项 “所有设备” 或者 “随机地址”， HwAddress 为空的情况下就会选择到这个项，相应地如果设置了这个选项，就要清掉配置文件中的 mac-address 之类的设置。

@listenerri @electricface

**Comment by zhuxiujuancindy** [comment]
文案：
【不指定设备】【No device bound】

**Comment by zhuxiujuancindy** [comment]
文案：
【不指定设备】【Not Bind】

**Comment by listenerri** [comment]
@wangjia12 

目前热点的界面设计跟要实现的方案有些冲突, 热点的设计没有 Connection 列表, 因此必须让 Connection 绑定到一个设备上

**Comment by listenerri** [comment]
@wangjia12 

给一下我们讨论的那两个文案

**Comment by wangjia12** [comment]
【热点】
【添加设置】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【热点】【Hotspot】
【添加设置】【Add Settings】

**Comment by listenerri** [comment]
更新 libdde-network-utils 相关包到内网最新, 然后再测试控制中心:

https://ci.deepin.io/job/dde-control-center-ci-debian/5215/

**Comment by listenerri** [comment]
主要测试网络配置文件的识别是否正常, 比如点击连接, 判断已连接, 连接应该显示在那些设备下, 还有有密码的连接, 特别是 wifi, 在输入密码连接一次后, 下次连接能否识别正确, 即不再要求输入密码

**Comment by zhaofangfangdeepin** [comment]
V+1 ，迭代测试通过
