### ISSUE TITLE
搜索文件后，右键打开文件所在位置，调节窗口大小，已选择文件会消失在视觉范围内

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#365]
【测试环境】：
dde-file-manager    4.6.10-1       amd64
【测试步骤】：
1.文管内搜索文件，出现很多搜索结果，选中某个文件，右键点击打开文件所在位置；
2.在新打开的窗口中，定位在选中文件。此时因为窗口太小，调节窗口大小，定位的文件消失在视野中。

**Comment by zccrs** [comment]
@mmxzmmxz 不管是不是从搜索进去的都一样吧，改变窗口大小的时候并不会保证已选中的文件一直留在事业范围

**Comment by liuwen123** [comment]
暂不处理，nautilus也是这样的
