### ISSUE TITLE
远程协助无法使用已经下架，装机系统的动画远程协助是否要去掉

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#367]
【测试步骤】
远程协助已经无法使用，在商店中已经下架，装机系统动画中依然存在，这个是否要去掉
![_vmware_20181109103121](https://user-images.githubusercontent.com/12492745/48239746-11d8e380-e40b-11e8-8393-e4aa3db8bae7.png)

**Comment by wangjia12** [comment]
@zhuxiujuancindy 这个下架吧

**Comment by zccrs** [comment]
@liuwen123 iso验证

**Comment by liuwen123** [comment]
已经修复
