### ISSUE TITLE
laucher图标更新

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#369]
![image](https://user-images.githubusercontent.com/24972525/48240825-3df66380-e40f-11e8-9209-47ccf1e34555.png)
laucher图标建议换成 深度螺旋图案，更有辨识度。
或者时尚模式换成深度螺旋，高效模式保留。
![default](https://user-images.githubusercontent.com/24972525/48240902-988fbf80-e40f-11e8-8b7d-c50a4a3da841.png)

**Comment by hualet** [comment]
我记得 @liuwenhuan 提过吧？ @shule1987

**Comment by shule1987** [comment]
这个是有好的就换，没好的还是维持原样

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
