### ISSUE TITLE
取色、录屏 窗口变黑，重启无效，复现率100%

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#370]
![3 l f yx hok2k y3cr l](https://user-images.githubusercontent.com/24972525/48241648-c591a180-e412-11e8-97b9-382d41211483.jpg)

**Comment by Aichang2017** [comment]
[deepin-feedback-cli-Deepin-15.8-all-20181109-112809.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2564654/deepin-feedback-cli-Deepin-15.8-all-20181109-112809.tar.gz)

**Comment by mmxzmmxz** [comment]
目前最新版本不存在问题。prime方案驱动下的问题
