### ISSUE TITLE
深度商店安装smartgit，smartgit无法启

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#372]
【测试环境】
smartgit:
  已安装：17.1.4-1
【预置条件】

【测试步骤】
1.打开深度商店，搜索smartgit，安装
2.安装完成之后，点击打开，打开smartgit
【预期结果】
1.能正常打开smartgit界面
【测试结果】
1.无法打开
【问题级别】
一般
【出现概率】
稳定复现
ss@ss-PC:~/Desktop$ smartgit 
Java version 1.8 or higher is required, currently  is used (version 11)
Add the line
jre=/path/to/jre
to ~/.smartgit/smartgit.vmoptions and change the path
to the one pointing to the desired JRE.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
