### ISSUE TITLE
高效模式下，dock栏控制中心图标显示为黑，但是可以点击响应

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#374]
【测试环境】：
dde-dock                              4.7.6-1                 amd64
【测试步骤】：
1.正常使用过程中，切换dock至高效模式，发现控制中心图标显示为黑，但是可以正常点击。
【出现概率】：
1.出现该现象后，killdock，问题仍然存在。

**Comment by mmxzmmxz** [comment]
![_desktop_20181112091102](https://user-images.githubusercontent.com/12388744/48321110-011eac80-e65b-11e8-8e49-8f671bb8bd5a.gif)

**Comment by shule1987** [comment]
更新图标主题到最新后即可
