### ISSUE TITLE
建议grub引导菜单中文界面

### ISSUE THREAD

**Issue by Aichang2017** [linuxdeepin/internal-discussion#376]
英文不好的小白用户很多，建议grub引导菜单换成中文，尤其是专业版，有利于体验提升。
![194133zh5w7k7gypbecubb](https://user-images.githubusercontent.com/24972525/48321593-5e682d00-e65e-11e8-8769-cf99dfcf5053.png)

**Comment by hualet** [comment]
@electricface 我看你不是设置了语言么？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
