### ISSUE TITLE
任务栏出现了不停的重绘的现象

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#378]
【测试环境】
dde-dock:
  已安装：4.7.7-1
【预置条件】

【测试步骤】
1.任务栏设置为时尚模式，位置放在左边。
2.打开多个程序，在插件栏上的程序上逐渐的退出程序，查看能否触发该现象
【预期结果】

【测试结果】
1.触发了该现象。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181109102825](https://user-images.githubusercontent.com/14539782/48323808-e6533480-e668-11e8-86dc-483a248bbc2c.gif)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39655

**Comment by zhaofangfangdeepin** [comment]
> https://cr.deepin.io/c/dde/dde-dock/+/39655

V+1
