### ISSUE TITLE
#高分屏  密码输入框的图标显示巨大

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#381]
【测试环境】
iso 
【预置条件】
高分屏
【测试步骤】
1.点击dock上的WiFi，进行链接，检查密码提示框的图标
【预期结果】
图标显示正常
【测试结果】
![image](https://user-images.githubusercontent.com/14539819/48327972-b4e46400-e67c-11e8-87f1-e80834cb1127.png)

【问题级别】
一般
【出现概率】
稳定

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-session-ui/+/39668
