### ISSUE TITLE
windows共享的ftp访问时无法显示包含中文字符的目录或文件

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#382]

**Comment by zccrs** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=170355&page=1#pid531069

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/48328923-58377800-e681-11e8-987d-cdec73a8c0e3.png) :sweat_smile: 

@liuwen123 看看能不能找个环境复现？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
