### ISSUE TITLE
锁屏后点击右下角的关机按钮，关机名称没显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#386]
【预置条件】
按Super+L 锁屏

【测试步骤】
锁屏后，点击右下角的关机按钮，系统弹出关机提示，查看界面显示

【预期结果】
界面显示正常

【测试结果】
关机名称显示为空

【出现概率】
100%
![_desktop_20181112152529](https://user-images.githubusercontent.com/12492745/48332583-5f658280-e68f-11e8-90e7-0812ced0696c.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39669/
