### ISSUE TITLE
默认程序，深度编辑器的图标是齿轮

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#388]
【测试环境】
15.8 ISO
【预置条件】
无
【测试步骤】
1.打开控制中心，默认程序，检查文本工具，默认显示深度编辑器，检查图标消失
【预期结果】
图标显示正常
【测试结果】
图标显示齿轮
【问题级别】
一般
【出现概率】
稳定

**Comment by rekols** [comment]
这个还没打 tag   -.-

**Comment by zccrs** [comment]
@yefei 回归测试
