### ISSUE TITLE
dock关机按钮无法隐藏

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#389]
【预置条件】
新装ISO

【测试步骤】
在dock上点击右键--插件，取消勾选关机按钮

【预期结果】
关机按钮隐藏

【测试结果】
关机按钮无法隐藏

【出现概率】
100%

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39683

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
