### ISSUE TITLE
时尚模式关机按钮单独分离出来之后，低电量提醒就没有了。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#391]
【测试环境】
dde-dock:
  已安装：4.7.9-1
【预置条件】

【测试步骤】
1.在笔记本上安装Deepin15.8 
2.任务栏设置为时尚模式，使用电池供电，知道电池电量低于10%
【预期结果】
1.低于10%的时候，电源图标有低电量提示
【测试结果】
1.电源图标没有低电量提示
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
@wangjia12

**Comment by hualet** [comment]
如果可以拖拽出来的话就没有问题了
