### ISSUE TITLE
深度商店已经安装微信，但是下载排行中微信依然是可以安装状态

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#392]
【测试环境】
deepin-appstore:
  已安装：5.1.2.1-2
【预置条件】

【测试步骤】
1.打开深度商店，在排行榜中-微信图标-安装
2.安装完成之后，再次查看排行榜的微信的状态
【预期结果】
1.微信的状态变成打开
【测试结果】
1.微信的状态依然是安装
【问题级别】
一般
【出现概率】
稳定出现

**Comment by hualet** [comment]
@myml

**Comment by myml** [comment]
> @myml 商店的这个问题是本次更新引入的吗

是的,正在修

**Comment by myml** [comment]
已提交修复补丁
https://cr.deepin.io/#/c/dstore/deepin-appstore/+/39694/
