### ISSUE TITLE
安装过程中轮循播放的图片没有显示完全

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#394]
【测试环境】：
1112最新ISO
deepin-installer:
  已安装：(无)
  候选： 2.4.8-1
【测试步骤】：
1.安装过程中，界面轮循播放图片。发现部分图片显示不全，右侧部分截断。主要为：dock、影院、看图、商店。

**Comment by mmxzmmxz** [comment]
![img_0110](https://user-images.githubusercontent.com/12388744/48389029-a8bcdd00-e736-11e8-848b-9b18d9ceef03.JPG)

**Comment by justforlxz** [comment]
在新iso中验证

**Comment by mmxzmmxz** [comment]
验证通过。181113ISO
