### ISSUE TITLE
深度音乐打开文件夹，默认没有选中主目录

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#395]
【测试环境】
deepin-music:
  已安装：3.1.9-1
【预置条件】

【测试步骤】
1.打开深度音乐-打开文件夹
2.查看打开的文件夹选择对话框默认选中的目录
【预期结果】
1.默认选中主目录
【测试结果】
1.默认没有选择任何目录
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181113111459](https://user-images.githubusercontent.com/14539782/48388910-34823980-e736-11e8-9aec-e118aeca4d13.gif)

**Comment by liuwen123** [comment]
已经修复，打Tag推出去

**Comment by liuwen123** [comment]
已修复
