### ISSUE TITLE
安装器全盘安装提示没有翻译

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#396]
【测试环境】：
1112最后一个ISO
deepin-installer:
已安装：(无)
候选： 2.4.8-1
【测试步骤】：
1.安装最新ISO，进入全盘安装界面，直接点击安装，弹出的提示没有翻译。

**Comment by justforlxz** [comment]
在新iso中验证

**Comment by mmxzmmxz** [comment]
验证通过
deepin-installer:

  候选： 2.4.9-1
