### ISSUE TITLE
授权确认对话框，super+D隐藏之后，就再也出不来了。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#398]
【测试环境】

【预置条件】

【测试步骤】
1.执行新建用户操作，弹出授权确认对话框。
2.super+d，影藏所有窗口
【预期结果】

【测试结果】
1.步骤2之后，授权对话框被隐藏。
被隐藏之后，就没有方法可以把该窗口调出来了
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dtkwidget/+/39834/1/src/widgets/ddialog.cpp

**Comment by zhaofangfangdeepin** [comment]
> https://cr.deepin.io/#/c/dtkwidget/+/39834/1/src/widgets/ddialog.cpp

V+1

**Comment by liuwen123** [comment]
已修复
