### ISSUE TITLE
需求中没有deepin-dark的图标主题需求，但是实际上加了这个主题，但是这个主题上面谷歌浏览器图标不正确。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#399]
【测试环境】
Deepin15.8 第三轮
【预置条件】

【测试步骤】
1.安装镜像之后，进入系统，打开控制中心-个性化-主题，查看图标主题
2.切换到主题deepin-dark。查看图标主题切换是否正常。
【预期结果】
1.deepin-dark的主题图标预览中，谷歌浏览器的图标和实际效果不一致。
【测试结果】

【问题级别】
提示
【出现概率】
稳定复现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181113141838](https://user-images.githubusercontent.com/14539782/48394581-06f5ba00-e74f-11e8-825f-0ea383686dc7.png)

**Comment by wangjia12** [comment]
这个是前两天才知道的，我忘记加上去了。我现在加上去。

**Comment by wangjia12** [comment]
你的图我刷不出来  @shule1987 看看图是什么意思

**Comment by hualet** [comment]
已修复
