### ISSUE TITLE
文件管理器无法挂载 iphone 手机的应用文档

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#40]
论坛反馈bug：https://bbs.deepin.org/forum.php?mod=viewthread&tid=170018&page=1#pid527327

**Comment by wangjia12** [comment]
bug放bug  放在搜集里干嘛啦

**Comment by BLumia** [comment]
[gvfsmountmanager.cpp#L620](https://github.com/linuxdeepin/dde-file-manager/blob/4.6.10/dde-file-manager-lib/gvfs/gvfsmountmanager.cpp#L620)

不知道是不是刻意的，但可能是这里导致的。手头没 iPhone ，这个应该算是新需求吧。

**Comment by BLumia** [comment]
@rekols 你看一下吧 :joy:

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39846/

**Comment by liuwen123** [comment]
已修复
