### ISSUE TITLE
控制中心首页通知图标不明确<周四>

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#400]
大概有三四个人(@felixonmars 算一个，还有几个社区的老外)跟我说那个图标不知道是通知的图标，不是特别明显，看看是不是要换一个 @shule1987 @wangjia12

**Comment by wangjia12** [comment]
是不明显，像主菜单。

**Comment by shule1987** [comment]
下个星期换吧

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=150

**Comment by zccrs** [comment]
@shule1987 图标做好了吗

**Comment by shule1987** [comment]
> @shule1987 图标做好了吗

[归档 2.zip](https://github.com/linuxdeepin/internal-discussion/files/2766842/2.zip)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/41604

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修改
