### ISSUE TITLE
ISO 新建自定义设置点击保存，无法保存

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#401]
【测试环境】
15.8 ISO-11.12 最新
【预置条件】
无
【测试步骤】
1.双屏环境，点击新建自定义，设置后点击保存，检查操作结果
【预期结果】
新建自定义设置保存成功
【测试结果】
点击保存没有保存成功，没有新建自定义设置1
【问题级别】
一般
【出现概率】
稳定

**Comment by hualet** [comment]
已修复
