### ISSUE TITLE
无线热点界面，打开热点，此时拔掉无线网卡，控制中心会崩溃

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#402]
【测试环境】
dde-control-center:4.7.4-2
【预置条件】
无
【测试步骤】
1.插上支持热点的无线网卡，控制中心点击网络热点，进入热点，创建热点，此时拔掉无线网卡
2.检查控制中心显示
【预期结果】
控制中心显示正常，不会崩溃
【测试结果】
控制中心崩溃
【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/39730

cr+1

**Comment by liuwen123** [comment]
已修复
