### ISSUE TITLE
锁屏输入错误密码提示和注销输入错误密码提示显示不一致

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#404]
【测试步骤】
用户登录成功后按Super+L锁屏，在登录界面输入错误密码，查看提示信息显示
按Alt+Ctrl+Delete注销系统，在登录界面输入错误密码，查看提示信息显示

【预期结果】
提示信息显示一致

【测试结果】
锁屏界面提示信息有圆角显示，且提示信息居中显示
注销界面提示信息没有圆角，提示信息在底部显示

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dtkwidget/+/39762/
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39763/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
