### ISSUE TITLE
更新模块和系统信息模块是否考虑合并？

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#409]
更新模块和系统信息模块合起来没有一个屏幕，导航栏是否已经失去意义？
合并在一起是否更简洁。
@wangjia12 @hualet @shule1987

**Comment by wangjia12** [comment]
虽然占得区域很少，但是他们是两种不同的内容。我的意见是不要合并。

**Comment by hualet** [comment]
以前有想法把更新模块拿出来的，放到商店或者是怎么样，因为将来商店也可以更新应用，控制中心也可以更新应用，而且控制中心更新的时候如果隐藏了特别容易忘掉还在更新。

**Comment by wangjia12** [comment]
> 以前有想法把更新模块拿出来的，放到商店或者是怎么样，因为将来商店也可以更新应用，控制中心也可以更新应用，而且控制中心更新的时候如果隐藏了特别容易忘掉还在更新。

想拿出来在商店是建立在实现应用独立更新之后的条件下，商店只更新应用，控制中心只更新系统。

**Comment by shule1987** [comment]
如果技术上没难题的话我赞成商店更新应用，控制中心更新系统

**Comment by deepinzhangshuang** [comment]
其实系统信息和更新  都归类到【系统】里面就可以。 手机里面一般也是这样区分的，内部二级页面再区分。 苹果是在【通用】里面，二级页面再有【更新】【系统信息】。 当然这里只是讨论一下，前提是首页是否越少越简单越好。

**Comment by wangjia12** [comment]
回复 @shule1987 的：技术上现在还做不到
回复 @deepinzhangshuang 的，如果控制中心只更新系统了其实可以像你说的那样做
