### ISSUE TITLE
深度商店登录对话框没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#41]
【测试环境】
deepin-appstore：5.1.0.1-1

【预置条件】
深度商店

【测试步骤】
打开深度商店，点击右上角设置--登录按钮，查看登录对话框显示

【预期结果】
登录对话框显示正常

【测试结果】
登录对话框没有翻译

【出现概率】
100%
![_deepin-appstore_20181030130429](https://user-images.githubusercontent.com/12492745/47697104-9a55c800-dc44-11e8-9d90-6b1a9b7ac7ef.png)

**Comment by Iceyer** [comment]
@felixonmars 上mm更新下服务器

**Comment by felixonmars** [comment]
已更新。
