### ISSUE TITLE
n卡独显机器，闭源切换默认驱动失败

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#410]
【测试环境】：

【测试步骤】：
1.台式机n卡独显+全盘加密安装场景，切换n卡驱动闭源至默认失败。
ps：默认的开源驱动切至闭源驱动正常；
    但是闭源切至默认则失败。

**Comment by listenerri** [comment]
没有重现这个问题, 使用的环境如下:

- 系统版本: 从15.7**升级**上来的15.8
- 驱动管理器版本: 最新tag版本
- nvidia显卡型号: NVIDIA Corporation GK107 [GeForce GT 740]

**Comment by listenerri** [comment]
找到原因了, 已修复:
https://cr.deepin.io/c/deepin-graphics-driver-manager/+/39788
