### ISSUE TITLE
智能镜像源

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#411]
在控制中心增加调节智能镜像源功能。

**Comment by zccrs** [comment]
@wangjia12 详细地说明一下吧，文案设计图什么的也贴上来

**Comment by wangjia12** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/50

**Comment by wangjia12** [comment]
> @wangjia12 详细地说明一下吧，文案设计图什么的也贴上来

明天来定，跟着后一批功能做吧
