### ISSUE TITLE
深度编辑器的预装顺序

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#412]
【测试环境】
15.8 最新ISO
【预置条件】
无
【测试步骤】
安装15.8最新iso ,检查launcher中深度编辑器的位置显示
【预期结果】
替换gedit的位置
【测试结果】
显示在最后一个
【问题级别】
一般
【出现概率】
稳定

**Comment by deepinzhangshuang** [comment]
https://cr.deepin.io/#/c/deepin-desktop-schemas/+/39715/
@yefeifei

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/deepin-desktop-schemas/+/39715/
> @yefeifei

安装了deb包后，窗管特效无法开启，dock一直在抖动
