### ISSUE TITLE
系统RTC时间错误

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#414]
【测试环境】
15.8iso
【预置条件】
无
【测试步骤】
1.安装新系统，重启后登录到系统，终端输入timedatectl 检查系统时间
【预期结果】
RTC时间应该显示当前系统的时间
【测试结果】
![123](https://user-images.githubusercontent.com/14539819/48410254-0d009080-e779-11e8-93e2-100b30628cf3.png)

【问题级别】
一般
【出现概率】
不稳定重现

**Comment by hualet** [comment]
@yefeifei 看看重启之后会不会正常同步

**Comment by yefeifei** [comment]
> @yefeifei看看重启之后会不会正常同步

重启也没解决

**Comment by hualet** [comment]
系统好像没有使用 UTC 时间，你这种情况是系统里面有windows安装了deepin吧？

**Comment by yefeifei** [comment]
> 系统好像没有使用UTC时间，你这种情况是系统里面有windows安装了deepin吧？

是的，装了win10
