### ISSUE TITLE
文件管理器目录大小显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#416]
【预置条件】
安装新ISO

【测试步骤】
进入主目录，然后将图标显示为列表模式，查看目录大小显示

【预期结果】
目录大小显示正确

【测试结果】
目录大小显示错误

【出现概率】
100%

https://cr.deepin.io/#/c/dde/dde-file-manager/+/39069/

![_dde-file-manager_20181114101259](https://user-images.githubusercontent.com/12492745/48455374-e2085200-e7f5-11e8-880d-67133f5e6c7e.png)

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-file-manager/commit/c8c43634bcd96bb15c98f0323ce13c95e85c7e68

这个导致的。 @zccrs 当时去掉这个检查是有什么特定原因/任务吗？

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/663

**Comment by BLumia** [comment]
再改成文件夹显示为空 :joy:

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39824/

**Comment by liuwen123** [comment]
已修复
