### ISSUE TITLE
QtCreator 的 DTK 集成

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#417]
方便 DTK 开发者使用 QtCreator 进行开发。

- [x] 增加 DTK 的程序模板
- [ ] 增加 DTK 的文档关联
- [ ] 增加一键打包 Deb/Flatpak 功能

**Comment by PikachuHy** [comment]
awesome

**Comment by rekols** [comment]
DTK 模板：https://cr.deepin.io/#/c/qtcreator-template-dtk/+/40083/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
