### ISSUE TITLE
控制中心的changelog 显示有截断

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#418]
【测试环境】
dde-control-center:
  已安装：4.7.6-1
【预置条件】

【测试步骤】
1.安装deepin15.7 ，升级到15.8 。
2.打开控制中心-更新-检查更新。查看changelog的显示。
【预期结果】
1.changelog显示正确和完整。
【测试结果】
1.changelog显示有截断
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181114104411](https://user-images.githubusercontent.com/14539782/48456957-ed5e7c00-e7fb-11e8-8df6-8678fb2af86a.png)

**Comment by liuwen123** [comment]
+1

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40339/

**Comment by liuwen123** [comment]
已修复
