### ISSUE TITLE
#cef# 网易云音乐搜索关键词前后带空格会导致卡死

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#42]
【测试环境】

netease-cloud-music: 1.1.3+r9+g3bd12196 1001

【测试步骤】

 1. 打开网易云音乐应用
 2. 激活搜索框，并以 ` keyword ` 为关键词（任意关键词前后加半角空格）进行搜索

【预期结果】

能够正常进行搜索

【测试结果】

窗口卡死

【出现概率】

稳定重现

**Comment by liuwen123** [comment]
netease-cloud-music：1.1.3.1-1   显示正常，没有窗口卡死现象

**Comment by liuwen123** [comment]
已修复
