### ISSUE TITLE
文件管理器无法记住最大化状态

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#423]
【测试步骤】
打开文件管理器，然后点击最大化按钮，窗口最大化后关闭窗口

【预期结果】
下次重新打开文件管理器时，最大化显示

【测试结果】
没有记住最大化状态

【出现概率】
100%

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-file-manager/issues/38

**Comment by wangjia12** [comment]
> [linuxdeepin/dde-file-manager#38](https://github.com/linuxdeepin/dde-file-manager/issues/38)

这个之前有后来去掉的吗  记得为什么吗？

**Comment by wangjia12** [comment]
这是一个之前代码重构做漏掉了的一个bug，修复了就行了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
