### ISSUE TITLE
控制中心启动菜单滚动条右键菜单建议去掉

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#424]
【测试步骤】
安装多个操作系统，打开控制中心--系统信息--启动菜单，在滚动条上点击右键

【预期结果】
无任何显示

【测试结果】
有右键菜单弹出

【出现概率】
100%
![_ _20181115132015](https://user-images.githubusercontent.com/12492745/48531983-75668380-e8d9-11e8-80ac-2573100ade44.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39757

**Comment by liuwen123** [comment]
还是会显示右键菜单

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
