### ISSUE TITLE
任务栏右键菜单和桌面右键菜单交替点击，会出现后者出现之后，前者还没有消失的现象。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#425]
【测试环境】
dde-dock:
  已安装：4.8.0-1
dde-desktop:
  已安装：4.7.1.1-1
【预置条件】

【测试步骤】
1.在任务栏上右键之后，快速的在桌面的空白处右键。
2.多次重复上面的操作
【预期结果】
1.不会出现后面一个菜单出来，前面一个菜单还没消失的现象。
【测试结果】
1.很容易出现后面的菜单出来之后，前面一个菜单还没消失的现象。
【问题级别】
提示
【出现概率】
大概率复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181115144418](https://user-images.githubusercontent.com/14539782/48535047-f5461b00-e8e4-11e8-8e8a-0ba732527e4f.png)

**Comment by zccrs** [comment]
试了半天没试出来

**Comment by liuwen123** [comment]
暂无法复现
