### ISSUE TITLE
控制中心无法换grub壁纸

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#426]

**Comment by justforlxz** [comment]
@wangjia12  说不要这个功能了

**Comment by wangjia12** [comment]
> 原来是有 grub 主题，所以想着不要图片设置了，后面不是不做主题了么……这个应该是忘记更改回来了

不是忘记做回来了，是 @shule1987 觉得用户自己换了壁纸但是又用这个主题会很难看，失去了主题的意义。

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/448
