### ISSUE TITLE
deepin 应用支持最近文件协议

### ISSUE THREAD

**Issue by rekols** [linuxdeepin/internal-discussion#429]
DtkCore 新增了一个 DRecentManager 工具类，可以方便添加到最近文件列表。

- [x] 深度看图
- [x] 深度编辑器
- [x] 深度字体安装器
- [x] 深度软件包管理器
- [x] 深度音乐
- [x] 深度影院

**Comment by rekols** [comment]
@wangjia12  @hualet  @zccrs 看看还有哪些需要支持的。

**Comment by hualet** [comment]
像 chrome 和 wps 会处理这个么？

**Comment by zccrs** [comment]
@rekols 文档写的不够严禁，removeItem(s) 这个接口需要的是一个url，不仅仅是文件路径

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-movie-reborn/+/39822/
https://cr.deepin.io/#/c/deepin-music/+/39823/

**Comment by hualet** [comment]
@rekols   @Iceyer 问你为啥不在 DApplication 搞事情 :joy:

**Comment by rekols** [comment]
@zccrs 说在 dtkcore 加  (

**Comment by liuwen123** [comment]
已修复
