### ISSUE TITLE
chrome无法打开mailto协议的url

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#43]
firefox没有问题。
论坛用户反馈：https://bbs.deepin.org/forum.php?mod=viewthread&tid=170339&page=1#pid529234

**Comment by zccrs** [comment]
@felixonmars arch的dde环境下有问题吗？

**Comment by felixonmars** [comment]
@zccrs 在我的 Arch DDE 环境里 Chrome 直接打开了 Gmail 撰写邮件界面，Firefox 打开了默认邮件客户端。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
