### ISSUE TITLE
从第一标签窗口复制一个文件到第二标签窗口后,  返回到第一标签窗口下时, 被选中的文件失去了焦距.<周五>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#431]
也就是没有文件被选中了

https://bbs.deepin.org/forum.php?mod=viewthread&tid=171130&extra= 

第三条

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41317/

**Comment by liuwen123** [comment]
已修复
