### ISSUE TITLE
在“推荐应用”列表中将wps设置为默认应用时不生效

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#432]
1. 设置 doc 文件默认关联到 deepin-editor
2. 从 “推荐应用” 列表中选中 wps 并勾选设为默认

结果未生效，从 “其它应用” 列表中勾选wps并设置为默认时可以生效。

论坛反馈问题：https://bbs.deepin.org/forum.php?mod=viewthread&tid=144048&extra=

**Comment by BLumia** [comment]
追了一下，并非所有“推荐应用”列表中的都不生效，是别的 bug 。

https://cr.deepin.io/#/c/dde/dde-file-manager/+/39835/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
