### ISSUE TITLE
智能镜像源

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#433]

**Comment by wangjia12** [comment]
控制中心增加调节智能镜像源的入口；
默认使用智能镜像源；
可以选择手动选择源，手动选择后使用当前选择的源；

**Comment by shule1987** [comment]
![2](https://user-images.githubusercontent.com/5448609/48753665-d1f6e380-ecc9-11e8-9d14-40d574fd96c2.png)
![Uploading 详细设置－更新设置.png…]()

**Comment by wangjia12** [comment]
@shule1987 第二张图我们都打不开呀

**Comment by shule1987** [comment]
![2](https://user-images.githubusercontent.com/5448609/48823455-dd1a4400-ed9b-11e8-906d-29b04fbff848.png)
![default](https://user-images.githubusercontent.com/5448609/48823456-ddb2da80-ed9b-11e8-8353-b7401b08367c.png)

**Comment by zccrs** [comment]
@shule1987 内测通道的不是没了吗

**Comment by wangjia12** [comment]
文案：
【智能镜像源】
【开启智能镜像源会自动匹配响应最快的镜像源】
@zhuxiujuancindy

**Comment by wangjia12** [comment]
> @shule1987 内测通道的不是没了吗

是没了，这张图重点不是这个啦

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39925/

**Comment by justforlxz** [comment]
#50  重复任务
