### ISSUE TITLE
系统有更新时，控制中心不会显示更新详情

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#434]
【测试环境】
deepin 15.8
【预置条件】
系统存在更新，但并未更新

【测试步骤】
打开控制中心，进入更新模块

【预期结果】
当系统存在更新时，应显示更新详情。例如深度商店有更新，要简要说明更新了哪些特性，修复了哪些问题。例如提示有新的系统补丁，应该说明有哪些补丁，更新了什么，或者修复了哪些问题。

【测试结果】
当系统存在更新是，只显示深度商店的版本和系统补丁

【问题级别】
对用户来说，虽然知道我们有更新，但根本不知道我们究竟更新了什么。

【出现概率】
100%

@wangjia12 @zhuxiujuancindy @deepinzhangshuang

**Comment by zhuxiujuancindy** [comment]
已创建应用，填写了日志
