### ISSUE TITLE
dock刚启动时最右边的图标显示不完全

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#435]

**Comment by listenerri** [comment]
![default](https://user-images.githubusercontent.com/7995379/48699249-f8624380-ec23-11e8-83f2-a4efe7a845af.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39839

**Comment by listenerri** [comment]
原因是小企鹅输入法在刚开机的时候迅速地刷了两次图标, 导致dock大小没有及时更新:

复现步骤: 杀掉小企鹅输入法, `killall fcitx`

**Comment by liuwen123** [comment]
+1

**Comment by listenerri** [comment]
还是会出现, 再次修复:
https://cr.deepin.io/c/dde/dde-dock/+/39985

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
