### ISSUE TITLE
文件管理器目录右侧小三角点击行为

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#436]
本地磁盘点击为“弹出”
外接磁盘点击为“卸载并弹出”
文案：【卸载并弹出】
@zhuxiujuancindy 麻烦翻译一下
@BLumia

**Comment by zhuxiujuancindy** [comment]
文案：【卸载并弹出】【Unmount and Reject】

**Comment by BLumia** [comment]
这里仍然有点问题，因为一个外部设备仍然有可能有多个分区，这时会显示多个挂载，这时候的行为需要确定一下。另外，对于托盘挂载插件也应当确认一下。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39995/

**Comment by liuwen123** [comment]
已修复
