### ISSUE TITLE
系统登录时有很大概率界面会卡住

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#437]
【前置条件】
deepin-wm：1.9.33-1

【测试步骤】
注销系统，然后输入密码进行登录

【预期结果】
登录正常

【测试结果】
系统登录时，有很大概率会被卡住，桌面和dock图标都无法点击

【出现概率】
大概率

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
