### ISSUE TITLE
双击任务栏无线热点"deepin",打开控制中心-网络设置页面之后，控制中心不能主动隐藏。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#44]
【测试环境】
dde-dock:
  已安装：4.7.4-2
dde-control-center:
  已安装：4.7.1-2
【预置条件】
测试环境中存在EAP加密的热点deepin
【测试步骤】
1.任务栏点击无线插件，打开无线SSID列表，双击“deepin”热点。
2.单击桌面上空白的地方，查看控制中心能否隐藏。
【预期结果】
1. 打开控制中心-网络设置-无线网络-deepin热点设置界面。
2.控制中心能够隐藏。
【测试结果】
1.控制中心不能主动隐藏
【问题级别】
一般
【出现概率】
稳定出现

**Comment by listenerri** [comment]
无法复现

**Comment by listenerri** [comment]
应该是后端崩溃导致的，已经修过了，回归测试吧

**Comment by zhaofangfangdeepin** [comment]
测试通过
