### ISSUE TITLE
desktop文件添加GenericName字段

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#441]
在所有DDE应用中添加此字段的支持，基本规则为：原Name字段去除“Deepin”前缀，且添加 X-Deepin-Vendor=deepin 字段用于辨别是否为DDE应用。
如dde-calendar需要添加：

````
GenericName=Calendar
X-Deepin-Vendor=deepin
````

在“启动器”、“文件管理器”、“桌面”和“dock”等应用中对于DDE应用则显示其 GenericName。

**Comment by zccrs** [comment]
根据 https://github.com/linuxdeepin/internal-discussion/issues/442，大家把各自负责的项目更新一下 desktop文件，另外还需要更新deksotp文件对应的翻译

**Comment by BLumia** [comment]
- [ ] dde-file-manager [gerrit](https://cr.deepin.io/#/c/dde/dde-file-manager/+/39959/)
 - [ ] deepin-terminal
 - [ ] deepin-image-viewer
 - [ ] deepin-music
 - [ ] deepin-movie

**Comment by liuwen123** [comment]
系统预装所有软件都已经去掉深度
