### ISSUE TITLE
自动探测 grub 最佳分辨率功能 <z3>

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#449]
实现原理：

## grub 模块
编写一个 grub 模块化， 将 grub 正在使用的视频适配器的所有分辨率列表和当前使用的分辨率信息通过linux内核参数，传递个 linux 系统。

内存参数名为 DEEPIN_GFXMODE, 格式 ',' 逗号分割的字段列表，第一字段为正在使用分辨率的索引，其余字段为分辨率列表，比如 `DEEPIN_GFXMODE=1,1024x768,1366x768,800x600,640x480` ，正在使用的分辨率为1366x768。

通过增加配置文件 /etc/default/grub.d/10_deepin.cfg 来保证 GRUB_CMDLINE_LINUX_DEFAULT 始终可以带上 DEEPIN_GFXMODE=\$DEEPIN_GFXMODE"。

## sys-grub 功能
sys-grub 指 /usr/lib/deepin-daemon/grub2 这个程序。

PrepareGfxmodeDetect 方法
修改  /etc/default/grub ，把 主题关闭，设置 GRUB_GFXMODE 为一串可用的分辨率列表，按从高到低排序，然后更新 grub.cfg 文件。

启动之时，检查是否需要进行自动修正分辨率的后续步骤，如果需要，则立即以 grub 当前使用的分辨率写入配置文件 /etc/default/grub，再执行 `adjust-grub-theme` 调整主题，然后更新grub.cfg 文件。

## dde-daemon-session 的 grub-gfx 模块
运行此模块之后，会检查是否需要进行自动修正分辨率的后续步骤，如果需要，调起 sys-grub 然后结束。 如果不需要，则继续检查是否需要重新探测分辨率。

## 自动修正分辨率的步骤

1. 登录桌面环境，自动运行 dde-session-daemon，运行 grub-gfx 模块；
2. 调用 sys-grub 的 PrepareGfxmodeDetect  方法；
3. 等待用户重启电脑，grub 自动加载并执行 deepin_gfxmode 模块，将信息传递给 linux 系统。
4. 登录桌面环境，自动运行 dde-session-daemon，再次运行 grub-gfx 模块，调起 sys-grub ，等待 grub.cfg 更新完成。

注：
grub.cfg 文件指 /boot/grub/grub.cfg 文件

**Comment by hualet** [comment]
突然还想到一点，如果用户在第一次弹出对话框的时候不小心点了否，如何方便地手动探测和修复呢？

**Comment by electricface** [comment]
这个需要在控制中心 启动菜单加一个按钮。

**Comment by hualet** [comment]
> 这个需要在控制中心 启动菜单加一个按钮。

这是个高级功能，应该没有什么太大的必要放到控制中心的界面中，我觉得只需要一个可执行程序，用户需要的话执行一下就行了。

**Comment by zccrs** [comment]
> > 这个需要在控制中心 启动菜单加一个按钮。
> 
> 这是个高级功能，应该没有什么太大的必要放到控制中心的界面中，我觉得只需要一个可执行程序，用户需要的话执行一下就行了。

主要是用户怎么知道这个隐藏的入口呀

**Comment by zccrs** [comment]
@hualet @electricface 我觉得最好在对话框上加一个复选框，如果用户勾选了下次就不提示了，默认不勾选

**Comment by zccrs** [comment]
@electricface 不谈对话框询问，检查到有问题之后自动帮用户更新。cc @wangjia12 @shule1987

**Comment by electricface** [comment]
> > 这个需要在控制中心 启动菜单加一个按钮。
> 
> 这是个高级功能，应该没有什么太大的必要放到控制中心的界面中，我觉得只需要一个可执行程序，用户需要的话执行一下就行了。

执行命令 `/usr/lib/deepin-daemon/grub -prepare-gfxmode-detect`，然后重启电脑。

**Comment by wangjia12** [comment]
需求背景：
15.8更换主题之后，对不同分辨率适配的不好。
需求说明：
启动菜单主题自动探测最佳分辨率，保证在不同分辨率下背景图片、文字显示位置正常。
备注：由于技术实现原因，安装系统后第一次进入系统时启动菜单是默认背景，第二次进入系统才能显示正常。

**Comment by electricface** [comment]
**测试方法**

增加源
```
deb http://pools.corp.deepin.com/ppa/dde experimental main
```
然后在控制中心升级，应该会弹出grub升级的配置对话框。

安装这三个提交：
dde-daemon: https://cr.deepin.io/#/c/dde/dde-daemon/+/39880/
dde-api: https://cr.deepin.io/#/c/dde/dde-api/+/39987/
deepin-desktop-schemas: https://cr.deepin.io/#/c/deepin-desktop-schemas/+/39869/

重启电脑，进入 grub 菜单，主题是 deepin-fallback 主题，就是之前的grub主题换上了最新的背景。

再次登录桌面环境
通过 ps aux|grep grub 看是否有 grub-mkconfig 进程判断是否更新完成。

重启电脑，进入 grub 菜单，主题是 deepin 主题，有模糊透明特效的。

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
