### ISSUE TITLE
控制中心声音的高级设置中，显示的声音端口不对

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#45]
【测试环境】
dde-daemon:
  已安装：3.3.0-1
  候选： 3.3.0-1
【预置条件】

【测试步骤】
1.打开控制中心-声音-高级设置。查看声音端口列表
【预期结果】
1.端口列表显示正确。
【测试结果】
1.列表显示不正确 。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181030134232](https://user-images.githubusercontent.com/14539782/47698274-aabc7180-dc49-11e8-985e-340bb5d434bc.png)

**Comment by electricface** [comment]
已经修正 https://cr.deepin.io/#/c/dde/dde-daemon/+/39315

**Comment by zhaofangfangdeepin** [comment]
测试通过
