### ISSUE TITLE
session ui重构测试

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#450]
测试项

- [x] 登录
- [x] 锁屏
- [x] 多用户切换
- [x] 多会话切换
- [x] 用户键盘布局
- [x] 启动速度
- [x] 多屏
- [x] 高分屏

**Comment by liuwen123** [comment]
- [ ] 锁屏后点击关机按钮弹出关机界面，点击重启按钮后移动鼠标，输入密码框会消失
- [ ] 在注销界面，点击桌面按钮弹出桌面选择界面后，按ESC无法取消
- [ ] 在注销界面，点击用户按钮弹出用户选择界面，一直按←或→，无法循环选中

**Comment by mmxzmmxz** [comment]
- [ ] 锁屏界面切换用户时，出现选项lightdm

- [ ] 切换用户时，未登录用户，点击键盘图标，没有显示所有的键盘布局

- [ ] 切换用户时，双屏环境，用户名没有居中显示

**Comment by mmxzmmxz** [comment]
上面新建选项已经重新添加issues
https://github.com/linuxdeepin/internal-discussion/issues/596

**Comment by liuwen123** [comment]
已修复
