### ISSUE TITLE
文件管理设置权限时能够递归

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#451]
在进行权限变更时，通常不会针对文件夹，而是针对文件夹中的文件。在文件管理器设置权限时（属性-权限管理），只能设置单个文件的权限，不能对文件夹中的文件进行递归设置。可以在权利管理中添加“应用到包含项目”之类的选项，帮助设置文件夹中所有文件的权限。
@wangjia12

**Comment by wangjia12** [comment]
文件夹内的文件类型不同不能一起改，权限是针对每种不同文件是不同的设置项。暂时不改。
