### ISSUE TITLE
鼠标中键打开新窗口时也要显示启动动画

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#452]
鼠标中键可以打开应用的新窗口，这个时候没有动画反馈。实际上也需要有启动动画。
@zccrs 

https://github.com/linuxdeepin/developer-center/issues/629

**Comment by listenerri** [comment]
如果当前应用没有任何已打开窗口时, 使用鼠标中键打开应用显示左右摇摆特效:
https://cr.deepin.io/c/dde/dde-dock/+/40182

**Comment by liuwen123** [comment]
已修复
