### ISSUE TITLE
文件管理器列表模式跟随窗口大小改变宽度的规则 <4>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#454]
当列宽无任何调整时，扩大/缩小窗口都优先处理文件名那一列；
如果手动调节列宽，无论是拉大还是缩小，都优先改变最后一列到右边边线的距离；
最右侧宽度变成最小大小时，优先压文件名，如果文件名也达到最小宽度时，出现横向滚动条；
文件名称最小宽度170px，最大宽度不限；
其他列的最小宽度为实际需要的宽度-40px，最大宽度为实际需要的宽度+20px

**Comment by zccrs** [comment]
@BLumia 这是文件管理器中一个比较大的功能，可以早一些开始做

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40243/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
