### ISSUE TITLE
增加对appimage文件特殊处理

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#456]
当打开appimage文件时，如果它没有可执行权限，且当前进程有权限为其添加可执行权限时，弹出对话框提示用户是否要添加可执行权限并执行。

**Comment by wangjia12** [comment]
需要文案的时候@ 我

**Comment by zccrs** [comment]
@wangjia12 @shule1987 这个可以给文案和设计图了

**Comment by wangjia12** [comment]
文案：
【此文件没有执行权限，是否添加可执行权限并执行操作？】
【取消】
【添加】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【此文件没有执行权限，是否添加可执行权限并执行操作？】
【This file is not executable, do you want to add the execute permission and perform? 】
【取消】【Cancel】
【添加】【Add】

**Comment by zccrs** [comment]
感觉可以这样：“此文件没有可执行权限，是否添加权限并运行？”
下面的按钮用 “取消”和“运行” @wangjia12

**Comment by zhuxiujuancindy** [comment]
> 缺失可执行权限这个翻译（该文件是不可执行的）感觉怪怪的.. 是不是把 is not executable 改成 requires executable permission to run 之类的会稍好点？

这样会和后半句的英文重复，is not executable 没问题吧

**Comment by BLumia** [comment]
> is not executable 没问题吧

文件本身是可以运行的，只是在当前文件系统中这个文件缺了可执行标志。

前面如果调整了的话后面应该改成 want to add it 吧。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40144/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复

**Comment by probonopd** [comment]
这不应该是`AppImage`特定的，对于任何类型的`ELF`文件都应该是相同的。

**Comment by BLumia** [comment]
> 非常感谢您实现这个非常有用的特性。
> 这不应该是AppImage特定的，对于任何类型的ELF文件都应该是相同的。

@wangjia12 考虑一下？

btw, sorry about i wrote the wrong commit msg which should be AppImage rather than flatpak :joy:
