### ISSUE TITLE
任务栏声音的右键菜单没有翻译

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#46]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】

【测试步骤】
1.在任务栏的插件如声音插件上右键。查看右键菜单。
【预期结果】
1.右键菜单显示“静音”“声音设置”两个菜单
【测试结果】
1.这俩菜单没有翻译
【问题级别】
提示
【出现概率】
稳定复现
![_ _20181102111045](https://user-images.githubusercontent.com/12492745/47891874-fceed400-de8f-11e8-905c-2154115d5a95.png)
![_ _20181102111050](https://user-images.githubusercontent.com/12492745/47891875-fceed400-de8f-11e8-8625-863ed7e079aa.png)

**Comment by listenerri** [comment]
新tag测试吧
