### ISSUE TITLE
Launcher 的 mini 模式所有文字跟随系统字体大小设置变化

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#460]
现在应用名称应该是跟随字体变化的，但是右边的文字很多是没有变化的。

**Comment by justforlxz** [comment]
打算改成相对于系统当前的字号来变化，而且不能小于14px，比如系统当前是13，就设置为14，系统是14，就设置为15.但是设置的值不能小于14px。
现在qss里是写了固定的14px。

**Comment by hualet** [comment]
这个你可以简单调一下效果给 @shule1987 看一下，作为临时方案。

系统级别的字体调整一直是个头大的事情，这个已经有一个初步方案了，等再做得具体一点就开始推一下。 cc @zccrs @shule1987

**Comment by hualet** [comment]
这个还没有做吧？

**Comment by justforlxz** [comment]
还没有，可以开始做了

**Comment by justforlxz** [comment]
已经做了，在4.6.1中验证

**Comment by liuwen123** [comment]
已修复
