### ISSUE TITLE
网络图标状态显示和错误提示

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#461]
总结集中常见的网络错误状态，表现到图标上，且在tooltip加上说明性提示

例如：
* 没有插网线
* 没有分配到ip地址

**Comment by wangjia12** [comment]
@zccrs 先总结出一份现有能归纳的错误，我出文案
@shule1987 设计图

**Comment by listenerri** [comment]
@wangjia12
目前我统计出了以下状态:

- 设备已禁用
- 未插入网线
- 未连接网络
- 正在连接
- 正在认证
- 正在获取ip地址
- 获取ip地址失败
- 已连接网络但无法访问互联网
- 已连接网络

**Comment by wangjia12** [comment]
需求说明：

1. 当网络有问题时，在dock的图标上显示错误图标状态（已经实现）；
2. hover到错误图标时，显示错误提示信息；
3. 当无线网络/有线网络连接正常时，显示正常的图标，tooltip显示“已连接网络”；
4. 当前无线网络/有线网络正在连接状态，显示跳动图标，tooltip显示“正在连接”“正在认证”“正在获取ip地址”；
5. 当前无线网络/有线网络连接出错，显示感叹号图标，tooltip显示“设备已禁用”“获取ip地址失败”“已连接网络但无法访问互联网”。有线网络多一种状态“未插入网线”；
6. 当前无线网络/有线网络环境正常，但是没有连接网络时，显示“未插入网线”；
7. 错误提示信息目前整理出这几种，后面持续收集并添加；

**Comment by wangjia12** [comment]
【设备已禁用】
【未插入网线】
【未连接网络】
【正在连接】
【正在认证】
【正在获取ip地址】
【获取ip地址失败】
【已连接网络但无法访问互联网】
【已连接网络】
@zhuxiujuancindy 有些应该是以前就有的

**Comment by listenerri** [comment]
@wangjia12 

我提出的那些状态都是我自己描述的, 所以上面那些文案以前可能并没有, 也可能跟以前的会不同, 比如 "设备已禁用" 以前没有, 或者说大多数都没有. 
另外 "未连接网络" 之前的hover文案可能是 "无网络访问".

需要考虑下是否修改旧文案?

**Comment by zhuxiujuancindy** [comment]
文案：
【设备已禁用】【Device was disabled】
【未插入网线】【Network cable unplugged】
【未连接网络】【Network disconnected】
【正在连接】【Connecting】
【正在认证】【Authenticating】
【正在获取IP地址】【Obtaining IP address】
【获取IP地址失败】【Failed to obtain IP address】
【已连接网络但无法访问互联网】【Connected but not Internet access】
【已连接网络】【Network connected】

**Comment by wangjia12** [comment]
@zhuxiujuancindy 上面的文案我改了一些，麻烦跟着更新一下。
@shule1987 把对应的图标贴一下吧

**Comment by zhuxiujuancindy** [comment]
文案更新：
【设备已禁用】【Device disabled】
【未插入网线】【Network cable unplugged】
【未连接】【Not connected】
【正在连接】【Connecting】
【正在认证】【Authenticating】
【正在获取IP地址】【Obtaining IP address】
【获取IP地址失败】【Failed to obtain IP address】
【已连接网络但无法访问互联网】【Connected but not Internet access】
@listenerri

**Comment by wangjia12** [comment]
@listenerri 我们看了一下以前的文案，还是把ip加上了

**Comment by shule1987** [comment]
<img width="657" alt="2018-11-29 2 03 25" src="https://user-images.githubusercontent.com/5448609/49202445-93ef7300-f3df-11e8-83bb-1922adc24555.png">

**Comment by listenerri** [comment]
@shule1987 目前缺少下面的图标
![default](https://user-images.githubusercontent.com/7995379/49203959-1fb7ce00-f3e5-11e8-9a70-cfb954e785b0.png)
![default](https://user-images.githubusercontent.com/7995379/49203972-30684400-f3e5-11e8-9bd6-e54b7a2c3feb.png)
![default](https://user-images.githubusercontent.com/7995379/49203981-3bbb6f80-f3e5-11e8-8732-1d855df39149.png)

**Comment by shule1987** [comment]
[trayicon.zip](https://github.com/linuxdeepin/internal-discussion/files/2627960/trayicon.zip)

**Comment by listenerri** [comment]
[trayicon2.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2631787/trayicon2.tar.gz)

**Comment by listenerri** [comment]
**dde-network-utils, libdframeworkdbus, deepin-icon-theme**
**上面这三个包需要更新到experimental最新**

https://cr.deepin.io/c/dde/dde-dock/+/40170

**Comment by liuwen123** [comment]
已修复
