### ISSUE TITLE
确认一下启动器的频率计算方式

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#466]

**Comment by liuwenhuan** [comment]
这个问题的结论是什么，当前实现没有问题? 能否描述一下排序规则？

**Comment by wangjia12** [comment]
> 这个问题的结论是什么，当前实现没有问题? 能否描述一下排序规则？

https://github.com/linuxdeepin/internal-discussion/issues/499
重复任务，所以这个关闭了。这个任务里有详情。
