### ISSUE TITLE
home为单独分区时查看磁盘信息

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#467]
home为单独分区时右键菜单增加一项“磁盘信息”，显示当前的信息，同系统盘一样；
其他磁盘的“属性”文案都改为“磁盘信息”；
文案：
【磁盘信息】
@zhuxiujuancindy @zccrs @BLumia

**Comment by zhuxiujuancindy** [comment]
文案：
【磁盘信息】
【Disk info】

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40052/

**Comment by liuwen123** [comment]
已添加
