### ISSUE TITLE
控制中心要把左侧的导航tooltip加回来

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#47]
【测试环境】

【预置条件】

【测试步骤】
滚动查看控制中心，鼠标移入左边图标上
【预期结果】
有tooltip显示模块名称。因为之前连带图标和tooltip一起都去掉了，后来只加回来了图标，没有tooltip用户反馈仅通过图标看不出来是什么意思。所以要加回来和以前一样就可以。
【测试结果】
没有
【问题级别】

【出现概率】

这个在需求文档里有，漏掉了没有完成。

**Comment by justforlxz** [comment]
已添加

**Comment by wangjia12** [comment]
@shule1987 这个效果看过了吗
