### ISSUE TITLE
控制中心增加统一的主题切换菜单

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#470]
控制中心增加统一的主题切换菜单，可以在深色和浅色模式切换，切换以后自动切换 GTK 主题、图标主题 和 各个深度应用的主题。

@shule1987 出一下设计图吧。

相关 issue:
https://github.com/linuxdeepin/dde-file-manager/issues/26

**Comment by wangjia12** [comment]
需求描述：
一键切换黑白主题

1. 控制中心增加一键切换黑白主题的入口；
2. 每个应用内主菜单改为一级菜单：主题，二级菜单：浅色主题、深色主题、跟随系统主题；
3. 应用内选择“跟随系统主题”的，在控制中心切换后当前应用一键随之生效；
4. 应用内选择“深色主题”、“浅色主题”的，不跟随系统一键选择生效；

@shule1987 加一下图吧

**Comment by shule1987** [comment]
> 需求描述：
> 一键切换黑白主题
> 
> 1. 控制中心增加一键切换黑白主题的入口；
> 2. 每个应用内主菜单改为一级菜单：主题，二级菜单：浅色主题、深色主题、跟随系统主题；
> 3. 应用内选择“跟随系统主题”的，在控制中心切换后当前应用一键随之生效；
> 4. 应用内选择“深色主题”、“浅色主题”的，不跟随系统一键选择生效；
> 
> @shule1987 加一下图吧

![default](https://user-images.githubusercontent.com/5448609/49063791-768d9e00-f253-11e8-939b-775a81e1b9d7.png)

有几点说明一下
开启深色模式, 所有dtk应用切到深色主题, gtk窗口主题自动切到deepin-dark,图标主题自动切到deepin-dark, 用户依然可以单独将窗口主题和图标主题切到别的

**Comment by wangjia12** [comment]
文案：
【深色主题】
@zhuxiujuancindy 这以前有。。。。

**Comment by zhuxiujuancindy** [comment]
文案：
【深色主题】【Dark Theme】

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=160

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
