### ISSUE TITLE
深度编辑器设置字体的combobox支持预览字体

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#471]
类似控制中心设置字体那种。

@rekols

**Comment by zccrs** [comment]
@wangjia12 你看要不要专门加到需求里？

**Comment by CallMeR** [comment]
@hualet  目前获得的反馈就是深度编辑器的字体列表是用接口拿到的数据，本身的实现在DTK中。若需要实现这个功能，需要对DTK进行修改。然后测试了深度终端中的字体设置部分，同样是没有预览的。所以这两个需求要执行的话，可以考虑合并在一起。

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40448/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
