### ISSUE TITLE
滚动更新内容总结

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#473]
请不要在这个 issue 中发布系统发布不相关的回复，不相关的回复会被删掉。

**Comment by zccrs** [comment]
15.9 第一阶段第一次更新内容：
* 所有Deepin应用在启动器、桌面、dock、文件管理器中的显示名称都去除“深度”二字（英文名称去除Deepin）
* 启动菜单再次支持拖拽更换壁纸
* 透明度调节去除数字显示
* 文件管理器支持gif动态图预览
* dock 优化时尚模式托盘区域展开和收缩动画
* 文件管理器列表模式不再显示文件夹大小（使用 "-" 代替）
* 深度看图上一张/下一张根据文件名排序

**Comment by zccrs** [comment]
github的代码同步插件出问题了。这次的更新内容我先手动贴出来

topic: 15.8.1-1
    
    dtkcore:
    * 修复Qt 5.6上编译失败
    * 增加 DRecentManager 类，用于管理最近访问文件
    
    deepin-clone:
    * 在Deepin系统上移除应用名称里的“深度”二字
    
    dde-calendar:
    * 在dde下显示为日历
    
    go-lib:
    * 支持 desktop 文件的 X-Deepin-Vendor 字段
    
    dde-api:
    * 修正 dde-open 崩溃
    * 修正 adjust-grub-theme 设置背景图片失败
    
    dde-daemon:
    * 修正不适当的错误打印
    * 把手指长按当做鼠标右键点击
    * 修正恢复镜像源之后没有执行apt update
    
    lastore-daemon:
    * 修正用 go 1.7 编译失败问题
    * 修正耗费商店api流量巨大问题
    
    dde-dock:
    * 优化dock大小变化时的动画
    * 优化触摸相关操作
    * 新增时尚模式托盘收起和展开的动画
    * 修复时间插件禁用状态重启后无效
    * 修复拖拽时尚模式托盘时托盘依然显示
    
    go-dbus-factory:
    * 更新 com.deepin.daemon.Daemon 接口
    
    go-x11-client:
    * 修正错误解析Setup结构
    
    deepin-system-monitor:
    * 更新显示名称
    
    deepin-desktop-schemas:
    * 增加触控屏设置
    * 增加deepin-editor到启动器应用列表
    
    deepin-screen-recorder:
    * 更新显示名称
    
    deepin-picker:
    * 更新显示名称
    
    startdde:
    * 修正配置文件中 allow_switch 字段的意义
    * 修正缩放比为1.5 时，gtk 窗口上鼠标光标大小错误问题。
    
    deepin-editor:
    * 更新显示名称
    
    deepin-screenshot:
    * 在dde下显示为截图
    
    deepin-font-installer:
    * 更新显示名称
    
    deepin-calculator:
    * 更新显示名称
    
    deepin-voice-recorder:
    * 更新显示名称
    
    deepin-deb-installer:
    * 更新desktop文件
    
    deepin-graphics-driver-manager:
    * 修复单n卡切换默认驱动失败
    * 新增暗色主题
    * 更新desktop文件
    
    deepin-movie-reborn:
    * Deepin vendor 支持 #7c0e2088
    * 支持最近文件标准 #b278820e
    * 触屏拖动窗口支持 #e443a7b6
    
    deepin-repair-tools:
    * 更新desktop文件
    
    deepin-terminal:
    * Deepin Vendor 支持
    * debian stretch 构建支持（使用 vendor lib）

**Comment by deepinzhangshuang** [comment]
ppa/dde-panda unstable  更新测试　@zhaofangfangdeepin

**Comment by zhaofangfangdeepin** [comment]
控制中心显示的changelog 写了吗 @zccrs

**Comment by deepinzhangshuang** [comment]
https://rr.deepin.io/#/review/703　@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
> [https://rr.deepin.io/#/review/703　@zhuxiujuancindy](https://rr.deepin.io/#/review/703%E3%80%80@zhuxiujuancindy) 注意填写日志

都没@到我 还好我自己看到了

**Comment by zhuxiujuancindy** [comment]
@deepinzhangshuang

**Comment by deepinzhangshuang** [comment]
@zhuxiujuancindy  flatpka 应用没在rr任务里面。　也需要写changelog日志

**Comment by zhuxiujuancindy** [comment]
changelog填写完毕



[15.8+2 changelog.txt](https://github.com/linuxdeepin/internal-discussion/files/2623518/15.8%2B2.changelog.txt)

**Comment by jingle0927** [comment]
回来看看，你们都github上面玩耍了。。。

**Comment by deepinzhangshuang** [comment]
@zhuxiujuancindy  已经更新外网

**Comment by zhuxiujuancindy** [comment]
稍后发系统更新新闻

**Comment by zhuxiujuancindy** [comment]
https://www.deepin.org/2018/11/29/deepin-system-updates-2018-11-29/

**Comment by rekols** [comment]
@jingle0927 你 blog 挂了 (

**Comment by hualet** [comment]
改进省电模式 (laptop-mode-tools)

https://github.com/linuxdeepin/internal-discussion/issues/477

**Comment by justforlxz** [comment]
* 支持调整缩放系数到3x [1]
* 修复控制中心自动下载后提示没有更新为已下载
* 去掉不透明度的数值 [2]
* 分离电源设置为直流电和使用电池 [3]
* 更新grub界面的提示 [4]
* 系统补丁有两个 [5]

[1] https://github.com/linuxdeepin/developer-center/issues/612
[2] https://github.com/linuxdeepin/internal-discussion/issues/480
[3] https://github.com/linuxdeepin/internal-discussion/issues/3
[4] https://github.com/linuxdeepin/internal-discussion/issues/492
[5] https://github.com/linuxdeepin/internal-discussion/issues/481

**Comment by zccrs** [comment]
15.8.1-2完成的需求：
* 控制中心启动菜单模块更换壁纸时的文案改动
* 在dock图标上提示网络问题
* 控制中心电源模块将针对电池和插上电源的设置分开（以前设置是放到一起的）
* dock时尚模式：支持拖动移动托盘图标的位置
* Launcher更改计算应用使用频率的方式
* 深度看图打印图片增加预览
* 针对AppImage格式文件特殊处理

**Comment by deepinzhangshuang** [comment]
ppa/dde-panda unstable 更新测试 @liuwen123

**Comment by deepinzhangshuang** [comment]
https://rr.deepin.io/#/review/704 @zhuxiujuancindy  注意changelog编写

**Comment by zccrs** [comment]
dde-launcher:
    * 新增平均启动次数排序 [1]
    * 禁用Mini模式下滚动条的右键菜单
    
    [1] https://github.com/linuxdeepin/internal-discussion/issues/499
    
    dde-control-center:
    * 支持调整缩放系数到3x [1]
    * 修复控制中心自动下载后提示没有更新为已下载
    * 去掉不透明度的数值 [2]
    * 分离电源设置为直流电和使用电池 [3]
    * 更新grub界面的提示 [4]
    * 系统补丁有两个 [5]
    
    [1] https://github.com/linuxdeepin/developer-center/issues/612
    [2] https://github.com/linuxdeepin/internal-discussion/issues/480
    [3] https://github.com/linuxdeepin/internal-discussion/issues/3
    [4] https://github.com/linuxdeepin/internal-discussion/issues/492
    [5] https://github.com/linuxdeepin/internal-discussion/issues/481
    
    qt5dxcb-plugin:
    * 修复在低版本gcc上编译失败（专业版环境中的gcc）
    * 提供可以获取当前窗管管理器名称的接口
    * 修复 DForeignPlatformWindow 在版本大于 5.9.0 的 Qt 环境中获取到的窗口数据错误
    * 修复获取到的当前工作区窗口列表不包含一些特殊窗口（例如桌面）
    
    dde-file-manager:
    * 当试图运行没有可执行权限的 AppImage 文件时，询问是否添加可执行权限并运行
    * 文件名无法显示完整时保证扩展名可以被显示完整
    * 修复试图移除视图外的文件时可能导致崩溃的问题（对应 samba 中使用 shift 选中一定范围的文件，按删除会导致崩溃的 issue）
    * 托盘不再卸载应当被忽略的分区
    * 托盘在卸载可移动设备（并非弹出）时不再刷新列表
    * 修复托盘创建设备失败时可能导致崩溃的问题（对应空光盘崩溃的问题）
    * 完善俄语编码检测支持
    * 更改复制文件时计算速度的方式，对于可移除设备，直接从此设备本身IO数据中读取，避免由于内核的buffer导致速度显示的异常的高，且修复文件复制对话框在 99% 或者 100% 时卡很久都不会消失
    
    dtkwidget:
    * 修复DTabBar拖动标签移动位置时不跟手
    * 从GSettings中读取值设置给 QTapAndHoldGesture::timeout
    * 修复DDialog类型的窗口在按下Super+D后会被关闭
    * 增加获取当前窗口管理器名称的接口
    
    dde-daemon:
    * default-terminal 直接传递命令行选项
    * network 模块 修正 NetworkManager  服务重启后数据数据被清空而后不能恢复的问题
    * network 模块 增加 Connectivity 属性
    * 修正有线连接配置启用安全且密码选项设置为总是询问，连接后立即失败的问题
    * 修正从 launcher 卸载 CrossOver 失败的问题
    
    qt5integration:
    * 修复某些情况下给菜单设置背景透明没有生效(如果菜单在设置之前已经创建了对应的native窗口)
    * 菜单绘制图标前检查图标是否为空
    * 修复QImageReader读取svg图片时，第二次调用read接口返回的QImage对象为空
    
    dde-qt-dbus-factory:
    * 添加智能镜像源的接口
    * 更新网络连接的接口
    
    deepin-image-viewer:
    * 打印支持预览
    * 修复将大图片缩小打印时模糊
    
    dde-dock:
    * 新增支持拖拽时尚模式托盘内图标 https://github.com/linuxdeepin/internal-discussion/issues/2
    * 新增更详细的网络状态提示 https://github.com/linuxdeepin/internal-discussion/issues/461
    * 修复wine程序点击无反应 https://github.com/linuxdeepin/internal-discussion/issues/440
    * 修复专业版音量插件applet不消失 (专业版特有的问题,tower)
    * 修复使用鼠标中间打开dock上的程序时没有动效 https://github.com/linuxdeepin/internal-discussion/issues/452
    * 修复时尚模式插件图标间歇性无法点击 https://github.com/linuxdeepin/internal-discussion/issues/486
    * 修复时尚托盘收起展开的配置文件没有合并到统一的里面 https://github.com/linuxdeepin/internal-discussion/issues/469
    
    dde-network-utils:
    * 新增更详细的网络状态提示 https://github.com/linuxdeepin/internal-discussion/issues/461

**Comment by zhuxiujuancindy** [comment]
> https://rr.deepin.io/#/review/704 @zhuxiujuancindy 注意changelog编写

已填写

**Comment by deepinzhangshuang** [comment]
第一阶段已经更新外网

**Comment by deepinzhangshuang** [comment]
已经同步外网 @zhuxiujuancindy @21wmd

**Comment by zhuxiujuancindy** [comment]
已发新闻
https://www.deepin.org/2018/12/05/deepin-system-updates-2018-12-05/

**Comment by liuwen123** [comment]
15.8.2 重新新建一个任务，不然任务拖的太长了
