### ISSUE TITLE
文件管理器新建文件模板的 word 文档并非完全空白文档

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#476]
【测试环境】

```
dde-file-manager:
  已安装：4.7.1.3+r0+ga2b7cf57
```

【预置条件】

安装有文件管理器和任意能够编辑 word 文档的软件

【测试步骤】

 1. 通过深度文件管理器右键新建一个新的 word 文档
 2. 使用任意办公软件打开新创建的文档
 3. 查看属性

【预期结果】

内容均为空

【测试结果】

可以看到属性的标题部分带有以下段落：

``` plain
童年如一朵朵雪白的浪花，拍打着海边的礁石，发出欢快的笑声；童年如一颗颗明亮的小星星，照亮了大地，照亮了人们；童年如一个个琴键灵活的跳动，奏着优美的琴声；童年如一盏盏油灯，用来照亮我们的心灵……。是啊，童年在我们的成长中是必不可少的一段经历。
```

【问题级别】

-

【出现概率】

100%

【附加信息】

https://bbs.deepin.org/forum.php?mod=viewthread&tid=171425

解决方案是换一个真空白的 word 文档，但应当讨论以下是否继续包含新建 office 文件模板，我觉得分一个包并预装要合理一些，这样不需要这个特性的人（比如压根不使用 office 软件的人）可以卸载这个支持包。

永中看上去支持了 kde 风格的新建文件模板，如果用户使用永中也可能导致新建菜单中出现重复的项。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40078/

**Comment by liuwen123** [comment]
已修复
