### ISSUE TITLE
laptop-mode-tools 更新上游git版本

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#477]
主要是 LMT 针对 intel_pstate 的处理稍有问题，一个是针对 intel_psate 就不再设置 scaling governor，另外一个是针对 cpufreq  里面设置 scaling governor 默认是 ondemand 在 intel_pstate 下是无效的。

针对第一个问题，git 版本已经修复；
针对第二个问题，昨天我提交了 PR，但是还没有合并，我们可以先自己用着https://github.com/rickysarraf/laptop-mode-tools/pull/134

上游项目地址： https://github.com/rickysarraf/laptop-mode-tools

**Comment by deepinzhangshuang** [comment]
已经更新到dde experimental

**Comment by hualet** [comment]
不是特别对啊， /usr/share/laptop-mode-tools/modules/cpufreq 这个文件不是我改的样子

**Comment by zccrs** [comment]
@hualet 回复一下测试方式

**Comment by hualet** [comment]
安装一下 linux-cpupower 这个包，使用  

>  sudo cpupower frequency-info

命令分别看一下在进入节能模式和非节能模式下的输出，节能模式下 `current policy` 一行里面应该包含`powersave` ，非节能模式下应该是 `performance`。

另外，我们之前给 laptop-mode-tools 打的patch是禁用 runtime-pm 和 intel-sata-powermgmt 两个模块，一同确认一下，方式是

> sudo python /usr/share/laptop-mode-tools/lmt.py

打开以后检查 runtime-pm 和 intel-sata-powermgmt 是否关闭。

**Comment by liuwen123** [comment]
已修复
