### ISSUE TITLE
控制中心的透明图显示，可以和下面的做成一致吗？要么在左右两边有标示符

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#480]
【测试环境】
dde-control-center:
  已安装：4.7.7-2
【预置条件】

【测试步骤】
1.打开控制中心-个性化-透明度设置。查看透明度设置界面显示
【预期结果】
1.界面比较人性化，提示信息让人一眼就看明白。
【测试结果】
1.只有滑块和刻录。只有实际操作之后，才知道是从透明设置到不透明设置。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181126144920](https://user-images.githubusercontent.com/14539782/48997473-103d4880-f18b-11e8-84f2-ccd08231fa55.png)

**Comment by justforlxz** [comment]
给舒乐说了，等图中。

**Comment by zccrs** [comment]
@shule1987 图放任务里吧，可以跟踪一下

**Comment by shule1987** [comment]
[归档.zip](https://github.com/linuxdeepin/internal-discussion/files/2618543/default.zip)

**Comment by justforlxz** [comment]
已经支持

**Comment by liuwen123** [comment]
已修复
