### ISSUE TITLE
打开图片文件或者音频文件之后，最近使用目录没有相关文件记录

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#482]
【测试环境】
dde-file-manager:
  已安装：4.7.1.3-2
【预置条件】

【测试步骤】
1.截取图片之后，双击打开图片。查看文件管理器-最近使用目录是否存在相关记录。
2.录音之后，双击打开音频文件。查看文件管理器-最近使用目录是否存在相关记录。
【预期结果】
1.相关记录存在相关记录。
【测试结果】
1.最近使用目录没有相关的记录
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181126145646](https://user-images.githubusercontent.com/14539782/48999757-91e4a480-f192-11e8-93f2-40f30d967adf.gif)

**Comment by BLumia** [comment]
需要 flatpak 更新到支持最近文件的版本。 @deepinzhangshuang

**Comment by liuwen123** [comment]
已修复
