### ISSUE TITLE
flatpak打包的应用，名称中“深度”没有去掉

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#483]
【测试环境】
15.8.1
【预置条件】

【测试步骤】
1.升级之后，打开启动器，查看深度应用的名称，“深度”字符串是否都去掉
【预期结果】
1.flatpak的应用，名称中深度字符串没有被去掉。
【测试结果】
提示
【问题级别】
稳定复现。
【出现概率】

**Comment by deepinzhangshuang** [comment]
flatpak 已经更新一遍

**Comment by liuwen123** [comment]
flatpak已经更新，还有应用没有去掉，对应任务https://github.com/linuxdeepin/internal-discussion/issues/485
