### ISSUE TITLE
卸载U盘后，计算机界面U盘图标没消失

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#484]
【测试步骤】
打开文件管理器，进入计算机界面插入U盘，然后点击右键--卸载

【预期结果】
U盘卸载后，图标会自动消失

【测试结果】
U盘卸载后，图标没有消失

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40156/
workaround

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
