### ISSUE TITLE
依然有一些深度应用的名称中有深度字符串。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#485]
【测试环境】
15.8.1
【预置条件】

【测试步骤】
1.升级到15.8.1之后，打开启动器。输入“深度”。查看搜索出来的应用。
【预期结果】

【测试结果】
1.搜索出来的应用名称，依然没有修改。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181126161355](https://user-images.githubusercontent.com/14539782/49000989-47fdbd80-f196-11e8-9c5f-17e4984b1e77.png)

**Comment by justforlxz** [comment]
云打印和云扫描还没改，其他这些应该都是flatpak的吧  @deepinzhangshuang  @zccrs

**Comment by zccrs** [comment]
> 云打印和云扫描还没改，其他这些应该都是flatpak的吧 @deepinzhangshuang @zccrs

@Iceyer 云打印和云扫描的改一下吧

**Comment by liuwen123** [comment]
目前还有深度云打印、深度云扫描、深度用户反馈  没有改名
深度商店名称变成Store，还没有修复

**Comment by liuwen123** [comment]
已经修复
