### ISSUE TITLE
时尚模式任务栏-异常时间插件之后，点击关机图标，概率性出现不响应的现象。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#486]
【测试环境】
dde-dock:
  已安装：4.8.1-3
【预置条件】

【测试步骤】
1.任务栏设置为时尚模式，隐藏时间查看之后，点击关机按钮
【预期结果】

【测试结果】
1.概率性出现关机按钮不响应的问题。
【问题级别】
一般
【出现概率】
概率性出现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181126163147](https://user-images.githubusercontent.com/14539782/49002018-5b5e5800-f199-11e8-85b2-a99c602c1b04.gif)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40193

**Comment by liuwen123** [comment]
已修复
