### ISSUE TITLE
desktop文件显示内容改了之后，桌面快捷方式、任务栏的提示信息，关于信息都需要同步修改

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#487]
【测试环境】
15.8.1
【预置条件】

【测试步骤】
1.打开启动器，发送显卡驱动管理器到桌面和任务栏。
2.分别查看关于、桌面快捷方式，任务栏提示信息
【预期结果】

【测试结果】
1.桌面快捷方式，关于对话框，任务栏提示信息都没有同步改过来。
【问题级别】

【出现概率】

**Comment by zhaofangfangdeepin** [comment]
![_ _20181126164201](https://user-images.githubusercontent.com/14539782/49002711-4c78a500-f19b-11e8-97ea-3d78d33ca34d.png)
![_ _20181126164148](https://user-images.githubusercontent.com/14539782/49002714-4edaff00-f19b-11e8-8bbc-f5fd21760566.png)
![_ _20181126164137](https://user-images.githubusercontent.com/14539782/49002718-50a4c280-f19b-11e8-8ad1-d6bd3d500027.png)

**Comment by liuwen123** [comment]
右键--打开方式也需要修改
![_ _20181127090659](https://user-images.githubusercontent.com/12492745/49051687-dd935e80-f223-11e8-9d24-ec8b48bb1984.png)

**Comment by zhaofangfangdeepin** [comment]
![_ _20181127090811](https://user-images.githubusercontent.com/14539782/49051782-3a8f1480-f224-11e8-87c2-ba951c467c53.png)
通知信息里面

**Comment by zhaofangfangdeepin** [comment]
![_ _20181127091051](https://user-images.githubusercontent.com/14539782/49051811-5b576a00-f224-11e8-9efe-b9bdea5bf7a3.png)

**Comment by zccrs** [comment]
除了桌面和文件管理器相关的图有问题，其它的都是正常的。

**Comment by zhaofangfangdeepin** [comment]
还有默认程序设置里面的名称显示：
![_ _20181127100730](https://user-images.githubusercontent.com/14539782/49053733-51d20000-f22c-11e8-88b7-8c5f5bd34b31.png)

**Comment by zhaofangfangdeepin** [comment]
![_ _20181127104211](https://user-images.githubusercontent.com/14539782/49055021-21409500-f231-11e8-8a8d-a1d54cb88b47.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40084/

修复文件管理器属性和打开方式位置的显示问题

**Comment by liuwen123** [comment]
已修复
