### ISSUE TITLE
深度商店卸载应用列表没有及时刷新

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#489]
【测试环境】
deepin-appstore：5.1.2.5-1

【测试步骤】
打开深度商店任意安装五六个软件，等安装完成后，进入到卸载应用界面，卸载刚才安装的应用

【预期结果】
软件卸载完成后，当前列表会及时刷新

【测试结果】
软件卸载完成后，列表没有及时刷新

【问题级别】

【出现概率】

**Comment by hualet** [comment]
@myml 看一下？

**Comment by myml** [comment]
> @myml 看一下？

新版本中'卸载列表'已被'个人中心-本地应用'取代
