### ISSUE TITLE
任务栏插件的右键菜单被插件挡住，右键菜单不好操作

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#49]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】

【测试步骤】
1.在任务栏-插件上右键，查看右键菜单。
【预期结果】
1.右键菜单显示正常。
【测试结果】
1.右键菜单被插件挡住。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by listenerri** [comment]
系统插件不应该可以放到那个容器里，已经修复了，回归测试吧
