### ISSUE TITLE
dock daemon 提供接口检查docked app是否存在

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#490]
需要提供一个接口来检查app是否存在, app 的格式 DockedApps 列表里的格式一致.

即要有一个接口能够检查 DockedApps 中的每一项是否存在

@jouyouyun

**Comment by electricface** [comment]
增加方法 GetDockedAppsDesktopFiles
 https://cr.deepin.io/#/c/dde/dde-daemon/+/40081

**Comment by hualet** [comment]
为什么需要这么一个接口？

**Comment by electricface** [comment]
为了准确获取驻留应用的 desktop 文件路径。
