### ISSUE TITLE
深度商店上架的深度取色器只有flatpak版本

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#491]
【测试环境】

【预置条件】

【测试步骤】
1.打开深度商店，搜索深度取色器。
【预期结果】
1.只有flatpak 版本，没有deb版本
【测试结果】

【问题级别】

【出现概率】

**Comment by zhuxiujuancindy** [comment]
以前就只有flatpak的版本，要上deb版本吗？
@deepinzhangshuang

**Comment by zhuxiujuancindy** [comment]
已上架深度取色器 deb版
