### ISSUE TITLE
修改控制中心启动菜单的文案

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#492]
因为把启动菜单增加壁纸的功能加回来了，但是没有加文案。现在把文案也补回来。
找不到之前的文案了重新写一句。
【您可以点击菜单改变默认启动项，也可以拖拽图片到窗口改变背景图片。】（转行）
【开启主题后您可以在开机时看到主题背景。】
@zhuxiujuancindy @zccrs @justforlxz

**Comment by zhuxiujuancindy** [comment]
文案：
【您可以点击菜单改变默认启动项，也可以拖拽图片到窗口改变背景图片。】
【You can click the option in boot menu to set it as the first boot, and drag and drop a picture to replace the background.】
【开启主题后您可以在开机时看到主题背景。】
【Switch theme on to view it in boot menu.】

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/39926/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
