### ISSUE TITLE
deepin clone 文案修改

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#493]
中文：克隆或还原磁盘（分区）会格式化目标位置的所有数据，且过程中不可取消。
旧文案：All data in target loacation will be formated during cloning or restoring disk (partition) without cancelable operation.
改为
新文案：All data in the target disk (partition) will be formatted during cloning or restoring, which cannot be cancelled during the process.

**Comment by zhuxiujuancindy** [comment]
Backup partition data to a image file
改为
Backup partition data to an image file

**Comment by zhuxiujuancindy** [comment]
@zccrs 这个要处理下了

**Comment by zccrs** [comment]
@zhuxiujuancindy 翻译已更新

**Comment by zhuxiujuancindy** [comment]
transifex翻译完毕
