### ISSUE TITLE
弹出设备图标显示不正确<周三>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#495]
【测试步骤】
使用NTFS格式的U盘插入PC并挂载成功，然后向U盘拷贝文件，文件拷贝完成后点击弹出按钮

【预期结果】
弹出提示对话框，内容显示正确

【测试结果】
弹出提示对话框，图标显示不正确

【问题级别】

【出现概率】
![11](https://user-images.githubusercontent.com/12492745/49060668-7d171800-f249-11e8-8dab-15e2a2455d57.png)

**Comment by BLumia** [comment]
这个问题好像之前说过，是 DTK 的问题， DDialog 只使用给出的第一个可用大小作为 Icon 。

截图的地方是这里（也可以做最小化复现代码）：

``` c++
void DialogManager::showErrorDialog(const QString &title, const QString &message)
{
    DDialog d(title, message);

    d.setIcon(QIcon::fromTheme("dialog-error"));
    d.addButton(tr("Confirm"), true, DDialog::ButtonRecommend);
    d.setMaximumWidth(640);
    d.exec();
}
```

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40515/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
