### ISSUE TITLE
U盘挂载和卸载状态分不清

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#496]
【测试步骤】
文件管理器挂载U盘，然后在dock上选择挂载图标，点击右键--卸载全部

【预期结果】
U盘全部卸载，没有挂载图标显示

【测试结果】
U盘还是显示为挂载状态，但U盘实际上已经卸载完成

【问题级别】

【出现概率】
![121](https://user-images.githubusercontent.com/12492745/49061200-1266dc00-f24b-11e8-906c-f65ae69a641c.png)

**Comment by zccrs** [comment]
@BLumia dock 插件卸载的时候行为要和文件管理器保持一致，可移动设备是要弹出的

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/484
