### ISSUE TITLE
在Smb中批量删除文件会导致文件管理器崩溃

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#497]
【测试步骤】
使用文件管理器登录smb，进入一个文件较多的目录，然后任意选中一个文件后按Shift选中其他文件，再按Delete大批量删除文件

【预期结果】
文件正常删除

【测试结果】
按Shift批量删除文件时，会导致文件管理器崩溃

【问题级别】
严重

【出现概率】
大概率

**Comment by zccrs** [comment]
@BLumia 这个我记得你修过了吧

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40180/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
