### ISSUE TITLE
启动器使用频率

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#499]
需求背景：15.8及以前是按照使用总次数排序，导致很多新应用在近期使用频繁却没有办法排到前面去，现重新定义使用频率算法。

（备注：由于技术实现时间原因，现在的算法只能针对在launcher里启动的行为，无法针对dock和桌面启动的行为，但是理论上应该计算一个系统总的。）
@zccrs @justforlxz 
可以把我们刚说的那个权重方案贴一下

**Comment by zccrs** [comment]
@wangjia12 在原本只是按打开次数计数的基础上添加 “时间” 作为此计数的权重值。比如：第一次记录顺序时（第一次从launcher中启动某应用）将此时间阶段（具体时间阶段未定，可根据实际效果调整）的权重设置为 0.000001，且记录下此权重所对应的时间，在此时间段内打开的应用记录次数时的规则为：此应用新的已打开次数 O = 之前已记录的值 x + 1 x 0.000001。此后，每次更新配置文件时，需要先根据存储的时间已经现在的时间更新新的权重值，假如权重值每次增加 0.0000002，则新的权重值 = 旧的权重值 + (当前时间 - 旧的权重存储时间)  / 时间阶段(能肯定的是，权重值肯定是单调递增的，不过最好不要用线性递增)。

**Comment by iamhyc** [comment]
1. 这个浮点数0.000001有什么意义
2. 时间段怎么划分，有什么依据
3. 为什么不可以： 使用+1， 每天（或时间段）-1（减到0为止），数值相同不交换排序；感觉这个更直观

**Comment by iamhyc** [comment]
> 这个算法是可行的，只是0.000001这个系数可以根据实际需求调整。
> 同时，有一个问题，这个需求是否真的存在，对于用户来说，图标的位置可以说是习惯的一部分，如果图标经常变动，是不是会给用户的使用带来不便，导致用户难以找到图标的情况。
> 举个例子：比如一个顾客每天早晨在三号粥铺买早餐，可是因为顾客频繁地买早餐，店主不停地将位置靠近顾客，会不会导致顾客找不到粥铺。
> 如果需求确实存在，也应考虑变动的频率。

类似体验的实现，可以参考Windows文管的 快速访问 中文件的排序

**Comment by electricface** [comment]
dde-launcher 用 SQLite 保存点击应用的次数。

按天记录 每个应用的启动次数，设定启动次数最大值为10。
排序时获取 从当天到前 30 天的记录，利用这个区间的应用启动次数来排序。

**Comment by iamhyc** [comment]
ok，我觉得你们的开发，完全依赖内部讨论，可能没有开放评论的必要

**Comment by hualet** [comment]
> ok，我觉得你们的开发，完全依赖内部讨论，可能没有开放评论的必要

@zccrs @justforlxz 怎么说？

**Comment by justforlxz** [comment]
> ok，我觉得你们的开发，完全依赖内部讨论，可能没有开放评论的必要

先说声抱歉，并不是不采纳你们提出的建议，现在提出的方案中，只有平均启动次数是有最明确的实现方法，最开始提出的排序规则略复杂，权重的调整并不是两三天就能决定的。

这次修改这个排序只是为了避免新安装的程序在很多次启动后仍然不能出现在上方，所以算法并不是只有上面提出的那一个，如果当前的算法不满足预期，还会继续更换算法的。

**Comment by iamhyc** [comment]
> > ok，我觉得你们的开发，完全依赖内部讨论，可能没有开放评论的必要
> 
> @zccrs @justforlxz 怎么说？

因为你们这还是内部讨论，但内部交流的工具你们不止依赖Github，没有全部放在这里，所以背景和思路都不完整；但看见又让人想掺和……
所以你们是否可以考虑开放一些 设计/算法 的讨论在这里，和论坛话题区分一下，不会那么水；或者单独开一些issue征集PR都可以

**Comment by hualet** [comment]
> > > ok，我觉得你们的开发，完全依赖内部讨论，可能没有开放评论的必要
> > 
> > 
> > @zccrs @justforlxz 怎么说？
> 
> 因为你们这还是内部讨论，但内部交流的工具你们不止依赖Github，没有全部放在这里，所以背景和思路都不完整；但看见又让人想掺和……
> 所以你们是否可以考虑开放一些 设计/算法 的讨论在这里，和论坛话题区分一下，不会那么水；或者单独开一些issue征集PR都可以

我们需要在效率和透明上做一个平衡点，所以所有事情尽可能透明，但是有些情况文字讨论不清楚的肯定优先当面讨论，结果尽量公开说明，如果漏掉了，比如这次的情况，那么根据需要进行补充说明即可。我倒不认为这是一个特别大的问题。

征集 PR 以后会考虑 增加特殊的 label ，表示哪些社区用户想要，但是在内部优先级不算太高的需求。

**Comment by liuwen123** [comment]
+1
