### ISSUE TITLE
智能镜像源

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#50]
控制中心提供两种镜像源使用方式：

1. 智能镜像源
2. 自定义镜像源

使用智能镜像源以后，系统会在镜像源列表中根据实际访问速度和资源的存在情况等选择镜像源进行软件包下载和更新等操作；用户可以关闭智能镜像源、使用自定义镜像源，选择一个镜像源进行软件包下载和更新等操作。

考虑要做的事情：

- [x] lastore-daemon 修改，包含自动更新镜像源列表、smart-mirror 工具修改等

- [x] apt 的 patch 修改 ？

- [x] 控制中心前端修改，支持相关设置

**Comment by Iceyer** [comment]
@myml

**Comment by myml** [comment]
mark
