### ISSUE TITLE
掌压检测，最小压力值设置，滑块可以停留在中间的位置。<下周三>

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#500]
【测试环境】
dde-control-center:
  已安装：4.7.6.2-1
【预置条件】
笔记本
【测试步骤】
１．在笔记本上，打开控制中心－鼠标和触摸板－掌压检测。
２．调节掌压检测的最小压力值
【预期结果】

【测试结果】
１．滑块可以停留在中间位置
【问题级别】

【出现概率】

**Comment by liuwen123** [comment]
已修复
