### ISSUE TITLE
看图打印控件

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#503]
打印预览
需求背景：
看图的打印控件预览非常不好用，重写一个代价太大，编辑器的预览功能比看图强，所以调用编辑器的打印控件。
需求说明：
看图的打印窗口替换成编辑器的打印窗口；
@shule1987 需要一个设计图（加一个按钮）
@zccrs

**Comment by wangjia12** [comment]
按钮名称：
【图像设置】
@zhuxiujuancindy 翻译一下吧

**Comment by zhuxiujuancindy** [comment]
文案：
【图像设置】【Image Settings】

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/40127/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
