### ISSUE TITLE
深度影院标题栏有“深度影院”，其他应用标题栏没有，如看图，录音等，行为不统一，且与去掉深度标签二字冲突。

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#504]
@zccrs @wangjia12 @hualet

**Comment by wangjia12** [comment]
深度影院默认窗口没有播放影片时，不显示“深度影院”四个字。

**Comment by hualet** [comment]
> 深度影院默认窗口没有播放影片时，不显示“深度影院”四个字。

@deepinzhangshuang 的意思是不应该显示 “深度” 两个字吧？

**Comment by wangjia12** [comment]
> > 深度影院默认窗口没有播放影片时，不显示“深度影院”四个字。
> 
> @deepinzhangshuang 的意思是不应该显示 “深度” 两个字吧？

我们所有应用除了影院都没有在标题栏显示应用名称
另外，通用名字和普通名字现在本来就是不同地方有不同显示，比如在launcher、dock、桌面、默认程序显示通用名字，在其他系统、商店和提醒显示普通名字。为了减少一处的误解，可以不要显示这个有歧义的名字。

**Comment by zccrs** [comment]
@BLumia 影院后面还有一些需要你改的，可以借这个任务先熟悉下代码

**Comment by liuwen123** [comment]
已修复
