### ISSUE TITLE
应用代理设置，保存的用户名和密码是明文方式保存的。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#507]
【测试环境】

【预置条件】

【测试步骤】
1.打开控制中心-网络-应用代理。设置地址，端口，用户名和密码。
2.查看文件~/.config/deepin/proxychains.conf文件中保存的配置
【预期结果】
1.密码以加密方式存储。
【测试结果】
1.密码明文方式存储
【问题级别】
一般
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
@zccrs  @electricface  咋办，就算加密了，别人还是能看后端代码知道怎么解密的。

**Comment by electricface** [comment]
这是配置文件，配置文件要求用明文保存。

**Comment by hualet** [comment]
proxychains 的配置文件需要明文写吧，不用处理。
