### ISSUE TITLE
dock上磁盘弹出

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#508]
需求背景：
由于文件管理器的外接磁盘改了弹出、卸载逻辑，所以这里也要一并修改。
需求说明：
dock上的外接磁盘显示也是一样逻辑，点击图标后是卸载并弹出，在真正弹出之前小窗口不消失，但由于无法获取到已使用的大小，所以已使用大小显示“-”（即不显示内容）；
@zccrs

**Comment by liuwen123** [comment]
已修复
