### ISSUE TITLE
文件管理器地址栏第二次搜索输入字符时漏字

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#509]
【测试步骤】
打开文件管理器，在地址栏中输入：你好，然后进行搜索，搜索成功后取消搜索，再次在地址栏中输入：你，再输入好

【预期结果】
可以正常输入

【测试结果】
输入好字，好字的第一个字符输入的是字符，无法显示汉字

【问题级别】

【出现概率】

**Comment by liuwen123** [comment]
用搜狗输入法输入，第二个汉字第一个字符会显示字母
用ibus拼音输入法是正常的

**Comment by zccrs** [comment]
@hualet

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
