### ISSUE TITLE
控制中心里不能调启动菜单的主题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#51]
【测试环境】

【预置条件】

【测试步骤】
在控制中心里调启动菜单的主题

【预期结果】
可以看到默认装的green这个主题

【测试结果】
没有主题，和15.7没有变化，是不是没合进去

【问题级别】

【出现概率】

**Comment by zccrs** [comment]
15.8版本中前端没有主题可选
