### ISSUE TITLE
双屏深度录屏录制桌面，视频中没有任务栏

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#510]
【测试环境】
15.8，并在2018年11月29日更新
【预置条件】

【测试步骤】
1、打开深度录屏
2、录全屏 或者 录 docker 的区域
3、点击托盘图标展开和收缩
4、结束录屏
 
【预期结果】
播放录制的视频，能够在视频中看到托盘位置的变化。
【测试结果】
播放录制视频，视频中没有托盘图标。
【问题级别】

【出现概率】
100%

**Comment by 21wmd** [comment]
@deepinzhangshuang

**Comment by hualet** [comment]
试了 mp4 和 gif 都没有问题呀。

**Comment by 21wmd** [comment]
@hualet 我找到问题了，在双屏幕（扩展）模式下，我录制的主屏幕内容，可实际录制的是扩展屏的内容。

**Comment by zccrs** [comment]
@justforlxz 有时间时看一下

**Comment by hualet** [comment]
> @hualet 我找到问题了，在双屏幕（扩展）模式下，我录制的主屏幕内容，可实际录制的是扩展屏的内容。

录屏好像一直都不支持双屏。。。

**Comment by justforlxz** [comment]
双屏问题有时间再处理，截图也有类似的问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
