### ISSUE TITLE
托盘区域增加hover状态 <z5>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#514]
需求背景：
两种模式下，托盘区域都没有hover状态，鼠标移入看起来没有反应，提示性不强。
需求描述：
托盘区域增加hover状态。
@shule1987 
@zccrs

**Comment by shule1987** [comment]
<img width="587" alt="2018-12-03 8 46 34" src="https://user-images.githubusercontent.com/5448609/49347286-fa260f80-f6d7-11e8-9f05-69f70ff88697.png">

宽度24X24, 颜色rgba(255,255,255,0.1), 圆角6px

**Comment by listenerri** [comment]
时尚模式下托盘图标的hover颜色与控制按钮保持一致

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40328

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
