### ISSUE TITLE
控制中心 网络连接编辑 内部认证默认为空

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#515]
【测试环境】
dde-control-center 4.7.7+r3+g20e23b2d
【预置条件】
无
【测试步骤】

1. 新建有线连接，打开安全开关，隧道TLS，设置EAP认证为“隧道TLS”，设置身份为 test，设置密码为 test，保存。
2. 再次进入刚才创建的连接，修改EAP认证为“FAST”，观察内部认证的设置，点击保存按钮。

【预期结果】
内部认证不为空，点击保存按钮有反应。
【测试结果】
内部认证默认为空，点击保存按钮没反应。
【问题级别】
一般
【出现概率】
稳定重现

**Comment by zccrs** [comment]
@listenerri 这个可以给测试了吧

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
