### ISSUE TITLE
系统更新

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#519]
需求背景：
来自专业版的需求，希望可以有一种状态是不提示更新。
需求描述：

1. 增加“更新提醒”的状态开关；
2. 当“更新提醒”关闭时，“自动下载更新”关闭，并且不显示。此时，当有更新时，控制中心首页不显示更新提示；
3. 当“更新提醒”打开且“自动下载更新”关闭，此时，当有更新时，控制中心首页显示更新提示，进入更新页面时需要下载并更新；
4. 当“更新提醒”打开且“自动下载更新”打开，此时，当有更新时，控制中心首页显示更新提示，进入更新页面已自动下载完成只需要安装；

备注：3、4条和目前已经实现的一样即可。

![default](https://user-images.githubusercontent.com/34432879/49274805-74764a00-f4b4-11e8-9717-b3f13874b84f.png)
![2](https://user-images.githubusercontent.com/34432879/49274807-77713a80-f4b4-11e8-9014-0b7067da9259.png)

@zccrs @justforlxz @21wmd

**Comment by wangjia12** [comment]
文案：
【更新提醒】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【更新提醒】【Updates Notification】

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40315/

**Comment by liuwen123** [comment]
+1

**Comment by wangjia12** [comment]
补充需求：更新提醒默认状态为开启
