### ISSUE TITLE
高效模式下，把声音插件移动到托盘里再移出来，声音插件的右键菜单跑到任务栏的最左边。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#52]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
1.任务栏设置为高效模式。
【测试步骤】
1.高效模式下，把声音插件移动到托盘，再移动出来。
2.再声音插件上右键。查看右键菜单。
【预期结果】
1、右键菜单显示位置正确。
【测试结果】
1.右键菜单显示在任务栏的最左边。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by listenerri** [comment]
系统插件不应该可以放到那个容器里，内网已经修复了，回归测试吧

**Comment by zhaofangfangdeepin** [comment]
测试通过
