### ISSUE TITLE
登录时密码连续错误处理

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#521]
需求背景：
来自专业版需求，对于登录时多次密码输入错误的情况做保护处理。
需求说明：
登录时密码连续输入5次以上，三分钟内不允许再次输入密码；
三分钟解除后可以继续输入密码；
![default](https://user-images.githubusercontent.com/34432879/49276537-c8cff880-f4b9-11e8-9d9d-81e545b828e8.jpg)
@zccrs @21wmd 
文案：
【请3分钟后再试】
@zhuxiujuancindy 麻烦翻译一下

**Comment by wangjia12** [comment]
【请2分钟后再试】
【Please try again 2 minutes later】
【请1分钟后再试】
【Please try again 1 minute later】

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/40369/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已添加

**Comment by liuwen123** [comment]
已添加
