### ISSUE TITLE
设置修改启动菜单的密码

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#523]
需求背景：
来自专业版需求，在修改系统启动菜单参数时需要输入密码保证系统的安全。
需求说明：

1. 在安装器设置用户名密码时，增加“同时设置为修改启动菜单密码”，默认勾选；
2. 勾选上此项之后，当今后进入系统在启动菜单界面按“E”进入修改启动菜单界面时，需要输入密码；
3. 不勾选时同现在一样处理；

![5](https://user-images.githubusercontent.com/34432879/49278304-5235f980-f4bf-11e8-988c-f49186b2d5ef.png)
@21wmd @zccrs 
文案：
【同时设置为修改启动菜单密码】
@zhuxiujuancindy

**Comment by wangjia12** [comment]
@21wmd @CallMeR 再考虑一下这个需求吧
@zccrs 考虑好之前先不做

**Comment by zccrs** [comment]
@justforlxz 安装器按需求做，控制中心暂时不用考虑

**Comment by justforlxz** [comment]
专业版已添加
