### ISSUE TITLE
在dock上使用鼠标也会触发Gesture事件

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#524]
下面这些情况都会触发GestureEvent:
- 在dock上右键显示**dock的菜单**时
- 鼠标长按一个item(app或者plugin)
- 鼠标拖拽起一个item(app或者plugin)

**Comment by listenerri** [comment]
在item重载的mousePresseEvent里如果直接调用QWidget::mousePressEvent就会导致右键也触发Gesture的问题

**Comment by hualet** [comment]
Qt 里面的处理是有 QGesture 产生的时候再去找这个 QGesture 的 target，如果你的菜单显示的geometry刚好覆盖了你的鼠标，那么这个新产生的 QGesture 会被发送到菜单（这是我自己写得例子中的情况），但是假如你的菜单显示的位置刚好跟鼠标错开了那么一点点，那么 QGesture 会发送到鼠标下面的 widget (Dock遇到的情况）。

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/dde/dde-dock/+/40442 这样就不会有了

**Comment by listenerri** [comment]
备忘, 相关issue: #486 

修改 dock菜单 的显示位置, 让鼠标hover到菜单上的确可以解决右键问题, 不过拖拽item会触发Gesture事件的问题还没有解决

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
