### ISSUE TITLE
开机启动后WiFi会自动连接，但不知道连接的是哪个WiFi

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#525]
【测试步骤】
用笔记本连接多个WiFi成功后，进入控制中心网络，断开--连接WiFi
在连接的过程中查看dock上的WiFi列表

【预期结果】
可以显示正在连接的WiFi

【测试结果】
dock上的WiFi列表没有任何显示，直到连接成功后，才知道连接的是哪个WiFi
在控制中心也是一样的问题，只显示正在连接，连接的是哪一个，不知道

【问题级别】
一般

【出现概率】
100%
![_ _20181203105335](https://user-images.githubusercontent.com/12492745/49350570-6a3d9100-f6ea-11e8-986d-e02c81c93540.png)
![_ _20181203105343](https://user-images.githubusercontent.com/12492745/49350573-6c9feb00-f6ea-11e8-8a55-fd8e08ade823.png)
![_ _20181203105359](https://user-images.githubusercontent.com/12492745/49350577-6f9adb80-f6ea-11e8-9aa8-d247b856b1a8.png)

**Comment by listenerri** [comment]
libdde-network-utils 更新到最新

控制中心：
https://cr.deepin.io/c/dde/dde-control-center/+/41928
任务栏：
https://cr.deepin.io/c/dde/dde-dock/+/41927

**Comment by listenerri** [comment]
修复刚进入桌面时任务栏上的网络列表没有显示 indicator：
https://cr.deepin.io/c/dde/dde-dock/+/41953

**Comment by liuwen123** [comment]
已修复
