### ISSUE TITLE
安装器增加密码复杂度检查开关<周一>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#527]
能够在OEM中设置开启用户密码负责度，实现安装过程中，及在控制中心新增用户设置密码时，必须满足以下条件：

1、口令长度至少8个字符；
2、口令必须包含如下至少两种字符的组合:
       －至少一个小写字母；
       －至少一个大写字母；
       －至少一个数字；
       －至少一个特殊字符：`~!@#$%^&*()-_=+\|[{}];:'",<.>/?  和空格
3、口令不能和帐号一样。

如果设置的密码不符合密码策略的要求，则提示用户“密码太简单，请重新输入”。

**Comment by zccrs** [comment]
@justforlxz  @hualet 说安装器之前已经支持这个功能了，只不过检查规则可能不太一样，另外还需要控制中心同步支持（如果安装器中未打开此检查则控制中心里也不检查），看一下安装器中已有的文案是怎样的，贴上来给 @wangjia12 看一下需不需要重新定

**Comment by justforlxz** [comment]
@wangjia12  https://shimo.im/doc/T1ecUJywC50bzaQc  最下面有

```
必须有大小写字母混合
必须有数字
必须至少有一个特殊符号：~!@#$%^&*()[]{}\|/?,.<>
长度大于等于8位
```

**Comment by wangjia12** [comment]
@CallMeR

**Comment by CallMeR** [comment]
@zccrs    根据 @hualet   对这个需求的描述，专业版默认开启检查这个密码强度，社区版默认不检查这个强度，因此安装器在安装过程中，需要有个地方来保存这个默认配置。
另，控制中心有一个开关来“开启-关闭”密码强度检查，即使在安装器中并未使用密码强度检查功能。

**Comment by hualet** [comment]
这个需求修改我还有疑问：

1. 加复选框的意义？如果OEM希望强制用户是强密码检查的，那是不是还需要隐藏这个复选框？
2. 都已经加了复选框了，为啥还要特地分个叉，让社区版和专业版行为不一致？

@CallMeR @21wmd

**Comment by CallMeR** [comment]
个人认为，不需要隐藏复选框。因为从实施人来考虑，这个实施过程可能大部分是工程部的人去实施的。然后不见得是所有OEM都有这个需求。
不过最终还是@21wmd 来决策吧。

**Comment by hualet** [comment]
@CallMeR

**Comment by CallMeR** [comment]
去掉安装器中的复选框，改为定制ISO时以代码形式来控制。

**Comment by zccrs** [comment]
最终需求：
密码复杂度开关
需求背景：
针对于企业用户的定制化需求。
代码级别开关，用户在安装过程中可选择开启“高强度密码”的检测功能。安装成功后，用户在控制中心中新建用户时，将同步启用“高强度密码”检测功能，该功能无法通过控制中心关闭。用户使用cli创建用户时，不受该功能限制。
需求说明：
【用例1】：安装器检测当前安装的是专业版还是社区版
【用例2】：若为专业版，则显示“启用高强度密码检测”功能的复选框；
【用例3】：若为社区版，则不显示该选项。
【用例4】：勾选“启用高强度密码检测”功能后，密码检测规则如下：
1、口令长度至少8个字符；
2、口令必须包含如下至少两种字符的组合:
至少一个小写字母；
至少一个大写字母；
至少一个数字；
至少一个特殊字符：`~!@#$%^&*()-_=+|[{}];:'",<.>/?  和空格
3、口令不能和帐号一样。
【用例5】：勾选“启用高强度密码检测”功能，且系统安装完成后。在控制中心的“账户”--“创建账户”功能中新增用户时，同样根据【用例4】中检测规则对密码强度进行检测，该检测无法使用图形界面关闭。

**Comment by zccrs** [comment]
@justforlxz 控制中心里密码复杂度提示的显示问题问一下 @wangjia12

**Comment by justforlxz** [comment]
控制中心的密码复杂度检查还没有添加
