### ISSUE TITLE
锁屏界面添加休眠

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#528]
识别到使用了swap分区才显示休眠

**Comment by wangjia12** [comment]
休眠 
锁屏界面增加“休眠”状态，休眠后挂载到硬盘；
识别机器有swap分区则显示，没有就不显示；
文案：
【休眠】
【Hibernate】

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/40314/

**Comment by liuwen123** [comment]
台式机会休眠失败

**Comment by justforlxz** [comment]
导致休眠失败的原因太多了，无法处理

**Comment by liuwen123** [comment]
已修复
