### ISSUE TITLE
保存VNPC时组密码被修改

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#529]
【测试环境】
15.8
【预置条件】
无
【测试步骤】
创建VPNC，设置密码和组密码
【预期结果】
正常连接
【测试结果】
组密码被修改为密码
【问题级别】
严重
【出现概率】
100%

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/40246

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
