### ISSUE TITLE
高效模式下打开无线网络列表，无线网络列表不能主动收回去

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#53]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
1.任务栏设置为高效模式。
【测试步骤】
1.打开任务栏-无线-无线列表。
2.点击桌面的空白处。
【预期结果】
1.点击桌面空白处，无线列表主动隐藏。
【测试结果】
1.点击桌面空白处之后，无线列表不能主动隐藏。
【问题级别】
一般
【出现概率】
稳定复现

**Comment by listenerri** [comment]
无法复现，应该已经被修了，回归吧

**Comment by zhaofangfangdeepin** [comment]
测试通过
