### ISSUE TITLE
系统预留500M大小 <z5>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#531]
需求背景：
来自专业版需求，防止用户因为没有空间而进不去系统；
需求描述：
系统默认留出500M空间；
@zccrs @21wmd @hualet

**Comment by zccrs** [comment]
@hualet @21wmd 在虚拟机里试了一下，当空间满了无法写入任何文件时还是能正常进系统的

**Comment by zccrs** [comment]
ext分区会默认预留 5% 的空间供root用户使用，其它用户没有权限写入到这部分

**Comment by zccrs** [comment]
@electricface 在处理 .Xauthority 文件时加一步，如果文件不存在，就帮它创建一个大小为 1024 的文件，内容全为0。这样就能保证只要ext分区中预留的空间没有占满用户就能正常登录

**Comment by zccrs** [comment]
@21wmd 这样能满足专业版的需求吗？

**Comment by zccrs** [comment]
> @electricface 在处理 .Xauthority 文件时加一步，如果文件不存在，就帮它创建一个大小为 1024 的文件，内容全为0。这样就能保证只要ext分区中预留的空间没有占满用户就能正常登录

@electricface 创建个空文件就行了，创建空文件时系统本身就会从预留的空间中释放一部分，所以不影响此文件的后续内容的写入

**Comment by zccrs** [comment]
@mmxzmmxz @liuwen123 这个任务的测试目的：测试用户家目录所在分区没有剩余空间时用户是否还可以正常登录。测试方法：
1. 先用dd或任何工具把空间大体占满
3. 删除家目录的 .Xauthority 文件
3. seq 1 3000|xargs touch 观察命令执行过程中有没有报空间不足的错误
4. 再使用 mkdir touch vim 等命令确认的确无法写入任何数据（最好是在家目录操作）
5. 注销用户或重新启动系统
6. 测试能否正常登录进入系统

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/40327

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
