### ISSUE TITLE
已连接但无法访问互联网的提示

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#532]
网络问题提示
需求背景：
15.9做了错误提示的功能，但是无法确认已连接但无法访问互联网“的状态。
需求描述：
当前无线网络/有线网络已连接但无法访问互联网，显示感叹号图标，tooltip显示“已连接但无法访问互联网”。图片: https://uploader.shimo.im/f/uMaYwVSsHwojCimW.png图片: https://uploader.shimo.im/f/T6xn8hf6MpkTKI15.png

文案：
【已连接网络但无法访问互联网】【Connected but not Internet access】

@zccrs @listenerri

**Comment by listenerri** [comment]
@deepinzhangshuang 

需要修改一下NetworkManager的配置文件:

https://cr.deepin.io/c/Patch/+/40417

**Comment by listenerri** [comment]
@deepinzhangshuang 
这个什么时候有空加一下? 这周tag要包含这个

**Comment by listenerri** [comment]
使用打过patch的NetworkManager测试:

如果已联网但不能访问互联网, 鼠标hover托盘里的网络图标会显示相应信息
如果存在多个设备, 只要其中一个可以连通互联网, 就不会出现这个提示

测试方法:
如果找不到真实的环境测试, 可以尝试修改NetworkManager的补丁, 在 `/etc/NetworkManager/NetworkManager.conf` 中的一个http链接, 修改这个链接到任意不可访问的地方就会导致已连接但无法访问互联网的问题(这种方法只是有提示, 实际可以访问互联网)

**Comment by liuwen123** [comment]
已添加
