### ISSUE TITLE
用户反馈问题，双击还原带边框窗口时，此窗口会跑到已经最大化的dtk窗口后面 <周四>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#534]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=171277&page=1&extra=#pid541928

触发一个双击还原窗口的动作是：Press->Release->Press，deepin-wm在第二次Press但还没有Release时导致下层窗口收到了一个Ungrab引起的Enter事件。
deepin-metacity是从始至终都未收到 Ungrab 引起的 Enter 事件。
kwin 是在第二次Release时才会产生 Ungrab 引起的Enter事件。
个人感觉kwin的行为更准确些

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-mutter/+/40370/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
