### ISSUE TITLE
dock电池提示没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#535]
【测试步骤】
在笔记本上，将鼠标移动到电池上，查看提示信息显示

【预期结果】
显示正常

【测试结果】
提示没有翻译，右键菜单也没有翻译

![_ _20181204094248](https://user-images.githubusercontent.com/12492745/49412961-51e07b80-f7a9-11e8-95c3-1b0d51c777a1.png)

**Comment by listenerri** [comment]
等 tag: 4.8.2.1 再测一下吧

**Comment by liuwen123** [comment]
已修复
