### ISSUE TITLE
文件管理器窗口/列拖拽规则 

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#537]
需求背景：
窗口扩大、缩小时没有特殊定义，导致缩小窗口看不见重要的信息如文件名；
需求说明：

1. 当列宽无任何调整时，扩大/缩小窗口都优先处理文件名那一列；
2. 如果手动调节列宽，无论是拉大还是缩小，都优先改变最后一列到右边边线的距离；
3. 最右侧宽度变成最小大小时，优先压文件名，如果文件名也达到最小宽度时，出现横向滚动条；
4. 文件名称最小宽度170px，最大宽度不限；
5. 其他列的最小宽度为实际需要的宽度-40px，最大宽度为实际需要的宽度+20px；
@zccrs @shule1987 @BLumia

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/454

**Comment by liuwen123** [comment]
重复
