### ISSUE TITLE
文件管理器 高级搜索

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#538]
需求背景：
强化搜索功能，根据不同条件搜索文件。
需求说明：

1. 点击放大镜图标或者快捷键ctrl+F，进入搜索状态，显示“高级搜索”按钮；
2. 点击“高级搜索”，出现高级搜索的筛选条件（同时出现，不需要添加删除）。再点一下按钮收起条件；
3. 搜索框内输入关键字后，结合筛选条件一起查询结果；
4.类型、大小、时间有选择为空的选项，显示为“-”；

增加高级搜索功能，可以按照多种条件同时筛选，筛选条件如下：

- 搜当前文件夹或者包含子文件夹，默认选择包含子文件夹；
- 按类型筛选，即我们支持的文件夹、应用、图片、音乐、视频、文档、压缩包、可执行文件、其它）；
- 按大小，选择大小区间，单位KB、MB、GB；
- 按修改时间，选择时间区间；

![image](https://user-images.githubusercontent.com/34432879/49413173-f82c8100-f7a9-11e8-96fe-f54a46181f27.png)
文案：
```
【搜索范围】【Search】
【当前文件夹】【Current directory】
【所有子文件夹】【All subdirectories】
【文件类型】【File Type】
【应用程序】【Application】
【视频】【Video】
【音频】【Audio】
【图片】【Picture】
【压缩包】 【Archive】
【文档】【Document】
【可执行文件】【Executable】
【其它】【Others】
【文件大小】【File Size】
【0~100KB】
【100KB~1MB】
【1~10MB】
【10~100MB】
【100MB～1GB】
【>1GB】
【修改时间】【Time Modified】
【今天】【Today】
【昨天】【Yesterday】
【本周】【This week】
【上周】【Last week】
【本月】【This month】
【上月】【Last month】
【今年】【This year】
【去年】【Last year】
【全部清除】【Clear All】
```
@zccrs @BLumia

**Comment by wangjia12** [comment]
需求变更：

1. 大小区间改为：【0~100KB】
【100KB~1MB】
【1~10MB】
【10~100MB】
【100MB～1G】
【1G以上】
2.【全部清楚】文案改成【重置】  @zhuxiujuancindy 



设计图改为：
![2018-12-11 10 32 31](https://user-images.githubusercontent.com/34432879/49774650-5cae8980-fd30-11e8-9d21-8c3a9a5ba327.png)

**Comment by zhuxiujuancindy** [comment]
文案：
【重置】【Reset】

**Comment by wangjia12** [comment]
@shule1987 你把下拉框的宽度写出来一下吧

**Comment by shule1987** [comment]
> @shule1987 你把下拉框的宽度写出来一下吧

190, 90

**Comment by BLumia** [comment]
过滤的小图标源文件贴一下。

顺便， deepin 图标主题里似乎没有这个图标，dialog-filters 看上去不对。以及确认一下这类图标是不是需要保持与主题提供的 actions 图标一致？

**Comment by shule1987** [comment]
> 过滤的小图标源文件贴一下。
> 
> 顺便， deepin 图标主题里似乎没有这个图标，dialog-filters 看上去不对。以及确认一下这类图标是不是需要保持与主题提供的 actions 图标一致？

这里肯定不读图标主题



[filter.zip](https://github.com/linuxdeepin/internal-discussion/files/2674243/filter.zip)

**Comment by shule1987** [comment]
[filter深色.zip](https://github.com/linuxdeepin/internal-discussion/files/2674265/filter.zip)
深色模式用的

**Comment by BLumia** [comment]
深色模式的 filter_normal.svg 不对吧？@shule1987

**Comment by shule1987** [comment]
对的

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40473/   （注：还没合到 master）

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
