### ISSUE TITLE
hover在任务栏插件上时，tooltips信息显示在任务栏的下方。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#54]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】

【测试步骤】
1.在任务栏上，网络和声音的插件上hover。查看提示信息。
【预期结果】
1.提示信息显示在合适的位置。如果任务栏在下面，提示信息显示在任务栏上面。如果任务栏再上面，提示显示显示在任务栏下面。如果任务栏在左边，提示信息显示在任务栏右边。
【测试结果】
1.任务栏在下面的时候，提示信息显示在任务栏下面。
2.任务栏左边的时候，提示信息显示在任务栏上面。
【问题级别】
一般
【出现概率】
稳定出现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39329
这个issue中描述的问题已经修复过了，这个提交修复的是下面这个问题：
系统托盘的tooltip和applet显示的位置覆盖在了dock上：
![default](https://user-images.githubusercontent.com/7995379/47766790-9476ea00-dd0b-11e8-8beb-8d07fb603390.png)

**Comment by zhaofangfangdeepin** [comment]
测试通过
