### ISSUE TITLE
应用商店名称调整

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#540]
通用名字（中文） | 通用名字（英文） | 普通名字（中文） | 普通名字（英文）
-- | -- | -- | --
应用商店 | App Store | 深度应用商店 | Deepin App Store

@zccrs

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dstore/deepin-appstore/+/40248/

**Comment by zccrs** [comment]
@mmxzmmxz 翻译还没拉

**Comment by mmxzmmxz** [comment]
是不是还没合进仓库？
deepin@deepin-PC:~$ apt-cache policy deepin-appstore
deepin-appstore:
  已安装：5.1.2.6-1
  候选： 5.1.2.6-1
  版本列表：
 *** 5.1.2.6-1 500
        500 http://pools.corp.deepin.com/deepin panda/main amd64 Packages
        500 http://pools.corp.deepin.com/ppa/dde-panda unstable/main amd64 Packages
        500 http://packages.deepin.com/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.2.2+r73+ga58bc0d 500
        500 http://pools.corp.deepin.com/ppa/dde experimental/main amd64 Packages

**Comment by liuwen123** [comment]
已修复
