### ISSUE TITLE
台式机控制中心也有使用电池选项

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#542]
【测试步骤】
在台式机上打开控制中心，查看电源选项

【预期结果】
只有使用电源

【测试结果】
使用电源和使用电池都有

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40242/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
