### ISSUE TITLE
deepin ID配置云同步

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#545]
**需求背景：**
当用户在一台机器上有了自己惯用的配置和软件，可以通过deepin ID的同步功能，选择将这些配置或者软件同步到另一台机器上。重装系统时这个功能也非常有用。
**需求描述：**

1. 通过deepin ID的专用登录入口登录；（同商店的入口一样）
2. 登录成功后可以设置是否自动同步配置项，默认开启。开启后可以将本机配置同步到云端，在另一台机器登录同一个deepin ID且同时打开此开关时可以互相同步配置；
3. 显示同步内容：网络、声音、鼠标、更新、任务栏、启动器、壁纸。总开关开启时，可以设置具体哪些同步项；总开关关闭时，不显示具体项，全部不同步；
4. 总是记录最后一次同步的信息：比如检测到差异时最后一次是本机修改，则从本机上传到云；如果换了一台机器同一个ID登录，检测到差异时最后一次是云上的修改，则从云同步到本机）
5. 每个id大约分10M；
6. 关于壁纸的同步策略：支持同步前四个工作区的壁纸，如A、B、C、D、，分别壁纸为1、2、3、4，删掉第一台电脑上的C、D两个工作区后，第二台电脑上的C、D壁纸不受影响。第一台电脑增加一个工作区C时，默认加了一个壁纸5，则第二胎电脑上的C工作区壁纸变成5；

具体的同步项如下：

- 控制中心：

1. 网络：无线网络的用户名密码。
2. 声音：音效开关
3. 鼠标和触控板：自然滚动开关
4. 键盘和语言：快捷键后面版本看用户反馈。语言不能同步。
5. 更新：设置项

- dock：

1. 模式
2. 位置
3. 大小
4. 状态
5. 插件

- launcher：

1. 窗口模式
2. 其他：
3. 热区
4. 静态壁纸（仅支持前4个工作区）

备注：目前登录方式和存储方式都只考虑实现我们自己的，但是后期这两项需要能通过第三方ID登录和第三方存储。

![image](https://user-images.githubusercontent.com/34432879/49420912-9b8c8e80-f7c8-11e8-9440-7723b588e575.png)
![image](https://user-images.githubusercontent.com/34432879/49420918-a2b39c80-f7c8-11e8-8634-5c295609401b.png)

文案：
【deepin ID】【deepin ID】
【登录】【Login】
【上次同步时间：X年X月X日 XX：XX】
【Last Sync: yyyy-MM-dd hh:mm】
【上次同步时间：X月X日 XX：XX】
【Last Sync: MM-dd hh:mm】
【正在同步...】【Syncing】
【注销】【Logout】
【自动同步配置】
【开启后会自动同步控制中心、启动器和任务栏的部分设置项。】

@zhuxiujuancindy 增加了两行文案

@zccrs @Iceyer @CallMeR

**Comment by zhuxiujuancindy** [comment]
文案：
【deepin ID】【deepin ID】
【登录】【Login】
【上次同步时间：X年X月X日 XX：XX】
【Last Sync: yyyy-MM-dd hh:mm】
【上次同步时间：X月X日 XX：XX】
【Last Sync: MM-dd hh:mm】
【正在同步...】【Syncing】
【注销】【Logout】
【自动同步配置】
【Auto Sync】
【开启后会自动同步控制中心、启动器和任务栏的部分设置项。】
【Switch it on to sync part of the settings for Control Center, Launcher and Dock automatically.】

**Comment by CallMeR** [comment]
默认关闭的么？

**Comment by Iceyer** [comment]
@CallMeR 是的，你要先注册才能使用

**Comment by wangjia12** [comment]
需求变更以下几点：

1. 登录成功后可以设置是否自动同步配置项，默认**开启**。开启后可以将本机配置同步到云端，在另一台机器登录同一个deepin ID且同时打开此开关时可以互相同步配置；
2. 显示同步内容：网络、声音、鼠标、更新、任务栏、启动器、壁纸。总开关开启时，可以设置具体哪些同步项；总开关关闭时，以下每一项都自动关闭，全部不同步；具体项的开启和关闭不影响总开关的状态；
3. 关于壁纸的同步策略：支持同步前四个工作区的壁纸，如A、B、C、D、，分别壁纸为1、2、3、4，删掉第一台电脑上的C、D两个工作区后，第二台电脑上的C、D壁纸不受影响。第一台电脑增加一个工作区C时，默认加了一个壁纸5，则第二胎电脑上的C工作区壁纸变成5；

@zccrs @Iceyer @jouyouyun @justforlxz @CallMeR 

增加文案：
【网络】
【声音】
【鼠标】
【更新】
【任务栏】
【启动器】
【壁纸】
@zhuxiujuancindy 

@shule1987 看一下是以上这些内容。

**Comment by zhuxiujuancindy** [comment]
文案：
【网络】【Network Settings】
【声音】【Sound Settings】
【鼠标】【Mouse Settings】
【更新】【Update Settings】
【任务栏】【Dock】
【启动器】【Launcher】
【壁纸】【Wallpaper】

**Comment by wangjia12** [comment]
@zhuxiujuancindy 需要补两个文案
【同步成功】
【同步失败】

**Comment by zhuxiujuancindy** [comment]
文案：
【同步成功】【Sync succeeded】
【同步失败】【Sync failed】
