### ISSUE TITLE
音效单独开关

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#546]
需求背景：
目前实现的音效开关是一个总开关，无法调节不想使用某个音效。
需求说明：

1. 音效开关细分为每一个都有自己的开关；
2. 开启则执行对应操作时产生音效，关闭则执行对应操作时不产生音效；
3. 每个音效可以预览效果，预览时界面上有提示；

@shule1987 提供一下设计图
@zccrs 麻烦提供一下现有音效对应的操作，我整理文案

**Comment by shule1987** [comment]
<img width="716" alt="2018-12-06 11 02 31" src="https://user-images.githubusercontent.com/5448609/49558570-7756bc00-f946-11e8-8367-8301040a4c72.png">

鼠标hover的时候显示预览声音的图标

**Comment by shule1987** [comment]
<img width="716" alt="2018-12-06 11 03 39" src="https://user-images.githubusercontent.com/5448609/49558608-9c4b2f00-f946-11e8-88a8-24a51751b02c.png">

鼠标hover的时候显示预览声音的图标

**Comment by shule1987** [comment]
加上总开关
<img width="715" alt="2018-12-06 11 09 08" src="https://user-images.githubusercontent.com/5448609/49558823-63f82080-f947-11e8-9fd0-52f3a9433ffe.png">

**Comment by zhuxiujuancindy** [comment]
文案：
【开机】【Boot up】
【关机】【Shut down】
【注销】【Log out】
【唤醒】【Wake up】
【音量调节】【Volume +/-】
【通知】【Notification】
【电量不足】【Low battery】
【从启动器发送图标到桌面】【Send icon in Launcher to Desktop】
【清空回收站】【Empty Trash】
【电源接入】【Plug in】
【电源拔出】【Plug out】
【移动设备接入】【Removable device connected】
【移动设备拔出】【Removable device removed】
【错误提示】【Error】

**Comment by zccrs** [comment]
@justforlxz 音效预览的时候使用QSound，不要用QMediaPlayer

**Comment by NeilRon** [comment]
期待

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/41397/

**Comment by liuwen123** [comment]
- [ ] 点击开机音效后在点击关机音效，开机音效不会立即停止，两个声音混在一起播放了

- [ ] Volume 没有声音
