### ISSUE TITLE
深度音乐优先读本地封面<下周一>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#547]
我们之前开会讨论过一次这个问题，当时说就是优先读的本地。今天 @BLumia 跟我验证了一下是优先读的网络的。 @hualet @zccrs 要处理一下吧

**Comment by zccrs** [comment]
这个问题我已经问过 @Iceyer 了，做起来麻烦一下，不会很简单就能改好的

**Comment by hualet** [comment]
> 这个问题我已经问过 @Iceyer 了，做起来麻烦一下，不会很简单就能改好的

啥问题呀 你问了就在这里面大概说一下嘛 省得你问过了别人又得再去问一遍。。。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
