### ISSUE TITLE
支持指纹的密码输入控件 <z4>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#548]
需求背景：
对于支持指纹的设备，因为技术原因之前只能先输入指纹后输入密码选择一种，并且没有办法提示用户现在要输入指纹了。现在技术问题解决了可以重新优化指纹和密码输入方式。
需求描述：
对于支持指纹的设备，且设置了指纹的情况下，授权窗口同时提供输入密码和验证指纹的入口；
二者中有一个匹配就可以通过；
![image](https://user-images.githubusercontent.com/34432879/49427383-2a57d600-f7de-11e8-84f6-002da6023a59.png)

文案：
【请验证指纹或输入密码】
【取消】
【认证】
第一句话用之前各自对话框的
@zhuxiujuancindy 麻烦翻译一下文案
@zccrs @justforlxz

**Comment by zhuxiujuancindy** [comment]
文案：
【请验证指纹或输入密码】【Please verify your fingerprint or enter the password】
【取消】【Cancel】
【授权】【Confirm】

**Comment by zccrs** [comment]
参见：https://github.com/linuxdeepin/internal-discussion/issues/689

**Comment by listenerri** [comment]
这是以前实现的界面，不知道现在还能不能用：
https://cr.deepin.io/c/dde/dde-polkit-agent/+/34709

**Comment by zhaofangfangdeepin** [comment]
@justforlxz @zccrs 还没实现，这个需要放到15.10里面了

**Comment by justforlxz** [comment]
界面可能还需要调整，先测试一下功能

**Comment by zhaofangfangdeepin** [comment]
在这个界面，指纹解锁失败之后，应该有提示：指纹解锁失败。
![深度截图_选择区域_20190401162022](https://user-images.githubusercontent.com/14539782/55313371-2ee58000-549a-11e9-82f6-72642ff14a29.png)

**Comment by zhaofangfangdeepin** [comment]
指纹解锁成功之后，再次启动认证时，会有coredump。
deepin@deepin-PC:~/Desktop$ coredumpctl   dump /usr/lib/polkit-1-dde/dde-polkit-agent 
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
           PID: 9883 (dde-polkit-agen)
           UID: 1000 (deepin)
           GID: 1000 (deepin)
        Signal: 11 (SEGV)
     Timestamp: Mon 2019-04-01 14:39:26 CST (1h 48min ago)
  Command Line: /usr/lib/polkit-1-dde/dde-polkit-agent
    Executable: /usr/lib/polkit-1-dde/dde-polkit-agent
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (deepin)
       Boot ID: cb41d86dbee94f1998669c4693f9ab35
    Machine ID: 7f8a0074889549f9a06c5daf03a69229
      Hostname: deepin-PC
       Storage: /var/lib/systemd/coredump/core.dde-polkit-agen.1000.cb41d86dbee94f1998669c4693f9ab35.9883.1554100766000000.lz4
       Message: Process 9883 (dde-polkit-agen) of user 1000 dumped core.
                
                Stack trace of thread 9883:
                #0  0x00007fe55c2ebcd5 g_mutex_lock (libglib-2.0.so.0)
                #1  0x00007fe55c2a3520 n/a (libglib-2.0.so.0)
                #2  0x00007fe55b1501fd n/a (libpolkit-agent-1.so.0)
                #3  0x00007fe55b150315 n/a (libpolkit-agent-1.so.0)
                #4  0x00007fe55b150860 n/a (libpolkit-agent-1.so.0)
                #5  0x00007fe55c2a60f5 g_main_context_dispatch (libglib-2.0.so.0)
                #6  0x00007fe55c2a64c0 n/a (libglib-2.0.so.0)
                #7  0x00007fe55c2a654c g_main_context_iteration (libglib-2.0.so.0)
                #8  0x00007fe55fd5cecf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #9  0x00007fe5504f75d1 n/a (libQt5XcbQpa.so.5)
                #10 0x00007fe55fd03d5a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #11 0x00007fe55fd0c9a4 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #12 0x00005588ad5f7d96 main (dde-polkit-agent)
                #13 0x00007fe55e913a87 __libc_start_main (libc.so.6)
                #14 0x00005588ad5f80fa n/a (dde-polkit-agent)
                
                Stack trace of thread 9884:
                #0  0x00007fe55e9de5d9 __poll (libc.so.6)
                #1  0x00007fe55cdf80f7 n/a (libxcb.so.1)
                #2  0x00007fe55cdf9d1a xcb_wait_for_event (libxcb.so.1)
                #3  0x00007fe5504763d9 n/a (libQt5XcbQpa.so.5)
                #4  0x00007fe55fb2fb10 n/a (libQt5Core.so.5)
                #5  0x00007fe55f5df5aa start_thread (libpthread.so.0)
                #6  0x00007fe55e9e8cbf __clone (libc.so.6)
                
                Stack trace of thread 9885:
                #0  0x00007fe55e9de5d9 __poll (libc.so.6)
                #1  0x00007fe55c2a6439 n/a (libglib-2.0.so.0)
                #2  0x00007fe55c2a654c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe55fd5cecf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007fe55fd03d5a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007fe55fb2ab1a _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007fe560182d15 n/a (libQt5DBus.so.5)
                #7  0x00007fe55fb2fb10 n/a (libQt5Core.so.5)
                #8  0x00007fe55f5df5aa start_thread (libpthread.so.0)
                #9  0x00007fe55e9e8cbf __clone (libc.so.6)
                
                Stack trace of thread 9888:
                #0  0x00007fe55e9de5d9 __poll (libc.so.6)
                #1  0x00007fe55c2a6439 n/a (libglib-2.0.so.0)
                #2  0x00007fe55c2a67d2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fe55e1dee26 n/a (libgio-2.0.so.0)
                #4  0x00007fe55c2cde05 n/a (libglib-2.0.so.0)
                #5  0x00007fe55f5df5aa start_thread (libpthread.so.0)
                #6  0x00007fe55e9e8cbf __clone (libc.so.6)
                
                Stack trace of thread 9886:
                #0  0x00007fe55e9de5d9 __poll (libc.so.6)
                #1  0x00007fe55c2a6439 n/a (libglib-2.0.so.0)
                #2  0x00007fe55c2a654c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe54c3eaccd n/a (libdconfsettings.so)
                #4  0x00007fe55c2cde05 n/a (libglib-2.0.so.0)
                #5  0x00007fe55f5df5aa start_thread (libpthread.so.0)
                #6  0x00007fe55e9e8cbf __clone (libc.so.6)
                
                Stack trace of thread 9887:
                #0  0x00007fe55e9de5d9 __poll (libc.so.6)
                #1  0x00007fe55c2a6439 n/a (libglib-2.0.so.0)
                #2  0x00007fe55c2a654c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe55c2a6591 n/a (libglib-2.0.so.0)
                #4  0x00007fe55c2cde05 n/a (libglib-2.0.so.0)
                #5  0x00007fe55f5df5aa start_thread (libpthread.so.0)
                #6  0x00007fe55e9e8cbf __clone (libc.so.6)
Refusing to dump core to tty (use shell redirection or specify --output).
