### ISSUE TITLE
smb浏览文件非常卡

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#551]
【测试步骤】
打开文件管理器进入smb，然后在smb中浏览任意文件

【预期结果】
浏览正常

【测试结果】
浏览文件非常卡

**Comment by hualet** [comment]
@zccrs 回来看一下吧

**Comment by zccrs** [comment]
samba部分和鹦鹉螺不同的是，我们这边用的是gvfs，走的是fuse通道，鹦鹉螺是直接用的smb协议，没有通过gvfs-fuse，这个改的方向只能是，针对gvfs挂载设备，使用gio的接口获取文件列表/读取文件信息

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
