### ISSUE TITLE
拖拽图片到启动菜单，修改启动图片失败 <周五>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#553]
【测试步骤】
打开控制中心--启动菜单，拖动图片进去修改背景图片

【预期结果】
修改成功

【测试结果】
修改失败
也没有对拖拽的图片类型和大小进行限制，tiff、gif、svg图片都可以拖进去

【问题级别】
一般

【出现概率】
100%

smb://10.0.12.150  /share/testfiles/图片/bmp

**Comment by electricface** [comment]
现在后端支持 jpeg, png, bmp, tiff 四种。

**Comment by electricface** [comment]
dde-api: https://cr.deepin.io/#/c/dde/dde-api/+/40294/
dde-daemon: https://cr.deepin.io/#/c/dde/dde-daemon/+/40302/
启动菜单 支持设置 gif 格式的背景

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40331 只允许jpg,jpeg,png,bmp,tiff,gif。

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
