### ISSUE TITLE
商店字体跟随系统变化

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#555]
需求背景：
在系统设置字体字号后，商店总是不能跟随显示，特别不一致。
需求描述：
商店的字体、字号跟随系统的字体调节而变化。
因为短描述信息有长度限制，这一行特殊处理不跟随系统字体变化，来保证可以显示完全。

@zccrs @shule1987 @hualet @Iceyer 
之前好像看到过这个任务，但是我没找到 要是有重复的就关了吧

**Comment by myml** [comment]
已实现跟随系统字体字号

**Comment by liuwen123** [comment]
已修复
