### ISSUE TITLE
网易云音乐搜索加入空格，会导致软件卡死

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#556]
【测试步骤】
打开网易云音乐，在搜索输入框中输入任意字符和空格符，然后回车

【预期结果】
可以正常搜索

【测试结果】
会导致网易云音乐内存暴涨，软件卡死

【问题级别】
严重

【出现概率】
100%

**Comment by CallMeR** [comment]
咦 我没有这个问题呀
