### ISSUE TITLE
影院-修改默认字体样式<周四>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#557]
需求来源：https://github.com/linuxdeepin/deepin-movie-reborn/issues/21
需求说明：
修改默认字体的样式，增加阴影或描边，保证在浅色背景下也可以正常显示字幕。
@shule1987 @zccrs

**Comment by shule1987** [comment]
font-family: SourceHanSansSC-Normal;
font-size: 26px;
color: #FFFFFF;
letter-spacing: 0;
text-align: center;
外描边border: 1px solid rgba(0,0,0,0.50);
box-shadow: 0 2px 4px 0 rgba(0,0,0,0.50);
![group 3](https://user-images.githubusercontent.com/5448609/50428711-b5ffe680-08f4-11e9-885a-f9871f681808.png)

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-movie-reborn/+/40894/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
