### ISSUE TITLE
影院-播放电影时保持屏幕常亮<周四>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#558]
需求背景：
播放电影时不动屏幕，屏幕会黑掉，影响体验。
需求说明：
播放电影时保持屏幕常亮。

@zccrs

**Comment by zccrs** [comment]
@BLumia 用 https://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html 这个接口试一下

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-movie-reborn/+/40917/

**Comment by liuwen123** [comment]
设置待机为1m，播放5m的视频，会导致视频卡住
设置待机为10m，播放5m的视频，视频播放正常

**Comment by rekols** [comment]
再试试：https://cr.deepin.io/#/c/deepin-movie-reborn/+/40917/

**Comment by liuwen123** [comment]
已修复
