### ISSUE TITLE
深度看图不是通过文件内容识别，而是通过文件后缀来识别的

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#559]
【测试步骤】
从网易云音乐朋友圈保存一张gif图片到桌面，但是保存到桌面后文件的后缀变成jpg
使用深度看图打开查看该文件

【预期结果】
深度看图可以自动识别为gif图片并播放

【测试结果】
深度看图只能识别为jpg图片
这个问题以前被修复过，现在又出来了

【问题级别】
一般

【出现概率】
100%
![109951163706329395](https://user-images.githubusercontent.com/12492745/49556280-162aea80-f93e-11e8-8ca7-bcea39385421.jpg)

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/40317/

**Comment by hualet** [comment]
这个不是 +1 了，还有什么问题么？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
