### ISSUE TITLE
连续两次启动、禁用网络之后，任务栏崩溃

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#56]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】

【测试步骤】
1.在控制中心禁用和启动有线网络。
【预期结果】
1.禁用和启用正常，任务栏正常。
【测试结果】
1.禁用和启动有线网络之后，导致任务栏崩溃
【问题级别】
一般
【出现概率】
稳定复现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39345

**Comment by zhaofangfangdeepin** [comment]
V+1
