### ISSUE TITLE
控制中心网络编辑 VPN SSTP <下周五>

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#560]
之前有任务 https://tower.im/projects/1d2977ef6b194727a97f96409f77038c/todos/7c85e4d5da754ca28563e81aeaadcd50/#f7c38753017e4808bf44dbb1e9f48af7

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41407

需要定一下下面红框里的文案, 这个图片是 gnome 网络编辑器使用的:

![default](https://user-images.githubusercontent.com/7995379/51459447-a2c92500-1d93-11e9-972f-b66fd6878852.png)

**Comment by listenerri** [comment]
@electricface 你先简单测一下吧

**Comment by electricface** [comment]
还少了高级设置 代理
![image](https://user-images.githubusercontent.com/3241440/51507760-58948200-1e2d-11e9-9e94-ffb8f1139e83.png)

**Comment by listenerri** [comment]
代理支持:
https://cr.deepin.io/c/dde/dde-control-center/+/41501

**Comment by electricface** [comment]
测试通过
