### ISSUE TITLE
鼠标移动到dock的QQ图标上，不会弹出QQ消息列表

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#561]
【测试步骤】
打开QQ等QQ有消息时，将鼠标移动到dock的QQ图标上，查看软件显示

【预期结果】
会自动弹出QQ列表显示

【测试结果】
没有任何反应

【问题级别】
一般

【出现概率】
100%

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40354

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
