### ISSUE TITLE
控制中心默认程序没有勾选

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#563]
【测试步骤】
打开控制中心--默认程序，查看默认程序勾选状态

【预期结果】
每一项都有一个默认程序被勾选

【测试结果】
有的没有被勾选

【问题级别】
一般

【出现概率】
100%
![_ _20181206143720](https://user-images.githubusercontent.com/12492745/49567264-2788ec80-f968-11e8-8a31-21a65aa1a976.png)

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/573 处理了

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
