### ISSUE TITLE
后端增加设置屏幕保护超时时间的接口

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#564]
跟超时关闭屏幕功能类型，分电源和使用电池模式，可以设置和读取不同模式下的超时时间。超时后调用
com.deepin.ScreenSaver /com/deepin/ScreenSaver com.deepin.ScreenSaver.Start() 接口

**Comment by zccrs** [comment]
感觉使用 Start 更合适

**Comment by electricface** [comment]
deepin-desktop-schemas: https://cr.deepin.io/#/c/deepin-desktop-schemas/+/40345/
dde-daemon: https://cr.deepin.io/#/c/dde/dde-daemon/+/40346/
