### ISSUE TITLE
控制中心添加默认程序后，删除默认程序时控制中心崩溃

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#573]
【测试步骤】
打开控制中心进入默认程序，选中邮件点击添加，任意选中一个文件添加成功后，再点击编辑删除刚才添加的文件

【预期结果】
可以正常删除

【测试结果】
删除文件时，控制中心崩溃

【问题级别】
严重

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40367/  和另外一个没有选择默认值的任务一块处理了。

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/563

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
