### ISSUE TITLE
建议在查看文件的属性时可以复制文件名

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#574]
对于有权限的文件可以通过重命名的方式来复制文件名称(不包含路径), 可以直接重命名或者在属性对话框中重命名, 如下图:

![default](https://user-images.githubusercontent.com/7995379/49636440-908e6400-fa3d-11e8-8823-6427d5aa8925.png)

但如果是没有权限的文件目前就没有一个便利的方式去复制文件名了:
![default](https://user-images.githubusercontent.com/7995379/49636510-c7fd1080-fa3d-11e8-8894-dbe0c4a88109.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
