### ISSUE TITLE
15.8.2 更新内容总结

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#576]

**Comment by zccrs** [comment]
# 15.8.2.1
## 已完成的需求部分
* 控制中心更新添加”不再提醒“开关
* 注销前帮助用户创建 .Xauthority 文件，防止硬盘空间占满后无法登录进系统
* dock托盘区域增加hover效果
* 触摸屏支持
* 启动菜单自动探测分辨率
* 锁屏增加休眠入口
* 锁屏界面默认情况下增加选中状态
* 登录时密码连续错误处理
* 启动器图标默认大小
* 文件管理器窗口/列拖拽规则 
* home为单独分区时查看磁盘信息
* 压缩默认为zip格式
* 商店名称改为应用商店
* 深度影院标题栏去掉应用名称
### 深度编辑器
* 添加底部信息栏 (显示行列信息，编辑状态，编码选择，高亮选择)
* 标签栏显示只读信息
* 设置窗口加入自动换行选项
* 增加 F5 刷新
* 支持高亮括号功能
* 主题优化

**Comment by deepinzhangshuang** [comment]
file-roller 更新：
    默认设置压缩方式为zip
grub2 更新：
    添加deepin_mode模块，和修复grub 分辨率一起测试使用。

**Comment by deepinzhangshuang** [comment]
还缺少 flatpak更新

**Comment by deepinzhangshuang** [comment]
触摸屏 onboard 需要添加到greater 建议依赖， 需要tag 提交crp。

**Comment by deepinzhangshuang** [comment]
dde-session-ui 回退到4.6.2.1 版本 @liuwen123 @mmxzmmxz @zccrs @justforlxz

**Comment by zhuxiujuancindy** [comment]
[15.8.2.1 changelog.txt](https://github.com/linuxdeepin/internal-discussion/files/2666876/15.8.2.1.changelog.txt)
日志填写完毕

**Comment by zccrs** [comment]
# 第二周已完成需求
* 智能镜像源
* dock 已连接网络但无法访问互联网 的网络问题
* 更换默认壁纸和启动器图标
* 更新 用户最终许可协议
* 文件管理器 home为单独分区时查看磁盘信息
* 文件管理器多选打开逻辑
* 编辑器的剩余所有需求 ( @rekols 补充一下 )

**Comment by rekols** [comment]
编辑器 1.2
被打开的文件已经丢失提醒
简单支持触屏

**Comment by BLumia** [comment]
文件管理器：

 - 相同类型的多文件支持”打开方式“选项
 - 修复文件列表模式下，扩展名大小写显示始终为小写的问题
 - 修复提示对话框图标大小不正确的问题
 - 侧边栏菜单中”系统盘“右键将”属性“的文案调整为”磁盘信息“

**Comment by listenerri** [comment]
dde-dock 4.8.4:

* 修复托盘图标触发拖拽过于灵敏 https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/d6bbed3e1c2bd8928a028c74b193d30a/
* 修复刚开机时一些开机自启动应用的托盘图标无法右键显示菜单 https://github.com/linuxdeepin/internal-discussion/issues/660
* 修复网络提示没有及时更新 https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/a7c3481830dab3290d1a1c9580883c92/
* 修复托盘图标在触摸屏下长按显示菜单的问题 https://github.com/linuxdeepin/internal-discussion/issues/619

**Comment by justforlxz** [comment]
控制中心 4.8.3
添加智能镜像源

**Comment by electricface** [comment]
dde-daemon: 3.14.0
* 处理无线网络加密类型更改
* 支持屏保
* 修正自动探测grub分辨率相关bug
* 修正任务栏驻留图标bug

dde-api: 3.12.0
* 当grub主题分辨率为1280x1024时，只显示4行选项的问题

deepin-desktop-schemas: 3.8.0
* 专业版默认不开启自动调节亮度
* 修改触摸屏长按时长默认值

**Comment by justforlxz** [comment]
控制中心 4.8.4
修复智能镜像源开关不同步

**Comment by liuwen123** [comment]
deepin-wine-helper 1.1deepin18
deepin-wine 2.18-16~rc2
deepin.com.thunderspeed:i386 7.10.35.366deepin18
deepin.com.cmbchina 7.6.0deepin0
ppa/dde-panda 更新上述项目详情见 tower @liuwen123 @zhuxiujuancindy
