### ISSUE TITLE
编辑器监听文件变化<周二>

### ISSUE THREAD

**Issue by rekols** [linuxdeepin/internal-discussion#577]
若某文件当前处于打开状态，但磁盘中的原文件已经被修改，则弹出提示对话框，显示“磁盘中的原文件已被修改，是否重新载入？”。

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40421/

**Comment by liuwen123** [comment]
- [ ] 提示框的提示图标需要修改
- [ ] 提示框不能随窗口的变化而变化

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40427/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
