### ISSUE TITLE
UDisks默认挂载参数更改，添加noexec <周三>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#578]

**Comment by zccrs** [comment]
@deepinzhangshuang patch和udev的rules文件都给你了，这个任务你处理一下吧

**Comment by zccrs** [comment]
> @deepinzhangshuang patch和udev的rules文件都给你了，这个任务你处理一下吧

@deepinzhangshuang 社区版和专业版都包含

**Comment by deepinzhangshuang** [comment]
ppa/dde-panda unstable 已经更新

**Comment by zccrs** [comment]
@liuwen123 需要重新验证，补充测试用例

规则是：只对U盘设备，且文件系统为 ext2 ext3 ext4 的分区添加noexec挂载参数。
要测试一下非U盘设备（包含ext或其它文件系统）移动硬盘、硬盘盒等、非ext文件系统U盘 等设备是否受到影响

**Comment by zccrs** [comment]
@liuwen123 需要重新验证，补充测试用例

规则是：只对U盘设备，且文件系统为 ext2 ext3 ext4 的分区添加noexec挂载参数。
要测试一下非U盘设备（包含ext或其它文件系统）移动硬盘、硬盘盒等、非ext文件系统U盘 等设备是否受到影响

**Comment by deepinzhangshuang** [comment]
而且限制为ext2  ext3 ext4 更加不合理

**Comment by zccrs** [comment]
> > 而且限制为ext2 ext3 ext4 更加不合理
> 
> 这个限制确实不大对，是怕其他文件系统不支持 noexec 选项？ @zccrs

不是吧 @21wmd

**Comment by zccrs** [comment]
> > 而且限制为ext2 ext3 ext4 更加不合理
> 
> 这个限制确实不大对，是怕其他文件系统不支持 noexec 选项？ @zccrs

不是吧 @21wmd 

> > 而且限制为ext2 ext3 ext4 更加不合理
> 
> 这个限制确实不大对，是怕其他文件系统不支持 noexec 选项？ @zccrs

vfat ntfs 之类的就没有可执行权限这个权限

**Comment by zhaofangfangdeepin** [comment]
Deepin15.10 测试通过
