### ISSUE TITLE
更换默认壁纸和启动器图标 <周三>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#579]
@shule123

**Comment by wangjia12** [comment]
这也有重复任务的

**Comment by zccrs** [comment]
> 这也有重复任务的

把任务贴上来关闭一个吧

**Comment by shule1987** [comment]
![coral-ouellette-974101-unsplash](https://user-images.githubusercontent.com/5448609/49845001-dceff000-fdff-11e8-9439-02b95822b98e.jpg)

就这张了

**Comment by zccrs** [comment]
![_ _20181214100839](https://user-images.githubusercontent.com/13449038/49979072-4d297d80-ff88-11e8-8f1e-6145f120d303.png)
把这一张删掉，上面的那个改成默认的，原本默认的壁纸还在预装壁纸列表中

**Comment by shule1987** [comment]
之前那张默认壁纸名字叫The Gongga Mountain_by_wangjinyu

**Comment by liuwen123** [comment]
已更换
