### ISSUE TITLE
深度影院右键菜单未翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#58]
【测试环境】
deepin-movie：3.2.12-1

【测试步骤】
打开深度影院，点击右键菜单--画面，查看右键菜单显示

【预期结果】
右键菜单显示正常

【测试结果】
右键菜单有的没有翻译

【出现概率】
100%
![_ _20181030152621](https://user-images.githubusercontent.com/12492745/47702635-89af4d00-dc58-11e8-8467-75a4e91b8c3c.png)
![_deepin-movie_20181030152648](https://user-images.githubusercontent.com/12492745/47702637-8b791080-dc58-11e8-92a8-bcdb16001c34.png)

**Comment by zccrs** [comment]
@wangjia12

**Comment by zhuxiujuancindy** [comment]
文案没有问题
需要提交到transifex翻译 @zccrs

**Comment by zccrs** [comment]
@zhuxiujuancindy 嗯，已经上传了

**Comment by zhuxiujuancindy** [comment]
> @zhuxiujuancindy 嗯，已经上传了
都翻译了
但你上传了两遍文案，不是说这个文案只在设置里出现，右键菜单里的去掉吗？@zccrs
