### ISSUE TITLE
锁屏界面切换用户，点击密码输入框，没有光标闪动的响应 <周四>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#581]
【测试环境】：
lightdm                          1.21.5-3deepin        amd64
【测试步骤】：
1.系统有两个用户，已经登录一个用户，点击锁屏--》切换用户，再次点击切换用户，点击输入密码处，输入框无光标闪动现象。
ps：此现象出现在双屏环境。

**Comment by liuwen123** [comment]
已修复
