### ISSUE TITLE
更新提醒默认状态为关闭

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#583]
【测试环境】：
dde-control-center:
  已安装：4.7.9+r15+ga356a336

【测试步骤】：
1.进入控制中心，查看更新提醒开关，默认关闭。

**Comment by zccrs** [comment]
@mmxzmmxz @wangjia12 @21wmd 默认应该是打开还是关闭呀

**Comment by wangjia12** [comment]
默认打开，我一会发邮件

**Comment by liuwen123** [comment]
默认开着的
