### ISSUE TITLE
更新提醒关闭场景，下方提示文字不应该显示

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#584]
【测试环境】：
dde-control-center:
  已安装：4.7.9+r15+ga356a336

【测试步骤】：
1.进入控制中心--》更新提醒--》关闭，下方不该出现提示文字。
只有打开的场景，才显示提示文字。

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40454

**Comment by liuwen123** [comment]
+1
