### ISSUE TITLE
右键菜单没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#586]
【测试步骤】
打开文件管理器，右键点击挂载磁盘，查看右键菜单显示

【预期结果】
右键菜单显示正常

【测试结果】
右键菜单没有翻译

【问题级别】
一般

【出现概率】
100%
![_ _20181210114038](https://user-images.githubusercontent.com/12492745/49709693-a0da5500-fc70-11e8-93cf-a08956e3afee.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40412/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
