### ISSUE TITLE
更新提醒开关、自动下载更新开关均处于关闭状态，此时仍有更新提醒

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#587]
【测试环境】：
dde-control-center:
  已安装：4.7.9+r15+ga356a336

【测试步骤】：
1.更新提醒开关、自动下载更新开关均处于关闭状态，降级某个包，重启系统，查看控制中心是否有提醒。
【测试结果】：
1.仍然有提醒。
【预期结果】：
1.没有更新提醒。

**Comment by justforlxz** [comment]
版本错误

**Comment by mmxzmmxz** [comment]
刚好降级的控制中心进行测试～
可以关闭了
