### ISSUE TITLE
双屏变单屏，grub分辨率显示不正确

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#590]
【测试环境】：
dde-daemon                       3.11.0+r2+g1d5a3106   amd64
【测试步骤】：
1.连接双屏显示，查看两个屏幕分辨率，取共有分辨率；
2.拔掉双屏，使用单屏，查看grub分辨，显示不正确，不是最佳分辨率。

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/40425/

**Comment by mmxzmmxz** [comment]
验证通过
dde-daemon 3.11.0-2
