### ISSUE TITLE
锁屏界面--》关机--》休眠按钮不响应

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#591]
【测试环境】：
dde-session-ui                   4.7.0+r1+g3122776     amd64 
【测试步骤】：
1.锁屏--》关机--》休眠，不起作用。

**Comment by zccrs** [comment]
@mmxzmmxz 这个是特定机器上不响应还是？

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/40490/

**Comment by mmxzmmxz** [comment]
+1

**Comment by mmxzmmxz** [comment]
在这个任务跟踪
https://github.com/linuxdeepin/internal-discussion/issues/596
