### ISSUE TITLE
grub分辨率双屏环境下，共同分辨率排序存在问题

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#595]
【测试环境】：
dde-daemon:
  已安装：3.11.0+r2+g1d5a3106

【测试步骤】：
1.低分辨率笔记本外接高分辨率显示器，grub筛选出的共有分辨率没有排序，会导致grub选用的分辨率不是最优的。

**Comment by electricface** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/595

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/40586

**Comment by mmxzmmxz** [comment]
验证通过
![image](https://user-images.githubusercontent.com/12388744/50142570-6cf0d680-02e5-11e9-9832-2bcad8acfcf6.png)
