### ISSUE TITLE
session-ui bug记录

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#596]
【测试环境】：
dde-session-ui:
  已安装：4.7.0+r1+g3122776
【测试步骤】：
进入锁屏、登录、切换用户进行测试。
【需要测试项】：
  登录
  锁屏
  多用户切换
  多会话切换
  用户键盘布局
  启动速度
  多屏
  高分屏

**Comment by mmxzmmxz** [comment]
- [ ] 登录2个用户，且密码均相同，注销用户2，切换用户，不用输入密码即可登录用户1

- [ ] 点击登录界面软键盘，黑屏

- [ ] 创建多个账户，切换账号，选中的账号与刚才切换的账号不一致。即：切换至用户c，此时继续点击切换账号，进入的界面默认选中并不是用户c

**Comment by zccrs** [comment]
@yefeifei 过一下这里边未完成的问题，有你没有测出来的就单独提出来，之后把这个任务关掉吧
