### ISSUE TITLE
高分屏环境，grub界面文字显示行数不正确 <z5>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#597]
【测试环境】：
dde-daemon:
  已安装：3.11.0+r2+g1d5a3106

【测试步骤】：
1.高分屏环境，测试grub分辨率。
【测试结果】：
1.grub界面选项只显示4项，计算高度仍然存在问题。

**Comment by electricface** [comment]
在分辨率为 1280x1024 下会出现只能显示4行的问题。

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-api/+/40521

**Comment by mmxzmmxz** [comment]
等3.14.0tag

**Comment by mmxzmmxz** [comment]
测试通过
dde-daemon                       3.14.0-1              amd64
