### ISSUE TITLE
打印控件-增加打印按钮

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#598]
需求背景：
来自专业版的需求。现在看图和编辑器的打印控件需要在“打印设置”窗口里面再次点击打印才可以真的打印，不需要设置的时候打印总是要多点一步很麻烦。
需求描述：
将现在的“打印”按钮文案改为“打印设置”，增加一个“打印”按钮，点击后直接打印；
文案：
【打印设置】
【打印】

@shule1987 增加一个打印图标
@zhuxiujuancindy 麻烦翻译一下

@21wmd @zccrs

**Comment by shule1987** [comment]
[SVG.zip](https://github.com/linuxdeepin/internal-discussion/files/2674162/SVG.zip)
增加了一个setting图标

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
