### ISSUE TITLE
设置屏保

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#599]
需求背景：
专业版有屏保的需求。本次仅加入选择和切换屏保的功能，后续会增加针对每个屏保的设置功能；
需求说明：

1. 桌面右键菜单将“设置壁纸”这一项改为“壁纸与屏保”；
2. 屏保同壁纸一样平铺在一排，静态显示；
3. 点击屏保，屏保预览图上出现“设置屏保”的按钮，同时在桌面上预览；
4. 点击“设置屏保”设置为屏保，并且退出设置界面；
5. 可以设置闲置时间：1m、5m、10m、15m、30m、1h、从不；设置项同控制中心待机时间一样；
6. 可以勾选是否恢复时需要密码，默认不勾选；

![image](https://user-images.githubusercontent.com/34432879/49720724-81a4ed00-fc9b-11e8-9f7b-7e8dfad7b4be.png)
文案：
【壁纸与屏保】
【屏保】
【闲置时间】
【1m】
【5m】
【10m】
【15m】
【30m】
【1h】
【从不】
【恢复时需要密码】
@zhuxiujuancindy 
@zccrs  @21wmd

**Comment by zhuxiujuancindy** [comment]
文案：
【壁纸与屏保】【Wallpaper and Screensaver】
【屏保】【Screensaver】
【设置屏保】【Apply】
【闲置时间】【Wait:】
【从不】【Never】
【恢复时需要密码】【Require a password on wake up】

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40846/

安装文件管理器的这个提交，且安装 deepin-screensaver 后注销再进入桌面测试

**Comment by liuwen123** [comment]
- [ ] 时间显示和需求不一致

- [ ] 恢复需要密码功能无效

**Comment by liuwen123** [comment]
已添加
