### ISSUE TITLE
添加新的国外镜像站

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#60]
之前联系过一个镜像站服务提供商，已经同步完成了。

0. mirror sponsor:
name:	IP-Connect LLC
GEOLOC:	Ukraine, Vinnytsia
site:	https://ip-connect.vn.ua/
conn.:	IPv4(multihome)+IPv6
bandw.:	2*1Gb unmetered
can be used as tier mirror for other mirrors (rsync'ing)

1. image mirror:
URL's for access
* rsync://deepin-cd.ip-connect.vn.ua/deepin-cd/
* https://deepin-cd.ip-connect.vn.ua/
* http://deepin-cd.ip-connect.vn.ua/
* ftp://deepin-cd.ip-connect.vn.ua/mirror/deepin-cd/
rsyncing each 6 hours (full)

2. packages mirror:
* rsync://deepin.ip-connect.vn.ua/deepin/
* https://deepin.ip-connect.vn.ua/
* http://deepin.ip-connect.vn.ua/
* ftp://deepin.ip-connect.vn.ua/mirror/deepin/
rsyncing:
* each 1 hours (only if needed by smart sync)
* + each day (1 time)  -- full sync

我们是否考虑将packages mirror添加到系统中

@wangjia12 @hualet

**Comment by 21wmd** [comment]
昨天收到了该镜像站点的邮件，询问我们为什么官网的mirror list列表中没有提及他们的镜像站地址，以及为什么没后检测到从该镜像站的任何下载。
已经跟艾菖沟通，将该镜像站地址加入www.deepin.org的mirror list列表中。但没有下载的问题，可能需要通过将镜像站地址集成如iso才能够解决。
@wangjia12 @hualet

**Comment by hualet** [comment]
我确认了一下，15.8发布的时候就会用上现在镜像源管理平台发布的镜像源列表，所以只要正常运营平台上的镜像源列表即可。

**Comment by zccrs** [comment]
@hualet @21wmd 这个任务需要留着备忘吗，还是说可以关闭了

**Comment by hualet** [comment]
得问 @21wmd

**Comment by 21wmd** [comment]
@zccrs 可以关了
