### ISSUE TITLE
skype 在托盘上显示两个图标

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#605]
目前支持了两种托盘协议，一般的应用发现支持新托盘协议 SNI 之后，就不会再走旧的托盘协议。应该是 skype 情况特殊。

@listenerri @deepinzhangshuang

**Comment by listenerri** [comment]
经测试社区版没有这个问题, 已测试的包: skype 和 skypeforlinux

**Comment by listenerri** [comment]
仓库里的包skypeforlinux没有这个问题, 但是这个包会带有一个仓库: `/etc/apt/sources.list.d/skype-unstable.list`, 更新到它自己的仓库最新版后会出现这个问题

**Comment by hualet** [comment]
> 仓库里的包skypeforlinux没有这个问题, 但是这个包会带有一个仓库: `/etc/apt/sources.list.d/skype-unstable.list`, 更新到它自己的仓库最新版后会出现这个问题

有在其他支持 SNI 的 DE 测试一下看看么？

**Comment by listenerri** [comment]
@hualet 
测试了有 KDE, GNOME, XFCE, 这几个都不是同时提供 SNI 和 Xembed 两种协议的, 所以没有可比性, 不知道还有其他桌面环境跟我们一样同时支持两种协议的吗?

**Comment by listenerri** [comment]
等 https://github.com/linuxdeepin/developer-center/issues/670 里的补丁打了应该可以解决这个问题

**Comment by liuwen123** [comment]
+1
