### ISSUE TITLE
升级到15.8之后，控制中心的缩放滑块在1.25的位置，但是右上角的值是1 <12.11>

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#606]
【测试环境】
dde-control-center:
  已安装：4.7.9-1
【预置条件】
15.5环境
【测试步骤】
1.从15.5的环境升级上来，打开控制中心-显示。
【预期结果】

【测试结果】
1.缩放显示缩放为1，但是滑块在1.25的位置
【问题级别】

【出现概率】
遇到两次，从15.5升级上来。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181211084745](https://user-images.githubusercontent.com/14539782/49770963-dc812780-fd21-11e8-9240-8582a74a8aba.png)

**Comment by justforlxz** [comment]
修复已经包含在上周的tag了   4.8.0
