### ISSUE TITLE
升级 cndrvcups ，不然佳能打印机不能使用

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#607]
cndrvcups-ufr2-uk 现在是 3.40  ，亲测 3.20 还可以用 据 @snyh 说 3.60 也可以用。

**Comment by snyh** [comment]
3.4的驱动会在使用时直接段错误。 本质问题还是更新软件包后的测试问题。当然每个软件都这样测试确实很难，但还是得考虑如何避免再次发生这种可以被检测出的错误。

**Comment by deepinzhangshuang** [comment]
已经升级到3.60
