### ISSUE TITLE
微信有消息时，托盘中微信的图标没有闪动

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#61]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
1.微信登录
【测试步骤】
1.把微信放入到托盘中。让人给微信发消息。
【预期结果】
1.接收到消息时，托盘中的微信图标会闪动
【测试结果】
1.接收到消息之后，托盘中微信的图标没有闪动。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by listenerri** [comment]
图标的闪烁没有问题
