### ISSUE TITLE
安装器 预先进入grub分辨率探测模式

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#611]
执行 /usr/lib/deepin-daemon/grub2 -prepare-gfxmode-detect 

并且不用执行 adjust-grub-theme 命令了

需要 X 环境，需要环境变量 DISPLAY 与 XAUTHORITY。

**Comment by electricface** [comment]
需要挂载外部的 /var/run，提供 XAUTHORITY 指定的文件。
需要与x服务器的连接，挂载外部的 /tmp/.X11-unix 。

**Comment by justforlxz** [comment]
已经支持
