### ISSUE TITLE
从15.8升级至15.8.2，出现错误Failed to request new SB state

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#612]
【测试环境】：
15.8升级至15.8.2
高分屏笔记本
【测试步骤】：
1.安装15.8社区版系统，后添加内部源进行升级，升级过程中报错。
正在设置 dde-session-ui (4.6.2.1-1) ...
正在设置 dde (15.8+4) ...
正在处理用于 libc-bin (2.27-3) 的触发器 ...
正在处理用于 shim-signed (1.23+0.9+1474479173.6c180c6-0ubuntu1) 的触发器 ...
Failed to request new SB state

**Comment by mmxzmmxz** [comment]
[history.log](https://github.com/linuxdeepin/internal-discussion/files/2666191/history.log)
[term.log](https://github.com/linuxdeepin/internal-discussion/files/2666193/term.log)

**Comment by deepinzhangshuang** [comment]
sudo mokutil --disable-validation 可以重现此问题。
可能是ubuntu的验证不支持此类设备。
https://askubuntu.com/questions/769268/unable-to-disable-secure-boot-with-mokutil-in-16-04
