### ISSUE TITLE
笔记本开启安全启动，导致deepin_gfxmode不能执行，故grub分辨率修复失败 <z4>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#614]
【测试环境】：
15.8升级至15.8.2
hw笔记本
【测试步骤】：
1.进入grub界面，执行`videoinfo`，提示安全启动禁止获取。
导致结果，grub不能自动调节分辨率，使用默认1024*768.

**Comment by deepinzhangshuang** [comment]
这个应该是对应驱动模块没有添加到uefi 签名中。
https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1104627  
可以参考这个bug记录。

**Comment by electricface** [comment]
遇到这种情况，将使用 deepin-fallback 这种与分辨率不太相关的主题。
如果想要使用 deepin 主题，就必须关闭安全启动。

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-api/+/40691/
https://cr.deepin.io/#/c/dde/dde-daemon/+/40700/

**Comment by mmxzmmxz** [comment]
v+1

**Comment by mmxzmmxz** [comment]
验证通过。Lenovo开启安全启动，grub界面默认使用deepin-fallback主题,grub选项在左上角。
