### ISSUE TITLE
托盘程序识别有问题

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#616]
- [x] 所有的wine程序都被识别为同一个程序
- [x] SNI协议的托盘重启系统后识别失效

**Comment by listenerri** [comment]
变动：

1. SNI 协议的托盘使用其 ”Id” 接口的数据作为 item 的 key
2. XEmbed 协议的托盘使用窗口属性 ”WM_CLASS“ 作为 item 的 key
3. wine 程序(也是XEmbed 协议)的托盘使用窗口属性 ”__wine_prefix“ 作为 item 的 key

https://cr.deepin.io/c/dde/dde-dock/+/41076

**Comment by listenerri** [comment]
@liuwen123 
根据一楼的两个检查项验证就可以了

**Comment by liuwen123** [comment]
已修复
