### ISSUE TITLE
切换主题后，dock挂载图标没有及时更新

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#617]
【测试步骤】
文件管理器挂载其他分区后，在控制中心中修改主题，查看dock挂载图标显示

【预期结果】
主题切换后，挂载图标会及时更新

【测试结果】
挂载图标没有及时更新

【问题级别】
一般

【出现概率】
100%

**Comment by listenerri** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40580

**Comment by listenerri** [comment]
@BLumia 上面的提交没有彻底修好, 只是让托盘图标可以适应主题修改了, applet里面的图标没有变化, 这个你参考上面提交修改吧

**Comment by BLumia** [comment]
> 上面的提交没有彻底修好, 只是让托盘图标可以适应主题修改了, applet 里面的图标没有变化, 这个你参考上面提交修改吧

好的

**Comment by liuwen123** [comment]
已修复

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40652/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
