### ISSUE TITLE
dock插件处，响应不灵敏，列出使用不方便的选项

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#619]
【测试环境】：
dde-dock 4.8.3.1-1
【测试步骤】：
1.手指单击、双击dock插件处，存在一些问题，以列表形式列出。

**Comment by mmxzmmxz** [comment]
响应不灵敏，导致点击事件多半响应为hover事件：

- [ ] 点击触摸屏图标，不能正常唤出软键盘；

- [ ] 点击软键盘图标，与鼠标点击响应不一致；

- [ ] 点击无线网络图标，响应的是hover的事件；

- [ ] 插件图标右键无法唤出。

**Comment by zccrs** [comment]
@21wmd

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40471

**Comment by listenerri** [comment]
目前遗留问题: 
高效模式，插件栏的右键菜单触发比较困难 @zhaofangfangdeepin 
会在手指松开时才显示插件的菜单, 稍后处理

**Comment by listenerri** [comment]
> @zccrs
> 
> 点击触摸屏图标，不能正常唤出软键盘；点击软键盘图标，与鼠标点击响应不一致；点击无线网络图标，响应的是hover的事件。
> 这三个问题是我觉得应该要优先修复的。

上面的cr提交应该已经修复了这些问题

**Comment by listenerri** [comment]
修复显示菜单的问题:

- 长按系统托盘图标或者插件一定时间后不必松手就会显示出来菜单
- 长按应用托盘图标会在松手之后才显示菜单, 这个目前无法做到与上面行为一致

https://cr.deepin.io/c/dde/dde-dock/+/40530

**Comment by mmxzmmxz** [comment]
4.8.4tag就有

**Comment by mmxzmmxz** [comment]
测试通过
dde-dock 4.8.4-1
