### ISSUE TITLE
launcher小窗口，点击系统管理，唤出了控制中心 <周四>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#621]
【测试环境】：
dde-launcher 4.5.4-1
【测试步骤】：
1.launcher小窗口，点击分类--》系统分类，唤出控制中心。
【预期结果】：
1.显示系统管理分类应用。

**Comment by zccrs** [comment]
系统管理这一项点开后，手指下面正好是控制中心，可以是误触的

**Comment by justforlxz** [comment]
现在还有这个问题么
