### ISSUE TITLE
软键盘大小写会出现错乱现象

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#622]
【测试环境】：
onboard 1.4.1.3-1
【测试步骤】：
1.多次点击软键盘的大小写切换按键，会出现显示如实际输入不一致现象。
如：显示的小写，但是输入文档的字符全部为大写字符。

**Comment by zccrs** [comment]
@21wmd

**Comment by hualet** [comment]
暂时么有重现

**Comment by mmxzmmxz** [comment]
暂未复现，先关闭处理
