### ISSUE TITLE
触摸屏响应不灵敏 <周三>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#623]

**Comment by mmxzmmxz** [comment]
【测试环境】：
onboard 1.4.1.3-1
【不灵敏选项】：

- [ ] 桌面双击文件夹

- [ ] 锁屏界面切换用户

**Comment by zccrs** [comment]
华为笔记本

**Comment by zccrs** [comment]
@21wmd

**Comment by 21wmd** [comment]
@zccrs 桌面双击文件夹、文件和快捷方式等双击相关的操作，都有优化的空间。

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/40703/

**Comment by mmxzmmxz** [comment]
v +1

**Comment by mmxzmmxz** [comment]
验证通过
dde-file-manager 4.7.1.10-1
