### ISSUE TITLE
控制中心添加快捷键，触摸屏不支持键入快捷键

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#625]
【测试环境】：
onboard 1.4.1.3-1
dde-control-center 4.8.0-1
【测试步骤】：
1.进入控制中心切换语言--》添加快捷键，键入快捷键时，用触摸屏软键盘无法实现。

**Comment by zccrs** [comment]
这个必要性不大，就不处理了。软键盘本身是支持的，只是改了键盘布局，没有Ctrl Super 这些特殊按键
