### ISSUE TITLE
WPS升级之后，会在桌面上创建三个WPS图标

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#63]
【测试环境】
wps-office:
  已安装：10.1.0.6757
【预置条件】

【测试步骤】
1.WPS升级之后会在桌面上创建三个WPS应用程序的图标。
【预期结果】
1.不创建图标。
【测试结果】

【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181030165034](https://user-images.githubusercontent.com/14539782/47706502-4d81e980-dc64-11e8-8dd3-5155a214daf6.png)

**Comment by deepinzhangshuang** [comment]
无产品回复　　暂不处理
