### ISSUE TITLE
文件管理器-增加光盘格式支持 <z4>

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#630]
需求背景：
希望可以增加一些光盘格式的支持；
需求说明：

1. 支持直接加载ISO/MDS等光盘镜像格式；
2. 右键菜单“打开”替换成“挂载”，双击默认行为也是挂载；
3. 点击挂载后挂载到左侧侧边栏，其他功能同外接磁盘一样处理；

文案：
【挂载】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【挂载】【Mount】

**Comment by zccrs** [comment]
关联：https://github.com/linuxdeepin/internal-discussion/issues/455

**Comment by iamhyc** [comment]
可以增加 VHD 挂载吗，windows用户/虚拟机用户可能会创建这种格式的文件

**Comment by keybreak** [comment]
Sorry for interrupting internal discussion, since it's asked about VHD, i'd quote myself from here https://github.com/linuxdeepin/developer-center/issues/912

> Separate option for all mounteable type files (.iso .mds .ccd .cue .bwt .cdi .nrg .pdi .b5t .isz) would imporve usability a lot!
>
> And i guess also it would be a good practice to have some configuration file with all those filetypes listed, where you can add formats for this rmb option to show Mount (in case some new format will come out, or we missed something)

This way you won't get through the pain of adding / removing formats for this option which is good)

**Comment by zccrs** [comment]
> Sorry for interrupting internal discussion, since it's asked about VHD, i'd quote myself from here [linuxdeepin/developer-center#912](https://github.com/linuxdeepin/developer-center/issues/912)
> 
> > Separate option for all mounteable type files (.iso .mds .ccd .cue .bwt .cdi .nrg .pdi .b5t .isz) would imporve usability a lot!
> > And i guess also it would be a good practice to have some configuration file with all those filetypes listed, where you can add formats for this rmb option to show Mount (in case some new format will come out, or we missed something)
> 
> This way you won't get through the pain of adding / removing formats for this option which is good)

@BLumia @chirs241097

**Comment by BLumia** [comment]
> 可以增加 VHD 挂载吗，windows用户/虚拟机用户可能会创建这种格式的文件

初步支持中不会涵盖对 VHD 的挂载支持，后续可能会考虑

**Comment by liuwen123** [comment]
已添加
