### ISSUE TITLE
触摸屏双击文管标题栏，出现响应不灵敏或者窗口无响应情况

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#631]
【测试环境】：
hw本
dde-file-manager 4.7.1.8-1 
【测试步骤】：
1.触摸屏双击文管标题栏。
【预期结果】：
1.文管窗口放大、缩小。
【测试结果】：
1.经常性出现点击无响应情况；
  还有出现导致窗口无响应情况，用鼠标移动窗口也无响应。

**Comment by hualet** [comment]
这个在新的 ISO 上验证一下吧

**Comment by mmxzmmxz** [comment]
@hualet 该问题仍然存在

**Comment by zccrs** [comment]
> 这个在新的 ISO 上验证一下吧

改了环境变量？

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/40703/

**Comment by mmxzmmxz** [comment]
Verified+1

**Comment by mmxzmmxz** [comment]
验证通过
dde-file-manager 4.7.1.10-1
