### ISSUE TITLE
文管列表模式，触摸屏上下滑动容易触发选中多个文件的事件

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#632]
【测试环境】：
hw本
dde-file-manager 4.7.1.8-1
【测试步骤】：
1.文管切换至列表模式，显示内容超过一屏。触摸屏上下滑动。
【预期结果】：
1.显示内容会上下滚动。
【测试结果】：
1.会出现选中多个文件的操作。

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40762/ 调整了一下时间，试一下。
@justforlxz launcher中也改一下

**Comment by mmxzmmxz** [comment]
v+1

**Comment by mmxzmmxz** [comment]
验证通过
dde-file-manager 4.7.1.10-1
