### ISSUE TITLE
文件管理器右键打开方式不支持触摸屏上下滚动

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#636]
【测试环境】：
dde-file-manager 4.7.1.8-1
【测试步骤】：
1.选择某个应用，右键--》打开方式，触摸屏上下滑动。
【预期结果】：
1.界面可以上下滑动。
【测试结果】：
1.不响应触摸屏上下滑动。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40690/

**Comment by liuwen123** [comment]
+1

**Comment by mmxzmmxz** [comment]
验证通过
dde-file-manager  4.7.1.10-1
