### ISSUE TITLE
预装软件包 libstrongswan-standard-plugins 与 libstrongswan-extra-plugins

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#638]
解决：deepin连接预共享秘钥的L2TP/IPSec的VPN下，出现“连接vpn失败，原因未知” https://www.liangzl.com/get-article-detail-15851.html

**Comment by electricface** [comment]
libstrongswan-standard-plugins 应该提供了 文章作者需要的 strongswan openssl 插件

@deepinzhangshuang @hualet

**Comment by deepinzhangshuang** [comment]
下个iso验证

**Comment by liuwen123** [comment]
已添加
