### ISSUE TITLE
控制中心个性化模块的几个设置概率性出现了叠在一块的情况。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#641]
tower问题单转移：
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/1c7179ee2e3cf00b6fac6af424c7fbd5/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
