### ISSUE TITLE
建议在控制中心增加一个开关，可以显示和屏蔽桌面通知

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#643]
在控制中心增加一个开关，可以屏蔽桌面的通知显示，但是通知的信息还是会被记录在控制中心日志列表中

每次截图后，截图的通知在桌面显示时间太长了，有时需要连续截图时，就把上次的截图信息截进去了
而且有时候网卡连接接触不良，会不停的弹出网络断开、网络连接，弹出的提示太多了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
