### ISSUE TITLE
默认程序页面进去之后，很多默认程序没有的打钩

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#644]
接tower问题单转移：

https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/cc70527e70536dc740df53e8842961bf/

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40367/ 已修复

**Comment by liuwen123** [comment]
已修复
