### ISSUE TITLE
从dock的无线网络列表打开控制中心后未收起

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#646]
步骤：
设置 dock 模式：高效；
设置 dock 位置：下；
打开控制中心 -> 网络 -> 无线网络，删除 deepin ；
点击 dock 上的 wifi 图标，打开无线网络列表，点击 deepin；
此时发现 dock 的 无线网络列表并没有收起，可透过控制中心的半透明界面看到。

**Comment by listenerri** [comment]
**这个提交做了比较大的改动, 可能会受到影响的地方有以下几点, 高校模式和时尚模式都需要测试:**
1. dock 上每一项(包括应用图标和插件图标)的点击事件, 包括左键和右键
2. 托盘内图标的点击事件, 包括左键和右键
3. 托盘图标的 hover 以及 press 状态表示

https://cr.deepin.io/c/dde/dde-dock/+/40628

**Comment by listenerri** [comment]
这个 issue 问题不大, 而提交代码变动比较大, 且由于专业版的问题, 暂时不合并这个 CR

**Comment by liuwen123** [comment]
已修复
