### ISSUE TITLE
任务栏的挂载插件中的卷标没有翻译

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#65]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】

【测试步骤】
1.挂载本地磁盘分区之后，打开任务栏-挂载插件-查看挂载分区列表。
【预期结果】
1.分区列表中的卷标显示正常。
【测试结果】
1.卷标没有翻译。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181030173613](https://user-images.githubusercontent.com/14539782/47709325-fcc1bf00-dc6a-11e8-9f2b-516d59e889f6.png)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39464/ 忘了贴cr

**Comment by liuwen123** [comment]
已修复
