### ISSUE TITLE
网易云音乐保存朋友圈图片会导致软件崩溃

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#654]
接Tower任务：
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/da4b05482ccef92312314232445d2c7e/#47e27f002fa2f7664f0c8b9969a0ae09

**Comment by zhaofangfangdeepin** [comment]
netease-cloud-music  1.1.3+r14+gcb341669 
测试通过

**Comment by liuwen123** [comment]
已修复
