### ISSUE TITLE
一键切换黑白主题

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#657]
控制中心增加一键切换黑白主题的入口

1. 每个应用内主菜单改为一级菜单：主题，二级菜单：浅色主题、深色主题、跟随系统主题；
2. 应用内选择“跟随系统主题”的，在控制中心切换后当前应用一键随之生效；
3. 应用内选择“深色主题”、“浅色主题”的，不跟随系统一键选择生效；-
4. 开启深色模式, 所有dtk应用切到深色主题, gtk窗口主题自动切到deepin-dark,图标主题自动切到deepin-dark, 用户依然可以单独将窗口主题和图标主题切到别的；
![image](https://user-images.githubusercontent.com/34432879/49927718-8f57ae00-fef9-11e8-9d9f-2b31c885fc37.png)
文案：
【主题】
【深色主题】
【浅色主题】
【跟随系统主题】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【主题】【Theme】
【深色主题】【Dark theme】
【浅色主题】【Light theme】
【跟随系统主题】【System theme】

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
