### ISSUE TITLE
大启动器鼠标拖动到dock触发不灵敏

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#659]

**Comment by zccrs** [comment]
@justforlxz 更改之后的launcher应该没问题了吧

**Comment by justforlxz** [comment]
恩

zccrs <notifications@github.com> 于2018年12月20日周四 上午10:02写道：

**Comment by mmxzmmxz** [comment]
在触摸屏上用手指移动仍然不灵敏
dde-launcher 4.5.9-1

**Comment by justforlxz** [comment]
tag 4.6.0才加的
