### ISSUE TITLE
开机自启动的SNI托盘程序的右键菜单显示不出来

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#660]
除了搜狗输入法以外, 有不少程序比如goldendict, 开机自启后其托盘图标的右键菜单无法使用

**Comment by listenerri** [comment]
@hualet 应该也可以修复之前hplip-gui的问题:
https://cr.deepin.io/#/c/dde/dde-dock/+/40574

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
