### ISSUE TITLE
文件管理器-顶部工具栏

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#662]
需求背景：
顶部工具栏的框一直存在，部分用户误以为不能点击那个区域拖拽，以为拖拽区域很窄不方便使用，所以调整一下。
需求描述：

1. 顶部工具栏的框框默认不显示，点击放大镜按钮框框显示；
2. 通过点击进入目录时，路径样式改成设计图的样子；
3. 右键菜单增加：复制路径、在新窗口打开、在新标签中打开；
4. 在哪个目录名称上点击右键就执行这个目录的对应操作；

文案：
【复制路径】
@zhuxiujuancindy 

@shule1987 把我们协商后的设计图贴上来一下吧

**Comment by zhuxiujuancindy** [comment]
文案：
【复制路径】【Copy as path】

**Comment by liuwen123** [comment]
已添加
