### ISSUE TITLE
dock动效

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#663]
1. 时尚模式，dock 上的 item 拖动到 dock 外部触发的操作
2. 时尚模式，launcher 上的 item 拖动到 dock 上的操作
3. 高效模式，任务栏上的图标拖拽移除
4. 高效模式，从launcher 上拖拽图标到任务栏

**Comment by listenerri** [comment]
实现了 第 1 和 3 的动画(是一种动画不过是高校和时尚两种模式下)：

https://cr.deepin.io/c/dde/dde-dock/+/41946

**Comment by listenerri** [comment]
@liuwen123 上面的提交完成的两个动效的视频已经在 MM 上发给你了

@wangjia12 这个 15.9.3 带出去吧

**Comment by listenerri** [comment]
剩下的那个动效在这个 issue 里面处理：https://github.com/linuxdeepin/internal-discussion/issues/1070

**Comment by zhaofangfangdeepin** [comment]
目前只实现了放弃拖拽的时候，图标有动画，缓慢回到任务栏。
目前从动画的视频上看，现在有下面的功能点没有实现，产品看下是否继续实现：
1.程序拖出来时，图标变大 ----这个还没实现
2.程序拖出来时，任务栏收缩-----这个还没实现 
@wangjia12

**Comment by listenerri** [comment]
修复部分拖拽的图标显示不全，尤其是火狐的图标：
https://cr.deepin.io/c/dde/dde-dock/+/42010
