### ISSUE TITLE
控制中心 网络 同时连接有线与VPN，但有线连接不打钩<周三>

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#664]
步骤：
打开控制中心 -> 网络；
创建有线连接 “有线连接1”，并连接成功；
创建VPN PPTP 连接 "VPN PPTP 1"，并连接成功；
返回上级，点击有线网络，会发现 “有线连接1”并没有打钩。

**Comment by listenerri** [comment]
cr:
https://cr.deepin.io/c/dde/dde-control-center/+/41028

ci:
https://ci.deepin.io/job/dde-control-center-ci-debian/5190/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
