### ISSUE TITLE
多张壁纸轮换

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#666]
1. 勾选“自动更换壁纸”，显示后面的时间选择，默认设置为10分钟。不勾选时不显示，默认不勾选；
2. 可以选择时间间隔，也可以选择登录系统时更换或者唤醒后自动更换；
3. 壁纸也添加鼠标移入状态；
4. 播放顺序是一个循环内随机；
5. 多工作区使用同一个设置，但是只在当前正在使用的工作区更换壁纸，没有在使用的工作区不用在后面默默更换；
 

![image](https://user-images.githubusercontent.com/34432879/49993954-1d4b9b80-ffc3-11e8-966e-3917178819c3.png)

文案：
【自动更换壁纸】【Wallpaper Slideshow】
【壁纸】【Wallpaper】
【1m】【5m】【10m】【30m】【1h】
【登录时】【When login】
【唤醒时】【When wakeup】

**Comment by electricface** [comment]
壁纸轮换的顺序改怎么定？

**Comment by electricface** [comment]
dde-daemon: https://cr.deepin.io/#/c/dde/dde-daemon/+/41429
deepin-desktop-schemas: https://cr.deepin.io/#/c/deepin-desktop-schemas/+/41424/

**Comment by electricface** [comment]
每隔一段时间、登录时、唤醒时 是不互斥的，是否允许同时选中？

**Comment by wangjia12** [comment]
> 每隔一段时间、登录时、唤醒时 是不互斥的，是否允许同时选中？

是单选的 一次选一个

**Comment by electricface** [comment]
后端功能基本完成:

service: com.deepin.daemon.Appearance
path: /com/deepin/daemon/Appearance
interface: com.deepin.daemon.Appearance

增加属性 WallpaperRotationPolicy 类型 string，
可能的值：
login - 登录时
wakeup - 唤醒时
数字 - 时间间隔，单位秒，最小值1，比如 30 表示每隔30秒换一次。

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41688/ 前端已完成

**Comment by liuwen123** [comment]
+1

**Comment by keybreak** [comment]
+1
This is really cool feature!

I wanted to add only one thing, if not from moment of development and first release, but at least in the future you should definitely implement some mechanism to select group of pictures that will be rotated (just like Windows 7+), while random as default could be nice - not all pictures could be desirable (at least for me) :smile_cat:

For example i really like idea of 12 hour cycle change of wallpaper representing a day and night :night_with_stars: 

Maybe **Ctrl**+**Left mouse click** is a good variant for selection, and also then there should be some type of selection outlines (main blue accent color / white outline as with user avatars in Settings) or something, to indicate what's selected.

**Comment by zhaofangfangdeepin** [comment]
壁纸没有添加鼠标移入状态 @zccrs

**Comment by liuwen123** [comment]
已添加
