### ISSUE TITLE
dock在AppItem上滚轮显示App所有窗口太过灵敏

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#667]
在AppItem上使用鼠标滚轮或者触摸板双指滑动会调用窗管显示App所有窗口, 但是太过灵敏, 比如要显示窗口预览的同时又调用了显示所有窗口, 就有可能导致窗管卡死, 在AppItem的滚动事件里设置一个阀值应该可以减少这种情况出现的几率

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40620

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
