### ISSUE TITLE
使用指纹时，打开系统修复工具打开时，没有提示用户输入指纹

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#669]
接tower：
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/702dc140b89c213a5bd44e4fa63606fe/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
