### ISSUE TITLE
deepin-manual 看图图片管理说明需要删除

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#67]

**Comment by zhuxiujuancindy** [comment]
深度看图的帮助手册已经写完了，等15.8和文件管理器的帮助手册写完一起更新到深度帮助手册

**Comment by zccrs** [comment]
@zhuxiujuancindy 今天要把文档给我

**Comment by zhuxiujuancindy** [comment]
已经提交了，关于这个的任务太多了
https://tower.im/projects/ee4711959bf44c0e827d52e6908a3b92/todos/22a075afb5b846279f6fe186966f4554/#5a661df5ed2647078ad89fa36390b947

**Comment by liuwen123** [comment]
已删除
