### ISSUE TITLE
添加阿拉伯社区网站到论坛国际社区列表中

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#671]
http://deepinarabic.com

![image](https://user-images.githubusercontent.com/2023967/50096838-93663180-0253-11e9-915d-e830835dff9d.png)

**Comment by sarojpoudel33** [comment]
thanks @hualet

**Comment by hualet** [comment]
@sarojpoudel33 Hi, with the help of @wangjia12, @21wmd and the designer of the logo of course, we've put your website in the international forums list, welcome to the family :)
