### ISSUE TITLE
文管计算机界面，磁盘的右键菜单还是显示属性

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#673]
【测试步骤】
打开文件管理器，进入计算机页面，任意选中一个磁盘点击右键菜单，查看右键菜单显示

【预期结果】
属性被换成磁盘信息

【测试结果】
还是显示为属性

【问题级别】
一般

【出现概率】
100%

**Comment by zccrs** [comment]
计算机不是一个分区，这个不用替换成磁盘信息吧 @wangjia12

**Comment by wangjia12** [comment]
计算机不用替换，和下面的磁盘不一样
