### ISSUE TITLE
触摸屏的控制中心，使用软键盘输入控制中心隐藏

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#674]
【测试环境】：
dde-control-center 4.8.3-1
【测试步骤】：
1.联想笔记本，控制中心--》键盘布局、切换语言，使用软键盘输入，控制中心会隐藏，导致无法顺利输入。

**Comment by justforlxz** [comment]
tag 4.8.4

**Comment by mmxzmmxz** [comment]
验证通过
dde-control-center 4.8.7-1
