### ISSUE TITLE
触摸屏launcher，右键长按之后，很难进行单指点击操作 <周五>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#676]
【测试环境】：
 dde-launcher                     4.5.6-1               amd64
【测试步骤】：
1.使用的是联想的触摸屏，打开launcher，长按某个图标，出现右键，此时点击其他地方取消右键；
2.点击点击其他图标。
【测试结果】：
2.单指点击无响应。
【预期结果】：
2，可以响应。
【重现概率】：
2.100%重现。

**Comment by mmxzmmxz** [comment]
@zccrs 这个问题仍然存在～

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
