### ISSUE TITLE
智能镜像源提示文案位置需要修正

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#677]
【测试环境】：
dde-control-center               4.8.3-1               amd64 
【测试步骤】：
1/，进入控制中心--》更新设置，查看智能镜像源提示文案显示位置。
【测试结果】：
1.左右上下位置均需调整，与其他提示文案保持一致。

**Comment by mmxzmmxz** [comment]
![image](https://user-images.githubusercontent.com/12388744/50134964-6b1b1900-02cd-11e9-9fa4-c68160704196.png)

**Comment by liuwen123** [comment]
已修复
