### ISSUE TITLE
修改时间设置时钟显示不对  <周五>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#678]
【测试步骤】
打开控制中心进入时间，点击修改时间设置，查看钟表显示

【预期结果】
钟表时间和当前系统时间保持一致

【测试结果】
时间显示不正确

【问题级别】
一般

【出现概率】
100%
![_ _20181218141712](https://user-images.githubusercontent.com/12492745/50135633-d36afa00-02cf-11e9-8fec-2163e9d310fc.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40772/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
