### ISSUE TITLE
控制中心WiFi列表顺序会到处乱串<下周一>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#679]
【测试步骤】
打开控制中心网络，进入WiFi列表，查看WiFi列表显示

【预期结果】
WiFi列表按字母排序，不会乱串

【测试结果】
每次连接一个WiFi后，WiFi列表都会重新刷新，WiFi顺序会乱串

【问题级别】
一般

【出现概率】
100%

**Comment by zccrs** [comment]
这个列表是按信号强度排序的吧

**Comment by liuwen123** [comment]
iPhone是按照名称来排序的，当前控制中心就是按信号强度来排序的，但是有问题
假如当前有10个WiFi列表，每个信号都是满格，在控制中心连接WiFi的时候会上下乱窜的

**Comment by wangjia12** [comment]
我观察了一下，我们的列表并没有一直乱窜。如果新加入一个WiFi，按名称排列也应该是会刷一遍位置的。
但是上面这种情况10个满格，会上下乱窜 @zccrs 这个要看看吧  都是满格就应该固定一个顺序在最上面啊 是不是太灵敏了。

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/dde-control-center/pull/158
