### ISSUE TITLE
动画还没有停，点击更新设置，会导致控制中心崩溃

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#681]
【测试步骤】
打开控制中心，点击侧边栏的更新按钮，在滚动还没有停止的时候点击更新设置按钮

【预期结果】
可以正常进入更新设置界面

【测试结果】
会导致控制中心崩溃

【问题级别】
严重

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40684/

**Comment by liuwen123** [comment]
已修复
