### ISSUE TITLE
更新自动下载更新提醒的文案

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#682]
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/fb9a627c5fec2cc90170636761d88a56/#52821ab1d1abcf958113537b195178e4

**Comment by wangjia12** [comment]
这里文案改为：
【开启自动下载更新，会在有无线网络和有线网络的情况下自动下载】
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案改为：
【开启自动下载更新，会在有无线网络和有线网络的情况下自动下载】
【Switch it on to automatically download the updates in wireless or wired network.】

**Comment by justforlxz** [comment]
已经更新

**Comment by liuwen123** [comment]
已更新
