### ISSUE TITLE
控制中心的密码不一致提示有中文的句号，去掉这个句号，和别的提示信息保持一致，因为别的提示信息都是没有句号的

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#683]
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/11cccdb51c1a042c45561193e0c0c7fa/#7e80ee8b68f909ec7446d3dc4a27f97f

**Comment by listenerri** [comment]
控制中心所有单句短句, 不适用任何标点符号

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41311

**Comment by listenerri** [comment]
使用内网最新版控制中心测试

**Comment by liuwen123** [comment]
已修复
