### ISSUE TITLE
控制中心快捷键不显示 <周五>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#684]
【测试步骤】
在终端中杀死控制中心，然后点击时间日期--时间设置，然后点击左上角的返回按钮，再点击侧边栏的键盘和语言，点击快捷键

【预期结果】
可以正常列出快捷键显示

【测试结果】
快捷键显示为空

【问题级别】
一般

【出现概率】
100%
![_ _20181219114254](https://user-images.githubusercontent.com/12492745/50197868-125a8780-0384-11e9-8281-8083bcd738a3.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/40771/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
