### ISSUE TITLE
启动器小窗模式，搜索框输入关键字后按一下 Tab 键，应用程序不会被高亮

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#685]
https://tower.im/projects/e4ae1ad0b5d5497fb4b7c14fe2d2efbf/todos/5f30078ab32eb48eb225c696b7c917f7/

**Comment by liuwen123** [comment]
+1

**Comment by 21wmd** [comment]
@deepinzhangshuang 专业版中会集成这个修复吧
