### ISSUE TITLE
从终端打开编辑器，显示为英文

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#686]
【测试步骤】
打开终端输入：dedit，查看编辑器显示

【预期结果】
编辑器显示为中文

【测试结果】
编辑器显示为英文

【问题级别】
一般

【出现概率】
100%

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40704/

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/40709/

**Comment by liuwen123** [comment]
+1
