### ISSUE TITLE
时尚模式下隐藏小图标，重启dock后小图标会自动展开

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#688]
【测试步骤】
将dock切换到时尚模式，然后隐藏小图标，在终端中重启dock，查看dock显示

【预期结果】
还是隐藏小图标

【测试结果】
小图标自动展开

【问题级别】
一般

【出现概率】
100%

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40711

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
