### ISSUE TITLE
将系统调整为改成：नेपाल，dock时间不显示

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#691]
【测试步骤】
将dock设置为时尚模式，然后把系统语言改成：नेपाल，查看时间显示

【预期结果】
时间显示正常

【测试结果】
时间显示为空白

【问题级别】
一般

【出现概率】
100%
![deepinscreenshot_select-area_](https://user-images.githubusercontent.com/12492745/50270677-5e352b80-046d-11e9-805c-62b197cd39fb.png)

**Comment by sarojpoudel33** [comment]
I can contribute Native Nepali language.

**Comment by sarojpoudel33** [comment]
दीपिन चलचित्र = Deepin Movie
दीपिन संगीत = Deepin Music
दीपिन फाइल मेनेजर = Deepin File Manager
लन्चर = launcher
क्यालेन्डर = Calender
क्याल्कुलेटर = calculator.

**Comment by hualet** [comment]
> दीपिन चलचित्र = Deepin Movie
> दीपिन संगीत = Deepin Music
> दीपिन फाइल मेनेजर = Deepin File Manager
> लन्चर = launcher
> क्यालेन्डर = Calender
> क्याल्कुलेटर = calculator.

you can contribute translations directly on transifex.

**Comment by sarojpoudel33** [comment]
How can I contribute Nepali Language. @hualet

**Comment by hualet** [comment]
> How can I contribute Nepali Language. @hualet

@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
> How can I contribute Nepali Language. @hualet

i18n for deepin
Users joining for i18n project can visit https://www.transifex.com and register to apply for the official i18n user group https://www.transifex.com/linuxdeepin/public/, we will regularly verify the request and send notification by transifex directly.

**Comment by liuwen123** [comment]
+1

**Comment by sarojpoudel33** [comment]
![deepinscreenshot_desktop_](https://user-images.githubusercontent.com/45546591/50476430-3ce5b980-09f0-11e9-836a-cc51c8507bf8.png)

**Comment by sarojpoudel33** [comment]
oh!

**Comment by liuwen123** [comment]
已修复
