### ISSUE TITLE
深度系统监视器-目标应用进程流量显示

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#693]
有用户反馈深度系统监视器不能很好的反应应用程序的流量，这个用户提出的是浏览器。我也不能确认这个用户的浏览器除了视频播放之外是否还存在其他网络进程，但我们可以先自查一下，或者评估我们当初的测试用例是否覆盖此类场景。
https://feedback.deepin.org/feedback/detail/22252

@deepinzhangshuang

**Comment by deepinzhangshuang** [comment]
可能算法不一样，和浏览器自己监控的下载速度有所差异。

**Comment by deepinzhangshuang** [comment]
@zccrs 看下是否需要处理

**Comment by zccrs** [comment]
> @zccrs 看下是否需要处理

这个项目现在还没有人有时间接手，暂不处理

**Comment by hualet** [comment]
我测试了一下，Firefox、Chrome、360浏览器观看 Youtube 网页视频，浏览器上传下载流量是会正常显示的。
