### ISSUE TITLE
在dock上会显示两个虚拟键盘图标

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#696]
【测试步骤】
升级到最新dock，查看dock小图标显示

【预期结果】
只显示一个虚拟键盘图标

【测试结果】
会显示两个虚拟键盘图标

【问题级别】
一般

【出现概率】
100%
![_ _20181224101141](https://user-images.githubusercontent.com/12492745/50389381-9934a900-0764-11e9-9ddf-670df4d2cc4a.png)

**Comment by zccrs** [comment]
@hualet 它的托盘没有被干掉吗

**Comment by hualet** [comment]
实际上托盘是被干掉的，不过 onboard 使用的是 libappindicator ，Dock 没有处理好 StatusNotifierItem 的 Status 是 Passive 的情况，这种情况下应该是要隐藏图标的。
 @listenerri 说已经给 libappindicator 的应用全部fallback到xembed模式，不过打过patch的包应该没有推到仓库。

**Comment by listenerri** [comment]
我试了下打过补丁的 libappindicator 不过 onboard 却还是在走 SNI 协议, 所以还是修了这个问题, 相关 issue: https://github.com/linuxdeepin/internal-discussion/issues/746
