### ISSUE TITLE
DDE在双屏的主屏切换时出现的问题

### ISSUE THREAD

**Issue by deadlineOvO** [linuxdeepin/internal-discussion#698]
【测试环境】
Arch 安装了 deepin与deepin-extra两个软件包
使用的桌面环境为dde
最后一次 pacman -Syu 时间：2018-12-25 09:22
【预置条件】
使用了两个屏幕的设备
多屏方法为扩展
已经拥有一个双屏配置
【测试步骤】
首先，在配置中将任意一屏设置为主屏
然后切换主屏
任意调整屏幕位置数次
主屏切换为第一次设置时屏幕
【预期结果】
桌面的应用程序与底栏应该立刻切换到主屏
【测试结果】
桌面应用程序与底栏并没有切换到主屏
【问题级别】
较高
【出现概率】
较高概率重现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
