### ISSUE TITLE
多屏时触摸屏需要设置映射关系

### ISSUE THREAD

**Issue by jouyouyun** [linuxdeepin/internal-discussion#699]
多屏时, 其中至少有一个触摸屏, 触摸屏默认映射在第一个 output 上, 但可能出现触摸屏并不是第一个 output, 此时在触摸屏上的手势操作就会响应在另一个屏幕上, 这是错误的.

这时就需要主动修正触摸屏的映射关系, 需要知道触摸屏的 `device id(xinput)` 和 `output name(xrandr)`, 然后使用 `xinput --map-to-output <device id> <output name>` 来设置映射关系.

这需要在 `display` 模块中处理, 每次调整多屏模式时都需要修正一下.

@hualet @electricface

**Comment by electricface** [comment]
没法确定 触摸屏设备 与 显示器设备的关联，也许需要一个硬件数据库。

**Comment by jouyouyun** [comment]
触摸屏中触摸的设备与显示的设备是不同的, 两者间没发现联系, 需要手动映射

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
