### ISSUE TITLE
深度看图复制图片到剪切板，粘贴到WPS中会导致WPS卡死

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#702]
【测试步骤】
进入/usr/share/wallpapers/deepin 目录，使用深度看图打开desktop.jpg图片，然后右键--复制到剪切板，然后打开WPS粘贴进去

【预期结果】
可以粘贴成功

【测试结果】
会导致WPS卡死，eog不会

【问题级别】
一般

【出现概率】
100%

**Comment by zccrs** [comment]
@electricface 只有后端改了剪切板相关的

**Comment by electricface** [comment]
这是深度看图的bug， qxcb 有一条报错，说明是超过了 请求的最大长度了。
             0] QXcbConnection: XCB error: 16 (BadLength), sequence: 7559, resource id: 115343443, major code: 18 (ChangeProperty), minor code: 0

**Comment by rekols** [comment]
看图有两个选项：复制、复制到粘贴板，"复制"选项是用了 x-special/gnome-copied-files 的 mime data 格式，所以没什么问题，“复制到粘贴板”是把图片的二进制拷贝到了粘贴板，然后就提示超过长度了....

感觉复制到粘贴板可以去除。。。

**Comment by electricface** [comment]
改成用 INCR 机制实现大数据的传输即可。https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#large_data_transfers

**Comment by zccrs** [comment]
> 改成用 INCR 机制实现大数据的传输即可。https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#large_data_transfers

好的，又可以给Qt提个patch了

**Comment by rekols** [comment]
https://bugreports.qt.io/browse/QTBUG-8644

**Comment by zccrs** [comment]
> 改成用 INCR 机制实现大数据的传输即可。https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#large_data_transfers

看了下，Qt用的就是INCR

**Comment by zccrs** [comment]
[fix_clipboard_big_image_data.patch.txt](https://github.com/linuxdeepin/internal-discussion/files/2739157/fix_clipboard_big_image_data.patch.txt)

给Qt的patch
@deepinzhangshuang 把 .txt 的后缀去掉。

**Comment by zccrs** [comment]
> [fix_clipboard_big_image_data.patch.txt](https://github.com/linuxdeepin/internal-discussion/files/2739157/fix_clipboard_big_image_data.patch.txt)
> 
> 给Qt的patch
> @deepinzhangshuang 把 .txt 的后缀去掉。

@liuwen123 同时验证此问题 https://github.com/linuxdeepin/internal-discussion/issues/712

**Comment by deepinzhangshuang** [comment]
@liuwen123  已经更新qt到 ppa/dde-panda
