### ISSUE TITLE
dock预览招商银行显示为空白

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#703]
【测试步骤】
打开招商银行，将鼠标移动到dock图标上

【预期结果】
显示正常

【测试结果】
显示为空白

【问题级别】
一般

【出现概率】
100%
![_ _20181225170835](https://user-images.githubusercontent.com/12492745/50418707-e6e60a00-0867-11e9-9baf-b6cf22fbbcbf.png)

**Comment by hualet** [comment]
@linuxdeepin/wine-team 能不能看一下？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
