### ISSUE TITLE
文件管理器中同时选中svg和png图片无法使用深度看图打开

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#705]
- [x]  深度开头desktop的图片文件关联中添加 image/svg+xml 等svg图片相关的mimetype @rekols 
- [ ]  文件管理器判断多文件打开时，如果此文件的默认打开程序是目标程序时也认为此程序可以打开此文件（不仅仅是当目标程序支持的mimetype列表中包含此文件的mimetype）@BLumia

**Comment by rekols** [comment]
看图desktop：https://cr.deepin.io/#/c/deepin-image-viewer/+/40915/
