### ISSUE TITLE
Dock 支持 AppImage 程序图标显示

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#707]
现在 Dock 上一直显示的是未知程序图标

**Comment by electricface** [comment]
有的appimage 程序会在启动前询问是否需要集成到系统中，比如 sabaki (https://github.com/SabakiHQ/Sabaki/releases)，选择集成到系统中会自动在 ~/.local/share/applications/ 目录下创建 desktop 文件。之后就可以靠 bamf 识别正确了。

**Comment by zccrs** [comment]
@electricface 图标查找时需要添加 appimage 文件解压出的路径

**Comment by listenerri** [comment]
> @electricface 图标查找时需要添加 appimage 文件解压出的路径

如果程序被驻留到 dock 上，且没有启动程序，那这时候有解压后的路径吗？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
