### ISSUE TITLE
分区编辑器授权对话框没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#71]
【测试环境】
gparted：0.30.0-3

【测试步骤】
点击分区编辑器，查看授权对话框显示

【预期结果】
授权对话框显示正常

【测试结果】
授权对话框没有翻译

【出现概率】
100%
![_dde-polkit-agent_20181030193208](https://user-images.githubusercontent.com/12492745/47715460-d572ee00-dc7a-11e8-840f-af06c51ac5f7.png)

**Comment by deepinzhangshuang** [comment]
@zccrs  搞个翻译吧

**Comment by wangjia12** [comment]
【运行分区编辑器需要进行身份验证】

**Comment by zccrs** [comment]
@deepinzhangshuang 已经更新到patch项目了

**Comment by zccrs** [comment]
stable 验证

**Comment by zhaofangfangdeepin** [comment]
stable 环境验证通过
