### ISSUE TITLE
安装skype，dock托盘图标显示错误

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#710]
【测试步骤】
安装Skype，然后打开查看dock图标显示

【预期结果】
显示正确

【测试结果】
显示为齿轮

【问题级别】
一般

【出现概率】
100%
![_ _20181228093609](https://user-images.githubusercontent.com/12492745/50499690-a1535800-0a86-11e9-96a6-020aac0c0eba.png)

**Comment by listenerri** [comment]
The QDirIterator class provides an iterator for directory entrylists.

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/41046

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
