### ISSUE TITLE
屏幕键盘托盘图标状态应该与任务栏插件状态统一

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#716]
第一，目前的状况是在任务栏开启了屏幕键盘的插件后，托盘图标中会出现一个我们自己画的屏幕键盘图标。通过这个图标，可以启动屏幕键盘。但通过这个我们自己画的托盘图标启动屏幕键盘后，托盘中又会出现一个屏幕键盘的托盘图标。也就是说，这个时候屏幕键盘在托盘区域有两个托盘图标。这个有点奇怪，理论上应该只有一个屏幕键盘的托盘图标才对。

第二，从任务栏的插件中关闭屏幕键盘插件后，我们自己画的屏幕键盘托盘图标就被删除，但托盘区域还是有一个屏幕键盘的托盘图标，这个逻辑也是有问题的。如果我们希望通过任务栏的插件来管理屏幕键盘，那就应该只有任务栏插件管理这一个维度的控制，但现在的现状是任务栏中屏幕键盘的插件只能够打开屏幕键盘，而无法进行关闭。

我觉得应该将屏幕键盘的两个托盘图标合并为一个。

**Comment by listenerri** [comment]
最新版本的 dock 已经修复了, 请检查问题是否依然存在

**Comment by liuwen123** [comment]
已修复
