### ISSUE TITLE
通过点击启动器（小窗模式）的时间和设置时，呼出控制中心的展示页面应该有区别

### ISSUE THREAD

**Issue by 21wmd** [linuxdeepin/internal-discussion#718]
当通过点击启动器（小窗模式）的时间和设置时（先点击时间，再点击设置），呼出的控制中心界面停留在时间设置模块，这个是有歧义的。点击设置呼出控制中心时，显示的应该是控制中心的首页。就像托盘中的电源图标，无论之前控制中心停留在哪个模块，点击电源图标后，弹出的都是电源设置模块界面。
@wangjia12

**Comment by wangjia12** [comment]
这两个行为不一样吧
点击某个指定的模块当然是去指定的地方
如果点控制中心只是把控制中心展示出来，如果之前没有打开指定模块就是显示首页，如果之前有已经展示的页面就显示之前的页面
就好像手动打开控制中心选了一个界面，收起来再打开还是会显示这个界面。

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=154
