### ISSUE TITLE
深度影院最大化后点击右键--mini模式功能无效<下周三>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#719]
【测试步骤】
使用深度影院打开视频，然后最大化播放， 在最大化的过程中点击右键--mini模式

【预期结果】
深度影院窗口mini播放

【测试结果】
mini模式无效

【问题级别】
一般

【出现概率】
100%

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/deepin-movie-reborn/+/41433/

存在一些问题：

https://github.com/linuxdeepin/deepin-movie-reborn/blob/34f3621efdbae9b070f7cde2e8fdab9511df2827/src/common/mainwindow.cpp#L1361

这里刻意的写了当前是最大化时这里返回 false 禁止切换到 mini 模式，最初的具体原因是什么？

https://github.com/linuxdeepin/deepin-movie-reborn/blob/34f3621efdbae9b070f7cde2e8fdab9511df2827/src/common/mainwindow.h#L213

另外，这次修改了 `SBEM_Maximized` 这个枚举的值，原本和 `SBEM_Fullscreen` 相等，原因是什么？这里的修改可能造成的影响包括这些情况，我不太清楚原本的目的：

https://github.com/linuxdeepin/deepin-movie-reborn/blob/34f3621efdbae9b070f7cde2e8fdab9511df2827/src/common/mainwindow.cpp#L2717

**Comment by BLumia** [comment]
cc @sonald

**Comment by sonald** [comment]
> 这里刻意的写了当前是最大化时这里返回 false 禁止切换到 mini 模式，最初的具体原因是什么？
年代久远，不记得了。有可能是存在一些无法逾越的问题。没事， 你可以取消，然后看看有什么问题，随便改：）

> 另外，这次修改了 SBEM_Maximized 这个枚举的值，原本和 SBEM_Fullscreen 相等，原因是什么？这里的修改可能造成的影响包括这些情况，我不太清楚原本的目的：
不记得了，也有可能是写错了吧。好像也没用到。。。
