### ISSUE TITLE
dde-api在安装过程中，会在终端打印很多类似调试信息

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#72]
【测试环境】
Deepin15.8 
dde-api:
  已安装：3.2.0-1
【预置条件】

【测试步骤】
1.在Deepin15.7的环境上，添加仓库，升级到15.8
2.升级完成之后，打开终端，查看升级的日志。
【预期结果】
1.升级的日志正常，没有调试相关的信息。
【测试结果】
dde-api包会打印一些调试相关的信息。
【问题级别】
提示
【出现概率】
稳定出现。

**Comment by zhaofangfangdeepin** [comment]
图片：
![_ _20181031095900](https://user-images.githubusercontent.com/14539782/47761657-3ee31300-dcf4-11e8-984d-fa242a70c9b2.png)

**Comment by electricface** [comment]
已经修正 https://cr.deepin.io/#/c/dde/dde-api/+/39334/

**Comment by zhaofangfangdeepin** [comment]
测试通过
