### ISSUE TITLE
系统监视器无法显示迅雷下载速度

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#725]
【测试步骤】
使用迅雷进行下载，然后在系统监视器中查看下载速度显示

【预期结果】
可以正常显示

【测试结果】
无法显示

【问题级别】
一般

【出现概率】
100%
![image](https://user-images.githubusercontent.com/12492745/50533964-c96ab600-0b6f-11e9-9f4f-5d391f14cc7a.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
