### ISSUE TITLE
编辑器识别文件编码会发生变化

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#727]
【测试步骤】
使用深度编辑器打开sh文件，查看编码识别显示

【预期结果】
每次识别显示一致

【测试结果】
每次识别显示不一致

【问题级别】
一般

【出现概率】
100%
![_ _20181229164135](https://user-images.githubusercontent.com/12492745/50535855-363e7a00-0b89-11e9-8feb-f4680b547fea.png)

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/41025/

**Comment by rekols** [comment]
这个暂时无解，应该是 libkf5syntaxhighlighting 识别的问题

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
