### ISSUE TITLE
12.24-12.29 更新内容总结

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#728]
## crp 日志：

    修复在dock上按下鼠标左边不释放，滚动鼠标滚动界面卡死

    deepin-mutter:

    增加对无效窗口id的检查，修复在切换浏览器窗口和其它应用窗口时可能会崩溃

    deepin-metacity:

    增加对无效窗口id的检查，修复在切换浏览器窗口和其它应用窗口时可能会崩溃

    deepin-music:

    修复在没有配置文件时首次选择文件，初始位置不正确的问题

    qt5dxcb-plugin:

    支持Qt 5.12.0

    修复启动器从mini切到全屏模式后无法拖拽图标到任务栏

dtkwidget:

    将 DSegmentedHighlight 类更改为 D-Point 结构

    更新 DSegmentedHighlight 控件样式，符合新的设计

    设置对话框支持触屏滚动

    DTiltebar 和 DBlurEffectWidget 增加中文文档

    dde-qt-dbus-factory:

    更新dbus接口

    dde-introduction:

    更新检查切换窗管的接口

    dde-control-center:

    修复键盘模块导致崩溃

    默认禁用密码强度检查

    dde-launcher:

    修复触屏无法在分类列表点击

    startdde:

    WMSwitcher 增加方法 AllowSwitch

    dde-file-manager:

    修复了用户目录检查纠错脚本中的错误

    检查如果模板目录被禁用（即被设置为家目录）则不启用对应的模板目录功能 #713

    live 系统中不再进行自动挂载（检测内核参数 boot=live 时自动挂载功能不再有效） #711

    部分 UI 调整和错误修复
    deepin-installer:

    修复uefi下无法探测windows来调整时间（安装deepin后重启到windows时间不对）

    修复高级安装模式下删除新建的分区时崩溃

dde-daemon:

    修复复制图片到剪切板后无法粘贴到wine程序内（如QQ、微信）

**Comment by zccrs** [comment]
@wangjia12 @zhuxiujuancindy @deepinzhangshuang @hualet

**Comment by zccrs** [comment]
@sonald @Iceyer @justforlxz @rekols @electricface @listenerri @BLumia 有漏掉的内容还请大家补充一下

**Comment by zccrs** [comment]
@deepinzhangshuang 麻烦更新一下Udisks2的patch，补充一下更新日志

**Comment by deepinzhangshuang** [comment]
ppa/dde-panda unstable  已经更新上述tag

**Comment by deepinzhangshuang** [comment]
@zccrs 补充15.9更新内容到此任务中

**Comment by zccrs** [comment]
## 15.9 更新内容
### 完成的需求：
* 增加屏幕保护功能（设置入口和壁纸一致）

### 修复的bug：
deepin-appstore:
* 增加了在线应用列表功能
* 支持自动同步安装应用
* 支持查看捐献列表和时间
* 支持查看自己的所有评论
    
    deepin-sync-client:
* 数据同步功能客户端
    
    deepin-sync-daemon:
* 数据同步功能服务端
    
    dde-session-ui:
* 修复登录界面的版本描述没有跟随用户语言
* 修复登录界面logo有截断
    
    qt5dxcb-plugin:
* 修复当一个最大化窗口下面有一个最大化的DTK窗口时，双击标题栏恢复最大化后窗口消失

qcef:
* 支持自定义HTTP协议的头部
    
    onboard:
*   添加了desktop翻译
    
    dtkcore:
* 更新版本号和dtkwidget库保持一致
    
    dtkwidget:
* 修复使用触摸屏滚动设置对话框时会同时导致窗口移动

**Comment by zccrs** [comment]
deepin-image-viewer:
* 修复无法双击打开 svg 文件
* 修复右下角预览关闭按钮不显示
* 修复鼠标样式问题
* 修复打开图片无法自适应
    
    deepin-movie-reborn:
* 优化字幕字体样式
* 播放电影时保持屏幕常亮
    
    deepin-terminal:
* 支持鼠标中键关闭标签页 deepin-terminal#88
* 支持选中文字后自动复制文字到剪切板（默认关闭该功能） deepin-terminal#89
* 修复大写锁定或数字锁定开启时，“Ctrl+点击”不能在浏览器中打开链接的问题 deepin-terminal#81
* TravisCI 构建支持，更新翻译
    
    dde-file-manager:
* 修复在计算机页面右键菜单打开磁盘时会提示“卷未实现挂载”的错误提示
    
    deepin-desktop-base:
*  更新15.9 info 信息
    
    dde-daemon:
* 修正在谷歌浏览器中单指长按，出现右键菜单出现又消失的问题
    
    deepin-desktop-schemas:
* com.deepin.dde.touchscreen 增加 longpress-blacklist 设置
    
    deepin-editor:
* 优化触屏体验
    
    dde-api:
* 移除依赖 grub-common
    
    go-lib:
* 修正打包失败
* dbus 包 在  systemd 240+ 下不能找到 session bus
    
    deepin-installer-reborn:
* 修复高级模式无法删除分区

**Comment by deepinzhangshuang** [comment]
* deepin-boot-maker
修复按空格时弹出格式化对话框问题
修复Deepin系统下工具名称

**Comment by liuwen123** [comment]
更新已推送
