### ISSUE TITLE
建议改进头像设置，提供调整裁剪位置和预览功能

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#729]
这是 oschina 修改头像的界面：
![image](https://user-images.githubusercontent.com/3241440/50538351-4c5c3280-0ba9-11e9-88e0-42c95938d015.png)

![image](https://user-images.githubusercontent.com/3241440/50538369-a52bcb00-0ba9-11e9-9bd2-f38a16a0c6c9.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
