### ISSUE TITLE
欢迎视频需要更新，里面的控制中心和任务栏相关的图片需要更新

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#73]
【测试环境】
Deepin15.8
【预置条件】

【测试步骤】
1.Deepin15.8刻录安装之后，登录系统。
2.打开视频目录-播放介绍视频。
【预期结果】
1.介绍视频的图片都是最新的
【测试结果】
1.视频中的控制中心和任务栏没有更新。
【问题级别】
提示
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
视频还在做

**Comment by wangjia12** [comment]
前几天已经在做了

**Comment by zccrs** [comment]
这个可以验证了吧

**Comment by zhaofangfangdeepin** [comment]
测试通过
