### ISSUE TITLE
在登录界面，点击屏幕键盘按钮，会导致界面黑屏

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#732]
【测试步骤】
在用户登录界面，点击屏幕键盘按钮

【预期结果】
可以弹出屏幕键盘

【测试结果】
会导致界面黑屏

【问题级别】
严重

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41075/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
