### ISSUE TITLE
在注销界面，点击关机按钮，在关机界面按→键，移动到待机按钮上，屏幕就黑屏了

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#734]
【测试步骤】
在注销界面，点击关机按钮，弹出关机界面，然后按→键移动到待机按钮上

【预期结果】
可以正常移动

【测试结果】
移动到待机按钮上后，屏幕就黑屏了

【问题级别】
严重

【出现概率】
100%

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41062/

**Comment by liuwen123** [comment]
已修复
