### ISSUE TITLE
新建用户，第一次登录时会提示密码错误<周二>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#735]
【测试步骤】
在控制中心新建用户a,b,c，然后注销系统，切换用户a进行登录

【预期结果】
可以正常登录

【测试结果】
输入的密码是正确的，但是第一次登录时会提示密码错误

【问题级别】
严重

【出现概率】
100%

**Comment by mmxzmmxz** [comment]
如果用户密码为大写字母，则每次登录第一次输入密码均提示错误。

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
