### ISSUE TITLE
用户注销后，会弹出错误信息

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#736]
【测试步骤】
登录用户，然后注销系统，在系统注销的过程中查看界面显示

【预期结果】
注销成功后会直接跳到登录界面

【测试结果】
在注销的过程中会有错误信息显示，再会跳转到登录界面

【问题级别】
一般

【出现概率】
100%

![_20190102171958](https://user-images.githubusercontent.com/12492745/50586011-a82d0100-0eb2-11e9-82a2-38f5bee59c19.jpg)

**Comment by Iceyer** [comment]
@jouyouyun 这个日志看看能不能处理一下

**Comment by jouyouyun** [comment]
@liuwen123 更新后测试下

**Comment by liuwen123** [comment]
已修复
