### ISSUE TITLE
在锁屏界面的关机界面中，按→键会解锁屏幕

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#738]
【测试步骤】
按Super+L锁屏，点击关机按钮，在关机界面一直按→键

【预期结果】
会循环选中

【测试结果】
跳到待机后，再按→键会解锁屏幕

在锁屏界面，点击屏幕键盘按钮，也会解锁

【问题级别】
严重

【出现概率】
100%

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41062/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
