### ISSUE TITLE
dock 后端提供插件设置的保存功能

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#739]
为了方便进行云同步，把前端的插件设置放在后端。

com.deepin.dde.daemon.Dock interface
增加方法
GetPluginSettings() -> string
SetPluginSettings(jsonStr string)
MergePluginSettings(jsonStr string)    合并插件设置集
RemovePluginSettings(key1 string, key2List []string)  删除设置，key1 为要删除的第一级map的键，key2List 为要删除的第二级 map 的键列表，如果 key2List 为空，则当作指定了第一级map 键 key1 下的二级 map 的所有键 。

增加信号
PluginSettingsSynced()    云同步后发出此信号

pluginSettings 的json 格式为
{
    "插件id" : {  "设置1": 值1， "设置2": 值2 }，
   ...
}

比如 
```json
{
	"datetime": {
		"24HourFormat": true,
		"enable": true,
		"pos_1": 1,
		"pos_2": 2
	},
	"onboard": {
		"enable": false,
		"pos_onboard_1": 9
	}
}
```

后端将此json保存在 gsettings com.deepin.dde.dock plugin-settings 中。

**Comment by electricface** [comment]
dde-daemon: https://cr.deepin.io/#/c/dde/dde-daemon/+/41054/
deepin-desktop-schemas: https://cr.deepin.io/#/c/deepin-desktop-schemas/+/41052/

**Comment by listenerri** [comment]
使用后端提供的 dbus 接口存取插件的配置:
https://cr.deepin.io/c/dde/dde-dock/+/41262

**Comment by electricface** [comment]
功能完成

**Comment by electricface** [comment]
还需要处理 PluginSettingsSynced 信号

**Comment by listenerri** [comment]
新增移除插件配置的接口:
https://cr.deepin.io/c/dde/dde-dock/+/41624
