### ISSUE TITLE
文件管理器-计算机页面-磁盘右键-打开。可以正常打开，但是会报 “卷未实现挂载” 错误

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#741]
【测试环境】
dde-file-manager:
  已安装：4.7.1.10-1

【测试步骤】
1.打开文件管理器-计算机页面
2.在本地任意磁盘上右键-打开

【测试结果】
1.打开正常，但是会弹报错框“卷未实现挂载”

cc: @yefeifei @zhaofangfangdeepin 
来自：[Bugzilla-14428](https://bugzilla.deepin.io/show_bug.cgi?id=14428)

**Comment by liuwen123** [comment]
已修复
