### ISSUE TITLE
launcher 图标找不到的改进方案<z3>

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#745]
从后端收到 ItemChanged created 信号，添加上新的 desktop。搜索desktop 的图标，但是没有找到。
把没有找到图标的item 记录在列表A 中。

监控 /usr/share/icons/hicolor/ 文件夹，如果发现 文件夹下的 icon-theme.cache 文件发生了改变，
说明有新的图标被添加了，遍历 列表A中的 item，为它们搜索图标，如果 item 的图标找到了，就移除 item 出列表 A。

@zccrs @listenerri @justforlxz

**Comment by zccrs** [comment]
意思是安装包的时候 desktop 放进去的时候图标还不在吗

**Comment by electricface** [comment]
应该是的

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/41781/

**Comment by electricface** [comment]
测试通过
