### ISSUE TITLE
重启系统在登录界面点击屏幕键盘按钮，无法弹出屏幕键盘

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#747]
【测试步骤】
升级最新的session-ui，然后点击屏幕键盘按钮，查看系统显示

【预期结果】
弹出屏幕键盘

【测试结果】
无法弹出屏幕键盘

【问题级别】
100%

【出现概率】
严重

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41124/

**Comment by yefeifei** [comment]
说过了啊，报不是自己测试的模块的问题，麻烦告知一下相关人员！！！！

**Comment by liuwen123** [comment]
已修复
