### ISSUE TITLE
第一次登录左上角会显示一个预览图标

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#748]
【测试步骤】
在系统中新建用户a，然后注销系统登录a账户，登录成功后查看界面显示

【预期结果】
显示正常

【测试结果】
桌面左上角会显示一个小预览图

【问题级别】
一般

【出现概率】
100%
![_desktop_20190104093131](https://user-images.githubusercontent.com/12492745/50670024-d706bc80-1003-11e9-8c65-07bb21b1041f.png)

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/744 可能是相同原因

**Comment by BLumia** [comment]
非稳定重现改一下吧，在遇到可以用 `xwininfo` 看看那个到底是啥，感觉不是桌面的问题。

**Comment by BLumia** [comment]
我这边遇到了，这个是 `dde-welcome` ，显示的内容应该是系统版本升级成功的那个提示。不知道为什么没有全屏。 @justforlxz

**Comment by aksh1618** [comment]
`pkill dde-welcome` works as a workaround, for now

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41123

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
