### ISSUE TITLE
文件管理器文案修改

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#749]
![6113cade-d103-4036-8213-0be158ddbcb8](https://user-images.githubusercontent.com/34432879/50670093-21883900-1004-11e9-9013-d72241a965ef.jpg)
如上图，第二点，修改为：
【关闭快速启动和休眠后重启系统】
@zhuxiujuancindy 翻译一下
@BLumia 这个上周忘记建任务了，看看还能不能加进去
@zccrs

**Comment by zhuxiujuancindy** [comment]
【关闭快速启动和休眠后重启系统】
【Uncheck “Turn on fast startup” and "Hibernate" in shutdown settings and reboot】

**Comment by liuwen123** [comment]
已修复
