### ISSUE TITLE
#15.9 打开无密码登录后，无法登录系统<周二>

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#753]
https://bugzilla.deepin.io/show_bug.cgi?id=14445
【测试环境】
dde-session-ui:4.8.2-1
dde-control-center:4.8.7.2-1
dde-daemon:3.17.0-1

【测试步骤】
1.控制中心打开无密码登录；
2.注销系统，检查是否可以使用无密码登录

【预期结果】
界面显示登录图标，不需要输入密码

【测试结果】
无法登录
【问题级别】
严重
【出现概率】
稳定重现

**Comment by yefeifei** [comment]
![qq 20190104144120](https://user-images.githubusercontent.com/14539819/50676346-d7687d00-102e-11e9-8252-e53bc1c9c025.jpg)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41190

**Comment by CallMeR** [comment]
这个问题我朋友也遇到过，他的账户之前是需要密码才能登陆的，后来更改了设置让他的账户不要密码进行登陆。重启后会卡在登陆界面，循环登陆，切换到tty查看，发现所有命令必须使用绝对路径才能使用，root账户同样。推测环境变量丢失。新建用户（adduser）时，新用户的默认环境变量丢失，passwd的默认bash丢失。

**Comment by justforlxz** [comment]
应该是两个问题，当前的问题其实是greeter界面崩溃。

ARGULER <notifications@github.com> 于2019年1月9日周三 上午10:04写道：
