### ISSUE TITLE
#15.9 登录和锁屏界面，指纹验证超时或者验证错误，没有提示

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#757]
https://bugzilla.deepin.io/show_bug.cgi?id=14449
【测试环境】
dde-session-ui:4.8.2-1

【测试步骤】
1.控制中心录入指纹；
2.注销系统，检查登录界面：验证超时和录入错误指纹的情况；
3.锁屏界面：验证超时和录入错误指纹的情况

【测试结果】
1.锁屏和登录界面，指纹超时和指纹解锁错误都没有任何提示

【预期结果】
1.指纹超时时，应该有提示“指纹验证超时，请手动输入密码....”
2.指纹验证错误，应该提示“指纹解锁失败...”

【问题级别】
一般
【出现概率】
稳定

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41270/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41270/

cr +1
