### ISSUE TITLE
<1d> 将dock中SNI的watcher服务转移到后端

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#76]

**Comment by justforlxz** [comment]
@hualet  tg对sni的支持有点问题，缺接口。

![image](https://user-images.githubusercontent.com/12298476/47768489-45cd4e00-dd13-11e8-915b-d7b13d0879a1.png)

![image](https://user-images.githubusercontent.com/12298476/47768501-5382d380-dd13-11e8-9263-2cf1aff5c3d7.png)

synergy虽然接口都有，但是activate方法没有用，传了坐标并没有显示出来窗口。

**Comment by listenerri** [comment]
@electricface watcher的接口说明:
https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierWatcher/

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/40145

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/40141

**Comment by listenerri** [comment]
**需要安装上面两个cr, 需要测试的有:**
1. 登录进入桌面后dock托盘图标是否有缺失(只看应用托盘图标, 系统托盘图标不会受到影响), 比如搜狗输入法可能会不见, 最好多设置两个带有托盘图标的程序开机自启动
3. 打开或者关闭带托盘的程序时, dock的托盘是否工作正常
4. 杀死后端(dde-session-dae)再启动后端后, 再次测试第2条

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
