### ISSUE TITLE
#15.9 高分屏关闭系统扬声器，注销系统时候，还会有音效

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#762]
https://bugzilla.deepin.io/show_bug.cgi?id=14455
【测试环境】
dde-control-center:4.8.7-2.1
dde-session-ui:4.8.2-1
dde-daemon:3.17.0-1

【测试步骤】
1.关闭系统的扬声器，点击关机，选择注销系统

【测试结果】
1.注销系统有声音

【预期结果】
1.注销系统没有声音

【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
台式机的声音有问题，关闭扬声器可以听到注销的声音；打开扬声器，关机的时候没有声音；
笔记本的声音测试正常

**Comment by electricface** [comment]
注销音乐是通过 alsa 发声的。
