### ISSUE TITLE
 #15.9 高分屏热区设置关闭窗口，锁屏界面移动到右上角，界面显示空白，只有一张模糊背景图

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#764]
https://bugzilla.deepin.io/show_bug.cgi?id=14458
【测试环境】
dde-session-ui:4.8.2-1

【测试步骤】
1.高分屏下，2缩放，桌面右键，设置热区，右上角设置为关闭窗口；
2.锁定屏幕，鼠标移动到右上角，检查界面显示

【测试结果】
锁屏界面消失，只显示模糊的背景图

【预期结果】
移动右上角没有任何反应，界面还是显示锁屏状态

【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
![qq 20190104173710](https://user-images.githubusercontent.com/14539819/50681698-65506200-1047-11e9-9542-89d061261656.jpg)

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41206/ 

@yefeifei  改了实现逻辑，要测试锁屏、登录和关机界面在双屏下的行为正确不（主要是跟随鼠标显示的行为）

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41206/
> 
> @yefeifei 改了实现逻辑，要测试锁屏、登录和关机界面在双屏下的行为正确不（主要是跟随鼠标显示的行为）
安装依赖有问题
![image](https://user-images.githubusercontent.com/14539819/50888849-817e4580-1431-11e9-93d8-4ad35a237b68.png)

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41206/
> 
> @yefeifei 改了实现逻辑，要测试锁屏、登录和关机界面在双屏下的行为正确不（主要是跟随鼠标显示的行为）

cr +1
