### ISSUE TITLE
lightdm-deepin-greeter 啥都不做默认高CPU占用

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#766]
![telegram-cloud-file-5-853234483-182809-2596506578094825543](https://user-images.githubusercontent.com/2023967/50690508-8b3a2e80-1068-11e9-9cf5-2b9b56c88b2b.jpg)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41359
