### ISSUE TITLE
需求：深度截图允许在保存时避免记住本次选择的保存方式

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#770]
### 现状

当前，在使用深度截图时，如果选择了某种保存方式，此时将会将保存方式存储到配置文件，下次进行保存时默认将会使用上次记住的保存方式来保存新的截图。而如果某次仅需要临时的使用另外一种保存方式保存截图，而不希望以后依然按照这种方式保存截图，则没有办法满足此类需求，用户只能手动在下一次截图时重新设置保存方式。

### 需求

允许通过某种方式避免某次手动选择的截图保存方式被记忆。

### 参考方案

按下 Shift 键点击某项保存方式按钮时，此次截图所选的保存方式不被视为需要被记忆。

### 参考实现

https://cr.deepin.io/#/c/deepin-screenshot/+/41120/  （注：该实现中用户界面没有进行任何有关此特性的状态提醒）

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=143

**Comment by BLumia** [comment]
当前最新版本的 `deepin-screenshot` 中已经包含了此功能（选择模式时按住 Shift 键即可避免记住本次选择）。

但 v20 中录屏将包含截图功能，并替换原截图软件包，就超过此 issue 讨论范围了。
