### ISSUE TITLE
匈牙利的新Deepin 镜像（Quantum Mirror）!!!

### ISSUE THREAD

**Issue by aledie** [linuxdeepin/internal-discussion#773]
你好Deepin团队，匈牙利的“Quantum Mirror”（http://quantum-mirror.hu/web/index_en.html
）
在这里反映了你：
http://quantum-mirror.hu/mirrors/pub/deepin-cd/
http://quantum-mirror.hu/web/distributions_en.html
但镜子所有者不知道如何联系你注册镜子。请你帮忙联系他以获取你需要的所有信息！
他的名字叫Peter
电子邮件：root [at] quantum-mirror [dot] hu 
谢谢!

**Comment by deepinzhangshuang** [comment]
这个应该意思想加入我们官方镜像吧， @wangjia12 @21wmd  评估后看是否更新镜像源

**Comment by lq95v5** [comment]
This mirror has been Added.

https://www.deepin.org/mirrors/packages/
