### ISSUE TITLE
 #15.9 单用户，锁屏和登录界面还是切换用户的图标

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#775]
https://bugzilla.deepin.io/show_bug.cgi?id=14466
【测试环境】
dde-session-ui:4.8.2-1

[测试步骤]
1.新装系统，检查登录和锁屏界面显示

【测试结果】
1.只有一个用户，锁屏和登录界面还显示切换用户的图标

【预期结果】
单用户时，不会显示切换用户的图标

【问题级别】
一般
【出现概率】
稳定

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41214/

@yefeifei 所有有用户切换的界面都试试
