### ISSUE TITLE
onboard cannot work in deepin of English

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#777]
https://bugzilla.deepin.io/show_bug.cgi?id=14468

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/onboard/+/41128/

英文系统下没有输入法，所以输入法切换的键现在会空余出来，有点奇怪。
不过至少还能用。

**Comment by liuwen123** [comment]
已修复
