### ISSUE TITLE
#15.9 断开蓝牙音响后，系统提示已断开，但是界面的状态还是显示已连接，实际上蓝牙音响已断开

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#779]
https://bugzilla.deepin.io/show_bug.cgi?id=14470
【测试环境】
dde-daemon:3.17.0-1
dde-control-center:4.8.7.2-1

[测试步骤]
1.连接蓝牙音响，播放音乐，此时点击蓝牙音响，点击断开；

【测试结果】
系统弹出蓝牙音响已断开；但是界面仍然显示已连接；实际上音响已经断开，声音切换到笔记本的扬声器。

【预期结果】
手动断开蓝牙音响后，界面显示应该同步

【问题级别】
一般
【出现概率】
只出现一次

**Comment by zccrs** [comment]
@yefeifei 这个问题后面还有遇到过吗，只重新一次就不准备花时间看了

**Comment by zccrs** [comment]
@yefeifei 再遇到的时候叫 @electricface 和 @justforlxz 一起去看看

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
