### ISSUE TITLE
任务栏放在右边时，已打开的应用，图标之间会出现没有间隔的情况。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#78]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
1.任务栏放在右边
【测试步骤】
1.打开多个应用。查看每个应用在任务栏之间是否都正确分隔。
【预期结果】
1.每个应用图标分隔正常。
【测试结果】
1.最后两个已打开的应用分割不正确。
【问题级别】
提示
【出现概率】
稳定出现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181031133156](https://user-images.githubusercontent.com/14539782/47768068-58df1e80-dd11-11e8-9d9f-0076c0d7eeb3.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39586

**Comment by zhaofangfangdeepin** [comment]
测试通过
