### ISSUE TITLE
#15.9 图标主题去掉sea主题了？

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#783]
https://bugzilla.deepin.io/show_bug.cgi?id=14476
【测试环境】
dde-control-center:4.8.7.2-1

【测试步骤】
1.打开控制中心，检查个性化，图标主题

【测试结果】
四个图标主题中缺少sea主题

【预期结果】
默认安装sea主题

【问题级别】
一般
【出现概率】
稳定重现

**Comment by yefeifei** [comment]
![image](https://user-images.githubusercontent.com/14539819/50752629-df702900-1289-11e9-93d6-085e03376a81.png)

**Comment by zccrs** [comment]
@yefeifei 已经去掉了
