### ISSUE TITLE
纯deepin场景，安装器时间标准选择错误，导致系统时间显示错误<周二>

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#786]
https://bugzilla.deepin.io/show_bug.cgi?id=14479

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41195/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/deepin-installer-reborn/+/41195/

v-1,在windows+deepin双硬盘环境时间标准选择错误。

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41224/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/deepin-installer-reborn/+/41224/

V+1

**Comment by liuwen123** [comment]
已修复
