### ISSUE TITLE
#15.9 锁屏界面的软键盘点击没有响应 

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#791]
https://bugzilla.deepin.io/show_bug.cgi?id=14484
【测试环境】
dde-session-ui:4.8.2-1

【测试步骤】
1.在锁屏界面或者登录界面点击软键盘

【测试结果】
1.点击无响应

【预期结果】
1.可以打开软键盘

【问题级别】
严重
【出现概率】
稳定重现

**Comment by justforlxz** [comment]
#747
