### ISSUE TITLE
IMWheel 默认会修改鼠标按键映射

### ISSUE THREAD

**Issue by jouyouyun** [linuxdeepin/internal-discussion#795]
`IMWheel` 不仅仅是一个滚轮速度调节工具, 同时也可以修改鼠标按键映射, 默认的配置见 `/etc/X11/imwheel/imwheelrc`, 用户的配置见 `~/.imwheelrc` 按键的改动可能导致一些奇怪的问题, 见: [Backward / Forward buttons stopped working...](https://github.com/linuxdeepin/developer-center/issues/629), 所以需要完善 `IMWheel` 的处理方案.

@hualet @zccrs @electricface

**Comment by zccrs** [comment]
> `IMWheel` 不仅仅是一个滚轮速度调节工具, 同时也可以修改鼠标按键映射, 默认的配置见 `/etc/X11/imwheel/imwheelrc`, 用户的配置见 `~/.imwheelrc` 按键的改动可能导致一些奇怪的问题, 见: [Backward / Forward buttons stopped working...](https://github.com/linuxdeepin/developer-center/issues/629), 所以需要完善 `IMWheel` 的处理方案.
> 
> @hualet @zccrs @electricface

完善配置吗

**Comment by jouyouyun** [comment]
> > `IMWheel` 不仅仅是一个滚轮速度调节工具, 同时也可以修改鼠标按键映射, 默认的配置见 `/etc/X11/imwheel/imwheelrc`, 用户的配置见 `~/.imwheelrc` 按键的改动可能导致一些奇怪的问题, 见: [Backward / Forward buttons stopped working...](https://github.com/linuxdeepin/developer-center/issues/629), 所以需要完善 `IMWheel` 的处理方案.
> > @hualet @zccrs @electricface
> 
> 完善配置吗

理想的应该改为 `imwheel` 只加载我们设置的项(鼠标加速)
另外需要测试 `imwheel` 会不会对鼠标自动加载一些配置项

**Comment by electricface** [comment]
imwheel 确实会修改 button 的map配置。

**Comment by electricface** [comment]
启动 imwheel 时传递选项 -b "4 5" 即可。

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/41191

**Comment by jouyouyun** [comment]
> https://cr.deepin.io/#/c/dde/dde-daemon/+/41191
> 让 imwheel 只 grab 鼠标的 wheel up 和 down。

如果遇到用户手动修改了 `imwheel` 配置, 改变一些键映射, 需要测试你的修复方案.

**Comment by electricface** [comment]
不管这部分用户了

**Comment by aiamuzz** [comment]
Hi,

Not sure if i am allowed to post here but its a connected issue ... @electricface ... thanks ... doing the following fixed the back/forward buttons ...

```
killall imwheel
imwheel -b "4 5"
INFO: imwheel started (pid=9706)
```
But the `Ctrl+scrolling` which controls the terminal windows opacity is not fixed ... it works after killing imwheel ... but with imwheel running with the above options it stops working ... 

Seems like imwheel is not just messing the back/forward buttons but also the `Ctrl+scroll` and its function on the terminal window. 

Please note that with imwheel running ... if i use `Ctrl+Scroll_click(kept pressed)+Scroll` and the opacity control works ... i guess you need to unpair the `scroll_click(kept pressed)` and `scroll` keys

**Comment by electricface** [comment]
I think this problem is a problem when deepin-terminal handles events.

**Comment by aiamuzz** [comment]
> I think this problem is a problem when deepin-terminal handles events.

but with the imwheel killed ... the deepin-terminal handles the opacity control as intended ... only when imwheel is running is when this control is lost, at least in the manner its expected.

@electricface ... please note that imwheel messed the back/forward buttons in exactly the same manner ... the back/forward buttons had gotten paired with the right/left buttons ... as reported here ...

[https://github.com/linuxdeepin/developer-center/issues/629#issuecomment-451438414](url)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
