### ISSUE TITLE
 #15.9 台式机出现休眠失败，系统死掉

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#796]
https://bugzilla.deepin.io/show_bug.cgi?id=14488
【测试环境】
dde-session-ui:4.8.2-1

【预置条件】
台式机：内存3.7G swap：23G

【测试步骤】
1.台式机点击关机，在关机界面点击休眠；

【测试结果】
系统死掉

【预期结果】
系统休眠正常，可以唤醒

【问题级别】
一般
【出现概率】
只出现一次

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
