### ISSUE TITLE
#15.9 系统休眠时，黑屏之后会再次显示一次锁屏界面再进入黑屏

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#797]
https://bugzilla.deepin.io/show_bug.cgi?id=14489
【测试环境】
dde-session-ui:4.8.2-1

【测试步骤】
1.点击休眠，检查系统显示

【测试结果】
1.点击之后会到锁屏界面，然后系统黑屏，1s后又显示一次锁屏，再次黑屏进入休眠。

【预期结果】
系统黑屏之后不会再次显示锁屏

【问题级别】
一般
【出现概率】
稳定重现

**Comment by zccrs** [comment]
休眠时的界面闪动应该是正常的
