### ISSUE TITLE
#15.9 修改麦克风的输入音量，反馈音量没有变化

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#799]
https://bugzilla.deepin.io/show_bug.cgi?id=14497
【测试环境】
dde-control-center:4.8.7.2-1

【测试步骤】
1.打开控制中心，修改麦克风的输入音量，检查反馈音量变化

【测试结果】
1.反馈音量没有变化

【预期结果】
1.反馈音量的进度条跟随输入音量的值变化，成正比

【问题级别】
一般
【出现概率】
稳定重现

**Comment by electricface** [comment]
同这个 https://github.com/linuxdeepin/internal-discussion/issues/805

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/805

在这里处理了
