### ISSUE TITLE
文件管理器调节列宽的鼠标样式没变

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#80]
【测试环境】

【预置条件】

【测试步骤】
在文件管理器列表模式调节列宽

【预期结果】
鼠标指针变化提示

【测试结果】
没有变化（以前是有的啊）

【问题级别】

【出现概率】

@zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
