### ISSUE TITLE
控制中心 声音 麦克风 反馈不动

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#805]
https://bugzilla.deepin.io/show_bug.cgi?id=14497
重现步骤：

1. 打开控制中心声音设置，打开麦克风开关，查看反馈音量，如果基本没有跳动可以调大输入音量。
2. 执行命令 killall dde-session-daemon，再重启 dde-session-daemon， 比如点击一次dock上的图标。
3. 打开控制中心声音，查看麦克风的反馈音量，发现无跳动现象。

另一种重现步骤：

1. 打开控制中心声音设置，打开麦克风开关，查看反馈音量，如果基本没有跳动可以调大输入音量。
2. 在控制中心往下翻页，离开声音设置的范围，等待1分钟。
3. 在控制中心往上翻页，回到声音设置的范围，查看麦克风的反馈音量，发现无跳动现象。

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41207

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/41207

cr+1
