### ISSUE TITLE
安装器高级模式，删除所有分区、新建一个分区，后进行编辑，会导致安装器崩溃

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#806]
https://bugzilla.deepin.io/show_bug.cgi?id=14506

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41171/

**Comment by hualet** [comment]
提交的代码有问题，可能导致用户原有的盘强制被格式化，顺便重构一下，再修改一下吧。。

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41205/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/deepin-installer-r-1eborn/+/41205/

V-1,仍然崩～

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41291/

**Comment by liuwen123** [comment]
已修复
