### ISSUE TITLE
 #15.9 控制中心删除用户，弹出密码输入框时，点击右上角x关闭，控制中心会卡顿一会，大概20s左右。

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#807]
https://bugzilla.deepin.io/show_bug.cgi?id=14507
【测试环境】
dde-control-center:4.8.7.2-1

【测试步骤】
1.控制中心删除用户，点击删除，确认删除事，在弹出的密码 输入框点击右上角的x。
2.检查控制中心显示

【测试结果】
1.控制中心卡顿20s

【预期结果】
1.点击x之后，取消删除用户，返回到用户列表，控制中心不会卡顿

【问题级别】
一般
【出现概率】
稳定重现

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/752

这个提交验证的时候有这个问题吗?

@yefeifei  @liuwen123

**Comment by listenerri** [comment]
和这个同一个问题:
https://github.com/linuxdeepin/internal-discussion/issues/808

**Comment by yefeifei** [comment]
dde-control-center:4.9.0-1
此版本测试问题还存在

**Comment by listenerri** [comment]
dde-polkit-agent 没有打 tag

**Comment by yefeifei** [comment]
> dde-polkit-agent 没有打 tag

为什么没打

**Comment by listenerri** [comment]
新 tag 0.2.3

**Comment by yefeifei** [comment]
> 新 tag 0.2.3

@zccrs 以后问题，cr验证完了，我觉得还是把问题指给开发，等开发回复tag了再给测试？

**Comment by listenerri** [comment]
> > 新 tag 0.2.3
> 
> @zccrs 以后问题，cr验证完了，我觉得还是把问题指给开发，等开发回复tag了再给测试？

那测试完了就修改下标题或者添加一个 lable 表示 "验证通过" 或者 "等待tag" 之类的, 再指回来, 不然没有明显标识的话总会重复过任务
