### ISSUE TITLE
#15.9 控制中心创建或删除用户，在用户密码认证界面，点击右上角x，之后再删除或新建用户，就不会弹出密码认证框了，导致无法删除新建用户

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#808]
https://bugzilla.deepin.io/show_bug.cgi?id=14508
【测试环境】
dde-control-center:4.8.7.2-1
dde-daemon:3.17.0-1

【测试步骤】
1.新建用户，在密码认证框界面点击x，再次创建用户，检查是否可以创建成功

【预期结果】
可以创建成功

【测试结果】
第二次创建时，不会有密码认证界面，所以不能创建成功
【问题级别】
严重
【出现概率】
稳定重现

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-polkit-agent/+/41198
