### ISSUE TITLE
lightdm登录界面，鼠标放在密码出错提示附近，鼠标会变成转圈的样式

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#81]
【测试环境】
lightdm 1.21.5-3deepin
【预置条件】

【测试步骤】
1.在用户登录界面，输入错误的密码；
2.密码错误提示出现之后，鼠标hover在错误提示上面。
【预期结果】
1.鼠标hover在错误提示上时，没有任何反应
【测试结果】
1.鼠标hover在错误提示上时，鼠标会变成转圈的样式。
【问题级别】
提示
【出现概率】
稳定出现。

**Comment by zhaofangfangdeepin** [comment]
![_ _20181031135525](https://user-images.githubusercontent.com/14539782/47768841-a446fc00-dd14-11e8-9b18-f12716a840dc.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39380

**Comment by zhaofangfangdeepin** [comment]
不能够加1.. 因为依然会变成“X”的样式。

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39601/

**Comment by justforlxz** [comment]
重构后没了

**Comment by liuwen123** [comment]
已修复
