### ISSUE TITLE
新硬盘、UEFI引导安装盘，使用简单模式安装失败

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#810]
https://bugzilla.deepin.io/show_bug.cgi?id=14513

**Comment by CallMeR** [comment]
@felixonmars   如果干掉Grub，不再支持Legacy+MBR模式装机，仅支持UEFI+GPT模式装机，会不会有严重后果啊。（

**Comment by zccrs** [comment]
> @felixonmars 如果干掉Grub，使用rEFInd替代开机引导。且不再支持Legacy+MBR模式装机，仅支持UEFI+GPT模式装机，会不会有严重后果啊。（

会啊，还有一大波人用 Legacy+MBR

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41239

**Comment by liuwen123** [comment]
已修复
