### ISSUE TITLE
#15.9 修改自定义快捷键，设置冲突的快捷键时，保存崩溃了，或者保存的时候没有提示，直接保存成功了，冲突的快捷键显示为无

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#812]
https://bugzilla.deepin.io/show_bug.cgi?id=14515
【测试环境】
dde-control-center:4.8.7.2-1

【测试步骤】
1.控制中心创建自定义快捷键：快捷键设置为super+a；
2.提示冲突，点击保存；
3.再次进入编辑界面，设置为super+d ，点击保存

【测试结果】
2.首次冲突直接崩溃；
3.第二次点击，冲突没有任何提示，直接保存成功了。

【预期结果】
2.保存成功，控制中不会崩溃；
3.设置冲突时，应该提示快捷键冲突。

【问题级别】
严重
【出现概率】
稳定重现

**Comment by zccrs** [comment]
@listenerri 看一下吧

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-control-center/+/41199

**Comment by yefeifei** [comment]
> https://cr.deepin.io/c/dde/dde-control-center/+/41199

CR+1
