### ISSUE TITLE
#15.9 多用户下，添加多个键盘布局，点击切换用户，切换到用户b，点击键盘布局，键盘布局显示截断

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#814]
【测试环境】
dde-session-ui:4.8.2-1

【测试步骤】
1.登录用户a,创建多个用户b,c,d
2.添加多个键盘布局，然后锁定屏幕；
3.在用户a的锁屏界面点击键盘布局，检查显示情况
4.切换用户，切换到用户b，点击键盘布局，检查显示情况

【测试结果】
3.用户a键盘布局显示正常；
4.用户b的键盘布局显示截断，不显示；

【预期结果】
4.用户b是否就不应该显示键盘布局？？默认只有一个键盘布局时是不是应该不用显示？
【问题级别】
一般
【出现概率】
稳定重现

**Comment by zccrs** [comment]
只有一个键盘布局时的确不显示

**Comment by zccrs** [comment]
@yefeifei 切到其它用户阶段的问题还没处理，先验证图标是否显示的

**Comment by yefeifei** [comment]
> @yefeifei 切到其它用户阶段的问题还没处理，先验证图标是否显示的

验证通过
