### ISSUE TITLE
#15.9 依赖有问题时，控制中心检测不到更新，是否要改进？

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#815]
https://bugzilla.deepin.io/show_bug.cgi?id=14521
【测试环境】
dde-control-center:4.8.7.2-1

【测试步骤】
1.添加测试源，dde-panda
2.手动修改版本号：/var/lib/dpkg/status
修改dock、影院、音乐等的版本号，将版本号修改低一点；
3.重启控制中心，点击更新，检查是否可以检测到更新
4.使用终端update，检查是否有更新

【测试结果】
3.控制中心提示系统已经是最新的
4.提示有更新

【预期结果】
3.控制中心应该检查到更新才对

【问题级别】
严重
【出现概率】
不稳定

**Comment by yefeifei** [comment]
[Info] [2019-01-08 17:40:31]@job_manager.go.132 CreateJob with "" "update_source" [] map[]

[Info] [2019-01-08 17:40:31]@start_job.go.114 "update_source" transition state from "ready" to "running" (Cancelable:true)

[Info] [2019-01-08 17:40:31]@apt.go.46 APTSystem AddCMD: AptCommand{id:"update_source", Cancelable:true, CMD:"/bin/sh -c apt-get -y -o APT::Status-Fd=3 -o Dir::Etc::sourceparts=/var/lib/lastore/source.d update && /var/lib/lastore/scripts/build_system_info -now"}

[Info] [2019-01-08 17:40:34]@apt.go.229 job update_source stdout: Hit:1 http://pools.corp.deepin.com/ppa/dde-panda unstable InRelease
Get:2 http://packages.deepin.com/deepin panda InRelease [11.4 kB]
Fetched 11.4 kB in 1s (17.8 kB/s)
Reading package lists...

[Info] [2019-01-08 17:40:34]@apt.go.230 job update_source stderr: 
[Info] [2019-01-08 17:40:34]@apt.go.55 APTSystem RemoveCMD: AptCommand{id:"update_source", Cancelable:true, CMD:"/bin/sh -c apt-get -y -o APT::Status-Fd=3 -o Dir::Etc::sourceparts=/var/lib/lastore/source.d update && /var/lib/lastore/scripts/build_system_info -now"} (exitCode:0)

[Info] [2019-01-08 17:40:34]@start_job.go.114 "update_source" transition state from "running" to "succeed" (Cancelable:false)

[Info] [2019-01-08 17:40:34]@start_job.go.114 "update_source" transition state from "succeed" to "end" (Cancelable:false)

[Warn] [2019-01-08 17:40:34]@manager.go.420 PackagesDownloadSize("")=0.00 not found resource: hasn't any packages

[Info] [2019-01-08 17:44:37]@job_manager.go.132 CreateJob with "" "update_source" [] map[]

[Info] [2019-01-08 17:44:37]@updater.go.85 start update metadata info service
[Warn] [2019-01-08 17:44:37]@updater.go.105 Next updater check will trigger at 2019-01-08 20:44:47.646731607 +0800 CST m=+12116.782956429
[Info] [2019-01-08 17:44:38]@start_job.go.114 "update_source" transition state from "ready" to "running" (Cancelable:true)

[Info] [2019-01-08 17:44:38]@apt.go.46 APTSystem AddCMD: AptCommand{id:"update_source", Cancelable:true, CMD:"/bin/sh -c apt-get -y -o APT::Status-Fd=3 -o Dir::Etc::sourceparts=/var/lib/lastore/source.d update && /var/lib/lastore/scripts/build_system_info -now"}

[Info] [2019-01-08 17:44:41]@apt.go.229 job update_source stdout: Hit:1 http://pools.corp.deepin.com/ppa/dde-panda unstable InRelease
Get:2 http://packages.deepin.com/deepin panda InRelease [11.4 kB]
Fetched 11.4 kB in 0s (30.7 kB/s)
Reading package lists...

[Info] [2019-01-08 17:44:41]@apt.go.230 job update_source stderr: 
[Info] [2019-01-08 17:44:41]@apt.go.55 APTSystem RemoveCMD: AptCommand{id:"update_source", Cancelable:true, CMD:"/bin/sh -c apt-get -y -o APT::Status-Fd=3 -o Dir::Etc::sourceparts=/var/lib/lastore/source.d update && /var/lib/lastore/scripts/build_system_info -now"} (exitCode:0)

[Info] [2019-01-08 17:44:41]@start_job.go.114 "update_source" transition state from "running" to "succeed" (Cancelable:false)

[Info] [2019-01-08 17:44:41]@start_job.go.114 "update_source" transition state from "succeed" to "end" (Cancelable:false)

[Warn] [2019-01-08 17:44:41]@manager.go.420 PackagesDownloadSize("")=0.00 not found resource: hasn't any packages

**Comment by electricface** [comment]
因为依赖关系被破坏，导致计算更新包失败。

**Comment by zccrs** [comment]
依赖出现问题的时候一般都需要手动修复，至少要有用户的交互参与，未修复时就算检测到更新也无法正常升级

**Comment by electricface** [comment]
控制中心需要在更新部分加上 手动修正功能？

**Comment by wangjia12** [comment]
如果是个人手动改了东西造成的问题，没有必要在控制中心特意去提示他吧
如果他自己能改，就应该能改好
如果改不好，提示了也改不好

**Comment by electricface** [comment]
比如是一个人改出依赖错误了，然后另一个人去控制中心升级，遇到了错误，但是也只会提示他没有检查到更新。

**Comment by wangjia12** [comment]
这种情况比较小众，但是可以当需求搜集起来，评审后出结果。https://pm.deepin.io/index.php?m=story&f=view&storyID=159

**Comment by yefeifei** [comment]
> 比如是一个人改出依赖错误了，然后另一个人去控制中心升级，遇到了错误，但是也只会提示他没有检查到更新。

你这说的就是我和 @justforlxz

**Comment by zhuxiujuancindy** [comment]
【检测更新失败】【Updates detecting failure】
【依赖错误，检测更新失败】【Dependency error, failed to detect the updates】

**Comment by buzheng95** [comment]
我觉得这个玩意儿，应该要告诉用户什么依赖出了问题，然后询问用户是否帮助进行修复，同意之后，修复依赖，然后进行更新吧。很多小白，比如我，检测更新失败，根本不知道去修复什么依赖。虽然我是开发人员，有时候需要源码安装，或者有些库需要版本和系统不一致，是需要手动解决的。不知不觉也会破坏系统依赖，但是也经常不明白怎么去解决的。官方是否可以考虑下这个问题。

**Comment by wangjia12** [comment]
@electricface 能做到自动修复么

**Comment by zccrs** [comment]
> 我觉得这个玩意儿，应该要告诉用户什么依赖出了问题，然后询问用户是否帮助进行修复，同意之后，修复依赖，然后进行更新吧。很多小白，比如我，检测更新失败，根本不知道去修复什么依赖。虽然我是开发人员，有时候需要源码安装，或者有些库需要版本和系统不一致，是需要手动解决的。不知不觉也会破坏系统依赖，但是也经常不明白怎么去解决的。官方是否可以考虑下这个问题。

没有手动安装或者卸载过包的用户一般不会出现依赖错误问题，如果是因为自动操作命令搞坏了依赖，这种情况下的用户也是有能力自己修复的。自动修复非常的不靠谱，简单的依赖问题，一条命令就能解决，但是能让用户束手无策的依赖错误仅仅靠自动检查是无法消除的，而且会多出来很多用户交互步骤。

**Comment by zccrs** [comment]
> > 我觉得这个玩意儿，应该要告诉用户什么依赖出了问题，然后询问用户是否帮助进行修复，同意之后，修复依赖，然后进行更新吧。很多小白，比如我，检测更新失败，根本不知道去修复什么依赖。虽然我是开发人员，有时候需要源码安装，或者有些库需要版本和系统不一致，是需要手动解决的。不知不觉也会破坏系统依赖，但是也经常不明白怎么去解决的。官方是否可以考虑下这个问题。
> 
> 没有手动安装或者卸载过包的用户一般不会出现依赖错误问题，如果是因为自动操作命令搞坏了依赖，这种情况下的用户也是有能力自己修复的。自动修复非常的不靠谱，简单的依赖问题，一条命令就能解决，但是能让用户束手无策的依赖错误仅仅靠自动检查是无法消除的，而且会多出来很多用户交互步骤。

cc @wangjia12

**Comment by buzheng95** [comment]
> > 我觉得这个玩意儿，应该要告诉用户什么依赖出了问题，然后询问用户是否帮助进行修复，同意之后，修复依赖，然后进行更新吧。很多小白，比如我，检测更新失败，根本不知道去修复什么依赖。虽然我是开发人员，有时候需要源码安装，或者有些库需要版本和系统不一致，是需要手动解决的。不知不觉也会破坏系统依赖，但是也经常不明白怎么去解决的。官方是否可以考虑下这个问题。
> 
> 没有手动安装或者卸载过包的用户一般不会出现依赖错误问题，如果是因为自动操作命令搞坏了依赖，这种情况下的用户也是有能力自己修复的。自动修复非常的不靠谱，简单的依赖问题，一条命令就能解决，但是能让用户束手无策的依赖错误仅仅靠自动检查是无法消除的，而且会多出来很多用户交互步骤。

但是如果只是提示依赖错误，就不更新了，对用户来说其实不太友好。而且很有可能小白询问之后，会强制在命令行更新，导致的结果就是更新之后系统出问题，比如无法登陆，无法启动，甚至桌面环境坏掉了。而且对于一些开发人员，其实他们也不一定是使用linux系统的高手，在编译安装一些库文件和环境的时候都是按照教程走的，遇到问题也只有搜索解决。

即使使用apt工具去安装，有时候也会因为库文件不一致，会对系统的依赖文件进行卸载，完全无法避免这种情况。但是如果因为卸载了依赖文件，导致更新出现问题，那么用户可能就不会更新了，如果用户无法解决这个问题，就只有直接重装新版本，对用户的体验不好。官方能否提供一个更好的解决方案，谢谢！！

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/lastore/lastore-daemon/+/41406

目前只实现对错误的报告：
实现原理，在 计算可更新包之前，先使用 apt-get check 检查错误。如果遇到了错误，则把错误记录在 
/var/lib/lastore/update_info.json 文件中。
比如文件内容为：
```json
{
  "ErrorType": "PkgSystemError::dependenciesBroken",
  "Detail": "The following packages have unmet dependencies:\n cardbook : Depends: bash (>= 5.0)\n"
}
```

调用 com.deepin.lastore.Updater 的 ApplicationUpdateInfos 方法会返回错误：
```
g-io-error-quark: GDBus.Error:com.deepin.lastore.Updater.Error.UpdateInfoError: {"ErrorType":"PkgSystemError::dependenciesBroken","Detail":"The following packages have unmet dependencies:\n cardbook : Depends: bash (\u003e= 5.0)\n"} (36)
```
错误名是 com.deepin.lastore.Updater.Error.UpdateInfoError
错误信息的格式是 json，内容与 update_info.json 中的相同。

**Comment by electricface** [comment]
PkgSystemError:: - 包管理系统错误

      dependenciesBroken - 依赖关系破坏
      dpkgInterrupted - dpkg被中断
      invalidSourcesList - 源列表无效

**Comment by electricface** [comment]
![image](https://user-images.githubusercontent.com/3241440/51880524-8ab85d80-23b2-11e9-8165-9917a35d8df6.png)
文字提示显示不全

**Comment by hualet** [comment]
<p>
        背景：
</p>
<p>
        手动把依赖调的有问题了，控制中心无法检测到更新。
</p>
<p>
        文案：<br />
<img src="https://user-images.githubusercontent.com/34432879/51301730-2f5da580-1a6b-11e9-9613-edf85861cf3c.png" alt="_ _20190117144821" /><br />
这里的提示显示为：<br />
【系统更新】（和之前一样）<br />
【依赖错误，检测更新失败】<br />
【检测更新失败】（未知原因时）<br />
<br />
<img src="https://user-images.githubusercontent.com/34432879/51301759-4d2b0a80-1a6b-11e9-8993-5d140910ffd7.png" alt="_ _20190117151827" /><br />
这里的提示显示为：<br />
【依赖错误，检测更新失败】【Dependency error, failed to detect the updates】<br />
【检测更新失败】（未知原因时）【Updates detecting failure】
</p>
<p>
        https://github.com/linuxdeepin/internal-discussion/issues/815
</p>

**Comment by hualet** [comment]
> > > 我觉得这个玩意儿，应该要告诉用户什么依赖出了问题，然后询问用户是否帮助进行修复，同意之后，修复依赖，然后进行更新吧。很多小白，比如我，检测更新失败，根本不知道去修复什么依赖。虽然我是开发人员，有时候需要源码安装，或者有些库需要版本和系统不一致，是需要手动解决的。不知不觉也会破坏系统依赖，但是也经常不明白怎么去解决的。官方是否可以考虑下这个问题。
> > 
> > 
> > 没有手动安装或者卸载过包的用户一般不会出现依赖错误问题，如果是因为自动操作命令搞坏了依赖，这种情况下的用户也是有能力自己修复的。自动修复非常的不靠谱，简单的依赖问题，一条命令就能解决，但是能让用户束手无策的依赖错误仅仅靠自动检查是无法消除的，而且会多出来很多用户交互步骤。
> 
> 但是如果只是提示依赖错误，就不更新了，对用户来说其实不太友好。而且很有可能小白询问之后，会强制在命令行更新，导致的结果就是更新之后系统出问题，比如无法登陆，无法启动，甚至桌面环境坏掉了。而且对于一些开发人员，其实他们也不一定是使用linux系统的高手，在编译安装一些库文件和环境的时候都是按照教程走的，遇到问题也只有搜索解决。
> 
> 即使使用apt工具去安装，有时候也会因为库文件不一致，会对系统的依赖文件进行卸载，完全无法避免这种情况。但是如果因为卸载了依赖文件，导致更新出现问题，那么用户可能就不会更新了，如果用户无法解决这个问题，就只有直接重装新版本，对用户的体验不好。
> 
> 嗯，说得更确切点，就是那部分介于小白用户和会熟练使用linux人员的那部分人，在linux使用方面就是半桶水（ps：我没骂人，我也在说我自己），他们就会一些常见的命令，会配置好自己的开发环境，会安装软件，但是出问题了，就不知道咋个解决了，尤其是依赖错误的问题。
> 
> 官方能否提供一个更好的解决方案，谢谢！！

依赖修复不好做，没有固定的方式去修复依赖问题，所以只能先提示，这样至少受影响的用户知道自己是依赖有问题，所以无法更新，可以找其他懂的人帮忙解决。

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
