### ISSUE TITLE
深度文件管理器在打开窗口后立即检查自己是否是默认文件管理器

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#816]
如果不是，可以弹出询问对话框，就如同谷歌浏览器那般。以防止一些特殊应用接管了文件管理。

https://bbs.deepin.org/forum.php?mod=viewthread&tid=158795&extra=

**Comment by zccrs** [comment]
这个必要性没有之前那么大了。15.9的文件管理器支持设置目录的默认关联应用了

**Comment by electricface** [comment]
还可以增加一个功能：
当检查到本文件管理器不是默认的时，菜单中就会出现 “设置为默认“的项目。

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=156
再考虑一下这个方式

**Comment by wangjia12** [comment]
15.10需求评审讨论过这个问题了，通过更换默认打开方式的方法把文件管理器设置为默认的。当用户用别的文件管理器就提示这个行为很强制。
