### ISSUE TITLE
虚拟机选择窗管的界面显示界面很小，不正常

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#818]
![image](https://user-images.githubusercontent.com/2023967/50872038-d0f44f80-13f8-11e9-800d-67d56f526e94.png)

**Comment by zccrs** [comment]
我没有遇到过

**Comment by listenerri** [comment]
回归测吧:

https://cr.deepin.io/c/dde/dde-session-ui/+/41213

**Comment by liuwen123** [comment]
新ISO安装，暂未出现
