### ISSUE TITLE
文件管理器tooltip优化 效果不行

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#82]
【测试环境】

【预置条件】

【测试步骤】
文件管理器列表模式，文件名显示不全时鼠标移入名称区域
【预期结果】
动画要流畅
【测试结果】
现在效果不行，还是一卡一卡的
【问题级别】

【出现概率】

@zccrs 和 @shule1987 一起调一下吧

**Comment by liuwen123** [comment]
任务重复，关闭
