### ISSUE TITLE
#15.9 蓝牙耳机连接后，耳机没有声音。<下周一>

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#821]
https://bugzilla.deepin.io/show_bug.cgi?id=14525
【测试环境】
dde-daemon:3.17.0-1

[测试步骤]
1.打开蓝牙，点击进行连接，华为耳机，连接成功；
2.检查声音高级输出，显示为蓝牙耳机
3.播放音乐，检查耳机是否有声音

【测试结果】
耳机无声音
1月 09 14:07:56 deepin-PC bluetoothd[2169]: /org/bluez/hci0/dev_5C_A8_6A_79_D0_45/fd3: fd(35) ready
1月 09 14:12:28 deepin-PC bluetoothd[2169]: Unable to get io data for Headset Voice gateway: getpeername: Transport endpoint is not connected (107)
1月 09 14:27:38 deepin-PC bluetoothd[2169]: Unable to connect Headset Voice gateway: connect: Device or resource busy (16)
1月 09 14:27:38 deepin-PC bluetoothd[2169]: Connecting Headset Voice gateway failed: Input/output error
1月 09 14:27:41 deepin-PC bluetoothd[2169]: /org/bluez/hci0/dev_8A_00_00_03_B0_FC/fd4: fd(33) ready

【预期结果】

蓝牙耳机使用正常

【问题级别】
一般
【出现概率】
不稳定重现

**Comment by electricface** [comment]
不稳定重现

**Comment by electricface** [comment]
没重现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
