### ISSUE TITLE
#15.9  控制中心从15.7 升级到15.9，升级完成重启到桌面显示15.8，提示当前版本为15.8

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#822]
【测试环境】
15.7 iso
外网源+ppa/dde-panda

【测试步骤】
1.点击控制中心，点击更新，检查更新，点击下载并安装更新；
2.在更新过程中弹出grub设置界面：
选择keep the local version currently installed,
选择不安装grub，完成后，点击重启

【测试结果】
升级成功界面显示15.8

【预期结果】
升级成功界面显示15.9

【问题级别】
一般
【出现概率】
稳定

**Comment by deepinzhangshuang** [comment]
本次升级不升级版本号，下周才升级版本号
