### ISSUE TITLE
设置鼠标滚轮加速大于等于2时，运行 imwheel ，不能使用ctrl+鼠标滚轮 调整深度终端的透明度

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#823]
相关 issue： https://github.com/linuxdeepin/internal-discussion/issues/795

运行 imwheel 后， ctrl + 鼠标滚轮可以在  firefox、google chrome、深度文件管理器等程序进行放大缩小显示比例的操作，因此我认为应该在深度终端项目中修正此问题。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
