### ISSUE TITLE
#15.9 无密码登录界面的登录按钮没有默认选中，无法回车登录到界面

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#824]
https://bugzilla.deepin.io/show_bug.cgi?id=14527
【测试环境】
dde-session-ui:4.8.3-1

【测试步骤】
1.控制中心开启无密码登录，注销或者锁屏；
2.在无密码登录界面直接回车

【测试结果】
没响应

【预期结果】
登录到桌面

【问题级别】
一般
【出现概率】
稳定

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41312/

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41333
