### ISSUE TITLE
建议 dock 时尚模式可以隐藏回收站、磁盘图标<z3>

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#827]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=166641&extra=

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=151

**Comment by listenerri** [comment]
磁盘图标现在被放到了托盘里，而不是作为 dock 插件加载的，目前不能禁用托盘内部的功能

**Comment by listenerri** [comment]
允许禁用回收站插件：
https://cr.deepin.io/#/c/dde/dde-dock/+/41780

**Comment by listenerri** [comment]
增加了文案：
中：回收站
英：Trash

**Comment by liuwen123** [comment]
已修复
