### ISSUE TITLE
制作启动器下载页面不清晰问题

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#828]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173415&extra=

我看了 http://cdimage.deepin.com/applications/deepin-boot-maker/windows/ 这个文件夹下，错误地放置了
deepin-system-installer.exe

**Comment by deepinzhangshuang** [comment]
这个是故意放的, wubi安装工具

**Comment by wangjia12** [comment]
https://www.deepin.org/original/deepin-boot-maker/
网站已经改了，点击链接直接下载
