### ISSUE TITLE
file-roller 新 patch 打包测试

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#83]
编码检测 patch ，用于 [file-roller 3.30.1-1](https://packages.debian.org/sid/file-roller) . 打包以供测试。

由 `git diff` 生成的 patch 文件：

[patchfile.patch.zip](https://github.com/linuxdeepin/internal-discussion/files/2532869/patchfile.patch.zip)

**Comment by deepinzhangshuang** [comment]
已经更新到 ppa/dde-panda unstable
