### ISSUE TITLE
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp 

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#831]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173362&extra=
考虑去除这个默认配置

**Comment by jay763190097** [comment]
嗯嗯，这个问题恼人，去不掉。按论坛的做法去掉了，IDE上仍然有。

**Comment by jouyouyun** [comment]
> 嗯嗯，这个问题恼人，去不掉。按论坛的做法去掉了，IDE上仍然有。

再把 ~/.pam_environment 中相关的行删掉

**Comment by electricface** [comment]
https://docs.oracle.com/javase/6/docs/technotes/guides/2d/flags.html#aaFonts

**Comment by electricface** [comment]
这个设置是调整 java awt 字体的抗锯齿设置，去掉这个设置对字体渲染影响也不大。

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/default-settings/+/41373

**Comment by electricface** [comment]
@deepinzhangshuang
