### ISSUE TITLE
#15.9 多用户下，网络配置和网络设备的开关设计逻辑不合理导致问题：用户a禁用WiFi后，用户b无法使用WiFi<周四>

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#832]
https://bugzilla.deepin.io/show_bug.cgi?id=14530
【测试环境】
dde--daemon:3.18.0-1
dde-control-center:4.8.7.2-1

【测试步骤】
1.用户a,连接WiFi，如连接deepin-guest，连接成功；
2.新建用户b,登录到用户b;
3.检查用户b 的WiFi连接状态；
4.关闭WiFi，切换到用户a，检查用户a的WiFi连接状态；
5.打开或者禁用WiFi，再次连接deepin-guest,
6.切换到用户b，开启WiFi，再切换到用户a，检查WiFi状态

【测试结果】
3.用户b的WiFi自动连接到deepin-guest；
4.用户a的WiFi开关是打开的，但是却无法成功连接到deepin-guest或者其他WiFi，
5.用户a多次尝试打开或者关闭WiFi开关都无法使用
6.用户a的WiFi可以正常连接

网络配置设置是系统级别的，一个用户修改会影响所有用户，但是网络的开关状态却又是用户级别的，导致一个用户禁用网络后，其他用户的状态没有同步生效，影响其他用户正常使用网络。且，只能切换回第一个修改网络开关的用户去修改才能生效。

【预期结果】
目前网络逻辑设计不合理，预期结果要产品确定。

【问题级别】
严重
【出现概率】
稳定重现

**Comment by electricface** [comment]
需要去除主动断开正在连接网络配置的功能

**Comment by yefeifei** [comment]
> 去除主动断开 被禁用设备 正在连接网络配置的功能
> https://cr.deepin.io/#/c/dde/dde-daemon/+/41260
这个逻辑不改，还是有问题的，返回用户a连接WiFi后，再返回用户b，WiFi状态是关闭的，但是却提示WiFi已连接，显示有ip

**Comment by electricface** [comment]
应该把设备开关做到 系统级别。

**Comment by zccrs** [comment]
目前先这样做，15.9 之后改成系统级别的开关 @yefeifei @electricface

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=149

**Comment by yefeifei** [comment]
> https://pm.deepin.io/index.php?m=story&f=view&storyID=149

这个是啥？要注册么？

**Comment by wangjia12** [comment]
> > https://pm.deepin.io/index.php?m=story&f=view&storyID=149
> 
> 这个是啥？要注册么？

暂时不用吧，你们还没开始用，我做需求管理用的。

**Comment by hualet** [comment]
@yefeifei 飞飞，这个不需要严重级别吧？:joy:

**Comment by yefeifei** [comment]
> 目前先这样做，15.9 之后改成系统级别的开关 @yefeifei @electricface

嗯，测试通过
