### ISSUE TITLE
驱动管理器重构方案

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#834]
只在 overlay 上测试, 测试成功后生成一个标记成功的 flag 然后重启, 真正的安装放到重启后去做, 安装完成之后再次重启.

这样做是为了避免在 overlay 阶段安装后同步数据时可能导致的一些奇怪的问题.

@deepinzhangshuang 确认下是否是上述方案?

@hualet @zccrs 是否按照这个方案重构呢?

相关任务:
- [x]  dde-polkit-agent提供一个dbus service

**Comment by zccrs** [comment]
> 只在 overlay 上测试, 测试成功后生成一个标记成功的 flag 然后重启, 真正的安装放到重启后去做, 安装完成之后再次重启.
> 
> 这样做是为了避免在 overlay 阶段安装后同步数据时可能导致的一些奇怪的问题.
> 
> @deepinzhangshuang 确认下是否是上述方案?
> 
> @hualet @zccrs 是否按照这个方案重构呢?

需要多少时间？

**Comment by listenerri** [comment]
@zccrs 驱动管理器要测试的方案比较多, 而且耗时, 从开始重构到稳定估计要一周

**Comment by listenerri** [comment]
https://cr.deepin.io/c/deepin-graphics-driver-manager/+/41415

**Comment by listenerri** [comment]
我这边测试单i可以正常工作

**Comment by listenerri** [comment]
## 专业版 i + n 测试结果:

> 由于专业版 Xorg 版本较低, 不支持 PRIME 方案的配置, 因此没有测试 PRIME 相关方案的切换.

测试结果按测试顺序如下:
1. 开源 -> 大黄蜂 `成功`
2. 大黄蜂 -> 默认 `成功`
3. 默认 -> 开源 `成功`
4. 开源 -> 默认 `成功`
5. 默认 -> 大黄蜂 `成功`
6. 大黄蜂 -> 开源 `成功`

**Comment by liuwen123** [comment]
建议将版本号写到驱动方案后面，直接用括号括起来，看起来更清楚一些
如： 使用开源驱动(1:1.0.15)

![_deepin-graphics-driver-manager_20190125160857](https://user-images.githubusercontent.com/12492745/51733262-bfc76600-20bb-11e9-854c-938c54de0f89.png)

**Comment by listenerri** [comment]
@liuwen123 等有 i+n 的机器后要着重测试大黄蜂和prime方案之间的切换, 在这两个方案之间多切几次

**Comment by listenerri** [comment]
@wangjia12 

正在更新驱动的对话框使用哪种图标合适? 

![_ _20190129165227](https://user-images.githubusercontent.com/7995379/51895953-5eb6cf80-23e6-11e9-9e84-3b89e4c174b6.png)

![_ _20190129151537](https://user-images.githubusercontent.com/7995379/51895993-75f5bd00-23e6-11e9-923a-3ebcbd02f817.png)

**Comment by listenerri** [comment]
@shule1987 
图标做好了吗?

**Comment by shule1987** [comment]
> @shule1987
> 图标做好了吗?

还没做,明天下班前给你

**Comment by shule1987** [comment]
[图标.zip](https://github.com/linuxdeepin/internal-discussion/files/2867443/default.zip)

**Comment by listenerri** [comment]
@liuwen123 翻译和图标全都已经完成了
