### ISSUE TITLE
#15.9 多用户界面，选中被遮挡住的用户，不会自动滚动到可视区域 

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#835]
https://bugzilla.deepin.io/show_bug.cgi?id=14531
【测试环境】
dde-session-ui:4.8.3-1

【测试步骤】
1.创建多个用户，沾满屏幕；
2.锁定，点击切换用户，鼠标点击被遮挡住的用户，检查是否会自动向上滚动到可视区域

【测试结果】
1.选中的用户不会自动滚动

【预期结果】
被选中的用户应该自动滚动到可视区域

【问题级别】
一般
【出现概率】
稳定

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
