### ISSUE TITLE
QQ多开状态栏显示错误  只显示一个

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#839]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173546&extra=

**Comment by electricface** [comment]
建议修正方案：
如果 遇到 重复的qq图标，把 window id 加入 标示中；
只永久记录第一个qq图标的位置，其余的qq图标不记录；
记录所有qq图标的临时位置；
当重启 dde-dock 时，前确定第一个qq图标的位置，然后把之后遇到的每个 qq 图标插入到 第一个qq图标的后面。

**Comment by electricface** [comment]
@liuwen123

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/41293

**Comment by liuwen123** [comment]
+1

**Comment by git4coder** [comment]
需要2个QQ的可以先 “QQ+轻聊QQ”，TIM试了不行

**Comment by listenerri** [comment]
> 需要2个QQ的可以先 “QQ+轻聊QQ”，TIM试了不行



> https://cr.deepin.io/c/dde/dde-dock/+/41293

这个提交已经修复了, 等下一波更新吧, 估计今天可以发出

**Comment by liuwen123** [comment]
已修复
