### ISSUE TITLE
高效模式下任务栏，托盘没有出现时，箭头的位置右键不能出现右键菜单

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#84]
【测试环境】
dde-dock:
  已安装：4.7.4-2
【预置条件】
任务栏设置为高效模式
【测试步骤】
1.在任务栏，右边，托盘箭头出现的位置右键，查看能否出现右键菜单
【预期结果】
1.只要箭头没出现，就能出现右键菜单。
【测试结果】
1.不能出现右键菜单
【问题级别】
一般
【出现概率】
稳定复现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181031140233](https://user-images.githubusercontent.com/14539782/47769252-38fe2980-dd16-11e8-8665-f59060e9511f.png)

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/39379

**Comment by zhaofangfangdeepin** [comment]
V+1

**Comment by zhaofangfangdeepin** [comment]
测试通过
