### ISSUE TITLE
#15.9 高分屏关机界面的鼠标没有缩放 

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#843]
https://bugzilla.deepin.io/show_bug.cgi?id=14537
【测试环境】
dde-session-ui:4.8.3-1

【测试步骤】
1.高分屏，点击关机，检查关机界面鼠标的大小

【测试结果】
鼠标突然缩小

【预期结果】
鼠标和桌面时的大小一样，2倍缩放

【问题级别】
一般
【出现概率】
稳定

**Comment by justforlxz** [comment]
没有重现了
