### ISSUE TITLE
完善深度 SDK 整体规划

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#844]
第一个阶段（2019.1）：

- 出 DTK 的 API 文档第一个版本；
- 同时完成 DTK 文档的生成、打包以及和 QtCreator 关联；

第二个阶段（2019.4）：

- 补充使用 DTK 的例子程序；
- 完成 QtCreator 的 DTK 模板；
- 同时完成使用 DTK 进行开发的向导文档，介绍 DTK 的概况，发展方向和几个主要模块、控件使用等；

第三个阶段（2019.6）：

- 完成 DTK 设计说明和Roadmap；
- 完成例子程序的完善；
- 完成 API 文档的完善；
- DTK 文档部分达到可用、稳定状态；

第四个阶段（2019.10）：

- 完成 QtCreator 打包插件的开发和集成工作（deb包、flatpak包和appimage包等）；

**Comment by c61292558** [comment]
我最期待的是第四个阶段

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
