### ISSUE TITLE
调整桌面文件名称字体的样式

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#846]
需求背景：
在某些浅色壁纸下看不清名称
需求描述：
字体调整，具体 @shule1987 来定。
关联任务：https://github.com/linuxdeepin/developer-center/issues/731

**Comment by shule1987** [comment]
那天和刘总讨论了一下这个问题
![default](https://user-images.githubusercontent.com/5448609/51095694-8ce6bd80-17f1-11e9-8578-b2670e49506a.jpg)

浅色投影的效果是目前的效果,但不完全一直, 加深投影效果是可以增强浅色壁纸阅读性,但是美感会降低, 看大家倾向哪个

**Comment by wangjia12** [comment]
右边两张差别不大，左边两张浅投影好看一些。
感觉左边两张不管什么投影都模模糊糊的啊

**Comment by shule1987** [comment]
> 右边两张差别不大，左边两张浅投影好看一些。
> 感觉左边两张不管什么投影都模模糊糊的啊

给你看高清的吧
![1](https://user-images.githubusercontent.com/5448609/51095810-4f366480-17f2-11e9-8126-b2f450731c10.jpg)
![3](https://user-images.githubusercontent.com/5448609/51095811-4fcefb00-17f2-11e9-9678-1b5c9670ad80.jpg)

**Comment by zccrs** [comment]
我是没有觉得目前的投影在白色壁纸下会看不清，可能也和文本内容和字体有关

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41778/ 

@shule1987 可以装一下看看在你那的效果
