### ISSUE TITLE
#15.9 控制中心用户和密码相同时，提示语没有翻译

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#847]
https://bugzilla.deepin.io/show_bug.cgi?id=14539
【测试环境】
dde-control-center:4.9.0-1

【测试步骤】
1.控制中心创建用户，输入用户名test，密码输入test
2.检查提示

【测试结果】
提示 “The password should be different from the username”

[预期结果]
提示要翻译

【问题级别】
一般
【出现概率】
稳定

**Comment by liuwen123** [comment]
已修复
