### ISSUE TITLE
#等tag 15.9 开启无密码登录后，点击锁屏直接登录到桌面

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#848]
https://bugzilla.deepin.io/show_bug.cgi?id=14540
【测试环境】
dde-session-ui:4.8.4-1

【测试步骤】
1.打开无密码登录，点击关机，选择锁屏，检查操作结果

【测试结果】
1.无法锁屏，到不了无密码登录界面

【预期结果】
无密码锁屏界面显示正常

【问题级别】
严重
【出现概率】
稳定

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41312/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41312/

cr +1
