### ISSUE TITLE
#等tag 15.9 重现概率高 指纹解锁时，登录到桌面会直接崩溃

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#849]
https://bugzilla.deepin.io/show_bug.cgi?id=14541
【测试环境】
dde-session-ui:4.8.4-1

【测试步骤】
1.录入指纹后，注销系统，使用指纹解锁，会出现指纹解锁成功后，界面崩溃了

【测试结果】
指纹解锁成功后，界面崩溃

【预期结果】
指纹解锁后能成功登录到桌面

【问题级别】
严重
【出现概率】
重现概率高

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41315/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41315/

cr +1

**Comment by justforlxz** [comment]
4.8.5
