### ISSUE TITLE
控制中心网络编辑界面加上“使用此连接时自动连接VPN"的设置

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#85]
![_ _20181031141149](https://user-images.githubusercontent.com/3241440/47769492-0ef93700-dd17-11e8-8675-97d0b4de6d94.png)

**Comment by electricface** [comment]
@listenerri @hualet @wangjia12 @justforlxz

**Comment by hualet** [comment]
好像用处不是特别大吧？

**Comment by electricface** [comment]
有些人有这个需求吧

**Comment by hualet** [comment]
那个肯定不能否认 但是应该在极少数吧 
这个如果你有需求的话可以考虑讨论一下 如果你自己都没有需求的话 就看用户有没有人反馈需要这个功能吧
