### ISSUE TITLE
#15.9 扩展模式下，笔记本待机唤醒后，副屏无输出了

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#850]
https://bugzilla.deepin.io/show_bug.cgi?id=14542
【测试环境】
dde-control-center:4.9.0-1

【测试步骤】
1.笔记本外接屏幕；设置为扩展模式，
2.合上笔记本，进入待机模式；
3.打开笔记本唤醒，检查外接屏幕输出

【测试结果】
外接屏幕提示无输出，黑屏状态

【预期结果】
唤醒后，副屏幕输出显示正常

【问题级别】
一般
【出现概率】
稳定

**Comment by yefeifei** [comment]
因为接了dvi转接头

**Comment by hualet** [comment]
@yefeifei 硬件问题就把任务关了吧

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
