### ISSUE TITLE
rtl8723be-dkms 安装失败

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#851]
rtl8723be-dkms
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 8 个软件包未被升级。
需要下载 0 B/183 kB 的归档。
解压缩后会消耗 1,122 kB 的额外空间。
(正在读取数据库 ... 系统当前共安装有 391617 个文件和目录。)
正准备解包 .../rtl8723be-dkms_0.1-3_all.deb  ...
正在解包 rtl8723be-dkms (0.1-3) ...
正在设置 rtl8723be-dkms (0.1-3) ...
Loading new 8723be-0.1 DKMS files...
Building for 4.15.0-29deepin-generic
Building initial module for 4.15.0-29deepin-generic
Error! Bad return status for module build on kernel: 4.15.0-29deepin-generic (x86_64)
Consult /var/lib/dkms/8723be/0.1/build/make.log for more information.

[make.log](https://github.com/linuxdeepin/internal-discussion/files/2754385/make.log)

**Comment by deepinzhangshuang** [comment]
内核已经包含支持，这个应该是老版本，从仓库移除
