### ISSUE TITLE
高效模式的任务栏，在插件的底部右键，不能弹出任务栏的右键菜单

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#853]
tower:

https://tower.im/teams/9487/todos/227204/

**Comment by listenerri** [comment]
https://cr.deepin.io/c/dde/dde-dock/+/41325

**Comment by listenerri** [comment]
ci: 
https://ci.deepin.io/job/dde-dock/1983/

**Comment by liuwen123** [comment]
已修复
