### ISSUE TITLE
部分屏保导致Xorg cpu 占用很高

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#855]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173731&extra=

需要找出这些屏保然后去除

测试方法：

设置等待时间为10s
```
gsettings set com.deepin.dde.power line-power-screensaver-delay 10
gsettings set com.deepin.dde.power battery-screensaver-delay 10
```

设置屏保成功后，通过这条命令确定屏保的id。
```
grep currentScreenSaver $HOME/.config/deepin/deepin-screensaver.conf
```

通过 ssh 连接上要运行屏保的电脑，显示屏保后，观察 cpu 使用情况。

已知有此问题的屏保：
whirlwindwarp

**Comment by electricface** [comment]
@zccrs

**Comment by zccrs** [comment]
![fireworkx 3x](https://user-images.githubusercontent.com/13449038/51155021-0a253780-18b1-11e9-8ee0-6e62b9880307.jpg)
![whirlwindwarp 3x](https://user-images.githubusercontent.com/13449038/51155028-0f828200-18b1-11e9-8fd2-f388a18c3ce4.jpg)
这俩占用较高，尤其是下面这个

**Comment by wangjia12** [comment]
好的 去掉这两个

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-screensaver/+/41329/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
