### ISSUE TITLE
 #15.9 指纹验证存在的问题

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#856]
问题1：
锁屏界面：
指纹验证超时或者指纹验证3次失败后；提示手动输入密码，第一次输入错误密码后，第二次输入时，指纹识别的又可以验证了，此时输入正确的密码，等待一段时间（指纹验证超时后）才能进入系统；

问题2：
登录界面：
同上操作，第二次输入正确密码后，无法正常登录到系统；需要手动清空密码，再次输入才能进入系统

问题3：
多用户登录界面，用户a添加了指纹；用户b没有添加指纹；注销用户a，切换到用户b，界面提示要输入指纹。锁屏界面不存在这个问题。

【问题级别】
一般
【出现概率】
稳定

**Comment by zccrs** [comment]
设备本身的问题，启动它之后无法取消认证，只能等待它返回数据

**Comment by zccrs** [comment]
暂不处理

**Comment by zccrs** [comment]
有时间可以看一下能否在切用户时通过接口直接让指纹验证超过或者以其他方式推出

**Comment by zhaofangfangdeepin** [comment]
叶飞反馈的问题2和问题3 依然存在啊

**Comment by zccrs** [comment]
> 叶飞反馈的问题1和问题2 依然存在啊

再测一下1，没问题就可以关闭了

**Comment by zhaofangfangdeepin** [comment]
测试通过
