### ISSUE TITLE
深度编辑器输入中文，再次打开乱码

### ISSUE THREAD

**Issue by mmxzmmxz** [linuxdeepin/internal-discussion#861]
【测试环境】：
15.5 sp2 ISO
【测试步骤】：
1.打开深度编辑器，输入中文，ctrl+s保存至桌面。
2.再次打开该文档，发现乱码。

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41330/


[无标题文档 1.txt](https://github.com/linuxdeepin/internal-discussion/files/2758177/1.txt)

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-editor/+/41331/

**Comment by mmxzmmxz** [comment]
> https://cr.deepin.io/#/c/dde/dde-file-manager/+/41330/
> 
> [无标题文档 1.txt](https://github.com/linuxdeepin/internal-discussion/files/2758177/1.txt)

V+1

**Comment by liuwen123** [comment]
已修复
