### ISSUE TITLE
文件管理器-属性对话框新设计

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#862]
https://github.com/linuxdeepin/developer-center/issues/720

@shule1987

**Comment by wangjia12** [comment]
https://pm.deepin.io/index.php?m=story&f=view&storyID=165

**Comment by wangjia12** [comment]
在V20的新设计中解决这个问题

**Comment by aiamuzz** [comment]
@zccrs ... i think this missed the 15.11 milestone ... !

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
