### ISSUE TITLE
设置无密码登录后，在锁屏界面login没有翻译

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#865]
【测试步骤】
在控制中心设置用户无密码登录，然后锁屏，查看登录对话框显示

【预期结果】
登录按钮已经翻译

【测试结果】
登录按钮没有翻译

【问题级别】
一般

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41352/

**Comment by liuwen123** [comment]
+1
