### ISSUE TITLE
移除 debian/rules 里面对 dpkg-parsechangelog 的依赖

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#866]
详细信息参看： https://github.com/linuxdeepin/deepin-image-viewer/issues/32

目前我看到还在依赖的项目：
- [x] deepin-voice-recorder
- [x] dtkwidget
- [x] dtkwm
- [x] dde-calendar
- [x] dtkcore
- [x] dde-file-manager
- [x] deepin-deb-installer
- [x] deepin-music
- [x] deepin-graphics-driver-manager
- [x] deepin-font-installer
- [ ] deepin-appstore
- [x] deepin-terminal
- [x] deepin-repair-tools
- [x] deepin-installer-reborn
- [x] deepin-image-viewer

@zccrs @deepinzhangshuang @Iceyer @listenerri @justforlxz @BLumia 15.9发布后，各自改一下自己的项目吧。

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/41304/

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/deepin-installer-reborn/+/41360/
https://cr.deepin.io/#/c/dde/dde-calendar/+/41361/

**Comment by listenerri** [comment]
https://cr.deepin.io/c/deepin-deb-installer/+/41384
https://cr.deepin.io/c/deepin-graphics-driver-manager/+/41385
https://cr.deepin.io/c/deepin-font-installer/+/41387
https://cr.deepin.io/c/deepin-repair-tools/+/41388

**Comment by zccrs** [comment]
* dtkcore: https://cr.deepin.io/#/c/dtkcore/+/41401/
* dtkwidget: https://cr.deepin.io/#/c/dtkwidget/+/41402/

**Comment by BLumia** [comment]
- deepin-terminal: linuxdeepin/deepin-terminal#113

**Comment by hualet** [comment]
商店处理一下吧 @Iceyer

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/dtkwm/+/41544/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
