### ISSUE TITLE
DDE  dock 的网络插件能不能至少在配置文件上恢复可选配置

### ISSUE THREAD

**Issue by ihipop** [linuxdeepin/internal-discussion#867]
DDE  dock 的网络插件能不能至少在配置文件上恢复可选配置？
以前dde的dock上的网络插件是可以通过勾选去掉的 原因就是一些NetworkManager的VPN插件在deepin自带的网络设置界面无法正常设置，所以我都是安装 `network-manager-gnome` 然后使用  nm-applet 代替的
自从某次更新以后，dock右击里面再也不能禁用网络插件了，修改配置文件 `~/.config/deepin/dde-dock.conf `  设置
```
[network]
enable=false
```
依然无效

我想官方移除这个右键可能是为了防止有人误操作把网络搞掉，但是起码保留下配置文件开关的有效性吧？如果你们的NetworkManager界面做的足够好我也愿意用，现在就是因为用不了才用别的代替，结果界面上出现了2套Applet，其中一套dde的还带两个网络图标。。还关不掉。

**Comment by ihipop** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=172176&page=1#pid543594

**Comment by listenerri** [comment]
这个已经支持了，你可以更新下 dock 试试

**Comment by ihipop** [comment]
@listenerri 实测是可以了测试的时候发现个疑问，当然，不影响功能：
这个conf配置风格看起来像ini，但是ini的注释符号不能用 会变成urlencode的#，这个是故意这样设计的吗？

**Comment by ihipop** [comment]
@listenerri  实测了还是不行
~/.config/deepin/dde-dock.conf 这个已经加上了，killall dde-dock以后网络图标还是出来了
```
[network]
enable=false
```
而且测试的时候发现个疑问，当然，不影响功能：
这个conf配置风格看起来像ini，但是ini的注释符号不能用 会变成urlencode的#，这个是故意这样设计的吗？

**Comment by ihipop** [comment]
```
apt policy dde-dock
dde-dock:
  已安装：4.9.0-1
  候选： 4.9.0-1
  版本列表：
 *** 4.9.0-1 500
        500 https://mirrors.ustc.edu.cn/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by listenerri** [comment]
键值对的 key 是：“enabled” 

另外有另一个跟配置文件相关的 issue，以后云同步功能推送后将不再使用上面你提到的配置文件，而是存在后端，你需要留意一下：https://github.com/linuxdeepin/developer-center/issues/862

**Comment by ihipop** [comment]
@listenerri 改成`enabled`，好了为什么其他模块的配置的key都是`enable`而这个是`enabled`？故意这么设计的吗？
![image](https://user-images.githubusercontent.com/423077/54327141-065d2980-4644-11e9-90e2-5a554cee424a.png)

**Comment by listenerri** [comment]
> @listenerri 改成`enabled`，好了为什么其他模块的配置的key都是`enable`而这个是`enabled`？故意这么设计的吗？
> ![image](https://user-images.githubusercontent.com/423077/54327141-065d2980-4644-11e9-90e2-5a554cee424a.png)

不是的，随手打出来的 : )

我刚刚也是去看了源码才知道是 enabled

**Comment by ihipop** [comment]
@listenerri 还会改回去么？：（

**Comment by listenerri** [comment]
> @listenerri 还会改回去么？：（

应该不会

**Comment by ihipop** [comment]
@listenerri 今天更新到15.10 开关失效了

**Comment by listenerri** [comment]
> 键值对的 key 是：“enabled”
> 
> 另外有另一个跟配置文件相关的 issue，以后云同步功能推送后将不再使用上面你提到的配置文件，而是存在后端，你需要留意一下：[linuxdeepin/developer-center#862](https://github.com/linuxdeepin/developer-center/issues/862)

早就已经给你说过了的

**Comment by ihipop** [comment]
![image](https://user-images.githubusercontent.com/423077/57288308-ca968b80-70eb-11e9-9932-a18b0a5b62fc.png)
改了没用

**Comment by ihipop** [comment]
@listenerri
