### ISSUE TITLE
修改grub主题下的文案

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#87]
更改为：
【您可以点击菜单改变默认启动项】
【You can click the option in boot menu to set it as the first boot】
【开启主题后您可以在开机时看到所选择的主题背景】
【Switch it on to view your theme in boot menu】
![deepinscreenshot_select-area_20181031142013](https://user-images.githubusercontent.com/34529003/47769816-1ff67800-dd18-11e8-86ed-55003042fd54.png)

**Comment by justforlxz** [comment]
已提交翻译
