### ISSUE TITLE
屏幕旋转界面为了应对旋转后黑屏，需要增加响应超时

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#871]
目前黑了就回不来了，需要去tty修改配置文件。

@zccrs @hualet @justforlxz

**Comment by wadelijie** [comment]
第一步  在登录界面  Ctrl+Alt+F2   
第二步  sudo vim ~/.config/deepin/startdde/display.json    将Rotation改为1,
最后  reboot解决

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=193
已经在15.10的计划里

**Comment by lolimay** [comment]
> 第一步 在登录界面 Ctrl+Alt+F2
> 第二步 sudo vim ~/.config/deepin/startdde/display.json 将Rotation改为1,
> 最后 reboot解决

总不能让普通用户搞这个吧 🙃
