### ISSUE TITLE
深度截图 建议在工具栏显示撤销按钮

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#872]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=173744&extra=

> 今天第一次使用深度截图，与qq截图类似，功能好用。但发现深度截图没有撤销返回键，涂鸦错了或者效果不满意需要撤销时只能关闭后重新Ctrl+Alt+A,非常不方便，希望增加该功能。

目前有 Ctrl+Z 与右键菜单中的“撤销编辑“，但是功能入口都比较隐蔽，不易被用户发现。

**Comment by wangjia12** [comment]
这个挺实用的 @shule1987 设计上加一个图标吧

**Comment by shule1987** [comment]
右键和快捷键都有这个功能,没必要加图标, 工具栏上的图标我都嫌多了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
