### ISSUE TITLE
有线网络新建的有线链接的自动链接逻辑不对。

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#874]
【测试环境】
dde-control-center:
  已安装：4.9.1-1
【预置条件】

【测试步骤】
1.新建三个有限链接，分别为有限连接1 有限连接2 有限连接3
2.设置有限连接1不自动连接，有限连接2不自动连接，有限连接3自动连接。
3.进入控制中心-有线网络-开关有限网络开关。
4.分别切换连接有限连接1，有限连接2，有限连接3之后，开关有线网络的开关。
5.分别查看开关有线网络的开关之后，有限连接的自动连接逻辑是否正确
【预期结果】
1.打开有限网络开关之后，能够自动连接有线连接3。
2.有线网络的自动连接的逻辑是正常的。
【测试结果】
1.开关有限网络开关，不能自动连接有线连接3
2.多次切换有限连接之后，开关有线网络的开关，其自动连接的逻辑不正确。
【问题级别】
一般
【出现概率】
稳定重现

**Comment by electricface** [comment]
确实有这个问题

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/dde-daemon/+/41438

**Comment by liuwen123** [comment]
+1
