### ISSUE TITLE
深度商店 失败任务立即被清除

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#876]
发现是控制中心调用了 CleanJob 方法

@justforlxz @zccrs

**Comment by electricface** [comment]
需要区分 job 的 id ，不要所有失败的job都一概清除。

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-control-center/+/41408/

**Comment by liuwen123** [comment]
+1
