### ISSUE TITLE
深度看图右下角会有一个×按钮

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#877]
https://bugzilla.deepin.io/show_bug.cgi?id=14673
![_deepin-image-viewer_20190121105033](https://user-images.githubusercontent.com/12492745/51450215-bca24200-1d6a-11e9-8f97-0e8d26840bae.png)

**Comment by liuwen123** [comment]
![_deepin-image-viewer_20190121111029](https://user-images.githubusercontent.com/12492745/51450811-2de2f480-1d6d-11e9-926a-67816e19934f.png)

**Comment by deepinzhangshuang** [comment]
我也出现过一次  单无法重现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
