### ISSUE TITLE
文件管理器不支持接收微信拖拽内容

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#878]
工程反馈的问题，nautilus可以接收，据说以前也是支持的，看看是什么问题？
@zccrs @BLumia

**Comment by BLumia** [comment]
https://tower.im/teams/9487/todos/228131/

**Comment by zccrs** [comment]
@linuxdeepin/wine-team

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
