### ISSUE TITLE
一些控制中心文案建议

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/internal-discussion#879]
![2019-01-21-171429-6e8754](https://user-images.githubusercontent.com/1006477/51464223-09544000-1da0-11e9-8bfa-f61637ac804d.png)
左手 -> 左手习惯/左手模式

![2019-01-21-171533-3fce91](https://user-images.githubusercontent.com/1006477/51464292-2ee14980-1da0-11e9-8e4e-1ade7cc7888b.png)
第二个“发行版” -> 发行版版本

![2019-01-21-171600-99cd67](https://user-images.githubusercontent.com/1006477/51464315-402a5600-1da0-11e9-95a0-ed1f716af7da.png)
建议移动两个修改密码的复选框到对应的滑杆下方，或修改第二个为“从待机恢复时需要密码”

下面几项是默认程序设置中的：
![2019-01-21-171754-8788aa](https://user-images.githubusercontent.com/1006477/51464429-81226a80-1da0-11e9-9aa8-229c57760d05.png)
文本工具 -> 文本编辑工具

![2019-01-21-171816-e0322a](https://user-images.githubusercontent.com/1006477/51464465-95fefe00-1da0-11e9-9392-4d1cb09ccdd2.png)
音乐 -> 音乐播放器

其他几项也有类似问题，各项应该属于同类别。所以应该是
浏览器/邮件客户端/文本编辑工具/音乐播放器/视频播放器/图片查看器/终端

或者如果都用被操作的对象，则应该是
网页/邮件/文本/音乐/视频/图片/终端

现在的效果是两者混合，比较奇怪。

![2019-01-21-172219-579ac3](https://user-images.githubusercontent.com/1006477/51464699-23425280-1da1-11e9-8104-36ab84472854.png)
热点 -> 无线网络共享，或者 Wifi 网络共享

![2019-01-21-172410-a6d601](https://user-images.githubusercontent.com/1006477/51464809-6270a380-1da1-11e9-815d-54a2fc795a7e.png)
让你 -> 让您

![2019-01-21-172520-165a84](https://user-images.githubusercontent.com/1006477/51464879-8af89d80-1da1-11e9-9688-22f42887c981.png)
此处建议也显示时区偏移量，如 (GMT+8)

![2019-01-21-172554-024449](https://user-images.githubusercontent.com/1006477/51464917-a1065e00-1da1-11e9-821c-0cce193837a4.png)
自动同步 -> 从互联网自动同步

![2019-01-21-172735-57d27b](https://user-images.githubusercontent.com/1006477/51465015-e034af00-1da1-11e9-812b-c75e9d80ec7c.png)
此处的协议名缩写应该全部使用大写，不应首字母大写。

![2019-01-21-173008-1a94ae](https://user-images.githubusercontent.com/1006477/51465148-39044780-1da2-11e9-8899-d67ad3c04de6.png)
这里需要写出前提“不活动时”/“空闲时”，可以直接加在两个短语前面，并去掉“于”

![2019-01-21-173205-fcea11](https://user-images.githubusercontent.com/1006477/51465247-841e5a80-1da2-11e9-9b8d-4b2d1431073e.png)
合上盖子 -> 合上笔记本

**Comment by zhuxiujuancindy** [comment]
@wangjia12

**Comment by wangjia12** [comment]
1、【左手】→【左手模式】
2、我们发型的正式版里不会像截图那样显示两个版本：
![_ _20190123163837](https://user-images.githubusercontent.com/34432879/51593537-59acd880-1f2d-11e9-9936-8b9d44033eb3.png)
3、【唤醒计算机时需要密码】→【待机恢复时需要密码】
4、【浏览器】→【网页】    【文本工具】→文本】
5、热点这个词我查了一些其他操作系统的写法，和开发同事讨论了一下，已经使用比较普遍了，就不改了。
6、后面没有意外情况【你】都统一为【您】。
7、时区显示不是文案问题，要改代码。
8、自动同步同热点一样，自动同步、自动设置这样的用法很普遍了。
9、协议都改成大写。
10、这里要考虑国际化长度的问题，暂时不改，并且设置这两项本来就是有场景的。
11、【合上盖子时待机】→【合上笔记本时待机】

**Comment by felixonmars** [comment]
@wangjia12 
2、这个问题只会在其他发行版出现，这部分在 Deepin 是隐藏的。
