### ISSUE TITLE
launcher大窗口时，右上角的切换窗口图标位置有点偏下了

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#88]
【测试环境】
dde-launcher:4.5.0-1
【预置条件】
launcher大窗口显示
【测试步骤】
1.打开launcher，检查右上角的切换窗口大小的图标位置显示
【预期结果】
1.应该在对准右上角
【测试结果】
1.在右上角偏下的位置
【问题级别】
![2](https://user-images.githubusercontent.com/14539819/47770391-3271b100-dd1a-11e8-929c-809f740288fc.png)

提示性
【出现概率】
稳定重现

**Comment by justforlxz** [comment]
已经修了，内网更新一下

**Comment by yefeifei** [comment]
> 已经修了，内网更新一下

内网验证通过，等待回归测试

**Comment by yefeifei** [comment]
iso 测试通过
