### ISSUE TITLE
一些帮助手册文案建议

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/internal-discussion#880]
深度操作系统：
”热区是为了简化您的操作，方便您快速进入系统的主要界面。“
=>
”热区可以简化您的操作，方便您快速进入系统的主要界面。“

深度操作系统（英文）：
"Everytime you click the mouse"
=>
"Every time you click the mouse"

文件管理器（英文）：
"you can set Deepin File Manger as the default file manager"
=>
"you can set Deepin File Manager as the default file manager"

系统监视器：
”它可以帮你实时监控处理器状态“
=>
”它可以帮您实时监控处理器状态“

深度终端：
”在添加服务器时，你可以点击“
=>
”在添加服务器时，您可以点击“

驱动管理器：
”你可以参考双显卡台式机进行选择“
=>
”您可以参考双显卡台式机进行选择“

”你可以尝试使用加速模式“
=>
”您可以尝试使用加速模式“

录音机：
”你可以通过以下方法查看文件保存位置“
=>
”您可以通过以下方法查看文件保存位置“

计算器：
”让你在键盘输入表达式时“
=>
”让您在键盘输入表达式时“

**Comment by zhuxiujuancindy** [comment]
> 深度操作系统：
> ”热区是为了简化您的操作，方便您快速进入系统的主要界面。“
> =>
> ”热区可以简化您的操作，方便您快速进入系统的主要界面。“
> 
> 深度操作系统（英文）：
> "Everytime you click the mouse"
> =>
> "Every time you click the mouse"
> 
> 文件管理器（英文）：
> "you can set Deepin File Manger as the default file manager"
> =>
> "you can set Deepin File Manager as the default file manager"
> 
> 系统监视器：
> ”它可以帮你实时监控处理器状态“
> =>
> ”它可以帮您实时监控处理器状态“
> 
> 深度终端：
> ”在添加服务器时，你可以点击“
> =>
> ”在添加服务器时，您可以点击“
> 
> 驱动管理器：
> ”你可以参考双显卡台式机进行选择“
> =>
> ”您可以参考双显卡台式机进行选择“
> 
> ”你可以尝试使用加速模式“
> =>
> ”您可以尝试使用加速模式“
> 
> 录音机：
> ”你可以通过以下方法查看文件保存位置“
> =>
> ”您可以通过以下方法查看文件保存位置“
> 
> 计算器：
> ”让你在键盘输入表达式时“
> =>
> ”让您在键盘输入表达式时“

除前两条外，其他几个不是一样的吗？或者我眼睛不好使？

**Comment by zhuxiujuancindy** [comment]
修改完毕，下次发版本时推送外网。

后面几条真考眼力啊，仔细看了几遍终于看出来了 哈哈
