### ISSUE TITLE
用dedit命令行新建空白文本文件，空白文本模板有内容

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#881]
用dedit命令行新建空白文本文件，空白文本模板有内容（模板错误）
@zccrs 看看是不是bug

**Comment by CallMeR** [comment]
@wangjia12  这个问题之前我就发现了 :) 
复现步骤是在编辑器里面打入文字，然后直接关闭编辑器，重新打开后，会保留上次写入但未保存的内容。
如果保存了，这个问题就没有了。
建议是如果输入了内容，但未保存的情况下，关闭编辑器时来一个提示。选择保存或放弃。

**Comment by wangjia12** [comment]
@zccrs 如果新建的输入了内容的文本，关闭时要和正常打开一个文件修改了内容再关闭的时候一样有保存提示。
这还是个bug！

**Comment by zccrs** [comment]
> @zccrs 如果新建的输入了内容的文本，关闭时要和正常打开一个文件修改了内容再关闭的时候一样有保存提示。
> 这还是个bug！我不当需求提了

这是个功能吧

**Comment by wangjia12** [comment]
> > @zccrs 如果新建的输入了内容的文本，关闭时要和正常打开一个文件修改了内容再关闭的时候一样有保存提示。
> > 这还是个bug！我不当需求提了
> 
> 这是个功能吧

这和已存在的文档被编辑了内容关闭时提示一样啊

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
