### ISSUE TITLE
安装器授权协议界面展示调整

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#883]
授权协议不默认展示，不一定非要用户看，默认可以是收拢状态。
@shule1987

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=164

**Comment by zhaofangfangdeepin** [comment]
这个不是15.10 的需求吗？怎么给分到15.9.3里面了

**Comment by zccrs** [comment]
iso 测试任务，移动到15.10
