### ISSUE TITLE
编辑器在设置里设置隐藏行号和状态栏

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#884]
背景：

行号和状态栏都一直显示。

需求：

在设置里添加这两项的设置，默认勾选。

文案：

【显示行号】

【显示状态栏】

@zccrs @zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
文案：
【显示行号】【Display line number】
【显示状态栏】【Display status bar】

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
