### ISSUE TITLE
待机后无法关机和重启

### ISSUE THREAD

**Issue by kikyoulzg** [linuxdeepin/internal-discussion#885]
【测试环境】
deepin15.9 

【预置条件】
待机一次以后
【测试步骤】
先待机，唤醒，切换到tty，sudo reboot
【预期结果】
重启
【测试结果】
nouveau 0000:02:00.0: Xorg[5839]:failed to idle channel 3
usb 2-4:device descriptor read/64,error -71
(省略）
watchdog：BUG： soft lockup -cpu#3 stuck for 23s！
【问题级别】
严重
【出现概率】
稳定复现

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
