### ISSUE TITLE
在launcher显示时，更换壁纸后显示错误

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#886]
![image](https://user-images.githubusercontent.com/3241440/51582082-85b46380-1f05-11e9-9362-f23b9db3caca.png)
如图，launcher 的上下部分有两条前一张壁纸的残留。

@zccrs @listenerri @liuwen123

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/41595/

**Comment by electricface** [comment]
测试通过

**Comment by liuwen123** [comment]
已修复
