### ISSUE TITLE
新安装的系统，商店选中始终都是中国区

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#888]
【测试步骤】
新安装系统，然后语言选择为英文，时区选择为国外，系统安装成功后，查看商店时区选择

【预期结果】
商店时区为国外时区

【测试结果】
商店始终都是中国区

【问题级别】
一般

【出现概率】
100%

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
