### ISSUE TITLE
扩展模式下，登录界面的用户头像位置发生偏移

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#89]
【测试环境】
dde-session-ui:4.6.0-1
【预置条件】
1.双屏模式，设置外接屏幕为主屏
【测试步骤】
1.扩展模式下，注销系统，检查登录界面用户头像位置显示
【预期结果】
1.头像位置居中显示
【测试结果】
1.头像位置偏移
【问题级别】
一般
【出现概率】
稳定出现
![111](https://user-images.githubusercontent.com/14539819/47771170-289d7d00-dd1d-11e8-8522-d188b47572a4.jpg)

**Comment by mmxzmmxz** [comment]
目前显示位置正常。
dde-session-ui:
  已安装：4.7.0~gerrit+40490~1

**Comment by iamhyc** [comment]
![image](https://user-images.githubusercontent.com/9068301/49853118-18e77d00-fe21-11e8-9424-43095275f33f.png)

“涉密不上网啊”

关一下你们testlink的注册，不然，我就要肆无忌惮了 😈

**Comment by mmxzmmxz** [comment]
@iamhyc 这都被你发现了(⊙﹏⊙)b，速速处理～

**Comment by mmxzmmxz** [comment]
最新版本验证正常，其他在下述任务跟踪：
https://github.com/linuxdeepin/internal-discussion/issues/596
dde-session-ui                   4.7.0+r11+gdb7470b    amd64
