### ISSUE TITLE
dock 上的无线网络展开时和控制中心无线网络列表打开时每秒自动刷新

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#901]
之前有讨论： https://tower.im/teams/9487/todos/228425/

控制中心如果隐藏了，则暂停自动刷新。

@listenerri @jouyouyun @wangjia12

**Comment by listenerri** [comment]
每秒自动刷新太频繁了吧? 而且我记得刷新频率过高时后端或NM服务会报一个警告, 说不允许扫描(类似)

**Comment by electricface** [comment]
也可以是 2秒

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
