### ISSUE TITLE
dtkwidget 提交导致深度影院标题栏无法正常显示问题

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#902]
由 [dtkwidget@010c75d#L281-L316](https://github.com/linuxdeepin/dtkwidget/blob/010c75d53417099132b85dc82d0768ad5c3520f3/src/widgets/dtitlebar.cpp#L281-L316) 引入，会导致深度影院无法正常显示标题栏，revert 此提交中的 `DTitlebarPrivate::updateButtonsState` 变动即可解决此问题。

受到影响的目前只有深度影院，其他程序正常。不清楚修改原因，所以不清楚是深度影院使用 dtkwidget 提供的 API 用法有误还是 DTitlebar 本身有问题。另外，对于当前的状态（dtkwidget tag 2.0.9.15）下，当通过 `setWindowFlags()` 同时设置 `Qt::FramelessWindowHint` 和 `Qt::WindowMinMaxButtonsHint` 时，`Qt::FramelessWindowHint` 似乎会被丢弃。

另外 @hualet 觉得目前的接口设计也有些问题，可以讨论一下。

cc: @Iceyer @hualet @zccrs

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
