### ISSUE TITLE
编辑器改名文本编辑器

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#903]

**Comment by deepinzhangshuang** [comment]
根据专业版用户工程反馈，编辑器目前辨识度不够存，根据询问发现存在两个问题
1.图标辨识度不够，目前看公司设计应该是扁平加拟物设计风格，但是目前图标辨识度不够。
2.《编辑器》命名有歧义，其他软件或者windows都是记事本或者文本编辑器，建议改为文本编辑器
@shule1987 @wangjia12 @zccrs @hualet @liuwenhuan

**Comment by shule1987** [comment]
觉得图标辨识度不够是没理解引号所能代表的含义， 图标暂时不会改的

**Comment by deepinzhangshuang** [comment]
引号所能代表的意义更偏向于程序员吧？

**Comment by shule1987** [comment]
谁跟你说的引导倾向程序员的， 难道我引用一个人说的话不能用引号， 引用一句歌词一句诗不能用引号吗，引号代表的是任何可能的话任何可能的文字

**Comment by deepinzhangshuang** [comment]
我的意思是对引号的敏感度上面我觉得程序员可能会更高一些。当然你想用什么设计是你的选择，我也不想和你探讨引号的用法，我只是反馈一下工程实施过程的问题。

**Comment by shule1987** [comment]
程序员好像不是用的这种引号吧，从来没想往程序员方向靠。这个图标不改

**Comment by wangjia12** [comment]
那不是有两个文本编辑器啊 一样的名字

**Comment by wangjia12** [comment]
@deepinzhangshuang 可以有两个完全一样的名字的应用吗

**Comment by hualet** [comment]
> @deepinzhangshuang 可以有两个完全一样的名字的应用吗

可以

**Comment by zinface** [comment]
这个建议不错，文本编辑器，文件管理器等命名，图标建议上面有一支笔。或者建议使用  > ~/ [ ] { }   等字符，不需要引号。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
