### ISSUE TITLE
ssh远程连接后，终端显示15.8 需要修改

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#904]
【测试步骤】
打开终端ssh连接到另一台pc机器上，查看打印显示

【预期结果】
显示Deepin 15.9

【测试结果】
还是显示Deepin 15.8

【问题级别】
一般

【出现概率】
100%

`
Connecting to 10.0.13.165:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Welcome to **Deepin 15.8** GNU/Linux

    * Homepage:https://www.deepin.org/

    * Bugreport:https://feedback.deepin.org/feedback/

    * Community:https://bbs.deepin.org/

Last login: Wed Jan 30 10:27:42 2019`

**Comment by deepinzhangshuang** [comment]
重复任务 15.9.2任务里已经处理
