### ISSUE TITLE
文件管理器 右键粘贴增加子菜单,允许以管理员身份粘贴

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#905]
原帖： https://bbs.deepin.org/forum.php?mod=viewthread&tid=174409&extra=

**Comment by BLumia** [comment]
我觉得不太合适，文件夹权限的目的之一本来就是防止用户去动这些文件夹，用户真的有需求可以用管理员身份开文管或者自行编写右键菜单插件来做这个需求。进行这样的操作本身就是不提倡的，所以我觉得不应该提供这样的支持。

不过对于帖子提到的另一个需求说对文件夹右键进行粘贴（避免双击打开再粘贴）的功能还是比较合理的，不过这是不同的需求，如果考虑的话应该另开一个issue。

**Comment by CallMeR** [comment]
是时候普及一下cli操作的时候了。

**Comment by wangjia12** [comment]
管理员操作可以不用提供这么便捷的方式，影响不使用管理员身份粘贴的用户。

**Comment by electricface** [comment]
你看用户提供的截图，那是菜单中“粘贴”是灰色的，用户的诉求其实就是在粘贴不能时增加一项 “以管理员权限粘贴”。
