### ISSUE TITLE
应用商店 个人中心-我的赞赏中显示出赞赏总额

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#906]
原帖： https://bbs.deepin.org/forum.php?mod=viewthread&tid=174407&extra=

**Comment by CallMeR** [comment]
目前打赏金额计算是根据汇率来的。。会发生变化。。。

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=285
记录的是当时打赏的汇率，赏完了当时是多少就记录的是多少了

**Comment by shule1987** [comment]
<img width="356" alt="2019-02-19 4 21 03" src="https://user-images.githubusercontent.com/5448609/53000068-6d7f2800-3462-11e9-956e-c2cfacdece7b.png">

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
