### ISSUE TITLE
应用商店 个人中心 - 我的赞赏 页面 支付渠道是支付宝，却显示是微信

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#907]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174407&extra=

确认有这个问题

**Comment by myml** [comment]
https://cr.deepin.io/#/c/dstore/deepin-appstore/+/41538/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
