### ISSUE TITLE
文件管理器 右键文件夹时，允许直接粘贴进文件夹，而不需要打开文件夹，再粘贴

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#909]
@BLumia 
原帖： https://bbs.deepin.org/forum.php?mod=viewthread&tid=174409&page=1#pid559013

**Comment by CallMeR** [comment]
hmmm，目前支持鼠标左键点中文件，按住ctrl键拖动到文件夹就是“复制并放入文件夹”的操作....
只不过现在没有动画...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
