### ISSUE TITLE
锁屏界面切换用户，已经登录用户的√图标没有放大适配高分屏

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#91]
【测试环境】
dde-session-ui:4.6.0-1
【预置条件】
高分屏、多个用户
【测试步骤】
1.登录用户deepin，super+l，锁屏，点击用户，检查已登录用户的图标显示
【预期结果】
图标大小要适配高分屏
【测试结果】
图标太小，没有缩放
【问题级别】
提示
![21](https://user-images.githubusercontent.com/14539819/47771722-5aafde80-dd1f-11e8-825f-bd581393d0e6.jpg)

【重现概率】
稳定重现

**Comment by rekols** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/39535/

**Comment by yefeifei** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/39535/

cr+1

**Comment by yefeifei** [comment]
iso 测试通过
