### ISSUE TITLE
看图在 2d 窗管下无法全屏

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#911]
社区原贴:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174402&extra=

试了一下跟 dock 无关, 只是没有全屏, 就算把 dock 调到其他位置, 底部依然会有空隙

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
