### ISSUE TITLE
[建议]应用商店中,增加“我推荐的应用”记录页面。

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#913]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174414&extra=

**Comment by CallMeR** [comment]
hmmm，推荐的应用，是不是还有收藏的应用？
不过这个感觉优先级还是比“提高应用更新速度”来的低。。。

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=286
这个问题归类到丰富商店的个人中心需求里去，但是现阶段不会做。
我的推荐比其他我的打赏、下载这些要不常用，且归类的必要性低。
用户说的每个推荐唯一ID，在真的收入到商店之前是不可能做到每个用户推荐的都是非常标准正确的信息，是不好做的。
另外，推荐排行是不错，可以看到哪个应用用户最需要，但现在不适合做这个，打包速度没跟上来的情况下会堆积很多很多。
先记录。
