### ISSUE TITLE
建议增加列表紧凑显示模式，类似Windows下面的“列表”显示方式，只显示文件夹列表，不显示详细信息。

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#914]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174166&extra=

**Comment by wangjia12** [comment]
以前就有这个信息，显示多少项，后来去掉的。因为开发那边反应显示这个多少项在某些机器上会影响性能，然而这些信息在底部状态栏和属性也是可以查看到的。所以就去掉了。

**Comment by liuwen123** [comment]
用户说的不是显示选项的意思，是增加一种视图，只显示列表不显示文件详情
![111](https://user-images.githubusercontent.com/12492745/53062047-791e2d80-34fa-11e9-839a-a69b75ff7f6c.png)
![default](https://user-images.githubusercontent.com/12492745/53062049-79b6c400-34fa-11e9-9fb9-d920878fdcdb.png)

**Comment by wangjia12** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/921
规划到下版本的需求评审

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
