### ISSUE TITLE
建议预装 network-manager-sstp 

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#915]
目前 控制中心已经增加了对 SSTP VPN 的支持

@listenerri

**Comment by listenerri** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/560

**Comment by electricface** [comment]
目前这个包 network-manager-sstp  还没推送到外网，@deepinzhangshuang 你尽快推送一下吧。

**Comment by deepinzhangshuang** [comment]
已经更新到ppa/dde-panda 会跟随15.9.3推送外网

**Comment by electricface** [comment]
iso 生成的时候要预装

**Comment by deepinzhangshuang** [comment]
network-manager-integration-plugins　　更新了这个预装包，添加了network-manager-sstp　依赖，下次跟随系统推送外网

**Comment by deepinzhangshuang** [comment]
已经更新外网
