### ISSUE TITLE
深度文本编辑器的宽度不能变得更窄

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#917]
如题，对比 gedit 的最小宽度，确实更宽。
原贴：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174420

![image](https://user-images.githubusercontent.com/3241440/52023759-620ea000-2539-11e9-9058-f69a48e191cb.png)

**Comment by wangjia12** [comment]
@shule1987 麻烦定一个最小尺寸吧

**Comment by shule1987** [comment]
最小400X300

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=283

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/929#issuecomment-479810458 这个里处理了。最终决定的大小是 450*250
