### ISSUE TITLE
应用商店 增加一种安装软件包失败的错误类型： 有未认证的包

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#918]
错误内容是：
E: There were unauthenticated packages and -y was used without --allow-unauthenticated

类型名: JobError::unauthenticatedPackages

https://cr.deepin.io/#/c/lastore/lastore-daemon/+/41547

推荐中文文案是【有未经认证的包】
推荐英文文案是 【There were unauthenticated packages】

**Comment by myml** [comment]
@zhuxiujuancindy
 
这个文案可以吗

**Comment by zhuxiujuancindy** [comment]
文案没有问题
@wangjia12 你看看

**Comment by wangjia12** [comment]
这个先不要加吧，原因如下：
1、这个错误是用户自己修改了源之后可能会出现的错误，正常使用不会有这个错误，可以归为失败的统一提示里面。
2、现在已经有用户改了源之后的提示，并且有一键改回官方源的方式。
3、这个提示是说包的问题，也不是说源的问题。
