### ISSUE TITLE
深色主题不够完全

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#919]
拿文件管理器来说，比如右键菜单，关于对话框，设置对话框，文件名过长鼠标移动到它的上方显示的tooltips 不是深色的。
![image](https://user-images.githubusercontent.com/3241440/52032473-0dc8e780-255c-11e9-957f-09b9ee4306e2.png)

**Comment by wangjia12** [comment]
@shule1987

**Comment by shule1987** [comment]
<img width="577" alt="2019-02-19 9 52 28" src="https://user-images.githubusercontent.com/5448609/52984842-1d856e80-342c-11e9-8175-27d95d1ff209.png">

font-size: 12px;
color: #ECECEC;
background: #424242;
border: 1px solid rgba(0,0,0,0.10);
box-shadow: 0 2px 4px 0 rgba(0,0,0,0.10);
border-radius: 4px;

**Comment by zccrs** [comment]
之前的设计就是这样的，只有主窗口深色

**Comment by shule1987** [comment]
后面深色控件反正都要慢慢补全的

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=284
15.11

**Comment by electricface** [comment]
我不是还说了其他的吗 如右键菜单，关于对话框，设置对话框。

**Comment by wangjia12** [comment]
> 我不是还说了其他的吗，如右键菜单，关于对话框，设置对话框。

https://pms.deepin.cn/index.php?m=story&f=view&storyID=195   以前就有了，最后一条。我直接把tooltip也补到这一条需求里去。不单独列了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
