### ISSUE TITLE
高分屏下打开文件管理器窗口会出现花屏

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#92]
【测试环境】
dde-file-manager:4.6.9-2
[AMD/ATI] Cape Verde XT [Radeon HD 7770/8760 / R7 250X]
【预置条件】
高分屏独立显卡
【测试步骤】
1.打开深度文件管理器，检查窗口显示
【预期结果】
窗口显示正常不会花屏
【测试结果】
打开过程中会出现花屏
【问题级别】
严重
【出现概率】
![92](https://user-images.githubusercontent.com/14539819/47772673-6a7cf200-dd22-11e8-9c46-1c9ebd299de1.gif)

稳定重现

**Comment by yefeifei** [comment]
快速点击控制中心，也会花屏
![_ _20181031155954](https://user-images.githubusercontent.com/14539819/47773868-62bf4c80-dd26-11e8-9186-23c2676901b7.gif)

**Comment by rekols** [comment]
估计和显卡有关。

**Comment by zccrs** [comment]
@yefeifei 换个驱动试试

**Comment by yefeifei** [comment]
> @yefeifei 换个驱动试试

我的电脑是I+A卡，怎么换？

**Comment by zccrs** [comment]
> > @yefeifei 换个驱动试试
> 
> 我的电脑是I+A卡，怎么换？

单I卡会这样吗

**Comment by yefeifei** [comment]
> > > @yefeifei 换个驱动试试
> > 
> > 
> > 我的电脑是I+A卡，怎么换？
> 
> 单I卡会这样吗

高分屏的问题，换成1080的不会花屏
