### ISSUE TITLE
记录窗口最大化状态是否成为规范

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#920]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174410 第一点
发现可以有最大化窗口的应用中，没有实现这个功能的有：

- 深度文件管理器
- 深度影院
- 深度文本编辑器
- 深度图片查看器
- 深度帮助手册
- 深度终端

实现了的有：
- 深度音乐
- 深度应用商店
- 系统监视器

这是需要窗口程序自己记录，还是靠窗口管理器记录？

@hualet @sonald @Iceyer

**Comment by sonald** [comment]
程序自己干

**Comment by hualet** [comment]
并不怎么好用吧？

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=279
已加入15.11的需求评审

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
