### ISSUE TITLE
按钮的虚线描边表示键盘操作的控件的焦点

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#921]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174410 第十点

> 当安装Shift+Del永久删除文件时弹出的确认框删除按钮可以响应Enter，但是无任何明显提示，用户未必知道可以按Enter，所以是否可以添加默认选中效果？

在 windows 系统下这种比较常见，gtk 窗口也是支持的，比如下图为 nautilus 文件管理器的确认对话框（使用Numix 主题）：

![image](https://user-images.githubusercontent.com/3241440/52034032-16bcb780-2562-11e9-9fe2-579d92bf3da4.png)

使用 Adwaita 主题，描边细到看不见。

![image](https://user-images.githubusercontent.com/3241440/52034848-2d640e00-2564-11e9-871e-728f769c2b71.png)

下图为深度文件管理器确认删除对话框，也许设计师想用红色表示警示，但是缺乏表达键盘操作控件的焦点。
![image](https://user-images.githubusercontent.com/3241440/52034163-9e0a2b00-2562-11e9-95b6-a0bac2a3e9d6.png)

@shule1987

**Comment by wangjia12** [comment]
@shule1987 我记得之前你处理了这个问题，选中项加了一条横线的，后面怎么样了？如果没做就把设计图贴一下我安排后面版本加上。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
