### ISSUE TITLE
软件中心首页最大化适配问题，热门推荐和下载排行未左响应式适配，导致左右留较大空白

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#922]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174410&page=1&extra=#pid559325  第十二点

![image](https://user-images.githubusercontent.com/3241440/52035290-1eca2680-2565-11e9-9e65-87fccb8116b6.png)

**Comment by wangjia12** [comment]
这是特意居中显示的
cc @shule1987

**Comment by electricface** [comment]
这个其实可以通过增加热门推荐那一栏的宽度（增加每行推荐app的数量）来填补空白的。

**Comment by shule1987** [comment]
可以这样做,只是当初计算的时候不太好计算,所有也就没这样做了,暂时不改了
