### ISSUE TITLE
软件中心登录输入用户名和密码登录左上角提示loading...文字，简直是简单粗暴

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#923]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174410&page=1&extra=#pid559325 第十四点

![image](https://user-images.githubusercontent.com/3241440/52035513-add73e80-2565-11e9-9696-e5b155a11af8.png)

**Comment by wangjia12** [comment]
这个界面没有设计吗 @shule1987

**Comment by Iceyer** [comment]
@shule1987 不要弄的太复杂啊，这个东西是一段纯html/js代码。

**Comment by Iceyer** [comment]
> > @shule1987 不要弄的太复杂啊，这个东西是一段纯html/js代码。
> 
> 我们不是有标准的loading吗
> <img alt="2019-02-19 3 03 10" width="280" src="https://user-images.githubusercontent.com/5448609/52996167-aa91ed00-3457-11e9-8234-9ee6ec560a15.png">

这个动画是依赖框架做的，我看下能不能抽离出来吧。
这个页面其实留白也可以的 :cry:

**Comment by myml** [comment]
> > > @shule1987 不要弄的太复杂啊，这个东西是一段纯html/js代码。
> > 
> > 
> > 我们不是有标准的loading吗
> > <img alt="2019-02-19 3 03 10" width="280" src="https://user-images.githubusercontent.com/5448609/52996167-aa91ed00-3457-11e9-8234-9ee6ec560a15.png">
> 
> 这个动画是依赖框架做的，我看下能不能抽离出来吧。
> 这个页面其实留白也可以的

加载动画的独立版本，在这个提交里可以参考
https://cr.deepin.io/#/c/dstore/deepin-appstore/+/39388/1/src/web/src/index.html

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
