### ISSUE TITLE
控制中心的时间没有地方可以设置 24/12 小时制

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#924]
原贴:
https://www.reddit.com/r/deepin/comments/almni7/24_hour_to_12_hour_clock_fix/

目前之后 dock 的时间插件上有选项可以设置

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=281
规划到15.11的需求评审

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
