### ISSUE TITLE
深度商店 深色模式下 登录图标看不清

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#925]
PC上的原图
![image](https://user-images.githubusercontent.com/3241440/52035805-4241a100-2566-11e9-8339-14d3384608bd.png)

手机照相机拍摄
![image](https://user-images.githubusercontent.com/3241440/52036165-5d60e080-2567-11e9-86e4-910541ef83d1.png)

**Comment by wangjia12** [comment]
@shule1987 看一下这个图标问题

**Comment by shule1987** [comment]
[商店深色用户头像.zip](https://github.com/linuxdeepin/internal-discussion/files/2874634/default.zip)

**Comment by myml** [comment]
@Iceyer

**Comment by Iceyer** [comment]
https://cr.deepin.io/c/dstore/deepin-appstore/+/41690

**Comment by electricface** [comment]
测试通过

**Comment by Iceyer** [comment]
https://cr.deepin.io/#/c/dstore/deepin-appstore/+/41691

**Comment by electricface** [comment]
发现严重问题，当用户登录时，切换深、浅色的主题，会导致用户头像看不见。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
