### ISSUE TITLE
deepin目前托盘图标大小不跟随dock上图标大小变化而变化

### ISSUE THREAD

**Issue by zhiw2019** [linuxdeepin/internal-discussion#926]
导致 的结果就是dock上托盘图标和其它任务栏图标大小不一致不协调。

**Comment by BLumia** [comment]
设计如此，cc @shule1987 。

顺便，您如果有什么好想法或者想要进行进一步的讨论，可以考虑发到 developer-center 那个 repo 的 issue 面板。internal-discussion 是供内部记录和讨论任务用的。
