### ISSUE TITLE
桌面右上角放置文件、文件夹等放大和缩小图标大小位置乱跑

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#927]
原帖： https://bbs.deepin.org/forum.php?mod=viewthread&tid=174410&page=1&extra=#pid559341 第三点

取消自动排列，文件放置在桌面的右上角，图标大小设置为**极小**时：
![image](https://user-images.githubusercontent.com/3241440/52037256-74083700-2569-11e9-95fa-717834e40345.png)
改变图标大小为**小**时：
![image](https://user-images.githubusercontent.com/3241440/52037277-84b8ad00-2569-11e9-8a2e-dc98d6f92344.png)
再次改变图标大小为**极小**时：
![image](https://user-images.githubusercontent.com/3241440/52037390-d82afb00-2569-11e9-92c4-8239fe39e363.png)

**Comment by wangjia12** [comment]
这不应该是个bug吗 ？
 @zccrs

**Comment by zccrs** [comment]
> 这不应该是个bug吗 ？
> @zccrs

不是bug，图标放大缩小就是这样的策略，并不会记录之前的位置

**Comment by wangjia12** [comment]
这个没有解的，改了大小真的只能换位置。
