### ISSUE TITLE
关闭窗管特效之后，在壁纸设置界面设置壁纸，点击壁纸设置壁纸之后，桌面画面没有立刻变化。<周四>

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#93]
【测试环境】
dde-desktop:
  已安装：4.6.9-2
【预置条件】
1.关闭窗管特效。
【测试步骤】
1.桌面空白处右键-设置壁纸。点击任意图片进行设置壁纸。
【预期结果】
1.设置壁纸，桌面立即变化，可以看到效果。
【测试结果】
1.桌面没有立即变化。退出桌面壁纸设置之后才能看到效果。
【问题级别】
一般
【出现概率】
稳定复现。

**Comment by zccrs** [comment]
@zhaofangfangdeepin 这个是按了 super + d 之后才会出现的吧

**Comment by zccrs** [comment]
https://cr.deepin.io/#/c/deepin-metacity/+/41380/
