### ISSUE TITLE
根据用户选择的时区判断商店默认打开的区

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#933]
需求描述
背景：

商店4.0时有这个需求，5.0时候没有单独提出来，做掉了。

需求：

用户在安装器选择了时区后，选择中国的默认商店打开中国区，选择其他国家的商店默认打开国际区；
用户手动选择时区后，改变这个默认选项，以手动选择为准；
后面通过deepin ID改变选区如果有冲突，再解决；

https://pms.deepin.cn/index.php?m=story&f=view&storyID=265
@Iceyer

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
