### ISSUE TITLE
锁屏双屏bug

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#934]
https://m.toutiaocdn.com/i6653291102805688835/?iid=59394749639&app=news_article&timestamp=1549115031&group_id=6653291102805688835&abtest_id=1&wxshare_count=1&tt_from=weixin&utm_source=weixin&utm_medium=toutiao_android&utm_campaign=client_share&from=groupmessage&isappinstalled=0

**Comment by justforlxz** [comment]
这个问题已经处理了。
