### ISSUE TITLE
深度看图提供修改操作的设置

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#935]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174485&page=1#pid559679

比如设置缩放为 ctrl+鼠标滚轮，切换图片为鼠标滚轮。

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=280
已经纳入15.11需求评审

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
