### ISSUE TITLE
特殊处理 google-chrome 的应用代理

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#937]
原帖：https://bbs.deepin.org/forum.php?mod=viewthread&tid=158210&page=2#lastpost

已知用 proxychains4 运行 google-chrome 将导致运行它失败，但是 google-chrome 支持使用命令行选项 --proxy-server 指定代理服务器，于是就想特殊处理 google-chrome，不使用 proxychains4 运行它，而是增加命令行选项。 

@hualet @zccrs @wangjia12

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/41673

**Comment by electricface** [comment]
支持了 360浏览器，google-chrome，chromium。
还需要测试一下需要用户名和密码的http代理。

**Comment by electricface** [comment]
使用 tinyproxy 测试了需要用户名和密码的 http 代理，发现不能在 --proxy-server 的值中带上用户名和密码，需要google chrome 弹出窗口来输入用户名和密码以登录代理服务器。

**Comment by liuwen123** [comment]
已修复
