### ISSUE TITLE
我在arm64上编译dde遇到了问题

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/internal-discussion#938]
有一个叫libdmr的依赖是我的源里没有的，于是我下载了deepin-movie-reborn的源码（libdmr构建在这里面），但是编译失败了，提示expected initializer before 'glMPGetNativeDispaly' 和'glMPGetNativeDisplay' was not declared in this socpe，这个怎么办？

**Comment by felixonmars** [comment]
看起来是 libmpv 的方法，需要安装 libmpv 的开发组件包。

**Comment by MCredbear** [comment]
> 看起来是 libmpv 的方法，需要安装 libmpv 的开发组件包。

libmpv-dev我已经安装了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
