### ISSUE TITLE
15.9.1更新后，只有文件管理器可以用

### ISSUE THREAD

**Issue by Pillar1989** [linuxdeepin/internal-discussion#939]
【测试环境】
我的电脑是intel [NUC6I7KYK](http://detail.zol.com.cn/mini-desktop_pc/index1211213.shtml) 

【预置条件】
直接从控制台更新

【测试步骤】

【预期结果】
完美更新

【测试结果】
只有文件管理器可以用

【问题级别】

【出现概率】

这是我工作用的电脑很多生产环境在里面，还希望能帮忙看看是怎么回事。深度系统还是很好用的，还是希望能继续用。
[deepin-feedback-cli-Deepin-15.9.1-all-20190211-101950.tar.gz](https://github.com/linuxdeepin/internal-discussion/files/2850161/deepin-feedback-cli-Deepin-15.9.1-all-20190211-101950.tar.gz)

**Comment by BLumia** [comment]
"只有文件管理器可以用" 指的是其他程序点击无任何响应还是打开会自动关闭还是其他的行为？

@hualet 移到 developer-center ?

**Comment by Pillar1989** [comment]
这个问题我已经解决了，主要原因是我在/etc/environment里面加了一句
```
$PATH:/opt/gcc-arm-none-eabi/bin/
```
我是很奇怪,我这是正确的设置环境变量的方法，为什么在deepin上面会导致系统出现问题。

**Comment by Pillar1989** [comment]
加了这一句以后，root用户的变量PATH会被清空，我看了，你们的系统应用相关的脚本，脚本里面的命令竟然都没有加上绝对路径，导致系统窗口管理器等启动失败。

**Comment by felixonmars** [comment]
> 这个问题我已经解决了，主要原因是我在/etc/environment里面加了一句
> 
> ```
> $PATH:/opt/gcc-arm-none-eabi/bin/
> ```
> 
> 我是很奇怪,我这是正确的设置环境变量的方法，为什么在deepin上面会导致系统出现问题。

正确的设置方法应该是

```
PATH="$PATH:/opt/gcc-arm-none-eabi/bin/"
```
吧……

**Comment by BLumia** [comment]
> 这个问题我已经解决了，主要原因是我在/etc/environment里面加了一句
> 
> ```
> $PATH:/opt/gcc-arm-none-eabi/bin/
> ```
> 我是很奇怪,我这是正确的设置环境变量的方法，为什么在deepin上面会导致系统出现问题。

你这个不正确...参见上面 @felixonmars 的说明（

解决了的话就先关掉 issue 了，如果有其它问题可以在 developer-center 这个 repo 开 issue ，这个 repo 是内部讨论用的所以...
