### ISSUE TITLE
快速点击打开控制中心，桌面右侧有一条细框闪

### ISSUE THREAD

**Issue by yefeifei** [linuxdeepin/internal-discussion#94]
【测试环境】
dde-control-center:4.7.1-2
dde-desktop:4.6.9-2

【预置条件】
无
【测试步骤】
1.快速点击dock的控制中心图标，检查打开和隐藏控制中心过程显示
【预期结果】
1.控制中心显示正常，没有细框显示
【测试结果】
打开过程中会有白色的细框显示
【问题级别】
一般
【出现概率】
稳定重现
![_ _20181031155954](https://user-images.githubusercontent.com/14539819/47773791-34da0800-dd26-11e8-8ab9-752b75c8794c.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
