### ISSUE TITLE
智能镜像源关闭后，选择其他镜像源无法生效

### ISSUE THREAD

**Issue by deepinzhangshuang** [linuxdeepin/internal-discussion#940]
如题

**Comment by deepinzhangshuang** [comment]
@zccrs @hualet @liuwen123 @wangjia12

**Comment by Iceyer** [comment]
https://cr.deepin.io/#/c/lastore/lastore-daemon/+/41697

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
