### ISSUE TITLE
【安全问题】锁屏异常退出后没有重新启动的处理方法

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#941]
startdde增加接口来维持锁屏的启动状态。锁屏启动后向startdde注册，startdde判断pid和启动路径确认是否为dde-lock，锁屏解锁成功后向startdde取消注册。

为了避免锁屏被恶意杀掉造成资源浪费，准备屏蔽一些信号来防止kill。 

@electricface

**Comment by justforlxz** [comment]
https://github.com/linuxdeepin/developer-center/issues/730

**Comment by electricface** [comment]
bus: session bus
service name: com.deepin.SessionManager
object path: /com/deepin/SessionManager

增加方法
SetLocking(value bool)

dde-lock 启动后，立即调用 SetLocking(true)
dde-lock 解锁之后，调用 SetLocking(false)

**Comment by listenerri** [comment]
> bus: session bus
> service name: com.deepin.SessionManager
> object path: /com/deepin/SessionManager
> 
> 增加方法
> SetLocking(value bool)
> 
> dde-lock 启动后，立即调用 SetLocking(true)
> dde-lock 解锁之后，调用 SetLocking(false)

增加一个读取的接口吧?

**Comment by hualet** [comment]
有一个相关的问题， loginctl lock-session 应该可以用来锁定屏幕的吧，我们的好像不生效 @electricface

**Comment by hualet** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/934 类似问题

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/41622/

**Comment by electricface** [comment]
> > bus: session bus
> > service name: com.deepin.SessionManager
> > object path: /com/deepin/SessionManager
> > 增加方法
> > SetLocking(value bool)
> > dde-lock 启动后，立即调用 SetLocking(true)
> > dde-lock 解锁之后，调用 SetLocking(false)
> 
> 增加一个读取的接口吧?

加了属性 Locking bool

**Comment by electricface** [comment]
> 有一个相关的问题， loginctl lock-session 应该可以用来锁定屏幕的吧，我们的好像不生效 @electricface

可能需要监听org.freedesktop.login1 session 的 Lock 和 Unlock 信号

gdbus monitor -y -d org.freedesktop.login1
Monitoring signals from all objects owned by org.freedesktop.login1
The name org.freedesktop.login1 is owned by :1.0


/org/freedesktop/login1/session/_350: org.freedesktop.login1.Session.Lock ()
/org/freedesktop/login1/session/_350: org.freedesktop.login1.Session.Unlock ()

**Comment by justforlxz** [comment]
@listenerri

**Comment by listenerri** [comment]
在锁屏显示和隐藏时向 com.deepin.SessionManager 设置状态:
https://cr.deepin.io/c/dde/dde-session-ui/+/41702
