### ISSUE TITLE
文件类型都改为英文首字母大写

### ISSUE THREAD

**Issue by zhuxiujuancindy** [linuxdeepin/internal-discussion#942]
因高级搜索的其他子选项都为首字母大写，为大小写一致，需要把：
高级搜索，列表视图以及文件属性里面的文件类型的英文都改为首字母大写。
Unknown
Application
Video
Audio
Image
Archive
Text
Executable
Directory

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41629/

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/dde-file-manager/commit/f28c12260b149ba300db166582e5c96055079e16

内网更新到这个版本之后就可以检查一下还有没有问题了。

**Comment by zhuxiujuancindy** [comment]
显示正确
