### ISSUE TITLE
关闭窗口特效时，dock 的窗口的关闭按钮位置不对

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#944]
如图
![image](https://user-images.githubusercontent.com/3241440/52828185-c10c1180-3102-11e9-9c28-0af712d013e3.png)

@shule1987 @wangjia12 @listenerri

**Comment by listenerri** [comment]
https://cr.deepin.io/#/c/dde/dde-dock/+/41987

**Comment by liuwen123** [comment]
已修复
