### ISSUE TITLE
系统没有更新的情况下，控制中心也会提示更新失败 <z5>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#945]
【测试步骤】
内网升级到最新版本，然后系统没有任何软件包更新，打开控制中心，查看提示信息显示

【预期结果】
系统没有包更新，不会给出提示信息

【测试结果】
系统没有包更新，也会弹出更新失败提示

【问题级别】
一般

【出现概率】
100%
![_ _20190215095758](https://user-images.githubusercontent.com/12492745/52829640-8ad19080-3108-11e9-959b-94e46724ea97.png)

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/lastore/lastore-daemon/+/41630

**Comment by liuwen123** [comment]
已修复
