### ISSUE TITLE
vncviwer官网下载的二进制客户端，从文件管理器双击，没有执行

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#948]
【测试环境】
https://www.realvnc.com/en/connect/download/viewer/
VNC-Viewer-6.19.107-Linux-x64
【预置条件】

【测试步骤】
1.进入vncviwer官网：https://www.realvnc.com/en/connect/download/viewer/，下载客户端VNC-Viewer-6.19.107-Linux-x64
2.打开文件管理器-下载-双击VNC-Viewer-6.19.107-Linux-x64。
【预期结果】
1.直接执行。
【测试结果】
1.没有任何响应。
【问题级别】
一般
【出现概率】
稳定复现
文件管理器上显示，该文件是可执行程序，但是双击，没有任何响应。终端进去看，没有x权限。

**Comment by zhaofangfangdeepin** [comment]
![_ _20190218101725](https://user-images.githubusercontent.com/14539782/52924165-768acf00-3366-11e9-95a5-a75d6cc94bf6.png)
![_ _20190218101742](https://user-images.githubusercontent.com/14539782/52924169-7a1e5600-3366-11e9-9e83-641ce556907d.png)

**Comment by zhaofangfangdeepin** [comment]
这个看下，是否提示用户手动添加可执行权限

**Comment by BLumia** [comment]
目前的行为是如果是可执行文件但没有权限执行的话不会弹出添加权限的对话框（相应的，AppImage是有的）。考虑也添加这样的对话框询问 @wangjia12 ？

**Comment by zccrs** [comment]
> 目前的行为是如果是可执行文件但没有权限执行的话不会弹出添加权限的对话框（相应的，AppImage是有的）。考虑也添加这样的对话框询问 @wangjia12 ？

这个好像定下了要加的，支持所有elf 二进制可执行文件

**Comment by wangjia12** [comment]
https://pms.deepin.cn/index.php?m=story&f=view&storyID=245
看看是不是这个需求

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/456
