### ISSUE TITLE
在非整数倍屏幕缩放下telegram-desktop花屏，显示异常

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#949]
![](http://ww1.sinaimg.cn/large/9f7599c7gy1g0aegswv8rj20rs0ku471.jpg)

如图1倍和2倍缩放不会出现此类现象，1.25\1.5倍缩放会出现此问题

**Comment by felixonmars** [comment]
这是应用程序问题，需要对应用程序取消缩放，然后在应用程序里单独设置为对应的小数倍数。

**Comment by lq95v5** [comment]
Deepin源里的
Package: telegram-desktop
Version: 1.2.17-1
 源里的版本1.2.17-1 有些旧了，在tg官网下载的显示正常，未出现此问题。官网版本v 1.5.12

**Comment by felixonmars** [comment]
我这里的 1.5.15 还能重现，可能因为官网版本静态链接了 Qt。
