### ISSUE TITLE
在桌面连续复制文件时，第二次以后复制-粘贴，会导致桌面非常卡

### ISSUE THREAD

**Issue by zhaofangfangdeepin** [linuxdeepin/internal-discussion#95]
【测试环境】
dde-desktop:
  已安装：4.6.9-2
【预置条件】
1.桌面上存在一个1GB的测试文件。
【测试步骤】
1.选中桌面测试文件，复制。
2.在桌面进行粘贴。然后再次粘贴。
【预期结果】
1.再次粘贴时，桌面不卡
【测试结果】
1.再次粘贴时，桌面很卡
【问题级别】
一般
【出现概率】
稳定出现

**Comment by zhaofangfangdeepin** [comment]
![_ _20181031160922](https://user-images.githubusercontent.com/14539782/47774388-dca40580-dd27-11e8-8d2b-7399cb71aa40.gif)

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39616/

**Comment by zhaofangfangdeepin** [comment]
V+1

**Comment by zhaofangfangdeepin** [comment]
测试通过
