### ISSUE TITLE
Intel 某些卡在当前 Xserver 版本旋转会黑屏

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#950]
目前确定的卡有 HD 520/ UHD 620，当前 xserver 版本 1.20.0-2

看上游的bug已经确定了，这里有patch https://bugs.freedesktop.org/show_bug.cgi?id=106715
我们需要打一下。

**Comment by deepinzhangshuang** [comment]
已经合并到内网，会跟随下次更新推送外网

**Comment by hualet** [comment]
测试OK

**Comment by zccrs** [comment]
@deepinzhangshuang 任务给 @liuwen123 了，15.9.2发布时做回归测试

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
