### ISSUE TITLE
显卡、显示问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#951]

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174767

联想y7000，显卡型号 Nvidia GTX 1050，切换prime，重启后提示失败。

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/25631

显卡驱动切换失败

**Comment by lq95v5** [comment]
1050ti无法切换显卡驱动
https://feedback.deepin.org/feedback/detail/25658

**Comment by lq95v5** [comment]
nvidia geforce 9400M. 9400M 需要nvidia-340 驱动， 深度显卡驱动管理器好像装成了390 @zccrs 

https://feedback.deepin.org/feedback/detail/25984

**Comment by zccrs** [comment]
> nvidia geforce 9400M. 9400M 需要nvidia-340 驱动， 深度显卡驱动管理器装成了390 @zccrs
> 
> https://feedback.deepin.org/feedback/detail/25984

@listenerri

**Comment by listenerri** [comment]
> nvidia geforce 9400M. 9400M 需要nvidia-340 驱动， 深度显卡驱动管理器装成了390 @zccrs
> 
> https://feedback.deepin.org/feedback/detail/25984

我们的驱动管理器目前没有判断具体型号，发现是 N 卡都是直接装 nvidia-driver (390)

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/25980

GTX750TI  显卡驱动管理器安装完成重启后，卡在“compiling linux kernel”

**Comment by lq95v5** [comment]
显示器没有信号
https://github.com/linuxdeepin/internal-discussion/issues/1045

**Comment by lq95v5** [comment]
显卡驱动切换失败，大黄蜂方案目前故障率较高
https://feedback.deepin.org/feedback/detail/26132
https://feedback.deepin.org/feedback/detail/26131
https://feedback.deepin.org/feedback/detail/26120
https://feedback.deepin.org/feedback/detail/26112
https://feedback.deepin.org/feedback/detail/26109

**Comment by lq95v5** [comment]
N卡960m大黄蜂切换失败
https://feedback.deepin.org/feedback/detail/26170

**Comment by lq95v5** [comment]
切换显卡驱动失败
https://feedback.deepin.org/feedback/detail/26347

GeForce 7500
https://feedback.deepin.org/feedback/detail/26348

**Comment by lq95v5** [comment]
无法更改默认的Intel驱动程序
https://feedback.deepin.org/feedback/detail/26344

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26314
显卡切换失败

**Comment by lq95v5** [comment]
nvidia 710 切换失败

https://feedback.deepin.org/feedback/detail/26395

**Comment by lq95v5** [comment]
大黄蜂方案切换失败
https://feedback.deepin.org/feedback/detail/26391

**Comment by lq95v5** [comment]
电脑待机后花屏，切换大黄蜂方案失败
https://feedback.deepin.org/feedback/detail/26413

**Comment by lq95v5** [comment]
英伟达 GTX950m独显官方驱动切换失败 无法使用NV-PRIME方案
https://feedback.deepin.org/feedback/detail/26540

**Comment by lq95v5** [comment]
1070ti闭源显卡驱动测试不成功
https://feedback.deepin.org/feedback/detail/26535

**Comment by lq95v5** [comment]
Nvidia 1080 driver does not work
https://feedback.deepin.org/feedback/detail/26528

**Comment by lq95v5** [comment]
1050安装失败 

https://feedback.deepin.org/feedback/detail/26521

**Comment by lq95v5** [comment]
切换大黄蜂方案失败
https://feedback.deepin.org/feedback/detail/26516

**Comment by lq95v5** [comment]
nvidia 820m切换失败

https://feedback.deepin.org/feedback/detail/26566

**Comment by lq95v5** [comment]
1050 显卡切换大黄蜂失败
https://feedback.deepin.org/feedback/detail/26562

**Comment by lq95v5** [comment]
nvidia  1080ti 安装闭源驱动失败

https://feedback.deepin.org/feedback/detail/26594

**Comment by lq95v5** [comment]
1060切换失败
https://feedback.deepin.org/feedback/detail/26759

**Comment by lq95v5** [comment]
NV-Prime fails on Matebook X Pro
https://feedback.deepin.org/feedback/detail/26752

**Comment by lq95v5** [comment]
无法切换显卡驱动到nv prime
https://feedback.deepin.org/feedback/detail/26740

**Comment by lq95v5** [comment]
切换闭源显卡驱动不成功 系统运行时间10-15分钟后开始卡顿 花屏

 https://feedback.deepin.org/feedback/detail/26718

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26711 切换nvidia驱动失败

**Comment by lq95v5** [comment]
笔记本无法用英伟达闭源驱动
https://feedback.deepin.org/feedback/detail/26709

**Comment by lq95v5** [comment]
显卡驱动管理器更换显卡驱动失败
https://feedback.deepin.org/feedback/detail/26870

**Comment by lq95v5** [comment]
大黄蜂驱动失败mx150
https://feedback.deepin.org/feedback/detail/27187

**Comment by lq95v5** [comment]
使用gpu驱动切换到inter加速显卡失败。
https://feedback.deepin.org/feedback/detail/27181

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27169

切换大黄蜂方案失败

**Comment by lq95v5** [comment]
切换显卡驱动失败
https://feedback.deepin.org/feedback/detail/27159

**Comment by lq95v5** [comment]
Cannot upgrade the Intel GPU driver to the Compatible or the Accelerated one
https://feedback.deepin.org/feedback/detail/27172

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27164
Dell E6500 always fail to swith to NVidia drvier

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27161

无法切换显卡驱动

**Comment by lq95v5** [comment]
cannot install nvidia driver 390.67-3deepin
https://feedback.deepin.org/feedback/detail/27148

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27202
切换大黄蜂驱动失败

**Comment by lq95v5** [comment]
显卡asus dual rtx2080 o8g 不支持 是因为nvidia390版本太低
https://feedback.deepin.org/feedback/detail/27249
GTX Titan 6GB doesn't boot with closed-source driver  这个可能也不支持
https://feedback.deepin.org/feedback/detail/27239

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27205
radeon驱动错误 https://github.com/linuxdeepin/internal-discussion/issues/1434

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27340
G105M的显卡驱动切换失败

**Comment by lq95v5** [comment]
无法更换显卡驱动模式
https://feedback.deepin.org/feedback/detail/27338

**Comment by lq95v5** [comment]
NVIDIA Corporation GM107M [GeForce GTX 960M] 大黄蜂失败
https://feedback.deepin.org/feedback/detail/27456

**Comment by lq95v5** [comment]
NVIDIA GM107[GTX 850M GDDR5] 
https://feedback.deepin.org/feedback/detail/27473

**Comment by lq95v5** [comment]
950m切换显卡失败
https://feedback.deepin.org/feedback/detail/27471

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27911
切换大黄酚方案失败

**Comment by lq95v5** [comment]
nvidia 930mx
https://feedback.deepin.org/feedback/detail/27927

**Comment by lq95v5** [comment]
failed bumblebee solution
https://feedback.deepin.org/feedback/detail/27921

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27971

nvidia GTX 1050 
切换显卡失败 无法恢复

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28018
双n卡安装失败，建议增加340的闭源驱动

**Comment by lq95v5** [comment]
gtx 1050 2G
https://feedback.deepin.org/feedback/detail/28118

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28444 

intel + nvidia 960m 大黄蜂 切换失败

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
