### ISSUE TITLE
同时登录用户A和B，正在使用A，关机或重启前的提醒中应该只有B

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#956]
同时登录用户A和B，切换到用户A，点击dock上的关机图标，弹出关机界面，然后点击关机或重启，不会立即执行，而是询问用户是否继续，目前会暂展示 A 和 B，但应该排出正在使用的 A，只展示 B。
![default](https://user-images.githubusercontent.com/3241440/53002588-f8165600-3467-11e9-8e10-de03931b7759.png)
上图中，正在使用中的 tp 是不需要展示的。

**Comment by electricface** [comment]
@wangjia12 @zccrs

**Comment by wangjia12** [comment]
@zccrs 重启是不是只对其他账户数据有影响，当前正在使用的数据不会丢失？

**Comment by justforlxz** [comment]
这个只是界面上多显示了一个，我给去掉就行了。

**Comment by justforlxz** [comment]
> @zccrs 重启是不是只对其他账户数据有影响，当前正在使用的数据不会丢失？

所有未保存的数据都会丢的。

**Comment by electricface** [comment]
这个是为了提醒正在操作的用户，电脑上还登录了其他用户。

**Comment by wangjia12** [comment]
> 这个只是界面上多显示了一个，我给去掉就行了。

那你直接去掉吧

**Comment by listenerri** [comment]
我觉得改文案就可以解决了:
此电脑目前已登录多个账户, 重启电脑可能会导致部分账户数据丢失....

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41706/

**Comment by wangjia12** [comment]
> 我觉得改文案就可以解决了:
> 此电脑目前已登录多个账户, 重启电脑可能会导致部分账户数据丢失....

我也是这样想的，但是竹子这么想去掉也可以

**Comment by liuwen123** [comment]
已修复
