### ISSUE TITLE
系统死机问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#959]

**Comment by lq95v5** [comment]
dde图形界面卡顿、死机
https://feedback.deepin.org/feedback/detail/25623
https://feedback.deepin.org/feedback/detail/25624
https://bbs.deepin.org/forum.php?mod=viewthread&tid=171707
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174894

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/25652

**Comment by lq95v5** [comment]
死机
https://feedback.deepin.org/feedback/detail/26167

**Comment by lq95v5** [comment]
上午刚刚发了一次GIMP死机的，现在是ssh死机，没有征兆，没有规律……上午忘记上传日志了……
https://feedback.deepin.org/feedback/detail/26707

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27114

死机

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27205
randon驱动问题，系统进入桌面后假死机

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27285 
1. 问题/建议描述
正常使用时突然浏览器页面丢失，vim无法保存文件，dock栏图标消失，桌面图标消失，无法进行任何操作（只能强制关机，还会导致我当前做的所有工作都丢失，尤其是代码）
2. 问题如何重现
之前在打开搜狗输入法时会百分百出现这个问题，换了别的输入法后能好一些，问题大多数出现在用chrome看视频的时候。
3. 问题重现频率
一天2-3次。

**Comment by lq95v5** [comment]
企业qq弹出框后突然死机，未黑屏，鼠标动不了，ctl+alt+f1终端打不开。有时候是其他原因突然死机。
https://feedback.deepin.org/feedback/detail/27489

**Comment by lq95v5** [comment]
前几天重装了15.10重启就卡死，只能强制关机
https://feedback.deepin.org/feedback/detail/27655

**Comment by lq95v5** [comment]
大概开机后二十多分钟后 系统就无响应 任何按健都无响应 无黑屏现像
https://feedback.deepin.org/feedback/detail/29069

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/29428


系统经常 卡死，只有鼠标能动，打开了WPS，开了微信，基本上就卡住了。

**Comment by lq95v5** [comment]
关机死机  https://bbs.deepin.org/forum.php?mod=viewthread&tid=180790

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1995 笔记本合盖唤醒后系统卡死

**Comment by qiphon** [comment]
升级系统内核可以解决盒盖死机问题，但是升级内核之后WLAN就没有了，我该怎么办

**Comment by BLumia** [comment]
v20 后 issue 处理流程变化，不再通过 internal-discussion 跟进和处理 issue。若您在获取最新的系统更新后仍有类似问题，请移步 developer-center 仓库进行汇报。感谢支持！
