### ISSUE TITLE
grub 编辑界面花屏

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#960]
![](http://ww1.sinaimg.cn/large/9f7599c7gy1g0cwznvja0j20qo0zkgql.jpg)

如图

**Comment by zccrs** [comment]
@electricface 图中的界面有问题吗？

**Comment by electricface** [comment]
用 Noto Sans 字体就会出这种问题

**Comment by lq95v5** [comment]
这个grub花屏问题在公司电脑上和家里笔记本上都出现，包括iso镜像文件的grub编辑界面。

**Comment by lq95v5** [comment]
个别用户安装时需要在grub添加Kernel parameters ，这个grub花屏操作起来比较困难。

**Comment by zccrs** [comment]
> 用 Noto Sans 字体就会出这种问题

以前的也会这样吗

**Comment by electricface** [comment]
修正方案：
终端字体换成 Unifont:style=Medium，由包 ttf-unifont 提供的文件 /usr/share/fonts/truetype/unifont/unifont.ttf

经过测试，字体大小在 [14,50] 范围内，只有为 16 时会出现字体残留光标的情况，把 16 修正为 17 即可解决问题。

字体残留光标与屏幕分辨率关系不大。

**Comment by zhaofangfangdeepin** [comment]
测试通过
