### ISSUE TITLE
网络问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#961]

**Comment by lq95v5** [comment]
微星笔记本GS65,待机休眠后开启电脑提示无线网络硬件关闭，wifi不能使用只能重启电脑
https://feedback.deepin.org/feedback/detail/25659

**Comment by Playhi** [comment]
隐藏SSID的无线网络可否自动连接
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174970

**Comment by lq95v5** [comment]
intel 9260 无线网卡无法使用

https://feedback.deepin.org/feedback/detail/26751

**Comment by lq95v5** [comment]
RTL8821AE 无线网卡没有驱动

https://feedback.deepin.org/feedback/detail/26865

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27224
intel 9260ac网速不正常

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27180
网速太慢
01:00.0 Network controller [0280]: Intel Corporation Wireless 8265 / 8275 [8086:24fd] (rev 78)
    Subsystem: Intel Corporation Wireless 8265 / 8275 [8086:1014]

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27300
06:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter [10ec:b822] (rev ff) (prog-if ff)
    !!! Unknown header type 7f
    Kernel driver in use: r8822be
    Kernel modules: r8822be, wl

wifi 网络异常断开

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27265

ntel(R) Dual Band Wireless AC 9260无线网卡无法驱动

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27276
02:00.0 Network controller [0280]: Intel Corporation PRO/Wireless 5100 AGN [Shiloh] Network Connection [8086:4237]
Subsystem: Intel Corporation WiFi Link 5100 AGN [8086:1211]
Kernel driver in use: iwlwifi
Kernel modules: iwlwifi, wl

没驱动

**Comment by lq95v5** [comment]
rtl8821ce 没驱动
https://bbs.deepin.org/forum.php?mod=viewthread&tid=177011

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1534
特定中文wifi无法连接 #1534

**Comment by lq95v5** [comment]
Surface GO 无法通过无线网卡上网
https://feedback.deepin.org/feedback/detail/27465

**Comment by lq95v5** [comment]
@liuwen123  @yefeifei   @zhaofangfangdeepin

**Comment by lq95v5** [comment]
wifi 无法连接 #1957

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1981  rtl8814au

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/2174 
联想Y7000电脑开机wifi设备识别不到 副网卡型号

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
