### ISSUE TITLE
"普通模式" 翻译问题

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/internal-discussion#962]
建议翻译为 "Normal mode" 而不是 "Common mode"，后者意思更接近”共同“。

![2019-02-21-204215-0e23e7](https://user-images.githubusercontent.com/1006477/53169818-44ed5e80-3619-11e9-9254-ff31df8474b1.png)

**Comment by felixonmars** [comment]
另外建议 ”特效模式“ 翻译为 "Fancy mode"，意思更加接近。

**Comment by wangjia12** [comment]
@zhuxiujuancindy 看看

**Comment by zhuxiujuancindy** [comment]
Common Mode 可改为Normal Mode，该界面上的三句话都要一起改
Fancy mode不太常用，且与控制中心“窗口特效”的表达不一致，建议保留Effect Mode

**Comment by zhuxiujuancindy** [comment]
@felixonmars 如果没有意见，就按照我上面的意见修改了。

@justforlxz 虚拟机安装系统的提示，请修改为以下内容（包含其他更改）：

1. It has detected that you are using a virtual machine, which will affect the system performance and operation experience, for a smooth experience, Normal Mode is recommended

2. Effect Mode: Have a delicate experience. Normal Mode: Enjoy the fast performance

3. 按钮Common Mode，改为Normal Mode

**Comment by felixonmars** [comment]
嗯，OK

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41850/

**Comment by liuwen123** [comment]
已修复
