### ISSUE TITLE
新建用户后切换用户，在切换用户界面所有的用户头像会叠加在一起

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#965]
【测试步骤】
在系统中新建一个用户a，然后点击关机按钮--切换用户

【预期结果】
可以正常切换用户

【测试结果】
所有用户头像都叠加在一起了

【问题级别】
一般

【出现概率】
100%

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41720

**Comment by liuwen123** [comment]
> https://cr.deepin.io/#/c/dde/dde-session-ui/+/41720

删除用户之后再新建用户，会如图显示
![_google-chrome_20190224100806](https://user-images.githubusercontent.com/12492745/53294157-3753f680-381c-11e9-86d6-0907d4cd7dc1.png)

**Comment by justforlxz** [comment]
https://cr.deepin.io/#/c/dde/dde-session-ui/+/41752

**Comment by liuwen123** [comment]
已修复
