### ISSUE TITLE
双屏下新建三个自定义设置，注销系统后自定义消失了

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#967]
【测试步骤】
系统连接双屏，然后新建三个自定义设置，然后启用自定义设置后注销系统

【预期结果】
还是显示为自定义设置

【测试结果】
注销系统后，自定义设置没了

【问题级别】
一般

【出现概率】
100%
[startdde-log-xu.txt](https://github.com/linuxdeepin/internal-discussion/files/2897632/startdde-log-xu.txt)
[display.json.zip](https://github.com/linuxdeepin/internal-discussion/files/2897636/display.json.zip)

**Comment by electricface** [comment]
https://cr.deepin.io/#/c/dde/startdde/+/41737

**Comment by liuwen123** [comment]
已修复
