### ISSUE TITLE
建议 启动器图标右键菜单“使用代理打开”文案改成“使用应用代理”

### ISSUE THREAD

**Issue by electricface** [linuxdeepin/internal-discussion#968]
目前的文案【使用代理打开】会让人以为点击之后就会打开，但其实不是。

**Comment by wangjia12** [comment]
现在点了【使用代理打开】之后确实让人以为是直接打开了，其实是没有打开，只是一种状态。
文案改成【使用代理】。
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
【使用代理】 【Use a proxy】
控制中心里面相关的一句也要改：
【配置好代理后，可在启动器的应用右键菜单查看“使用代理”选项，勾选后即可使用代理】
【Check "Use a proxy" in application context menu in Launcher after configured】

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
