### ISSUE TITLE
文件管理器samba文件共享无法自动搜索文件共享服务器

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#969]
bbs：https://bbs.deepin.org/forum.php?mod=viewthread&tid=174937&extra=
feedback：https://feedback.deepin.org/feedback/detail/25676

**Comment by wphu** [comment]
我也遇到了这个问题，局域网内小米路由器连接了一个磁盘柜，手机和windows都能够自动搜索到，并成功进入读写文件，而deepin不能自动搜索到，只能手动输入smb://ip，有时候需要到手机上看下ip，非常麻烦。

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26637

新反馈

**Comment by jiangzihan** [comment]
同样碰到了自动发现服务失效的问题，请问有新进展吗？

**Comment by lq95v5** [comment]
已知问题，这个目前可以通过smb://地址:端口  访问



---原始邮件---
发件人: "jiangzihan"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 上午10:51
收件人: "linuxdeepin/internal-discussion"<internal-discussion@noreply.github.com>;
抄送: "lq95v5"<lqv5@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [linuxdeepin/internal-discussion] 文件管理器samba文件共享无法自动搜索文件共享服务器 (#969)



同样碰到了自动发现服务失效的问题，请问有新进展吗？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
