### ISSUE TITLE
深度截图修改为自己响应通知里的Action

### ISSUE THREAD

**Issue by justforlxz** [linuxdeepin/internal-discussion#972]
以前因为不支持通过dbus截图，启动以后就导致因为单例而无法截图了，所以用了dde的通知做了一个委托打开的功能，准备修改成支持dbus操作，走org.freedesktop.Notifications的action接口做打开。

**Comment by hualet** [comment]
通知新设计看一下 #983

不过题目里面的支持dbus操作是有什么需求？

**Comment by justforlxz** [comment]
> 通知新设计看一下 #983
> 
> 不过题目里面的支持dbus操作是有什么需求？

截图现在是注册dbus失败就退出了，打算支持一下根据命令行参数来调对应的dbus方法的。不然改成自己相应action的话，在通知没有回应action的时候，就没办法继续截图了

**Comment by hualet** [comment]
> > 通知新设计看一下 #983
> > 不过题目里面的支持dbus操作是有什么需求？
> 
> 截图现在是注册dbus失败就退出了，打算支持一下根据命令行参数来调对应的dbus方法的。不然改成自己相应action的话，在通知没有回应action的时候，就没办法继续截图了

之所以扩展通知action（你说得托管打开功能），就是为了解决截图长时间不退出的问题。
如果让截图自己处理action，然后在截图还没有退出的时候还能再进行截图，你还得引入上下文支持，不然没法处理第二次截图已经开始的时候，第一次截图的action被触发的情况。
这样搞反而复杂了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
