### ISSUE TITLE
启动器拖拽图标时图标大小错误

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#974]
在全屏模式的启动器下，拖拽一个图标，抓起后图标变得很大

**Comment by listenerri** [comment]
https://cr.deepin.io/#/c/dde/dde-launcher/+/41747

**Comment by listenerri** [comment]
@liuwen123 测试时留一下高分屏下是否也是正确的

**Comment by liuwen123** [comment]
> @liuwen123 测试时留一下高分屏下是否也是正确的
拖拽图标有时候会显示为空白
![_ _20190225172254](https://user-images.githubusercontent.com/12492745/53327075-05c55300-3922-11e9-9019-f458a02be31b.png)

**Comment by liuwen123** [comment]
已修复
