### ISSUE TITLE
在桌面按Ctrl+i 无法打开文件属性对话框<z4>

### ISSUE THREAD

**Issue by liuwen123** [linuxdeepin/internal-discussion#976]
【测试步骤】
在桌面任意选中一个文件，按Ctrl+i

【预期结果】
弹出文件属性对话框

【测试结果】
无任何反应

【问题级别】
一般

【出现概率】
100%

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41792/

**Comment by liuwen123** [comment]
已修复
