### ISSUE TITLE
最近使用文件特别多的时候，文件管理器启动特别慢<z5>

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#977]
检查一下启动部分的逻辑吧，看看是不是有地方没有做异步处理。

**Comment by hualet** [comment]
@liuwenhuan 报的问题，清掉最近使用文件就会启动快很多，不过，相较于以前的版本还是稍微慢了一点，顺便一起检查下看看吧。

**Comment by BLumia** [comment]
和 https://tower.im/teams/9487/todos/229079/ 是一回事，之前的修复是 linuxdeepin/developer-center#840 任务里的，修的不是很彻底，只改了监视文件夹逻辑。

**Comment by zccrs** [comment]
同源项目结束之后优化一下这部分的逻辑

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/41864/

**Comment by liuwen123** [comment]
已修复
