### ISSUE TITLE
屏幕旋转增加确认对话框 <周三>

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/internal-discussion#982]
背景：

避免显卡驱动问题旋转后黑屏无法操作和看到提示。
分辨率设置也有这个问题。
需求：

1. 旋转屏幕时，在旋转状态时增加提示信息按“Ctrl+S”键保存，加入倒计时，倒计时从15秒开始，如果没有操作倒计时完成后自动恢复且退出旋转状态。鼠标左键旋转，右键还原并退出。
2. 点击设置的分辨率，生效的同时弹出对话框（用标准的对话框样式就可以，图标不知道找舒乐），用户点击保存才保存设置，点击还原或者在倒计时内无任何操作还原。默认焦点在还原按钮上。
3. 双屏：调整分辨率后直接在当前窗口上弹出对话框提示（同单屏）， 旋转方向和单屏保持一致。
4. 双屏去掉保存永久配置的功能，只保留当前的一个设置。点击自定义设置后弹出窗口，两个按钮【取消】和【保存】，点击保存即保存当前设置，一直生效。

文案：

【是否要保存显示设置？如无任何操作将在%1秒后还原。】

【Do you want to save the display settings? If no operation, the display will be restored after %1s.】
 

【还原】【Restore】（左边，默认选中）

 【保存】【Save】（右边）

 

------------------------------

 

【鼠标左键旋转，右键还原并退出，按Ctrl+S键保存。】

【Left click to rotate, right click to exit, press Ctrl+S to save.】

【如无任何操作将在%1秒后还原。】（显示在第二行）

【If no operation, the display will be restored after %1s.】

**Comment by listenerri** [comment]
@zccrs @wangjia12 

看任务描述是屏幕缩放和旋转都要增加倒计时恢复功能吗？

另外屏幕旋转目前有一个确认界面，但没有倒计时恢复，这个是在原有的界面上修改还是再弹出一个对话框？

**Comment by listenerri** [comment]
新的讨论结果：
- 旋转屏幕使用 1# 的方案
- 调整分辨率：
    - 单屏时：弹出新设计的倒计时还原对话框
    - 多屏时：在已经显示出来的自定义对话框上显示倒计时提示，同时修改“应用”按钮的逻辑，点击应用按钮将终止倒计时，“取消”按钮保持原有功能不变，“保存”按钮功能改为现在的“应用按钮”，那么此时现在的“保存”按钮的功能就没有了，建议增加一个按钮“保存为新配置”来做现在的“保存”按钮的功能，有点绕。。

**Comment by wangjia12** [comment]
单屏方案不变。
双屏：
调整分辨率后直接在当前窗口上倒计时， @shule1987 要有一个新设计
旋转方向和单屏保持一致。
按钮名称，取消不变，应用改为【保存】，保存改为【保存新配置】，逻辑不变。

**Comment by wangjia12** [comment]
@zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
【保存新配置】【Save as New】

**Comment by listenerri** [comment]
@wangjia12 
我跟 @justforlxz 商量了下，感觉双屏下的设计还是不对。

首先现在的“应用”按钮所做的改动只会维持到当前用户注销，下次登录后“本次”的改动就没有了，这点我之前不知道，所以仅仅把“应用”按钮的文案改成保存其逻辑不变是不行的，建议把的“应用”按钮的逻辑改为就只是停掉倒计时，保存按钮依旧是保存按钮，文案和逻辑都不变。

另外按照上面的逻辑，外层界面的“自定义配置”按钮文案应为“新增配置”或“新增自定义配置”。

**Comment by shule1987** [comment]
![default](https://user-images.githubusercontent.com/5448609/53535283-3cc38080-3b3d-11e9-9b7b-90a19056a555.png)

切换分辨率后按钮上面一行空出来显示提示文字

**Comment by shule1987** [comment]
![group 13](https://user-images.githubusercontent.com/5448609/53537208-253bc600-3b44-11e9-95ef-708cff0c0cc1.png)

**Comment by listenerri** [comment]
@wangjia12 
屏幕旋转新文案【鼠标左键旋转，右键退出，按Enter键保存。】
其中右键退出时是否还原设置呢？

**Comment by wangjia12** [comment]
【鼠标左键旋转，右键还原并退出，按Ctrl+S键保存。】

【Left click to rotate, right click to exit, press Ctrl+S to save.】
@zhuxiujuancindy 这里右键后面增加了一点文案，麻烦更新一下。

**Comment by zhuxiujuancindy** [comment]
【鼠标左键旋转，右键还原并退出，按Ctrl+S键保存。】

【Left click to rotate, right click to restore and exit, press Ctrl+S to save.】

**Comment by listenerri** [comment]
@liuwen123 
功能基本完成，可以测试了，留意单屏，双屏，多屏下，设置分辨率、屏幕旋转相关功能

https://cr.deepin.io/c/dde/dde-control-center/+/41795

**Comment by listenerri** [comment]
@shule1987 给一下图标吧？

**Comment by listenerri** [comment]
另外砍掉配置列表这个放到另一个 issue 里做吧：https://github.com/linuxdeepin/internal-discussion/issues/992

**Comment by shule1987** [comment]
[display_setting_icon.svg.zip](https://github.com/linuxdeepin/internal-discussion/files/2917660/display_setting_icon.svg.zip)

**Comment by liuwen123** [comment]
已添加
