### ISSUE TITLE
通知系统重新设计

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#983]
通知系统重新设计的话，应该这样改一下：

- UI只做UI，不要涉及协议实现部分；
- 协议支持部分放置到后端（常驻，解决其他通知服务抢注的问题）；
- 现在通知里面扩展action的部分放到后端处理。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/deepin-notifications/+/37291/

之前这个社区 PR 对应的事情也考虑一下，支持标准里提到的时间长度？

**Comment by hualet** [comment]
> https://cr.deepin.io/#/c/deepin-notifications/+/37291/
> 
> 之前这个社区 PR 对应的事情也考虑一下，支持标准里提到的时间长度？

上面说得是不涉及界面改动的修改，如果支持时间长度就必须添加多个气泡并存的设计。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
