### ISSUE TITLE
谷歌浏览器标签页

### ISSUE THREAD

**Issue by wangjia12** [linuxdeepin/internal-discussion#984]
需求综述：https://shimo.im/docs/85f3b3719d0440fc

查看这个链接的需求清单页面：https://shimo.im/sheet/gI4sfQlebqUWjygR/50df2

**Comment by hualet** [comment]
来个设计图？@wangjia @shule1987

**Comment by wangjia12** [comment]
@shule1987 在pms上贴一份吧

**Comment by shule1987** [comment]
还没完全设计完,现在只有两张图

**Comment by shule1987** [comment]
![1](https://user-images.githubusercontent.com/5448609/53612240-87f89480-3c0c-11e9-857b-7483fb06c78e.jpg)
![2](https://user-images.githubusercontent.com/5448609/53612241-88912b00-3c0c-11e9-9121-e236c4a3a1bb.jpg)

**Comment by shule1987** [comment]
壁纸每日从unsplash.com拉取一张

**Comment by hualet** [comment]
收藏夹、历史记录也是在右侧打开？

**Comment by shule1987** [comment]
> 收藏夹、历史记录也是在右侧打开？

是的

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
