### ISSUE TITLE
高分屏支持多屏不同缩放比的设置

### ISSUE THREAD

**Issue by hualet** [linuxdeepin/internal-discussion#985]

**Comment by hualet** [comment]
@shule1987 弄个设计图呗

**Comment by chirs241097** [comment]
![image](https://user-images.githubusercontent.com/11586814/53475468-f1609200-3aaa-11e9-9a28-a0a4526e2f27.png)

当前的界面实现

**Comment by wangjia12** [comment]
@shule1987 快看看

**Comment by shule1987** [comment]
单屏显示在外面,和现在一样
<img width="369" alt="2019-02-28 9 26 01" src="https://user-images.githubusercontent.com/5448609/53534923-bce8e680-3b3b-11e9-9f6c-97f9245580fc.png">

多屏像亮度一样合并在一起,进去显示所有屏幕的缩放调节
<img width="361" alt="2019-02-28 9 27 44" src="https://user-images.githubusercontent.com/5448609/53534931-c1ad9a80-3b3b-11e9-9d2e-6f7fdeb027b0.png">

**Comment by chirs241097** [comment]
实现已基本完成，但使用 `QT_SCREEN_SCALE_FACTORS` 会导致部分应用行为异常。

https://cr.deepin.io/#/c/dde/dde-control-center/+/41798/
https://cr.deepin.io/#/c/dde/startdde/+/41799/
https://cr.deepin.io/#/c/deepin-desktop-schemas/+/41800/

参考：
https://wiki.archlinux.org/index.php/HiDPI#Multiple_displays
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by BLumia** [comment]
@listenerri @electricface @justforlxz 看看 review 一下代码 :)

**Comment by zccrs** [comment]
> 实现已基本完成，但使用 `QT_SCREEN_SCALE_FACTORS` 会导致部分应用行为异常。
> 
> https://cr.deepin.io/#/c/dde/dde-control-center/+/41798/
> https://cr.deepin.io/#/c/dde/startdde/+/41799/
> https://cr.deepin.io/#/c/deepin-desktop-schemas/+/41800/
> 
> 参考：
> https://wiki.archlinux.org/index.php/HiDPI#Multiple_displays
> https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/
> https://phabricator.kde.org/D12405

哪些应用的行为异常呀?

**Comment by chirs241097** [comment]
> 哪些应用的行为异常呀?

鼠标指针大小（鼠标移至dock中会变小，移至低dpi屏幕上反而仍然使用大尺寸指针）
`dde-polkit-agent`（窗口变高）
非Qt或使用Qt版本<5.6的程序（不支持相关的环境变量）
~~vlc, QtCreator~~（图标/文字被缩放两次，已解决）

**Comment by zccrs** [comment]
> 实现已基本完成，但使用 `QT_SCREEN_SCALE_FACTORS` 会导致部分应用行为异常。
> 
> https://cr.deepin.io/#/c/dde/dde-control-center/+/41798/
> https://cr.deepin.io/#/c/dde/startdde/+/41799/
> https://cr.deepin.io/#/c/deepin-desktop-schemas/+/41800/
> 
> 参考：
> https://wiki.archlinux.org/index.php/HiDPI#Multiple_displays
> https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/
> https://phabricator.kde.org/D12405

@justforlxz @hualet @electricface 审核一下剩余的两个项目, 代码没问题就尽快合了, 功能方面合并后再测试

**Comment by electricface** [comment]
dde-daemon : https://cr.deepin.io/#/c/dde/dde-daemon/+/41942/

在 session bus 的 com.deepin.daemon.Appearance 的 /com/deepin/daemon/Appearance 
增加接口
GetScreenScaleFactors() -> map[string]float64
SetScreenScaleFactors(v map[string]float64)

**Comment by hualet** [comment]
> dde-daemon : https://cr.deepin.io/#/c/dde/dde-daemon/+/41942/
> 
> 在 session bus 的 com.deepin.daemon.Appearance 的 /com/deepin/daemon/Appearance
> 增加接口
> GetScreenScaleFactors() -> map[string]float64
> SetScreenScaleFactors(v map[string]float64)

原来的缩放不是在 Display 接口上设置的么？怎么跑到 Appearance 上了？

**Comment by electricface** [comment]
一直都在 Appearance 上

**Comment by zhaofangfangdeepin** [comment]
@zccrs 把experimental 仓库中的代码推送一下，我加这个仓库重点测试下这个功能

**Comment by yefeifei** [comment]
- [ ] 接入双屏前已经开启高分屏缩放为2，接入双屏后，2个缩放设置显示都为1.

- [ ] 修改显示模式，从单屏显示切换到复制模式下，双屏的缩放设置显示不对，只显示一个缩放。

**Comment by chirs241097** [comment]
1) 需要确定期望的行为
2) 3) 已确定维持当前行为

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
