### ISSUE TITLE
触摸板、触摸屏问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#986]

**Comment by lq95v5** [comment]
触控板问题，重启之后消失，有相关日志。
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175087

**Comment by Playhi** [comment]
磁吸键盘，触摸板问题，磁吸键盘上的键盘是可以用的，触摸板不行，“所有设置”中有显示“触控板”。
(社区没人回复诶，我把东西丢这里来了，如有打扰还请谅解。如果需要更多有关我这贴的信息，我可以试着提供)
https://bbs.deepin.org/forum.php?mod=viewthread&tid=174489

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
