### ISSUE TITLE
休眠、唤醒、待机等问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#989]

**Comment by lq95v5** [comment]
休眠唤醒后亮度低不能恢复正常
https://feedback.deepin.org/feedback/detail/25999

**Comment by lq95v5** [comment]
（笔记本）有时候盖上盖子，然后再打开盖子，会回到新开机状态
https://feedback.deepin.org/feedback/detail/26237

**Comment by lq95v5** [comment]
待机=死机+关机
https://feedback.deepin.org/feedback/detail/26193

**Comment by lq95v5** [comment]
待机唤醒后 窗口全部丢失  未测试 @liuwen123 
https://bbs.deepin.org/forum.php?mod=viewthread&tid=175833

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26796
笔记本关机后自动开机

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26744
休眠、唤醒、待机后卡死不能登录

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26743
无法关机

**Comment by lq95v5** [comment]
无法关机
每次关机都卡在灰色的logo处
https://feedback.deepin.org/feedback/detail/26635

**Comment by lq95v5** [comment]
看视频时鼠标不活动，屏幕休眠
https://feedback.deepin.org/feedback/detail/26861

**Comment by lq95v5** [comment]
关机自动重启
https://feedback.deepin.org/feedback/detail/26815

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27216
点击关机后卡在logo界面

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27299
大约平均每2天，关机时，会卡在logo处，一直停留在那个界面。只能按电脑的电源键，强制关机

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27270 
联想miix520电池显示问题，电池图标无论是否插上电源都显示正在充电

**Comment by Playhi** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=176934
睡眠后再次唤醒，密码框无法输入，点关机图标，再取消，密码框恢复可输入

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27491
开机后键盘失灵，睡眠后，唤醒后恢复（神舟K650D I7）

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27861
关机以后，不停自动重启

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27858
电脑关机假死

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27917
15.10合上盖子休眠后无法再次唤醒屏幕

**Comment by lq95v5** [comment]
系统无操作黑屏后,再激活电脑,亮屏后一直是白屏,无响应,需要长按电源键强制关机再重启
https://feedback.deepin.org/feedback/detail/27969

**Comment by lq95v5** [comment]
15.10.1休眠后恢复到桌面死机了。。
https://bbs.deepin.org/forum.php?mod=viewthread&tid=178297

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28851
关机后会自动重启（Linux四个关机命令也都相继重启），但有时候又可以正常关机

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/29102

deepin休眠后，无法唤醒，不能点亮屏幕，但按屏幕截图会在桌面生成图片。

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/29161 
thinkpad无法正常关机

**Comment by lq95v5** [comment]
无法关机 CPU#3 stack for 22S

https://github.com/linuxdeepin/internal-discussion/issues/1719

**Comment by lq95v5** [comment]
休眠后无法唤醒
https://feedback.deepin.org/feedback/detail/29443

**Comment by lq95v5** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=180790 关机司机

**Comment by lq95v5** [comment]
[HP probook 446 G3 i5/8G/250G 笔记本]待机时死机 #2053

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
