### ISSUE TITLE
声音问题汇总

### ISSUE THREAD

**Issue by lq95v5** [linuxdeepin/internal-discussion#990]

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26758
凌动8300处理器，声音没有，

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26713 没有声音

**Comment by lq95v5** [comment]
声音效果未被禁用。
https://feedback.deepin.org/feedback/detail/26860

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/26818 笔记本安装的系统，插着耳机启动后耳机有声音，拔掉耳机后没有外音。

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27044

安装后电脑没声音

**Comment by lq95v5** [comment]
插着耳机关机后，拔下耳机再开机无声音，必须插上耳机引导一下才可以

https://feedback.deepin.org/feedback/detail/27068

**Comment by longwusha** [comment]
安装后电脑没声音
https://feedback.deepin.org/feedback/detail/27131

**Comment by hualet** [comment]
@electricface @jouyouyun 关注一下

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1518
重新启动时，扬声器持续发出噪音，听起来像声卡没有复位。该问题大概率出现，30%左右。

**Comment by lq95v5** [comment]
近期有两个反馈没有声音
https://feedback.deepin.org/feedback/detail/27929
没有声音
https://github.com/linuxdeepin/internal-discussion/issues/1551
全局没有声音

**Comment by lq95v5** [comment]
控制中心->声音->高级设置->输出_切换输出设备时, 虽然成功切换. 但选中图标不刷新
https://github.com/linuxdeepin/internal-discussion/issues/1549

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/27996
云音乐播放没有声音，网页播放也没有
近期声音的问题出现的比较多

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28005
小米笔记本外放没有声音

**Comment by lq95v5** [comment]
每次重新启动，扬声器发出长时间强烈噪音 #1586

**Comment by bibichuan** [comment]
命令行什么命令没输的时候，按退格键，能不能不发出声音？

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1605、
声卡问题，每次开机都一卡一卡的响

**Comment by lq95v5** [comment]
> 命令行什么命令没输的时候，按退格键，能不能不发出声音？

我这里试了一下没声音呀 试试控制中心-声音-音效-错误提示

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28315
deepin15.10.1 外放耳机都没有声音

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/28275
屏幕经常弹出声音图标，并伴有“当、当”的响声。

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/29166

电脑联耳机无声音

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/29209

终端内按Backspace键退到行首时，笔记本有很大声的蜂鸣器提示音

复现了一次，在我更换debian 4.9.0内核后出现

请排查一下 @zccrs

**Comment by lq95v5** [comment]
重复打开文件夹会一直响应 #1730

**Comment by lq95v5** [comment]
@yefeifei  @zhaofangfangdeepin  @liuwen123

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/30839

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/1994

**Comment by lq95v5** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/2024  

No sound on Intel HDMP/DP LPE device

**Comment by lq95v5** [comment]
alc262声卡 未被识别，无声音 #2045

**Comment by lq95v5** [comment]
https://feedback.deepin.org/feedback/detail/32242 更了 更了

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
