### ISSUE TITLE
去掉控制中心显示设置中配置列表功能，只使用一份配置文件，且用户不可见

### ISSUE THREAD

**Issue by listenerri** [linuxdeepin/internal-discussion#992]
相关讨论：https://github.com/linuxdeepin/internal-discussion/issues/982

**Comment by listenerri** [comment]
需要额外留意保存和还原的功能是否正常：

https://cr.deepin.io/c/dde/dde-control-center/+/41827

**Comment by liuwen123** [comment]
设置了自定义设置后，在控制中心中不能直接明了的显示当前的设置模式
![_ _20190305165159](https://user-images.githubusercontent.com/12492745/53792693-35e6a480-3f67-11e9-9536-52f535e4485c.png)

**Comment by liuwen123** [comment]
已修复
