### ISSUE TITLE
使用 Welcome bot 引导新贡献/反馈者完善其 Issue / PR

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/internal-discussion#999]
Welcome bot: https://github.com/apps/welcome 

由于新的反馈者或者贡献者可能会直接忽略现有的文档或 issue 模板，导致提交的反馈或 PR 不够规范，例如反馈时没有给出足以让其他人复现问题的步骤或环境等。

Welcome bot 可以在新贡献/反馈者首次提交时自动回复相应内容以告知需要注意的事项。效果如：

![image](https://user-images.githubusercontent.com/10095765/53622308-55629200-3c34-11e9-9ce4-79e4b224b604.png)

cc: @hualet

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
